apiDir: ../headless-site-api/src/main/java
apiPackagePath: com.liferay.headless.site
application:
    baseURI: /headless-site
    className: HeadlessSiteApplication
    name: Liferay.Headless.Site
author: Rubén Pulido
clientDir: ../headless-site-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateBatch: true
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../headless-site-test/src/testIntegration/java