modified.files.includes[relevant][frontend-js-item-selector-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][frontend-js-item-selector-web-playwright-rule]=\
    frontend-js-item-selector-web.main

relevant.rule.names=frontend-js-item-selector-web-playwright-rule

test.batch.names[relevant][frontend-js-item-selector-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57