modified.files.includes[relevant][layout-content-page-editor-web-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][layout-content-page-editor-web-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][layout-content-page-editor-web-java-rule]=\
    apps/layout/layout-content-page-editor-web/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][layout-content-page-editor-web-java-rule]=\
    apps/layout/layout-content-page-editor-web/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][layout-content-page-editor-web-playwright-rule]=\
    layout-content-page-editor-web.form-container,\
    layout-content-page-editor-web.fragments,\
    layout-content-page-editor-web.main

relevant.rule.names=\
    layout-content-page-editor-web-java-rule,\
    layout-content-page-editor-web-playwright-rule

test.batch.names[relevant][layout-content-page-editor-web-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][layout-content-page-editor-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Content Pages