dependencies {
	compile group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.0.0"
	compile group: "ch.qos.reload4j", name: "reload4j", version: "1.2.26"
	compile group: "org.osgi", name: "org.osgi.compendium", version: "5.0.0"
}

liferay {
	deployDir = file("${liferayHome}/osgi/test")
}
