{{- if and .Values.enabled .Values.secretStoreName .Values.license.externalSecretName .Values.license.targetSecretName }}
{{- $fullSecretName := include "liferay.getFullLicenseSecretName" .Values.license.externalSecretName -}}
{{- include "liferay.validateSecretNameSuffix" $fullSecretName -}}
{{- $k8sName := include "liferay.k8sFriendlyString" $fullSecretName -}}
{{- $targetName := include "liferay.k8sFriendlyString" .Values.license.targetSecretName -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-40"
    labels:
        app: liferay
        component: license
    name: {{ $k8sName }}
    namespace: {{ .Release.Namespace }}
spec:
    data:
        -   remoteRef:
                decodingStrategy: Auto
                key: {{ $fullSecretName }}
                property: license.xml
            secretKey: rawLicense
    refreshInterval: 1h0m0s
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ .Values.secretStoreName }}
    target:
        name: {{ $targetName }}
        template:
            data:
                license.xml: "{{"{{ .rawLicense | toString }}"}}"
            type: Opaque
{{- end -}}