{{- if and .Values.enabled .Values.secretStoreName }}
{{- $renderedSecrets := dict -}}
{{- with .Values.endpoints }}
{{- range $name, $config := . }}
{{- with $config.tls.externalSecretNames }}
{{- range $secretName := . }}
{{- $fullSecretName := include "liferay.getFullCertificateSecretName" $secretName -}}
{{- include "liferay.validateSecretNameSuffix" $fullSecretName -}}
{{- $k8sName := include "liferay.k8sFriendlyString" $secretName -}}
{{- if not (hasKey $renderedSecrets $k8sName) }}
{{- $_ := set $renderedSecrets $k8sName "true" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-40"
    labels:
        app: liferay
        component: certificate
    name: {{ $k8sName }}
    namespace: {{ $.Release.Namespace }}
spec:
    dataFrom:
        -   extract:
                decodingStrategy: Auto
                key: {{ $fullSecretName }}
    refreshInterval: 1h0m0s
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ $.Values.secretStoreName }}
    target:
        name: {{ $k8sName }}
        template:
            type: kubernetes.io/tls
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end -}}