{{- if .Values.enabled -}}
apiVersion: aws.liferay.com/v1alpha1
kind: LiferayInfrastructure
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true
        argocd.argoproj.io/sync-wave: "-20"
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    backup: {{ .Values.backup | toYaml | nindent 8 }}
    cmk: {{ .Values.cmk | toYaml | nindent 8 }}
    commonTags:
        EnvironmentId: {{ .Values.environmentId }}
        ProjectId: {{ .Values.projectId }}
    database: {{ .Values.database | toYaml | nindent 8 }}
    environmentId: {{ .Values.environmentId }}
    forceDestroy: {{ .Values.forceDestroy }}
    orphanOnDelete: {{ .Values.orphanOnDelete }}
    overlayAccess:
        enabled: {{ .Values.overlayAccess.enabled }}
    projectId: {{ .Values.projectId }}
    region: {{ .Values.region }}
    search:
        elasticsearch:
            enabled: {{ .Values.search.elasticsearch.enabled }}
        opensearch: {{ .Values.search.opensearch | toYaml | nindent 12 }}
    storage: {{ .Values.storage | toYaml | nindent 8 }}
{{- end -}}