modified.files.includes[relevant][site-cms-site-initializer-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][site-cms-site-initializer-playwright-rule]=\
    site-cms-site-initializer.main,\
    site-cms-site-initializer.structure-builder

relevant.rule.names=site-cms-site-initializer-playwright-rule

test.batch.names[relevant][site-cms-site-initializer-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Content Management System