dependencies {
	compileInclude group: "jfree", name: "jcommon", version: "1.0.16"
	compileInclude group: "jfree", name: "jfreechart", version: "1.0.13"

	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "ch.qos.reload4j", name: "reload4j", version: "1.2.26"
	compileOnly group: "com.liferay", name: "com.liferay.application.list.api", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.captcha.api", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.frontend.taglib", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.lang", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.log4j", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.instances.api", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.upgrade", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "2.4.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.23.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.java", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "2.0.0"
	compileOnly group: "javax.portlet", name: "portlet-api", version: "2.0"
	compileOnly group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	compileOnly group: "javax.servlet.jsp", name: "javax.servlet.jsp-api", version: "2.3.1"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
}
