modified.files.includes[relevant][image-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][image-java-rule]=\
    apps/image/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][image-java-rule]=\
    apps/image/**/*Test.java

relevant.rule.names=image-java-rule

test.batch.names[relevant][image-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Documents and Media