modified.files.includes[relevant][portal-security-audit-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][portal-security-audit-java-rule]=\
    **/ldap**/**/src/testIntegration/**/*Test.java,\
    **/oauth2-provider/**/src/testIntegration/**/*Test.java,\
    **/portal-security/**/src/testIntegration/**/*Test.java,\
    **/portal-security-audit/**/src/testIntegration/**/*Test.java,\
    **/portal-security-sso/**/src/testIntegration/**/*Test.java,\
    **/portal-security-sso-ntlm/**/src/testIntegration/**/*Test.java,\
    **/portal-security-sso-openid/**/src/testIntegration/**/*Test.java,\
    **/saml/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-security-audit-java-rule]=\
    **/ldap**/**/src/test/**/*Test.java,\
    **/oauth2-provider/**/src/test/**/*Test.java,\
    **/portal-security/**/src/test/**/*Test.java,\
    **/portal-security-audit/**/src/test/**/*Test.java,\
    **/saml/**/src/test/**/*Test.java

relevant.rule.names=portal-security-audit-java-rule

test.batch.names[relevant][portal-security-audit-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Audit