/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.calendar.model.impl;

import com.liferay.calendar.model.CalendarBooking;
import com.liferay.calendar.model.CalendarBookingModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CalendarBooking service. Represents a row in the &quot;CalendarBooking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CalendarBookingModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CalendarBookingImpl}.
 * </p>
 *
 * @author Eduardo Lundgren
 * @see CalendarBookingImpl
 * @generated
 */
@JSON(strict = true)
public class CalendarBookingModelImpl
	extends BaseModelImpl<CalendarBooking> implements CalendarBookingModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a calendar booking model instance should use the <code>CalendarBooking</code> interface instead.
	 */
	public static final String TABLE_NAME = "CalendarBooking";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"externalReferenceCode", Types.VARCHAR},
		{"calendarBookingId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"calendarId", Types.BIGINT},
		{"calendarResourceId", Types.BIGINT},
		{"parentCalendarBookingId", Types.BIGINT},
		{"recurringCalendarBookingId", Types.BIGINT},
		{"vEventUid", Types.VARCHAR}, {"title", Types.VARCHAR},
		{"description", Types.CLOB}, {"location", Types.VARCHAR},
		{"startTime", Types.BIGINT}, {"endTime", Types.BIGINT},
		{"allDay", Types.BOOLEAN}, {"recurrence", Types.VARCHAR},
		{"firstReminder", Types.BIGINT}, {"firstReminderType", Types.VARCHAR},
		{"secondReminder", Types.BIGINT}, {"secondReminderType", Types.VARCHAR},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("calendarBookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("calendarId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("calendarResourceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentCalendarBookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("recurringCalendarBookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("vEventUid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("location", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("endTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("allDay", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("recurrence", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstReminder", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("firstReminderType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secondReminder", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("secondReminderType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CalendarBooking (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,calendarBookingId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,calendarId LONG,calendarResourceId LONG,parentCalendarBookingId LONG,recurringCalendarBookingId LONG,vEventUid VARCHAR(255) null,title STRING null,description TEXT null,location STRING null,startTime LONG,endTime LONG,allDay BOOLEAN,recurrence STRING null,firstReminder LONG,firstReminderType VARCHAR(75) null,secondReminder LONG,secondReminderType VARCHAR(75) null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (calendarBookingId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table CalendarBooking";

	public static final String ORDER_BY_JPQL =
		" ORDER BY calendarBooking.startTime ASC, calendarBooking.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CalendarBooking.startTime ASC, CalendarBooking.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CALENDARID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CALENDARRESOURCEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTCALENDARBOOKINGID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECURRINGCALENDARBOOKINGID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VEVENTUID_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STARTTIME_COLUMN_BITMASK = 1024L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TITLE_COLUMN_BITMASK = 2048L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CalendarBookingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _calendarBookingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCalendarBookingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _calendarBookingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CalendarBooking.class;
	}

	@Override
	public String getModelClassName() {
		return CalendarBooking.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CalendarBooking, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CalendarBooking, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalendarBooking, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CalendarBooking)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CalendarBooking, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CalendarBooking, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CalendarBooking)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CalendarBooking, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CalendarBooking, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CalendarBooking, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CalendarBooking, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<CalendarBooking, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CalendarBooking::getMvccVersion);
			attributeGetterFunctions.put(
				"ctCollectionId", CalendarBooking::getCtCollectionId);
			attributeGetterFunctions.put("uuid", CalendarBooking::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				CalendarBooking::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"calendarBookingId", CalendarBooking::getCalendarBookingId);
			attributeGetterFunctions.put(
				"groupId", CalendarBooking::getGroupId);
			attributeGetterFunctions.put(
				"companyId", CalendarBooking::getCompanyId);
			attributeGetterFunctions.put("userId", CalendarBooking::getUserId);
			attributeGetterFunctions.put(
				"userName", CalendarBooking::getUserName);
			attributeGetterFunctions.put(
				"createDate", CalendarBooking::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", CalendarBooking::getModifiedDate);
			attributeGetterFunctions.put(
				"calendarId", CalendarBooking::getCalendarId);
			attributeGetterFunctions.put(
				"calendarResourceId", CalendarBooking::getCalendarResourceId);
			attributeGetterFunctions.put(
				"parentCalendarBookingId",
				CalendarBooking::getParentCalendarBookingId);
			attributeGetterFunctions.put(
				"recurringCalendarBookingId",
				CalendarBooking::getRecurringCalendarBookingId);
			attributeGetterFunctions.put(
				"vEventUid", CalendarBooking::getVEventUid);
			attributeGetterFunctions.put("title", CalendarBooking::getTitle);
			attributeGetterFunctions.put(
				"description", CalendarBooking::getDescription);
			attributeGetterFunctions.put(
				"location", CalendarBooking::getLocation);
			attributeGetterFunctions.put(
				"startTime", CalendarBooking::getStartTime);
			attributeGetterFunctions.put(
				"endTime", CalendarBooking::getEndTime);
			attributeGetterFunctions.put("allDay", CalendarBooking::getAllDay);
			attributeGetterFunctions.put(
				"recurrence", CalendarBooking::getRecurrence);
			attributeGetterFunctions.put(
				"firstReminder", CalendarBooking::getFirstReminder);
			attributeGetterFunctions.put(
				"firstReminderType", CalendarBooking::getFirstReminderType);
			attributeGetterFunctions.put(
				"secondReminder", CalendarBooking::getSecondReminder);
			attributeGetterFunctions.put(
				"secondReminderType", CalendarBooking::getSecondReminderType);
			attributeGetterFunctions.put(
				"lastPublishDate", CalendarBooking::getLastPublishDate);
			attributeGetterFunctions.put("status", CalendarBooking::getStatus);
			attributeGetterFunctions.put(
				"statusByUserId", CalendarBooking::getStatusByUserId);
			attributeGetterFunctions.put(
				"statusByUserName", CalendarBooking::getStatusByUserName);
			attributeGetterFunctions.put(
				"statusDate", CalendarBooking::getStatusDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CalendarBooking, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CalendarBooking, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<CalendarBooking, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setMvccVersion);
			attributeSetterBiConsumers.put(
				"ctCollectionId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setCtCollectionId);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<CalendarBooking, String>)CalendarBooking::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"calendarBookingId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setCalendarBookingId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<CalendarBooking, Long>)CalendarBooking::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<CalendarBooking, Long>)CalendarBooking::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<CalendarBooking, Date>)
					CalendarBooking::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<CalendarBooking, Date>)
					CalendarBooking::setModifiedDate);
			attributeSetterBiConsumers.put(
				"calendarId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setCalendarId);
			attributeSetterBiConsumers.put(
				"calendarResourceId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setCalendarResourceId);
			attributeSetterBiConsumers.put(
				"parentCalendarBookingId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setParentCalendarBookingId);
			attributeSetterBiConsumers.put(
				"recurringCalendarBookingId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setRecurringCalendarBookingId);
			attributeSetterBiConsumers.put(
				"vEventUid",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setVEventUid);
			attributeSetterBiConsumers.put(
				"title",
				(BiConsumer<CalendarBooking, String>)CalendarBooking::setTitle);
			attributeSetterBiConsumers.put(
				"description",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setDescription);
			attributeSetterBiConsumers.put(
				"location",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setLocation);
			attributeSetterBiConsumers.put(
				"startTime",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setStartTime);
			attributeSetterBiConsumers.put(
				"endTime",
				(BiConsumer<CalendarBooking, Long>)CalendarBooking::setEndTime);
			attributeSetterBiConsumers.put(
				"allDay",
				(BiConsumer<CalendarBooking, Boolean>)
					CalendarBooking::setAllDay);
			attributeSetterBiConsumers.put(
				"recurrence",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setRecurrence);
			attributeSetterBiConsumers.put(
				"firstReminder",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setFirstReminder);
			attributeSetterBiConsumers.put(
				"firstReminderType",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setFirstReminderType);
			attributeSetterBiConsumers.put(
				"secondReminder",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setSecondReminder);
			attributeSetterBiConsumers.put(
				"secondReminderType",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setSecondReminderType);
			attributeSetterBiConsumers.put(
				"lastPublishDate",
				(BiConsumer<CalendarBooking, Date>)
					CalendarBooking::setLastPublishDate);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<CalendarBooking, Integer>)
					CalendarBooking::setStatus);
			attributeSetterBiConsumers.put(
				"statusByUserId",
				(BiConsumer<CalendarBooking, Long>)
					CalendarBooking::setStatusByUserId);
			attributeSetterBiConsumers.put(
				"statusByUserName",
				(BiConsumer<CalendarBooking, String>)
					CalendarBooking::setStatusByUserName);
			attributeSetterBiConsumers.put(
				"statusDate",
				(BiConsumer<CalendarBooking, Date>)
					CalendarBooking::setStatusDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getCalendarBookingId() {
		return _calendarBookingId;
	}

	@Override
	public void setCalendarBookingId(long calendarBookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarBookingId = calendarBookingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCalendarId() {
		return _calendarId;
	}

	@Override
	public void setCalendarId(long calendarId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarId = calendarId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCalendarId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("calendarId"));
	}

	@JSON
	@Override
	public long getCalendarResourceId() {
		return _calendarResourceId;
	}

	@Override
	public void setCalendarResourceId(long calendarResourceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_calendarResourceId = calendarResourceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCalendarResourceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("calendarResourceId"));
	}

	@JSON
	@Override
	public long getParentCalendarBookingId() {
		return _parentCalendarBookingId;
	}

	@Override
	public void setParentCalendarBookingId(long parentCalendarBookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentCalendarBookingId = parentCalendarBookingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentCalendarBookingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentCalendarBookingId"));
	}

	@JSON
	@Override
	public long getRecurringCalendarBookingId() {
		return _recurringCalendarBookingId;
	}

	@Override
	public void setRecurringCalendarBookingId(long recurringCalendarBookingId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recurringCalendarBookingId = recurringCalendarBookingId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRecurringCalendarBookingId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("recurringCalendarBookingId"));
	}

	@JSON
	@Override
	public String getVEventUid() {
		if (_vEventUid == null) {
			return "";
		}
		else {
			return _vEventUid;
		}
	}

	@Override
	public void setVEventUid(String vEventUid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vEventUid = vEventUid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalVEventUid() {
		return getColumnOriginalValue("vEventUid");
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getLocation() {
		if (_location == null) {
			return "";
		}
		else {
			return _location;
		}
	}

	@Override
	public void setLocation(String location) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_location = location;
	}

	@JSON
	@Override
	public long getStartTime() {
		return _startTime;
	}

	@Override
	public void setStartTime(long startTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startTime = startTime;
	}

	@JSON
	@Override
	public long getEndTime() {
		return _endTime;
	}

	@Override
	public void setEndTime(long endTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endTime = endTime;
	}

	@JSON
	@Override
	public boolean getAllDay() {
		return _allDay;
	}

	@JSON
	@Override
	public boolean isAllDay() {
		return _allDay;
	}

	@Override
	public void setAllDay(boolean allDay) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allDay = allDay;
	}

	@JSON
	@Override
	public String getRecurrence() {
		if (_recurrence == null) {
			return "";
		}
		else {
			return _recurrence;
		}
	}

	@Override
	public void setRecurrence(String recurrence) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recurrence = recurrence;
	}

	@JSON
	@Override
	public long getFirstReminder() {
		return _firstReminder;
	}

	@Override
	public void setFirstReminder(long firstReminder) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstReminder = firstReminder;
	}

	@JSON
	@Override
	public String getFirstReminderType() {
		if (_firstReminderType == null) {
			return "";
		}
		else {
			return _firstReminderType;
		}
	}

	@Override
	public void setFirstReminderType(String firstReminderType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstReminderType = firstReminderType;
	}

	@JSON
	@Override
	public long getSecondReminder() {
		return _secondReminder;
	}

	@Override
	public void setSecondReminder(long secondReminder) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondReminder = secondReminder;
	}

	@JSON
	@Override
	public String getSecondReminderType() {
		if (_secondReminderType == null) {
			return "";
		}
		else {
			return _secondReminderType;
		}
	}

	@Override
	public void setSecondReminderType(String secondReminderType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secondReminderType = secondReminderType;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("status"));
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CalendarBooking.class.getName()));
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CalendarBooking.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			CalendarBooking.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public CalendarBooking toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CalendarBooking>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CalendarBookingImpl calendarBookingImpl = new CalendarBookingImpl();

		calendarBookingImpl.setMvccVersion(getMvccVersion());
		calendarBookingImpl.setCtCollectionId(getCtCollectionId());
		calendarBookingImpl.setUuid(getUuid());
		calendarBookingImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		calendarBookingImpl.setCalendarBookingId(getCalendarBookingId());
		calendarBookingImpl.setGroupId(getGroupId());
		calendarBookingImpl.setCompanyId(getCompanyId());
		calendarBookingImpl.setUserId(getUserId());
		calendarBookingImpl.setUserName(getUserName());
		calendarBookingImpl.setCreateDate(getCreateDate());
		calendarBookingImpl.setModifiedDate(getModifiedDate());
		calendarBookingImpl.setCalendarId(getCalendarId());
		calendarBookingImpl.setCalendarResourceId(getCalendarResourceId());
		calendarBookingImpl.setParentCalendarBookingId(
			getParentCalendarBookingId());
		calendarBookingImpl.setRecurringCalendarBookingId(
			getRecurringCalendarBookingId());
		calendarBookingImpl.setVEventUid(getVEventUid());
		calendarBookingImpl.setTitle(getTitle());
		calendarBookingImpl.setDescription(getDescription());
		calendarBookingImpl.setLocation(getLocation());
		calendarBookingImpl.setStartTime(getStartTime());
		calendarBookingImpl.setEndTime(getEndTime());
		calendarBookingImpl.setAllDay(isAllDay());
		calendarBookingImpl.setRecurrence(getRecurrence());
		calendarBookingImpl.setFirstReminder(getFirstReminder());
		calendarBookingImpl.setFirstReminderType(getFirstReminderType());
		calendarBookingImpl.setSecondReminder(getSecondReminder());
		calendarBookingImpl.setSecondReminderType(getSecondReminderType());
		calendarBookingImpl.setLastPublishDate(getLastPublishDate());
		calendarBookingImpl.setStatus(getStatus());
		calendarBookingImpl.setStatusByUserId(getStatusByUserId());
		calendarBookingImpl.setStatusByUserName(getStatusByUserName());
		calendarBookingImpl.setStatusDate(getStatusDate());

		calendarBookingImpl.resetOriginalValues();

		return calendarBookingImpl;
	}

	@Override
	public CalendarBooking cloneWithOriginalValues() {
		CalendarBookingImpl calendarBookingImpl = new CalendarBookingImpl();

		calendarBookingImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		calendarBookingImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		calendarBookingImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		calendarBookingImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		calendarBookingImpl.setCalendarBookingId(
			this.<Long>getColumnOriginalValue("calendarBookingId"));
		calendarBookingImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		calendarBookingImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		calendarBookingImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		calendarBookingImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		calendarBookingImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		calendarBookingImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		calendarBookingImpl.setCalendarId(
			this.<Long>getColumnOriginalValue("calendarId"));
		calendarBookingImpl.setCalendarResourceId(
			this.<Long>getColumnOriginalValue("calendarResourceId"));
		calendarBookingImpl.setParentCalendarBookingId(
			this.<Long>getColumnOriginalValue("parentCalendarBookingId"));
		calendarBookingImpl.setRecurringCalendarBookingId(
			this.<Long>getColumnOriginalValue("recurringCalendarBookingId"));
		calendarBookingImpl.setVEventUid(
			this.<String>getColumnOriginalValue("vEventUid"));
		calendarBookingImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		calendarBookingImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		calendarBookingImpl.setLocation(
			this.<String>getColumnOriginalValue("location"));
		calendarBookingImpl.setStartTime(
			this.<Long>getColumnOriginalValue("startTime"));
		calendarBookingImpl.setEndTime(
			this.<Long>getColumnOriginalValue("endTime"));
		calendarBookingImpl.setAllDay(
			this.<Boolean>getColumnOriginalValue("allDay"));
		calendarBookingImpl.setRecurrence(
			this.<String>getColumnOriginalValue("recurrence"));
		calendarBookingImpl.setFirstReminder(
			this.<Long>getColumnOriginalValue("firstReminder"));
		calendarBookingImpl.setFirstReminderType(
			this.<String>getColumnOriginalValue("firstReminderType"));
		calendarBookingImpl.setSecondReminder(
			this.<Long>getColumnOriginalValue("secondReminder"));
		calendarBookingImpl.setSecondReminderType(
			this.<String>getColumnOriginalValue("secondReminderType"));
		calendarBookingImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));
		calendarBookingImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));
		calendarBookingImpl.setStatusByUserId(
			this.<Long>getColumnOriginalValue("statusByUserId"));
		calendarBookingImpl.setStatusByUserName(
			this.<String>getColumnOriginalValue("statusByUserName"));
		calendarBookingImpl.setStatusDate(
			this.<Date>getColumnOriginalValue("statusDate"));

		return calendarBookingImpl;
	}

	@Override
	public int compareTo(CalendarBooking calendarBooking) {
		int value = 0;

		if (getStartTime() < calendarBooking.getStartTime()) {
			value = -1;
		}
		else if (getStartTime() > calendarBooking.getStartTime()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getTitle().compareToIgnoreCase(calendarBooking.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CalendarBooking)) {
			return false;
		}

		CalendarBooking calendarBooking = (CalendarBooking)object;

		long primaryKey = calendarBooking.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CalendarBooking> toCacheModel() {
		CalendarBookingCacheModel calendarBookingCacheModel =
			new CalendarBookingCacheModel();

		calendarBookingCacheModel.mvccVersion = getMvccVersion();

		calendarBookingCacheModel.ctCollectionId = getCtCollectionId();

		calendarBookingCacheModel.uuid = getUuid();

		String uuid = calendarBookingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			calendarBookingCacheModel.uuid = null;
		}

		calendarBookingCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			calendarBookingCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			calendarBookingCacheModel.externalReferenceCode = null;
		}

		calendarBookingCacheModel.calendarBookingId = getCalendarBookingId();

		calendarBookingCacheModel.groupId = getGroupId();

		calendarBookingCacheModel.companyId = getCompanyId();

		calendarBookingCacheModel.userId = getUserId();

		calendarBookingCacheModel.userName = getUserName();

		String userName = calendarBookingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			calendarBookingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			calendarBookingCacheModel.createDate = createDate.getTime();
		}
		else {
			calendarBookingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			calendarBookingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			calendarBookingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		calendarBookingCacheModel.calendarId = getCalendarId();

		calendarBookingCacheModel.calendarResourceId = getCalendarResourceId();

		calendarBookingCacheModel.parentCalendarBookingId =
			getParentCalendarBookingId();

		calendarBookingCacheModel.recurringCalendarBookingId =
			getRecurringCalendarBookingId();

		calendarBookingCacheModel.vEventUid = getVEventUid();

		String vEventUid = calendarBookingCacheModel.vEventUid;

		if ((vEventUid != null) && (vEventUid.length() == 0)) {
			calendarBookingCacheModel.vEventUid = null;
		}

		calendarBookingCacheModel.title = getTitle();

		String title = calendarBookingCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			calendarBookingCacheModel.title = null;
		}

		calendarBookingCacheModel.description = getDescription();

		String description = calendarBookingCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			calendarBookingCacheModel.description = null;
		}

		calendarBookingCacheModel.location = getLocation();

		String location = calendarBookingCacheModel.location;

		if ((location != null) && (location.length() == 0)) {
			calendarBookingCacheModel.location = null;
		}

		calendarBookingCacheModel.startTime = getStartTime();

		calendarBookingCacheModel.endTime = getEndTime();

		calendarBookingCacheModel.allDay = isAllDay();

		calendarBookingCacheModel.recurrence = getRecurrence();

		String recurrence = calendarBookingCacheModel.recurrence;

		if ((recurrence != null) && (recurrence.length() == 0)) {
			calendarBookingCacheModel.recurrence = null;
		}

		calendarBookingCacheModel.firstReminder = getFirstReminder();

		calendarBookingCacheModel.firstReminderType = getFirstReminderType();

		String firstReminderType = calendarBookingCacheModel.firstReminderType;

		if ((firstReminderType != null) && (firstReminderType.length() == 0)) {
			calendarBookingCacheModel.firstReminderType = null;
		}

		calendarBookingCacheModel.secondReminder = getSecondReminder();

		calendarBookingCacheModel.secondReminderType = getSecondReminderType();

		String secondReminderType =
			calendarBookingCacheModel.secondReminderType;

		if ((secondReminderType != null) &&
			(secondReminderType.length() == 0)) {

			calendarBookingCacheModel.secondReminderType = null;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			calendarBookingCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			calendarBookingCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		calendarBookingCacheModel.status = getStatus();

		calendarBookingCacheModel.statusByUserId = getStatusByUserId();

		calendarBookingCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = calendarBookingCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			calendarBookingCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			calendarBookingCacheModel.statusDate = statusDate.getTime();
		}
		else {
			calendarBookingCacheModel.statusDate = Long.MIN_VALUE;
		}

		return calendarBookingCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CalendarBooking, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CalendarBooking, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CalendarBooking, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CalendarBooking)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CalendarBooking>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CalendarBooking.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private String _externalReferenceCode;
	private long _calendarBookingId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _calendarId;
	private long _calendarResourceId;
	private long _parentCalendarBookingId;
	private long _recurringCalendarBookingId;
	private String _vEventUid;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _location;
	private long _startTime;
	private long _endTime;
	private boolean _allDay;
	private String _recurrence;
	private long _firstReminder;
	private String _firstReminderType;
	private long _secondReminder;
	private String _secondReminderType;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CalendarBooking, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CalendarBooking)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put("calendarBookingId", _calendarBookingId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("calendarId", _calendarId);
		_columnOriginalValues.put("calendarResourceId", _calendarResourceId);
		_columnOriginalValues.put(
			"parentCalendarBookingId", _parentCalendarBookingId);
		_columnOriginalValues.put(
			"recurringCalendarBookingId", _recurringCalendarBookingId);
		_columnOriginalValues.put("vEventUid", _vEventUid);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("location", _location);
		_columnOriginalValues.put("startTime", _startTime);
		_columnOriginalValues.put("endTime", _endTime);
		_columnOriginalValues.put("allDay", _allDay);
		_columnOriginalValues.put("recurrence", _recurrence);
		_columnOriginalValues.put("firstReminder", _firstReminder);
		_columnOriginalValues.put("firstReminderType", _firstReminderType);
		_columnOriginalValues.put("secondReminder", _secondReminder);
		_columnOriginalValues.put("secondReminderType", _secondReminderType);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusByUserId", _statusByUserId);
		_columnOriginalValues.put("statusByUserName", _statusByUserName);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("externalReferenceCode", 8L);

		columnBitmasks.put("calendarBookingId", 16L);

		columnBitmasks.put("groupId", 32L);

		columnBitmasks.put("companyId", 64L);

		columnBitmasks.put("userId", 128L);

		columnBitmasks.put("userName", 256L);

		columnBitmasks.put("createDate", 512L);

		columnBitmasks.put("modifiedDate", 1024L);

		columnBitmasks.put("calendarId", 2048L);

		columnBitmasks.put("calendarResourceId", 4096L);

		columnBitmasks.put("parentCalendarBookingId", 8192L);

		columnBitmasks.put("recurringCalendarBookingId", 16384L);

		columnBitmasks.put("vEventUid", 32768L);

		columnBitmasks.put("title", 65536L);

		columnBitmasks.put("description", 131072L);

		columnBitmasks.put("location", 262144L);

		columnBitmasks.put("startTime", 524288L);

		columnBitmasks.put("endTime", 1048576L);

		columnBitmasks.put("allDay", 2097152L);

		columnBitmasks.put("recurrence", 4194304L);

		columnBitmasks.put("firstReminder", 8388608L);

		columnBitmasks.put("firstReminderType", 16777216L);

		columnBitmasks.put("secondReminder", 33554432L);

		columnBitmasks.put("secondReminderType", 67108864L);

		columnBitmasks.put("lastPublishDate", 134217728L);

		columnBitmasks.put("status", 268435456L);

		columnBitmasks.put("statusByUserId", 536870912L);

		columnBitmasks.put("statusByUserName", 1073741824L);

		columnBitmasks.put("statusDate", 2147483648L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CalendarBooking _escapedModel;

}