modified.files.includes[relevant][ant-bnd-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][ant-bnd-java-rule]=\
    sdk/ant-bnd/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][ant-bnd-java-rule]=\
    sdk/ant-bnd/**/*Test.java

relevant.rule.names=ant-bnd-java-rule

test.batch.names[relevant][ant-bnd-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Dev Tools