modified.files.includes[relevant][osgi-bundle-builder-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][osgi-bundle-builder-java-rule]=\
    util/osgi-bundle-builder/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][osgi-bundle-builder-java-rule]=\
    util/osgi-bundle-builder/**/*Test.java

relevant.rule.names=osgi-bundle-builder-java-rule

test.batch.names[relevant][osgi-bundle-builder-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Dev Tools