modified.files.includes[relevant][talend-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][talend-java-rule]=\
    core/talend/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][talend-java-rule]=\
    core/talend/**/*Test.java

relevant.rule.names=talend-java-rule

test.batch.names[relevant][talend-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=REST Infrastructure