buildService {
	apiDir = "../adaptive-media-image-api/src/main/java"
	testDir = "../adaptive-media-image-test/src/testIntegration/java"
}

dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.jsoup", name: "jsoup", version: "1.23.1"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.cm", version: "1.6.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:adaptive-media:adaptive-media-api")
	compileOnly project(":apps:adaptive-media:adaptive-media-image-api")
	compileOnly project(":apps:change-tracking:change-tracking-spi")
	compileOnly project(":apps:change-tracking:change-tracking-store-api")
	compileOnly project(":apps:export-import:export-import-api")
	compileOnly project(":apps:portal:portal-aop-api")
	compileOnly project(":apps:portal:portal-dao-orm-custom-sql-api")
	compileOnly project(":apps:static:osgi:osgi-util")
	compileOnly project(":apps:static:portal:portal-upgrade-api")
	compileOnly project(":core:osgi-service-tracker-collections")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-sql-dsl-api")
	compileOnly project(":core:petra:petra-sql-dsl-spi")
	compileOnly project(":core:petra:petra-string")
}