modified.files.includes[relevant][portal-search-admin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][portal-search-admin-web-playwright-rule]=\
    portal-search-admin-web.main

relevant.rule.names=portal-search-admin-web-playwright-rule

test.batch.names[relevant][portal-search-admin-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Web Search