dependencies {
	compileInclude group: "com.liferay", name: "org.drools.compiler", version: "5.4.0.Final.JAKARTA_LIFERAY-PATCHED-1"
	compileInclude group: "com.liferay", name: "org.drools.core", version: "5.4.0.Final.LIFERAY-PATCHED-3.JAKARTA_LIFERAY-PATCHED-1"
	compileInclude group: "com.liferay", name: "org.drools.knowledge", version: "5.4.0.Final.JAKARTA_LIFERAY-PATCHED-1"
	compileInclude group: "com.liferay", name: "org.mvel2", version: "2.1.0.drools16.LIFERAY-PATCHED-3"
	compileInclude group: "org.antlr", name: "antlr-runtime", version: "3.5.3"
	compileInclude group: "org.drools", name: "knowledge-internal-api", version: "5.4.0.Final"
	compileInclude group: "org.eclipse.jdt.core.compiler", name: "ecj", version: "4.5.1"
	compileOnly group: "com.google.protobuf", name: "protobuf-java", version: "3.25.5"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.annotation", name: "jakarta.annotation-api", version: "2.1.1"
	compileOnly group: "jakarta.xml.bind", name: "jakarta.xml.bind-api", version: "4.0.2"
	compileOnly group: "org.osgi", name: "org.osgi.service.component", version: "1.4.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:portal-rules-engine:portal-rules-engine-api")
}