javascript.single.page.application.enabled=false
users.reminder.queries.enabled=false
terms.of.use.required=false
session.cookie.domain=analytics-stg.liferay.com
session.tracker.memory.enabled=false
layout.user.private.layouts.enabled=false
layout.user.public.layouts.enabled=false
layout.template.cache.enabled=false
browser.launcher.url=
direct.servlet.context.reload=false
module.framework.properties.osgi.console=0.0.0.0:11311
scheduler.group.name.max.length=100
scheduler.job.name.max.length=100
com.liferay.portal.sharepoint.SharepointFilter=false
com.liferay.portal.servlet.filters.strip.StripFilter=false
web.server.host=analytics-stg.liferay.com
web.server.protocol=https
jsonws.servlet.hosts.allowed=127.0.0.1,SERVER_IP
webdav.servlet.hosts.allowed=127.0.0.1,SERVER_IP
dl.file.indexing.max.size=0
dl.file.entry.preview.enabled=false
dl.file.entry.thumbnail.enabled=false
portlet.css.enabled=false
sites.control.panel.members.visible=false