modified.files.includes[relevant][site-initializer-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][site-initializer-java-rule]=\
    apps/site-initializer/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][site-initializer-java-rule]=\
    apps/site-initializer/**/*Test.java

relevant.rule.names=site-initializer-java-rule

test.batch.names[relevant][site-initializer-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Site Management > Site Initializer