#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.headless.cms.dto.v1_0.BulkAction
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.CMS)
osgi.jaxrs.resource=true