modified.files.includes[relevant][portal-search-functional-rule]=**

modified.files.includes[relevant][portal-search-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][portal-search-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-search-java-rule]=\
    apps/portal-search/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-search-java-rule]=\
    apps/portal-search/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][portal-search-playwright-rule]=\
    portal-search-admin-web.main,\
    portal-search-web.main

relevant.rule.names=\
    portal-search-functional-rule,\
    portal-search-java-rule,\
    portal-search-playwright-rule

test.batch.names[relevant][portal-search-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][portal-search-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][portal-search-playwright-rule]=\
    playwright-js-tomcat101-mysql57

test.batch.run.property.query[functional-upgrade-tomcat*-mysql*][relevant][portal-search-functional-rule]=\
    (portal.suite.search.engine ~ "elasticsearch7") AND \
    (testray.main.component.name ~ "Upgrades Search")

testray.main.component.name=Web Search