apiDir: ../portal-language-rest-api/src/main/java
apiPackagePath: com.liferay.portal.language.rest
application:
    baseURI: /language
    className: PortalLanguageRESTApplication
    name: Liferay.Portal.Language.REST
author: Thiago Buarque
clientDir: ../portal-language-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../portal-language-rest-test/src/testIntegration/java