sourceCompatibility = "17"
targetCompatibility = "17"

configurations.all {
	exclude group: "com.liferay", module: "org.springframework.test"
}

dependencies {
	api group: "org.springframework.boot", name: "spring-boot-starter-oauth2-client", version: "3.5.16"
	api group: "org.springframework.boot", name: "spring-boot-starter-oauth2-resource-server", version: "3.5.16"
	api group: "org.springframework.boot", name: "spring-boot-starter-web", version: "3.5.16"
	api group: "org.springframework.boot", name: "spring-boot-starter-webflux", version: "3.5.16"
	implementation group: "org.json", name: "json", version: "20231013"
	testImplementation group: "junit", name: "junit", version: "4.13.1"
	testImplementation group: "org.mock-server", name: "mockserver-client-java", version: "3.12"
	testImplementation group: "org.mock-server", name: "mockserver-netty", version: "3.12"
	testImplementation group: "org.mockito", name: "mockito-core", version: "5.15.2"
	testImplementation group: "org.springframework", name: "spring-test", version: "6.2.19"
	testImplementation group: "org.springframework.boot", name: "spring-boot-test-autoconfigure", version: "3.5.16"
}