/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export const EMOJI_GROUPS = [
	'Smileys & Emotion',
	'People & Body',
	'Animals & Nature',
	'Food & Drink',
	'Travel & Places',
	'Activities',
	'Objects',
	'Symbols',
	'Flags',
];

export interface EmojiEntry {
	c: string;

	g: number;

	n: string;
}

export const EMOJI: EmojiEntry[] = [
	{c: '😀', g: 0, n: 'grinning face'},
	{c: '😃', g: 0, n: 'grinning face with big eyes'},
	{c: '😄', g: 0, n: 'grinning face with smiling eyes'},
	{c: '😁', g: 0, n: 'beaming face with smiling eyes'},
	{c: '😆', g: 0, n: 'grinning squinting face'},
	{c: '😅', g: 0, n: 'grinning face with sweat'},
	{c: '🤣', g: 0, n: 'rolling on the floor laughing'},
	{c: '😂', g: 0, n: 'face with tears of joy'},
	{c: '🙂', g: 0, n: 'slightly smiling face'},
	{c: '🙃', g: 0, n: 'upside-down face'},
	{c: '🫠', g: 0, n: 'melting face'},
	{c: '😉', g: 0, n: 'winking face'},
	{c: '😊', g: 0, n: 'smiling face with smiling eyes'},
	{c: '😇', g: 0, n: 'smiling face with halo'},
	{c: '🥰', g: 0, n: 'smiling face with hearts'},
	{c: '😍', g: 0, n: 'smiling face with heart-eyes'},
	{c: '🤩', g: 0, n: 'star-struck'},
	{c: '😘', g: 0, n: 'face blowing a kiss'},
	{c: '😗', g: 0, n: 'kissing face'},
	{c: '☺️', g: 0, n: 'smiling face'},
	{c: '😚', g: 0, n: 'kissing face with closed eyes'},
	{c: '😙', g: 0, n: 'kissing face with smiling eyes'},
	{c: '🥲', g: 0, n: 'smiling face with tear'},
	{c: '😋', g: 0, n: 'face savoring food'},
	{c: '😛', g: 0, n: 'face with tongue'},
	{c: '😜', g: 0, n: 'winking face with tongue'},
	{c: '🤪', g: 0, n: 'zany face'},
	{c: '😝', g: 0, n: 'squinting face with tongue'},
	{c: '🤑', g: 0, n: 'money-mouth face'},
	{c: '🤗', g: 0, n: 'smiling face with open hands'},
	{c: '🤭', g: 0, n: 'face with hand over mouth'},
	{c: '🫢', g: 0, n: 'face with open eyes and hand over mouth'},
	{c: '🫣', g: 0, n: 'face with peeking eye'},
	{c: '🤫', g: 0, n: 'shushing face'},
	{c: '🤔', g: 0, n: 'thinking face'},
	{c: '🫡', g: 0, n: 'saluting face'},
	{c: '🤐', g: 0, n: 'zipper-mouth face'},
	{c: '🤨', g: 0, n: 'face with raised eyebrow'},
	{c: '😐', g: 0, n: 'neutral face'},
	{c: '😑', g: 0, n: 'expressionless face'},
	{c: '😶', g: 0, n: 'face without mouth'},
	{c: '🫥', g: 0, n: 'dotted line face'},
	{c: '😶‍🌫️', g: 0, n: 'face in clouds'},
	{c: '😏', g: 0, n: 'smirking face'},
	{c: '😒', g: 0, n: 'unamused face'},
	{c: '🙄', g: 0, n: 'face with rolling eyes'},
	{c: '😬', g: 0, n: 'grimacing face'},
	{c: '😮‍💨', g: 0, n: 'face exhaling'},
	{c: '🤥', g: 0, n: 'lying face'},
	{c: '🫨', g: 0, n: 'shaking face'},
	{c: '🙂‍↔️', g: 0, n: 'head shaking horizontally'},
	{c: '🙂‍↕️', g: 0, n: 'head shaking vertically'},
	{c: '😌', g: 0, n: 'relieved face'},
	{c: '😔', g: 0, n: 'pensive face'},
	{c: '😪', g: 0, n: 'sleepy face'},
	{c: '🤤', g: 0, n: 'drooling face'},
	{c: '😴', g: 0, n: 'sleeping face'},
	{c: '🫩', g: 0, n: 'face with bags under eyes'},
	{c: '😷', g: 0, n: 'face with medical mask'},
	{c: '🤒', g: 0, n: 'face with thermometer'},
	{c: '🤕', g: 0, n: 'face with head-bandage'},
	{c: '🤢', g: 0, n: 'nauseated face'},
	{c: '🤮', g: 0, n: 'face vomiting'},
	{c: '🤧', g: 0, n: 'sneezing face'},
	{c: '🥵', g: 0, n: 'hot face'},
	{c: '🥶', g: 0, n: 'cold face'},
	{c: '🥴', g: 0, n: 'woozy face'},
	{c: '😵', g: 0, n: 'face with crossed-out eyes'},
	{c: '😵‍💫', g: 0, n: 'face with spiral eyes'},
	{c: '🤯', g: 0, n: 'exploding head'},
	{c: '🤠', g: 0, n: 'cowboy hat face'},
	{c: '🥳', g: 0, n: 'partying face'},
	{c: '🥸', g: 0, n: 'disguised face'},
	{c: '😎', g: 0, n: 'smiling face with sunglasses'},
	{c: '🤓', g: 0, n: 'nerd face'},
	{c: '🧐', g: 0, n: 'face with monocle'},
	{c: '😕', g: 0, n: 'confused face'},
	{c: '🫤', g: 0, n: 'face with diagonal mouth'},
	{c: '😟', g: 0, n: 'worried face'},
	{c: '🙁', g: 0, n: 'slightly frowning face'},
	{c: '☹️', g: 0, n: 'frowning face'},
	{c: '😮', g: 0, n: 'face with open mouth'},
	{c: '😯', g: 0, n: 'hushed face'},
	{c: '😲', g: 0, n: 'astonished face'},
	{c: '😳', g: 0, n: 'flushed face'},
	{c: '🫪', g: 0, n: 'distorted face'},
	{c: '🥺', g: 0, n: 'pleading face'},
	{c: '🥹', g: 0, n: 'face holding back tears'},
	{c: '😦', g: 0, n: 'frowning face with open mouth'},
	{c: '😧', g: 0, n: 'anguished face'},
	{c: '😨', g: 0, n: 'fearful face'},
	{c: '😰', g: 0, n: 'anxious face with sweat'},
	{c: '😥', g: 0, n: 'sad but relieved face'},
	{c: '😢', g: 0, n: 'crying face'},
	{c: '😭', g: 0, n: 'loudly crying face'},
	{c: '😱', g: 0, n: 'face screaming in fear'},
	{c: '😖', g: 0, n: 'confounded face'},
	{c: '😣', g: 0, n: 'persevering face'},
	{c: '😞', g: 0, n: 'disappointed face'},
	{c: '😓', g: 0, n: 'downcast face with sweat'},
	{c: '😩', g: 0, n: 'weary face'},
	{c: '😫', g: 0, n: 'tired face'},
	{c: '🥱', g: 0, n: 'yawning face'},
	{c: '😤', g: 0, n: 'face with steam from nose'},
	{c: '😡', g: 0, n: 'enraged face'},
	{c: '😠', g: 0, n: 'angry face'},
	{c: '🤬', g: 0, n: 'face with symbols on mouth'},
	{c: '😈', g: 0, n: 'smiling face with horns'},
	{c: '👿', g: 0, n: 'angry face with horns'},
	{c: '💀', g: 0, n: 'skull'},
	{c: '☠️', g: 0, n: 'skull and crossbones'},
	{c: '💩', g: 0, n: 'pile of poo'},
	{c: '🤡', g: 0, n: 'clown face'},
	{c: '👹', g: 0, n: 'ogre'},
	{c: '👺', g: 0, n: 'goblin'},
	{c: '👻', g: 0, n: 'ghost'},
	{c: '👽', g: 0, n: 'alien'},
	{c: '👾', g: 0, n: 'alien monster'},
	{c: '🤖', g: 0, n: 'robot'},
	{c: '😺', g: 0, n: 'grinning cat'},
	{c: '😸', g: 0, n: 'grinning cat with smiling eyes'},
	{c: '😹', g: 0, n: 'cat with tears of joy'},
	{c: '😻', g: 0, n: 'smiling cat with heart-eyes'},
	{c: '😼', g: 0, n: 'cat with wry smile'},
	{c: '😽', g: 0, n: 'kissing cat'},
	{c: '🙀', g: 0, n: 'weary cat'},
	{c: '😿', g: 0, n: 'crying cat'},
	{c: '😾', g: 0, n: 'pouting cat'},
	{c: '🙈', g: 0, n: 'see-no-evil monkey'},
	{c: '🙉', g: 0, n: 'hear-no-evil monkey'},
	{c: '🙊', g: 0, n: 'speak-no-evil monkey'},
	{c: '💌', g: 0, n: 'love letter'},
	{c: '💘', g: 0, n: 'heart with arrow'},
	{c: '💝', g: 0, n: 'heart with ribbon'},
	{c: '💖', g: 0, n: 'sparkling heart'},
	{c: '💗', g: 0, n: 'growing heart'},
	{c: '💓', g: 0, n: 'beating heart'},
	{c: '💞', g: 0, n: 'revolving hearts'},
	{c: '💕', g: 0, n: 'two hearts'},
	{c: '💟', g: 0, n: 'heart decoration'},
	{c: '❣️', g: 0, n: 'heart exclamation'},
	{c: '💔', g: 0, n: 'broken heart'},
	{c: '❤️‍🔥', g: 0, n: 'heart on fire'},
	{c: '❤️‍🩹', g: 0, n: 'mending heart'},
	{c: '❤️', g: 0, n: 'red heart'},
	{c: '🩷', g: 0, n: 'pink heart'},
	{c: '🧡', g: 0, n: 'orange heart'},
	{c: '💛', g: 0, n: 'yellow heart'},
	{c: '💚', g: 0, n: 'green heart'},
	{c: '💙', g: 0, n: 'blue heart'},
	{c: '🩵', g: 0, n: 'light blue heart'},
	{c: '💜', g: 0, n: 'purple heart'},
	{c: '🤎', g: 0, n: 'brown heart'},
	{c: '🖤', g: 0, n: 'black heart'},
	{c: '🩶', g: 0, n: 'grey heart'},
	{c: '🤍', g: 0, n: 'white heart'},
	{c: '💋', g: 0, n: 'kiss mark'},
	{c: '💯', g: 0, n: 'hundred points'},
	{c: '💢', g: 0, n: 'anger symbol'},
	{c: '🫯', g: 0, n: 'fight cloud'},
	{c: '💥', g: 0, n: 'collision'},
	{c: '💫', g: 0, n: 'dizzy'},
	{c: '💦', g: 0, n: 'sweat droplets'},
	{c: '💨', g: 0, n: 'dashing away'},
	{c: '🕳️', g: 0, n: 'hole'},
	{c: '💬', g: 0, n: 'speech balloon'},
	{c: '👁️‍🗨️', g: 0, n: 'eye in speech bubble'},
	{c: '🗨️', g: 0, n: 'left speech bubble'},
	{c: '🗯️', g: 0, n: 'right anger bubble'},
	{c: '💭', g: 0, n: 'thought balloon'},
	{c: '💤', g: 0, n: 'ZZZ'},
	{c: '👋', g: 1, n: 'waving hand'},
	{c: '🤚', g: 1, n: 'raised back of hand'},
	{c: '🖐️', g: 1, n: 'hand with fingers splayed'},
	{c: '✋', g: 1, n: 'raised hand'},
	{c: '🖖', g: 1, n: 'vulcan salute'},
	{c: '🫱', g: 1, n: 'rightwards hand'},
	{c: '🫲', g: 1, n: 'leftwards hand'},
	{c: '🫳', g: 1, n: 'palm down hand'},
	{c: '🫴', g: 1, n: 'palm up hand'},
	{c: '🫷', g: 1, n: 'leftwards pushing hand'},
	{c: '🫸', g: 1, n: 'rightwards pushing hand'},
	{c: '👌', g: 1, n: 'OK hand'},
	{c: '🤌', g: 1, n: 'pinched fingers'},
	{c: '🤏', g: 1, n: 'pinching hand'},
	{c: '✌️', g: 1, n: 'victory hand'},
	{c: '🤞', g: 1, n: 'crossed fingers'},
	{c: '🫰', g: 1, n: 'hand with index finger and thumb crossed'},
	{c: '🤟', g: 1, n: 'love-you gesture'},
	{c: '🤘', g: 1, n: 'sign of the horns'},
	{c: '🤙', g: 1, n: 'call me hand'},
	{c: '👈', g: 1, n: 'backhand index pointing left'},
	{c: '👉', g: 1, n: 'backhand index pointing right'},
	{c: '👆', g: 1, n: 'backhand index pointing up'},
	{c: '🖕', g: 1, n: 'middle finger'},
	{c: '👇', g: 1, n: 'backhand index pointing down'},
	{c: '☝️', g: 1, n: 'index pointing up'},
	{c: '🫵', g: 1, n: 'index pointing at the viewer'},
	{c: '👍', g: 1, n: 'thumbs up'},
	{c: '👎', g: 1, n: 'thumbs down'},
	{c: '✊', g: 1, n: 'raised fist'},
	{c: '👊', g: 1, n: 'oncoming fist'},
	{c: '🤛', g: 1, n: 'left-facing fist'},
	{c: '🤜', g: 1, n: 'right-facing fist'},
	{c: '👏', g: 1, n: 'clapping hands'},
	{c: '🙌', g: 1, n: 'raising hands'},
	{c: '🫶', g: 1, n: 'heart hands'},
	{c: '👐', g: 1, n: 'open hands'},
	{c: '🤲', g: 1, n: 'palms up together'},
	{c: '🤝', g: 1, n: 'handshake'},
	{c: '🙏', g: 1, n: 'folded hands'},
	{c: '✍️', g: 1, n: 'writing hand'},
	{c: '💅', g: 1, n: 'nail polish'},
	{c: '🤳', g: 1, n: 'selfie'},
	{c: '💪', g: 1, n: 'flexed biceps'},
	{c: '🦾', g: 1, n: 'mechanical arm'},
	{c: '🦿', g: 1, n: 'mechanical leg'},
	{c: '🦵', g: 1, n: 'leg'},
	{c: '🦶', g: 1, n: 'foot'},
	{c: '👂', g: 1, n: 'ear'},
	{c: '🦻', g: 1, n: 'ear with hearing aid'},
	{c: '👃', g: 1, n: 'nose'},
	{c: '🧠', g: 1, n: 'brain'},
	{c: '🫀', g: 1, n: 'anatomical heart'},
	{c: '🫁', g: 1, n: 'lungs'},
	{c: '🦷', g: 1, n: 'tooth'},
	{c: '🦴', g: 1, n: 'bone'},
	{c: '👀', g: 1, n: 'eyes'},
	{c: '👁️', g: 1, n: 'eye'},
	{c: '👅', g: 1, n: 'tongue'},
	{c: '👄', g: 1, n: 'mouth'},
	{c: '🫦', g: 1, n: 'biting lip'},
	{c: '👶', g: 1, n: 'baby'},
	{c: '🧒', g: 1, n: 'child'},
	{c: '👦', g: 1, n: 'boy'},
	{c: '👧', g: 1, n: 'girl'},
	{c: '🧑', g: 1, n: 'person'},
	{c: '👱', g: 1, n: 'person: blond hair'},
	{c: '👨', g: 1, n: 'man'},
	{c: '🧔', g: 1, n: 'person: beard'},
	{c: '🧔‍♂️', g: 1, n: 'man: beard'},
	{c: '🧔‍♀️', g: 1, n: 'woman: beard'},
	{c: '👨‍🦰', g: 1, n: 'man: red hair'},
	{c: '👨‍🦱', g: 1, n: 'man: curly hair'},
	{c: '👨‍🦳', g: 1, n: 'man: white hair'},
	{c: '👨‍🦲', g: 1, n: 'man: bald'},
	{c: '👩', g: 1, n: 'woman'},
	{c: '👩‍🦰', g: 1, n: 'woman: red hair'},
	{c: '🧑‍🦰', g: 1, n: 'person: red hair'},
	{c: '👩‍🦱', g: 1, n: 'woman: curly hair'},
	{c: '🧑‍🦱', g: 1, n: 'person: curly hair'},
	{c: '👩‍🦳', g: 1, n: 'woman: white hair'},
	{c: '🧑‍🦳', g: 1, n: 'person: white hair'},
	{c: '👩‍🦲', g: 1, n: 'woman: bald'},
	{c: '🧑‍🦲', g: 1, n: 'person: bald'},
	{c: '👱‍♀️', g: 1, n: 'woman: blond hair'},
	{c: '👱‍♂️', g: 1, n: 'man: blond hair'},
	{c: '🧓', g: 1, n: 'older person'},
	{c: '👴', g: 1, n: 'old man'},
	{c: '👵', g: 1, n: 'old woman'},
	{c: '🙍', g: 1, n: 'person frowning'},
	{c: '🙍‍♂️', g: 1, n: 'man frowning'},
	{c: '🙍‍♀️', g: 1, n: 'woman frowning'},
	{c: '🙎', g: 1, n: 'person pouting'},
	{c: '🙎‍♂️', g: 1, n: 'man pouting'},
	{c: '🙎‍♀️', g: 1, n: 'woman pouting'},
	{c: '🙅', g: 1, n: 'person gesturing NO'},
	{c: '🙅‍♂️', g: 1, n: 'man gesturing NO'},
	{c: '🙅‍♀️', g: 1, n: 'woman gesturing NO'},
	{c: '🙆', g: 1, n: 'person gesturing OK'},
	{c: '🙆‍♂️', g: 1, n: 'man gesturing OK'},
	{c: '🙆‍♀️', g: 1, n: 'woman gesturing OK'},
	{c: '💁', g: 1, n: 'person tipping hand'},
	{c: '💁‍♂️', g: 1, n: 'man tipping hand'},
	{c: '💁‍♀️', g: 1, n: 'woman tipping hand'},
	{c: '🙋', g: 1, n: 'person raising hand'},
	{c: '🙋‍♂️', g: 1, n: 'man raising hand'},
	{c: '🙋‍♀️', g: 1, n: 'woman raising hand'},
	{c: '🧏', g: 1, n: 'deaf person'},
	{c: '🧏‍♂️', g: 1, n: 'deaf man'},
	{c: '🧏‍♀️', g: 1, n: 'deaf woman'},
	{c: '🙇', g: 1, n: 'person bowing'},
	{c: '🙇‍♂️', g: 1, n: 'man bowing'},
	{c: '🙇‍♀️', g: 1, n: 'woman bowing'},
	{c: '🤦', g: 1, n: 'person facepalming'},
	{c: '🤦‍♂️', g: 1, n: 'man facepalming'},
	{c: '🤦‍♀️', g: 1, n: 'woman facepalming'},
	{c: '🤷', g: 1, n: 'person shrugging'},
	{c: '🤷‍♂️', g: 1, n: 'man shrugging'},
	{c: '🤷‍♀️', g: 1, n: 'woman shrugging'},
	{c: '🧑‍⚕️', g: 1, n: 'health worker'},
	{c: '👨‍⚕️', g: 1, n: 'man health worker'},
	{c: '👩‍⚕️', g: 1, n: 'woman health worker'},
	{c: '🧑‍🎓', g: 1, n: 'student'},
	{c: '👨‍🎓', g: 1, n: 'man student'},
	{c: '👩‍🎓', g: 1, n: 'woman student'},
	{c: '🧑‍🏫', g: 1, n: 'teacher'},
	{c: '👨‍🏫', g: 1, n: 'man teacher'},
	{c: '👩‍🏫', g: 1, n: 'woman teacher'},
	{c: '🧑‍⚖️', g: 1, n: 'judge'},
	{c: '👨‍⚖️', g: 1, n: 'man judge'},
	{c: '👩‍⚖️', g: 1, n: 'woman judge'},
	{c: '🧑‍🌾', g: 1, n: 'farmer'},
	{c: '👨‍🌾', g: 1, n: 'man farmer'},
	{c: '👩‍🌾', g: 1, n: 'woman farmer'},
	{c: '🧑‍🍳', g: 1, n: 'cook'},
	{c: '👨‍🍳', g: 1, n: 'man cook'},
	{c: '👩‍🍳', g: 1, n: 'woman cook'},
	{c: '🧑‍🔧', g: 1, n: 'mechanic'},
	{c: '👨‍🔧', g: 1, n: 'man mechanic'},
	{c: '👩‍🔧', g: 1, n: 'woman mechanic'},
	{c: '🧑‍🏭', g: 1, n: 'factory worker'},
	{c: '👨‍🏭', g: 1, n: 'man factory worker'},
	{c: '👩‍🏭', g: 1, n: 'woman factory worker'},
	{c: '🧑‍💼', g: 1, n: 'office worker'},
	{c: '👨‍💼', g: 1, n: 'man office worker'},
	{c: '👩‍💼', g: 1, n: 'woman office worker'},
	{c: '🧑‍🔬', g: 1, n: 'scientist'},
	{c: '👨‍🔬', g: 1, n: 'man scientist'},
	{c: '👩‍🔬', g: 1, n: 'woman scientist'},
	{c: '🧑‍💻', g: 1, n: 'technologist'},
	{c: '👨‍💻', g: 1, n: 'man technologist'},
	{c: '👩‍💻', g: 1, n: 'woman technologist'},
	{c: '🧑‍🎤', g: 1, n: 'singer'},
	{c: '👨‍🎤', g: 1, n: 'man singer'},
	{c: '👩‍🎤', g: 1, n: 'woman singer'},
	{c: '🧑‍🎨', g: 1, n: 'artist'},
	{c: '👨‍🎨', g: 1, n: 'man artist'},
	{c: '👩‍🎨', g: 1, n: 'woman artist'},
	{c: '🧑‍✈️', g: 1, n: 'pilot'},
	{c: '👨‍✈️', g: 1, n: 'man pilot'},
	{c: '👩‍✈️', g: 1, n: 'woman pilot'},
	{c: '🧑‍🚀', g: 1, n: 'astronaut'},
	{c: '👨‍🚀', g: 1, n: 'man astronaut'},
	{c: '👩‍🚀', g: 1, n: 'woman astronaut'},
	{c: '🧑‍🚒', g: 1, n: 'firefighter'},
	{c: '👨‍🚒', g: 1, n: 'man firefighter'},
	{c: '👩‍🚒', g: 1, n: 'woman firefighter'},
	{c: '👮', g: 1, n: 'police officer'},
	{c: '👮‍♂️', g: 1, n: 'man police officer'},
	{c: '👮‍♀️', g: 1, n: 'woman police officer'},
	{c: '🕵️', g: 1, n: 'detective'},
	{c: '🕵️‍♂️', g: 1, n: 'man detective'},
	{c: '🕵️‍♀️', g: 1, n: 'woman detective'},
	{c: '💂', g: 1, n: 'guard'},
	{c: '💂‍♂️', g: 1, n: 'man guard'},
	{c: '💂‍♀️', g: 1, n: 'woman guard'},
	{c: '🥷', g: 1, n: 'ninja'},
	{c: '👷', g: 1, n: 'construction worker'},
	{c: '👷‍♂️', g: 1, n: 'man construction worker'},
	{c: '👷‍♀️', g: 1, n: 'woman construction worker'},
	{c: '🫅', g: 1, n: 'person with crown'},
	{c: '🤴', g: 1, n: 'prince'},
	{c: '👸', g: 1, n: 'princess'},
	{c: '👳', g: 1, n: 'person wearing turban'},
	{c: '👳‍♂️', g: 1, n: 'man wearing turban'},
	{c: '👳‍♀️', g: 1, n: 'woman wearing turban'},
	{c: '👲', g: 1, n: 'person with skullcap'},
	{c: '🧕', g: 1, n: 'woman with headscarf'},
	{c: '🤵', g: 1, n: 'person in tuxedo'},
	{c: '🤵‍♂️', g: 1, n: 'man in tuxedo'},
	{c: '🤵‍♀️', g: 1, n: 'woman in tuxedo'},
	{c: '👰', g: 1, n: 'person with veil'},
	{c: '👰‍♂️', g: 1, n: 'man with veil'},
	{c: '👰‍♀️', g: 1, n: 'woman with veil'},
	{c: '🤰', g: 1, n: 'pregnant woman'},
	{c: '🫃', g: 1, n: 'pregnant man'},
	{c: '🫄', g: 1, n: 'pregnant person'},
	{c: '🤱', g: 1, n: 'breast-feeding'},
	{c: '👩‍🍼', g: 1, n: 'woman feeding baby'},
	{c: '👨‍🍼', g: 1, n: 'man feeding baby'},
	{c: '🧑‍🍼', g: 1, n: 'person feeding baby'},
	{c: '👼', g: 1, n: 'baby angel'},
	{c: '🎅', g: 1, n: 'Santa Claus'},
	{c: '🤶', g: 1, n: 'Mrs. Claus'},
	{c: '🧑‍🎄', g: 1, n: 'Mx Claus'},
	{c: '🦸', g: 1, n: 'superhero'},
	{c: '🦸‍♂️', g: 1, n: 'man superhero'},
	{c: '🦸‍♀️', g: 1, n: 'woman superhero'},
	{c: '🦹', g: 1, n: 'supervillain'},
	{c: '🦹‍♂️', g: 1, n: 'man supervillain'},
	{c: '🦹‍♀️', g: 1, n: 'woman supervillain'},
	{c: '🧙', g: 1, n: 'mage'},
	{c: '🧙‍♂️', g: 1, n: 'man mage'},
	{c: '🧙‍♀️', g: 1, n: 'woman mage'},
	{c: '🧚', g: 1, n: 'fairy'},
	{c: '🧚‍♂️', g: 1, n: 'man fairy'},
	{c: '🧚‍♀️', g: 1, n: 'woman fairy'},
	{c: '🧛', g: 1, n: 'vampire'},
	{c: '🧛‍♂️', g: 1, n: 'man vampire'},
	{c: '🧛‍♀️', g: 1, n: 'woman vampire'},
	{c: '🧜', g: 1, n: 'merperson'},
	{c: '🧜‍♂️', g: 1, n: 'merman'},
	{c: '🧜‍♀️', g: 1, n: 'mermaid'},
	{c: '🧝', g: 1, n: 'elf'},
	{c: '🧝‍♂️', g: 1, n: 'man elf'},
	{c: '🧝‍♀️', g: 1, n: 'woman elf'},
	{c: '🧞', g: 1, n: 'genie'},
	{c: '🧞‍♂️', g: 1, n: 'man genie'},
	{c: '🧞‍♀️', g: 1, n: 'woman genie'},
	{c: '🧟', g: 1, n: 'zombie'},
	{c: '🧟‍♂️', g: 1, n: 'man zombie'},
	{c: '🧟‍♀️', g: 1, n: 'woman zombie'},
	{c: '🧌', g: 1, n: 'troll'},
	{c: '🫈', g: 1, n: 'hairy creature'},
	{c: '💆', g: 1, n: 'person getting massage'},
	{c: '💆‍♂️', g: 1, n: 'man getting massage'},
	{c: '💆‍♀️', g: 1, n: 'woman getting massage'},
	{c: '💇', g: 1, n: 'person getting haircut'},
	{c: '💇‍♂️', g: 1, n: 'man getting haircut'},
	{c: '💇‍♀️', g: 1, n: 'woman getting haircut'},
	{c: '🚶', g: 1, n: 'person walking'},
	{c: '🚶‍♂️', g: 1, n: 'man walking'},
	{c: '🚶‍♀️', g: 1, n: 'woman walking'},
	{c: '🚶‍➡️', g: 1, n: 'person walking facing right'},
	{c: '🚶‍♀️‍➡️', g: 1, n: 'woman walking facing right'},
	{c: '🚶‍♂️‍➡️', g: 1, n: 'man walking facing right'},
	{c: '🧍', g: 1, n: 'person standing'},
	{c: '🧍‍♂️', g: 1, n: 'man standing'},
	{c: '🧍‍♀️', g: 1, n: 'woman standing'},
	{c: '🧎', g: 1, n: 'person kneeling'},
	{c: '🧎‍♂️', g: 1, n: 'man kneeling'},
	{c: '🧎‍♀️', g: 1, n: 'woman kneeling'},
	{c: '🧎‍➡️', g: 1, n: 'person kneeling facing right'},
	{c: '🧎‍♀️‍➡️', g: 1, n: 'woman kneeling facing right'},
	{c: '🧎‍♂️‍➡️', g: 1, n: 'man kneeling facing right'},
	{c: '🧑‍🦯', g: 1, n: 'person with white cane'},
	{c: '🧑‍🦯‍➡️', g: 1, n: 'person with white cane facing right'},
	{c: '👨‍🦯', g: 1, n: 'man with white cane'},
	{c: '👨‍🦯‍➡️', g: 1, n: 'man with white cane facing right'},
	{c: '👩‍🦯', g: 1, n: 'woman with white cane'},
	{c: '👩‍🦯‍➡️', g: 1, n: 'woman with white cane facing right'},
	{c: '🧑‍🦼', g: 1, n: 'person in motorized wheelchair'},
	{c: '🧑‍🦼‍➡️', g: 1, n: 'person in motorized wheelchair facing right'},
	{c: '👨‍🦼', g: 1, n: 'man in motorized wheelchair'},
	{c: '👨‍🦼‍➡️', g: 1, n: 'man in motorized wheelchair facing right'},
	{c: '👩‍🦼', g: 1, n: 'woman in motorized wheelchair'},
	{c: '👩‍🦼‍➡️', g: 1, n: 'woman in motorized wheelchair facing right'},
	{c: '🧑‍🦽', g: 1, n: 'person in manual wheelchair'},
	{c: '🧑‍🦽‍➡️', g: 1, n: 'person in manual wheelchair facing right'},
	{c: '👨‍🦽', g: 1, n: 'man in manual wheelchair'},
	{c: '👨‍🦽‍➡️', g: 1, n: 'man in manual wheelchair facing right'},
	{c: '👩‍🦽', g: 1, n: 'woman in manual wheelchair'},
	{c: '👩‍🦽‍➡️', g: 1, n: 'woman in manual wheelchair facing right'},
	{c: '🏃', g: 1, n: 'person running'},
	{c: '🏃‍♂️', g: 1, n: 'man running'},
	{c: '🏃‍♀️', g: 1, n: 'woman running'},
	{c: '🏃‍➡️', g: 1, n: 'person running facing right'},
	{c: '🏃‍♀️‍➡️', g: 1, n: 'woman running facing right'},
	{c: '🏃‍♂️‍➡️', g: 1, n: 'man running facing right'},
	{c: '🧑‍🩰', g: 1, n: 'ballet dancer'},
	{c: '💃', g: 1, n: 'woman dancing'},
	{c: '🕺', g: 1, n: 'man dancing'},
	{c: '🕴️', g: 1, n: 'person in suit levitating'},
	{c: '👯', g: 1, n: 'people with bunny ears'},
	{c: '👯‍♂️', g: 1, n: 'men with bunny ears'},
	{c: '👯‍♀️', g: 1, n: 'women with bunny ears'},
	{c: '🧖', g: 1, n: 'person in steamy room'},
	{c: '🧖‍♂️', g: 1, n: 'man in steamy room'},
	{c: '🧖‍♀️', g: 1, n: 'woman in steamy room'},
	{c: '🧗', g: 1, n: 'person climbing'},
	{c: '🧗‍♂️', g: 1, n: 'man climbing'},
	{c: '🧗‍♀️', g: 1, n: 'woman climbing'},
	{c: '🤺', g: 1, n: 'person fencing'},
	{c: '🏇', g: 1, n: 'horse racing'},
	{c: '⛷️', g: 1, n: 'skier'},
	{c: '🏂', g: 1, n: 'snowboarder'},
	{c: '🏌️', g: 1, n: 'person golfing'},
	{c: '🏌️‍♂️', g: 1, n: 'man golfing'},
	{c: '🏌️‍♀️', g: 1, n: 'woman golfing'},
	{c: '🏄', g: 1, n: 'person surfing'},
	{c: '🏄‍♂️', g: 1, n: 'man surfing'},
	{c: '🏄‍♀️', g: 1, n: 'woman surfing'},
	{c: '🚣', g: 1, n: 'person rowing boat'},
	{c: '🚣‍♂️', g: 1, n: 'man rowing boat'},
	{c: '🚣‍♀️', g: 1, n: 'woman rowing boat'},
	{c: '🏊', g: 1, n: 'person swimming'},
	{c: '🏊‍♂️', g: 1, n: 'man swimming'},
	{c: '🏊‍♀️', g: 1, n: 'woman swimming'},
	{c: '⛹️', g: 1, n: 'person bouncing ball'},
	{c: '⛹️‍♂️', g: 1, n: 'man bouncing ball'},
	{c: '⛹️‍♀️', g: 1, n: 'woman bouncing ball'},
	{c: '🏋️', g: 1, n: 'person lifting weights'},
	{c: '🏋️‍♂️', g: 1, n: 'man lifting weights'},
	{c: '🏋️‍♀️', g: 1, n: 'woman lifting weights'},
	{c: '🚴', g: 1, n: 'person biking'},
	{c: '🚴‍♂️', g: 1, n: 'man biking'},
	{c: '🚴‍♀️', g: 1, n: 'woman biking'},
	{c: '🚵', g: 1, n: 'person mountain biking'},
	{c: '🚵‍♂️', g: 1, n: 'man mountain biking'},
	{c: '🚵‍♀️', g: 1, n: 'woman mountain biking'},
	{c: '🤸', g: 1, n: 'person cartwheeling'},
	{c: '🤸‍♂️', g: 1, n: 'man cartwheeling'},
	{c: '🤸‍♀️', g: 1, n: 'woman cartwheeling'},
	{c: '🤼', g: 1, n: 'people wrestling'},
	{c: '🤼‍♂️', g: 1, n: 'men wrestling'},
	{c: '🤼‍♀️', g: 1, n: 'women wrestling'},
	{c: '🤽', g: 1, n: 'person playing water polo'},
	{c: '🤽‍♂️', g: 1, n: 'man playing water polo'},
	{c: '🤽‍♀️', g: 1, n: 'woman playing water polo'},
	{c: '🤾', g: 1, n: 'person playing handball'},
	{c: '🤾‍♂️', g: 1, n: 'man playing handball'},
	{c: '🤾‍♀️', g: 1, n: 'woman playing handball'},
	{c: '🤹', g: 1, n: 'person juggling'},
	{c: '🤹‍♂️', g: 1, n: 'man juggling'},
	{c: '🤹‍♀️', g: 1, n: 'woman juggling'},
	{c: '🧘', g: 1, n: 'person in lotus position'},
	{c: '🧘‍♂️', g: 1, n: 'man in lotus position'},
	{c: '🧘‍♀️', g: 1, n: 'woman in lotus position'},
	{c: '🛀', g: 1, n: 'person taking bath'},
	{c: '🛌', g: 1, n: 'person in bed'},
	{c: '🧑‍🤝‍🧑', g: 1, n: 'people holding hands'},
	{c: '👭', g: 1, n: 'women holding hands'},
	{c: '👫', g: 1, n: 'woman and man holding hands'},
	{c: '👬', g: 1, n: 'men holding hands'},
	{c: '💏', g: 1, n: 'kiss'},
	{c: '👩‍❤️‍💋‍👨', g: 1, n: 'kiss: woman, man'},
	{c: '👨‍❤️‍💋‍👨', g: 1, n: 'kiss: man, man'},
	{c: '👩‍❤️‍💋‍👩', g: 1, n: 'kiss: woman, woman'},
	{c: '💑', g: 1, n: 'couple with heart'},
	{c: '👩‍❤️‍👨', g: 1, n: 'couple with heart: woman, man'},
	{c: '👨‍❤️‍👨', g: 1, n: 'couple with heart: man, man'},
	{c: '👩‍❤️‍👩', g: 1, n: 'couple with heart: woman, woman'},
	{c: '👨‍👩‍👦', g: 1, n: 'family: man, woman, boy'},
	{c: '👨‍👩‍👧', g: 1, n: 'family: man, woman, girl'},
	{c: '👨‍👩‍👧‍👦', g: 1, n: 'family: man, woman, girl, boy'},
	{c: '👨‍👩‍👦‍👦', g: 1, n: 'family: man, woman, boy, boy'},
	{c: '👨‍👩‍👧‍👧', g: 1, n: 'family: man, woman, girl, girl'},
	{c: '👨‍👨‍👦', g: 1, n: 'family: man, man, boy'},
	{c: '👨‍👨‍👧', g: 1, n: 'family: man, man, girl'},
	{c: '👨‍👨‍👧‍👦', g: 1, n: 'family: man, man, girl, boy'},
	{c: '👨‍👨‍👦‍👦', g: 1, n: 'family: man, man, boy, boy'},
	{c: '👨‍👨‍👧‍👧', g: 1, n: 'family: man, man, girl, girl'},
	{c: '👩‍👩‍👦', g: 1, n: 'family: woman, woman, boy'},
	{c: '👩‍👩‍👧', g: 1, n: 'family: woman, woman, girl'},
	{c: '👩‍👩‍👧‍👦', g: 1, n: 'family: woman, woman, girl, boy'},
	{c: '👩‍👩‍👦‍👦', g: 1, n: 'family: woman, woman, boy, boy'},
	{c: '👩‍👩‍👧‍👧', g: 1, n: 'family: woman, woman, girl, girl'},
	{c: '👨‍👦', g: 1, n: 'family: man, boy'},
	{c: '👨‍👦‍👦', g: 1, n: 'family: man, boy, boy'},
	{c: '👨‍👧', g: 1, n: 'family: man, girl'},
	{c: '👨‍👧‍👦', g: 1, n: 'family: man, girl, boy'},
	{c: '👨‍👧‍👧', g: 1, n: 'family: man, girl, girl'},
	{c: '👩‍👦', g: 1, n: 'family: woman, boy'},
	{c: '👩‍👦‍👦', g: 1, n: 'family: woman, boy, boy'},
	{c: '👩‍👧', g: 1, n: 'family: woman, girl'},
	{c: '👩‍👧‍👦', g: 1, n: 'family: woman, girl, boy'},
	{c: '👩‍👧‍👧', g: 1, n: 'family: woman, girl, girl'},
	{c: '🗣️', g: 1, n: 'speaking head'},
	{c: '👤', g: 1, n: 'bust in silhouette'},
	{c: '👥', g: 1, n: 'busts in silhouette'},
	{c: '🫂', g: 1, n: 'people hugging'},
	{c: '👪', g: 1, n: 'family'},
	{c: '🧑‍🧑‍🧒', g: 1, n: 'family: adult, adult, child'},
	{c: '🧑‍🧑‍🧒‍🧒', g: 1, n: 'family: adult, adult, child, child'},
	{c: '🧑‍🧒', g: 1, n: 'family: adult, child'},
	{c: '🧑‍🧒‍🧒', g: 1, n: 'family: adult, child, child'},
	{c: '👣', g: 1, n: 'footprints'},
	{c: '🫆', g: 1, n: 'fingerprint'},
	{c: '🐵', g: 2, n: 'monkey face'},
	{c: '🐒', g: 2, n: 'monkey'},
	{c: '🦍', g: 2, n: 'gorilla'},
	{c: '🦧', g: 2, n: 'orangutan'},
	{c: '🐶', g: 2, n: 'dog face'},
	{c: '🐕', g: 2, n: 'dog'},
	{c: '🦮', g: 2, n: 'guide dog'},
	{c: '🐕‍🦺', g: 2, n: 'service dog'},
	{c: '🐩', g: 2, n: 'poodle'},
	{c: '🐺', g: 2, n: 'wolf'},
	{c: '🦊', g: 2, n: 'fox'},
	{c: '🦝', g: 2, n: 'raccoon'},
	{c: '🐱', g: 2, n: 'cat face'},
	{c: '🐈', g: 2, n: 'cat'},
	{c: '🐈‍⬛', g: 2, n: 'black cat'},
	{c: '🦁', g: 2, n: 'lion'},
	{c: '🐯', g: 2, n: 'tiger face'},
	{c: '🐅', g: 2, n: 'tiger'},
	{c: '🐆', g: 2, n: 'leopard'},
	{c: '🐴', g: 2, n: 'horse face'},
	{c: '🫎', g: 2, n: 'moose'},
	{c: '🫏', g: 2, n: 'donkey'},
	{c: '🐎', g: 2, n: 'horse'},
	{c: '🦄', g: 2, n: 'unicorn'},
	{c: '🦓', g: 2, n: 'zebra'},
	{c: '🦌', g: 2, n: 'deer'},
	{c: '🦬', g: 2, n: 'bison'},
	{c: '🐮', g: 2, n: 'cow face'},
	{c: '🐂', g: 2, n: 'ox'},
	{c: '🐃', g: 2, n: 'water buffalo'},
	{c: '🐄', g: 2, n: 'cow'},
	{c: '🐷', g: 2, n: 'pig face'},
	{c: '🐖', g: 2, n: 'pig'},
	{c: '🐗', g: 2, n: 'boar'},
	{c: '🐽', g: 2, n: 'pig nose'},
	{c: '🐏', g: 2, n: 'ram'},
	{c: '🐑', g: 2, n: 'ewe'},
	{c: '🐐', g: 2, n: 'goat'},
	{c: '🐪', g: 2, n: 'camel'},
	{c: '🐫', g: 2, n: 'two-hump camel'},
	{c: '🦙', g: 2, n: 'llama'},
	{c: '🦒', g: 2, n: 'giraffe'},
	{c: '🐘', g: 2, n: 'elephant'},
	{c: '🦣', g: 2, n: 'mammoth'},
	{c: '🦏', g: 2, n: 'rhinoceros'},
	{c: '🦛', g: 2, n: 'hippopotamus'},
	{c: '🐭', g: 2, n: 'mouse face'},
	{c: '🐁', g: 2, n: 'mouse'},
	{c: '🐀', g: 2, n: 'rat'},
	{c: '🐹', g: 2, n: 'hamster'},
	{c: '🐰', g: 2, n: 'rabbit face'},
	{c: '🐇', g: 2, n: 'rabbit'},
	{c: '🐿️', g: 2, n: 'chipmunk'},
	{c: '🦫', g: 2, n: 'beaver'},
	{c: '🦔', g: 2, n: 'hedgehog'},
	{c: '🦇', g: 2, n: 'bat'},
	{c: '🐻', g: 2, n: 'bear'},
	{c: '🐻‍❄️', g: 2, n: 'polar bear'},
	{c: '🐨', g: 2, n: 'koala'},
	{c: '🐼', g: 2, n: 'panda'},
	{c: '🦥', g: 2, n: 'sloth'},
	{c: '🦦', g: 2, n: 'otter'},
	{c: '🦨', g: 2, n: 'skunk'},
	{c: '🦘', g: 2, n: 'kangaroo'},
	{c: '🦡', g: 2, n: 'badger'},
	{c: '🐾', g: 2, n: 'paw prints'},
	{c: '🦃', g: 2, n: 'turkey'},
	{c: '🐔', g: 2, n: 'chicken'},
	{c: '🐓', g: 2, n: 'rooster'},
	{c: '🐣', g: 2, n: 'hatching chick'},
	{c: '🐤', g: 2, n: 'baby chick'},
	{c: '🐥', g: 2, n: 'front-facing baby chick'},
	{c: '🐦', g: 2, n: 'bird'},
	{c: '🐧', g: 2, n: 'penguin'},
	{c: '🕊️', g: 2, n: 'dove'},
	{c: '🦅', g: 2, n: 'eagle'},
	{c: '🦆', g: 2, n: 'duck'},
	{c: '🦢', g: 2, n: 'swan'},
	{c: '🦉', g: 2, n: 'owl'},
	{c: '🦤', g: 2, n: 'dodo'},
	{c: '🪶', g: 2, n: 'feather'},
	{c: '🦩', g: 2, n: 'flamingo'},
	{c: '🦚', g: 2, n: 'peacock'},
	{c: '🦜', g: 2, n: 'parrot'},
	{c: '🪽', g: 2, n: 'wing'},
	{c: '🐦‍⬛', g: 2, n: 'black bird'},
	{c: '🪿', g: 2, n: 'goose'},
	{c: '🐦‍🔥', g: 2, n: 'phoenix'},
	{c: '🐸', g: 2, n: 'frog'},
	{c: '🐊', g: 2, n: 'crocodile'},
	{c: '🐢', g: 2, n: 'turtle'},
	{c: '🦎', g: 2, n: 'lizard'},
	{c: '🐍', g: 2, n: 'snake'},
	{c: '🐲', g: 2, n: 'dragon face'},
	{c: '🐉', g: 2, n: 'dragon'},
	{c: '🦕', g: 2, n: 'sauropod'},
	{c: '🦖', g: 2, n: 'T-Rex'},
	{c: '🐳', g: 2, n: 'spouting whale'},
	{c: '🐋', g: 2, n: 'whale'},
	{c: '🐬', g: 2, n: 'dolphin'},
	{c: '🫍', g: 2, n: 'orca'},
	{c: '🦭', g: 2, n: 'seal'},
	{c: '🐟', g: 2, n: 'fish'},
	{c: '🐠', g: 2, n: 'tropical fish'},
	{c: '🐡', g: 2, n: 'blowfish'},
	{c: '🦈', g: 2, n: 'shark'},
	{c: '🐙', g: 2, n: 'octopus'},
	{c: '🐚', g: 2, n: 'spiral shell'},
	{c: '🪸', g: 2, n: 'coral'},
	{c: '🪼', g: 2, n: 'jellyfish'},
	{c: '🦀', g: 2, n: 'crab'},
	{c: '🦞', g: 2, n: 'lobster'},
	{c: '🦐', g: 2, n: 'shrimp'},
	{c: '🦑', g: 2, n: 'squid'},
	{c: '🦪', g: 2, n: 'oyster'},
	{c: '🐌', g: 2, n: 'snail'},
	{c: '🦋', g: 2, n: 'butterfly'},
	{c: '🐛', g: 2, n: 'bug'},
	{c: '🐜', g: 2, n: 'ant'},
	{c: '🐝', g: 2, n: 'honeybee'},
	{c: '🪲', g: 2, n: 'beetle'},
	{c: '🐞', g: 2, n: 'lady beetle'},
	{c: '🦗', g: 2, n: 'cricket'},
	{c: '🪳', g: 2, n: 'cockroach'},
	{c: '🕷️', g: 2, n: 'spider'},
	{c: '🕸️', g: 2, n: 'spider web'},
	{c: '🦂', g: 2, n: 'scorpion'},
	{c: '🦟', g: 2, n: 'mosquito'},
	{c: '🪰', g: 2, n: 'fly'},
	{c: '🪱', g: 2, n: 'worm'},
	{c: '🦠', g: 2, n: 'microbe'},
	{c: '💐', g: 2, n: 'bouquet'},
	{c: '🌸', g: 2, n: 'cherry blossom'},
	{c: '💮', g: 2, n: 'white flower'},
	{c: '🪷', g: 2, n: 'lotus'},
	{c: '🏵️', g: 2, n: 'rosette'},
	{c: '🌹', g: 2, n: 'rose'},
	{c: '🥀', g: 2, n: 'wilted flower'},
	{c: '🌺', g: 2, n: 'hibiscus'},
	{c: '🌻', g: 2, n: 'sunflower'},
	{c: '🌼', g: 2, n: 'blossom'},
	{c: '🌷', g: 2, n: 'tulip'},
	{c: '🪻', g: 2, n: 'hyacinth'},
	{c: '🌱', g: 2, n: 'seedling'},
	{c: '🪴', g: 2, n: 'potted plant'},
	{c: '🌲', g: 2, n: 'evergreen tree'},
	{c: '🌳', g: 2, n: 'deciduous tree'},
	{c: '🌴', g: 2, n: 'palm tree'},
	{c: '🌵', g: 2, n: 'cactus'},
	{c: '🌾', g: 2, n: 'sheaf of rice'},
	{c: '🌿', g: 2, n: 'herb'},
	{c: '☘️', g: 2, n: 'shamrock'},
	{c: '🍀', g: 2, n: 'four leaf clover'},
	{c: '🍁', g: 2, n: 'maple leaf'},
	{c: '🍂', g: 2, n: 'fallen leaf'},
	{c: '🍃', g: 2, n: 'leaf fluttering in wind'},
	{c: '🪹', g: 2, n: 'empty nest'},
	{c: '🪺', g: 2, n: 'nest with eggs'},
	{c: '🍄', g: 2, n: 'mushroom'},
	{c: '🪾', g: 2, n: 'leafless tree'},
	{c: '🍇', g: 3, n: 'grapes'},
	{c: '🍈', g: 3, n: 'melon'},
	{c: '🍉', g: 3, n: 'watermelon'},
	{c: '🍊', g: 3, n: 'tangerine'},
	{c: '🍋', g: 3, n: 'lemon'},
	{c: '🍋‍🟩', g: 3, n: 'lime'},
	{c: '🍌', g: 3, n: 'banana'},
	{c: '🍍', g: 3, n: 'pineapple'},
	{c: '🥭', g: 3, n: 'mango'},
	{c: '🍎', g: 3, n: 'red apple'},
	{c: '🍏', g: 3, n: 'green apple'},
	{c: '🍐', g: 3, n: 'pear'},
	{c: '🍑', g: 3, n: 'peach'},
	{c: '🍒', g: 3, n: 'cherries'},
	{c: '🍓', g: 3, n: 'strawberry'},
	{c: '🫐', g: 3, n: 'blueberries'},
	{c: '🥝', g: 3, n: 'kiwi fruit'},
	{c: '🍅', g: 3, n: 'tomato'},
	{c: '🫒', g: 3, n: 'olive'},
	{c: '🥥', g: 3, n: 'coconut'},
	{c: '🥑', g: 3, n: 'avocado'},
	{c: '🍆', g: 3, n: 'eggplant'},
	{c: '🥔', g: 3, n: 'potato'},
	{c: '🥕', g: 3, n: 'carrot'},
	{c: '🌽', g: 3, n: 'ear of corn'},
	{c: '🌶️', g: 3, n: 'hot pepper'},
	{c: '🫑', g: 3, n: 'bell pepper'},
	{c: '🥒', g: 3, n: 'cucumber'},
	{c: '🥬', g: 3, n: 'leafy green'},
	{c: '🥦', g: 3, n: 'broccoli'},
	{c: '🧄', g: 3, n: 'garlic'},
	{c: '🧅', g: 3, n: 'onion'},
	{c: '🥜', g: 3, n: 'peanuts'},
	{c: '🫘', g: 3, n: 'beans'},
	{c: '🌰', g: 3, n: 'chestnut'},
	{c: '🫚', g: 3, n: 'ginger root'},
	{c: '🫛', g: 3, n: 'pea pod'},
	{c: '🍄‍🟫', g: 3, n: 'brown mushroom'},
	{c: '🫜', g: 3, n: 'root vegetable'},
	{c: '🍞', g: 3, n: 'bread'},
	{c: '🥐', g: 3, n: 'croissant'},
	{c: '🥖', g: 3, n: 'baguette bread'},
	{c: '🫓', g: 3, n: 'flatbread'},
	{c: '🥨', g: 3, n: 'pretzel'},
	{c: '🥯', g: 3, n: 'bagel'},
	{c: '🥞', g: 3, n: 'pancakes'},
	{c: '🧇', g: 3, n: 'waffle'},
	{c: '🧀', g: 3, n: 'cheese wedge'},
	{c: '🍖', g: 3, n: 'meat on bone'},
	{c: '🍗', g: 3, n: 'poultry leg'},
	{c: '🥩', g: 3, n: 'cut of meat'},
	{c: '🥓', g: 3, n: 'bacon'},
	{c: '🍔', g: 3, n: 'hamburger'},
	{c: '🍟', g: 3, n: 'french fries'},
	{c: '🍕', g: 3, n: 'pizza'},
	{c: '🌭', g: 3, n: 'hot dog'},
	{c: '🥪', g: 3, n: 'sandwich'},
	{c: '🌮', g: 3, n: 'taco'},
	{c: '🌯', g: 3, n: 'burrito'},
	{c: '🫔', g: 3, n: 'tamale'},
	{c: '🥙', g: 3, n: 'stuffed flatbread'},
	{c: '🧆', g: 3, n: 'falafel'},
	{c: '🥚', g: 3, n: 'egg'},
	{c: '🍳', g: 3, n: 'cooking'},
	{c: '🥘', g: 3, n: 'shallow pan of food'},
	{c: '🍲', g: 3, n: 'pot of food'},
	{c: '🫕', g: 3, n: 'fondue'},
	{c: '🥣', g: 3, n: 'bowl with spoon'},
	{c: '🥗', g: 3, n: 'green salad'},
	{c: '🍿', g: 3, n: 'popcorn'},
	{c: '🧈', g: 3, n: 'butter'},
	{c: '🧂', g: 3, n: 'salt'},
	{c: '🥫', g: 3, n: 'canned food'},
	{c: '🍱', g: 3, n: 'bento box'},
	{c: '🍘', g: 3, n: 'rice cracker'},
	{c: '🍙', g: 3, n: 'rice ball'},
	{c: '🍚', g: 3, n: 'cooked rice'},
	{c: '🍛', g: 3, n: 'curry rice'},
	{c: '🍜', g: 3, n: 'steaming bowl'},
	{c: '🍝', g: 3, n: 'spaghetti'},
	{c: '🍠', g: 3, n: 'roasted sweet potato'},
	{c: '🍢', g: 3, n: 'oden'},
	{c: '🍣', g: 3, n: 'sushi'},
	{c: '🍤', g: 3, n: 'fried shrimp'},
	{c: '🍥', g: 3, n: 'fish cake with swirl'},
	{c: '🥮', g: 3, n: 'moon cake'},
	{c: '🍡', g: 3, n: 'dango'},
	{c: '🥟', g: 3, n: 'dumpling'},
	{c: '🥠', g: 3, n: 'fortune cookie'},
	{c: '🥡', g: 3, n: 'takeout box'},
	{c: '🍦', g: 3, n: 'soft ice cream'},
	{c: '🍧', g: 3, n: 'shaved ice'},
	{c: '🍨', g: 3, n: 'ice cream'},
	{c: '🍩', g: 3, n: 'doughnut'},
	{c: '🍪', g: 3, n: 'cookie'},
	{c: '🎂', g: 3, n: 'birthday cake'},
	{c: '🍰', g: 3, n: 'shortcake'},
	{c: '🧁', g: 3, n: 'cupcake'},
	{c: '🥧', g: 3, n: 'pie'},
	{c: '🍫', g: 3, n: 'chocolate bar'},
	{c: '🍬', g: 3, n: 'candy'},
	{c: '🍭', g: 3, n: 'lollipop'},
	{c: '🍮', g: 3, n: 'custard'},
	{c: '🍯', g: 3, n: 'honey pot'},
	{c: '🍼', g: 3, n: 'baby bottle'},
	{c: '🥛', g: 3, n: 'glass of milk'},
	{c: '☕', g: 3, n: 'hot beverage'},
	{c: '🫖', g: 3, n: 'teapot'},
	{c: '🍵', g: 3, n: 'teacup without handle'},
	{c: '🍶', g: 3, n: 'sake'},
	{c: '🍾', g: 3, n: 'bottle with popping cork'},
	{c: '🍷', g: 3, n: 'wine glass'},
	{c: '🍸', g: 3, n: 'cocktail glass'},
	{c: '🍹', g: 3, n: 'tropical drink'},
	{c: '🍺', g: 3, n: 'beer mug'},
	{c: '🍻', g: 3, n: 'clinking beer mugs'},
	{c: '🥂', g: 3, n: 'clinking glasses'},
	{c: '🥃', g: 3, n: 'tumbler glass'},
	{c: '🫗', g: 3, n: 'pouring liquid'},
	{c: '🥤', g: 3, n: 'cup with straw'},
	{c: '🧋', g: 3, n: 'bubble tea'},
	{c: '🧃', g: 3, n: 'beverage box'},
	{c: '🧉', g: 3, n: 'mate'},
	{c: '🧊', g: 3, n: 'ice'},
	{c: '🥢', g: 3, n: 'chopsticks'},
	{c: '🍽️', g: 3, n: 'fork and knife with plate'},
	{c: '🍴', g: 3, n: 'fork and knife'},
	{c: '🥄', g: 3, n: 'spoon'},
	{c: '🔪', g: 3, n: 'kitchen knife'},
	{c: '🫙', g: 3, n: 'jar'},
	{c: '🏺', g: 3, n: 'amphora'},
	{c: '🌍', g: 4, n: 'globe showing Europe-Africa'},
	{c: '🌎', g: 4, n: 'globe showing Americas'},
	{c: '🌏', g: 4, n: 'globe showing Asia-Australia'},
	{c: '🌐', g: 4, n: 'globe with meridians'},
	{c: '🗺️', g: 4, n: 'world map'},
	{c: '🗾', g: 4, n: 'map of Japan'},
	{c: '🧭', g: 4, n: 'compass'},
	{c: '🏔️', g: 4, n: 'snow-capped mountain'},
	{c: '⛰️', g: 4, n: 'mountain'},
	{c: '🛘', g: 4, n: 'landslide'},
	{c: '🌋', g: 4, n: 'volcano'},
	{c: '🗻', g: 4, n: 'mount fuji'},
	{c: '🏕️', g: 4, n: 'camping'},
	{c: '🏖️', g: 4, n: 'beach with umbrella'},
	{c: '🏜️', g: 4, n: 'desert'},
	{c: '🏝️', g: 4, n: 'desert island'},
	{c: '🏞️', g: 4, n: 'national park'},
	{c: '🏟️', g: 4, n: 'stadium'},
	{c: '🏛️', g: 4, n: 'classical building'},
	{c: '🏗️', g: 4, n: 'building construction'},
	{c: '🧱', g: 4, n: 'brick'},
	{c: '🪨', g: 4, n: 'rock'},
	{c: '🪵', g: 4, n: 'wood'},
	{c: '🛖', g: 4, n: 'hut'},
	{c: '🏘️', g: 4, n: 'houses'},
	{c: '🏚️', g: 4, n: 'derelict house'},
	{c: '🏠', g: 4, n: 'house'},
	{c: '🏡', g: 4, n: 'house with garden'},
	{c: '🏢', g: 4, n: 'office building'},
	{c: '🏣', g: 4, n: 'Japanese post office'},
	{c: '🏤', g: 4, n: 'post office'},
	{c: '🏥', g: 4, n: 'hospital'},
	{c: '🏦', g: 4, n: 'bank'},
	{c: '🏨', g: 4, n: 'hotel'},
	{c: '🏩', g: 4, n: 'love hotel'},
	{c: '🏪', g: 4, n: 'convenience store'},
	{c: '🏫', g: 4, n: 'school'},
	{c: '🏬', g: 4, n: 'department store'},
	{c: '🏭', g: 4, n: 'factory'},
	{c: '🏯', g: 4, n: 'Japanese castle'},
	{c: '🏰', g: 4, n: 'castle'},
	{c: '💒', g: 4, n: 'wedding'},
	{c: '🗼', g: 4, n: 'Tokyo tower'},
	{c: '🗽', g: 4, n: 'Statue of Liberty'},
	{c: '⛪', g: 4, n: 'church'},
	{c: '🕌', g: 4, n: 'mosque'},
	{c: '🛕', g: 4, n: 'hindu temple'},
	{c: '🕍', g: 4, n: 'synagogue'},
	{c: '⛩️', g: 4, n: 'shinto shrine'},
	{c: '🕋', g: 4, n: 'kaaba'},
	{c: '⛲', g: 4, n: 'fountain'},
	{c: '⛺', g: 4, n: 'tent'},
	{c: '🌁', g: 4, n: 'foggy'},
	{c: '🌃', g: 4, n: 'night with stars'},
	{c: '🏙️', g: 4, n: 'cityscape'},
	{c: '🌄', g: 4, n: 'sunrise over mountains'},
	{c: '🌅', g: 4, n: 'sunrise'},
	{c: '🌆', g: 4, n: 'cityscape at dusk'},
	{c: '🌇', g: 4, n: 'sunset'},
	{c: '🌉', g: 4, n: 'bridge at night'},
	{c: '♨️', g: 4, n: 'hot springs'},
	{c: '🎠', g: 4, n: 'carousel horse'},
	{c: '🛝', g: 4, n: 'playground slide'},
	{c: '🎡', g: 4, n: 'ferris wheel'},
	{c: '🎢', g: 4, n: 'roller coaster'},
	{c: '💈', g: 4, n: 'barber pole'},
	{c: '🎪', g: 4, n: 'circus tent'},
	{c: '🚂', g: 4, n: 'locomotive'},
	{c: '🚃', g: 4, n: 'railway car'},
	{c: '🚄', g: 4, n: 'high-speed train'},
	{c: '🚅', g: 4, n: 'bullet train'},
	{c: '🚆', g: 4, n: 'train'},
	{c: '🚇', g: 4, n: 'metro'},
	{c: '🚈', g: 4, n: 'light rail'},
	{c: '🚉', g: 4, n: 'station'},
	{c: '🚊', g: 4, n: 'tram'},
	{c: '🚝', g: 4, n: 'monorail'},
	{c: '🚞', g: 4, n: 'mountain railway'},
	{c: '🚋', g: 4, n: 'tram car'},
	{c: '🚌', g: 4, n: 'bus'},
	{c: '🚍', g: 4, n: 'oncoming bus'},
	{c: '🚎', g: 4, n: 'trolleybus'},
	{c: '🚐', g: 4, n: 'minibus'},
	{c: '🚑', g: 4, n: 'ambulance'},
	{c: '🚒', g: 4, n: 'fire engine'},
	{c: '🚓', g: 4, n: 'police car'},
	{c: '🚔', g: 4, n: 'oncoming police car'},
	{c: '🚕', g: 4, n: 'taxi'},
	{c: '🚖', g: 4, n: 'oncoming taxi'},
	{c: '🚗', g: 4, n: 'automobile'},
	{c: '🚘', g: 4, n: 'oncoming automobile'},
	{c: '🚙', g: 4, n: 'sport utility vehicle'},
	{c: '🛻', g: 4, n: 'pickup truck'},
	{c: '🚚', g: 4, n: 'delivery truck'},
	{c: '🚛', g: 4, n: 'articulated lorry'},
	{c: '🚜', g: 4, n: 'tractor'},
	{c: '🏎️', g: 4, n: 'racing car'},
	{c: '🏍️', g: 4, n: 'motorcycle'},
	{c: '🛵', g: 4, n: 'motor scooter'},
	{c: '🦽', g: 4, n: 'manual wheelchair'},
	{c: '🦼', g: 4, n: 'motorized wheelchair'},
	{c: '🛺', g: 4, n: 'auto rickshaw'},
	{c: '🚲', g: 4, n: 'bicycle'},
	{c: '🛴', g: 4, n: 'kick scooter'},
	{c: '🛹', g: 4, n: 'skateboard'},
	{c: '🛼', g: 4, n: 'roller skate'},
	{c: '🚏', g: 4, n: 'bus stop'},
	{c: '🛣️', g: 4, n: 'motorway'},
	{c: '🛤️', g: 4, n: 'railway track'},
	{c: '🛢️', g: 4, n: 'oil drum'},
	{c: '⛽', g: 4, n: 'fuel pump'},
	{c: '🛞', g: 4, n: 'wheel'},
	{c: '🚨', g: 4, n: 'police car light'},
	{c: '🚥', g: 4, n: 'horizontal traffic light'},
	{c: '🚦', g: 4, n: 'vertical traffic light'},
	{c: '🛑', g: 4, n: 'stop sign'},
	{c: '🚧', g: 4, n: 'construction'},
	{c: '⚓', g: 4, n: 'anchor'},
	{c: '🛟', g: 4, n: 'ring buoy'},
	{c: '⛵', g: 4, n: 'sailboat'},
	{c: '🛶', g: 4, n: 'canoe'},
	{c: '🚤', g: 4, n: 'speedboat'},
	{c: '🛳️', g: 4, n: 'passenger ship'},
	{c: '⛴️', g: 4, n: 'ferry'},
	{c: '🛥️', g: 4, n: 'motor boat'},
	{c: '🚢', g: 4, n: 'ship'},
	{c: '✈️', g: 4, n: 'airplane'},
	{c: '🛩️', g: 4, n: 'small airplane'},
	{c: '🛫', g: 4, n: 'airplane departure'},
	{c: '🛬', g: 4, n: 'airplane arrival'},
	{c: '🪂', g: 4, n: 'parachute'},
	{c: '💺', g: 4, n: 'seat'},
	{c: '🚁', g: 4, n: 'helicopter'},
	{c: '🚟', g: 4, n: 'suspension railway'},
	{c: '🚠', g: 4, n: 'mountain cableway'},
	{c: '🚡', g: 4, n: 'aerial tramway'},
	{c: '🛰️', g: 4, n: 'satellite'},
	{c: '🚀', g: 4, n: 'rocket'},
	{c: '🛸', g: 4, n: 'flying saucer'},
	{c: '🛎️', g: 4, n: 'bellhop bell'},
	{c: '🧳', g: 4, n: 'luggage'},
	{c: '⌛', g: 4, n: 'hourglass done'},
	{c: '⏳', g: 4, n: 'hourglass not done'},
	{c: '⌚', g: 4, n: 'watch'},
	{c: '⏰', g: 4, n: 'alarm clock'},
	{c: '⏱️', g: 4, n: 'stopwatch'},
	{c: '⏲️', g: 4, n: 'timer clock'},
	{c: '🕰️', g: 4, n: 'mantelpiece clock'},
	{c: '🕛', g: 4, n: 'twelve o’clock'},
	{c: '🕧', g: 4, n: 'twelve-thirty'},
	{c: '🕐', g: 4, n: 'one o’clock'},
	{c: '🕜', g: 4, n: 'one-thirty'},
	{c: '🕑', g: 4, n: 'two o’clock'},
	{c: '🕝', g: 4, n: 'two-thirty'},
	{c: '🕒', g: 4, n: 'three o’clock'},
	{c: '🕞', g: 4, n: 'three-thirty'},
	{c: '🕓', g: 4, n: 'four o’clock'},
	{c: '🕟', g: 4, n: 'four-thirty'},
	{c: '🕔', g: 4, n: 'five o’clock'},
	{c: '🕠', g: 4, n: 'five-thirty'},
	{c: '🕕', g: 4, n: 'six o’clock'},
	{c: '🕡', g: 4, n: 'six-thirty'},
	{c: '🕖', g: 4, n: 'seven o’clock'},
	{c: '🕢', g: 4, n: 'seven-thirty'},
	{c: '🕗', g: 4, n: 'eight o’clock'},
	{c: '🕣', g: 4, n: 'eight-thirty'},
	{c: '🕘', g: 4, n: 'nine o’clock'},
	{c: '🕤', g: 4, n: 'nine-thirty'},
	{c: '🕙', g: 4, n: 'ten o’clock'},
	{c: '🕥', g: 4, n: 'ten-thirty'},
	{c: '🕚', g: 4, n: 'eleven o’clock'},
	{c: '🕦', g: 4, n: 'eleven-thirty'},
	{c: '🌑', g: 4, n: 'new moon'},
	{c: '🌒', g: 4, n: 'waxing crescent moon'},
	{c: '🌓', g: 4, n: 'first quarter moon'},
	{c: '🌔', g: 4, n: 'waxing gibbous moon'},
	{c: '🌕', g: 4, n: 'full moon'},
	{c: '🌖', g: 4, n: 'waning gibbous moon'},
	{c: '🌗', g: 4, n: 'last quarter moon'},
	{c: '🌘', g: 4, n: 'waning crescent moon'},
	{c: '🌙', g: 4, n: 'crescent moon'},
	{c: '🌚', g: 4, n: 'new moon face'},
	{c: '🌛', g: 4, n: 'first quarter moon face'},
	{c: '🌜', g: 4, n: 'last quarter moon face'},
	{c: '🌡️', g: 4, n: 'thermometer'},
	{c: '☀️', g: 4, n: 'sun'},
	{c: '🌝', g: 4, n: 'full moon face'},
	{c: '🌞', g: 4, n: 'sun with face'},
	{c: '🪐', g: 4, n: 'ringed planet'},
	{c: '⭐', g: 4, n: 'star'},
	{c: '🌟', g: 4, n: 'glowing star'},
	{c: '🌠', g: 4, n: 'shooting star'},
	{c: '🌌', g: 4, n: 'milky way'},
	{c: '☁️', g: 4, n: 'cloud'},
	{c: '⛅', g: 4, n: 'sun behind cloud'},
	{c: '⛈️', g: 4, n: 'cloud with lightning and rain'},
	{c: '🌤️', g: 4, n: 'sun behind small cloud'},
	{c: '🌥️', g: 4, n: 'sun behind large cloud'},
	{c: '🌦️', g: 4, n: 'sun behind rain cloud'},
	{c: '🌧️', g: 4, n: 'cloud with rain'},
	{c: '🌨️', g: 4, n: 'cloud with snow'},
	{c: '🌩️', g: 4, n: 'cloud with lightning'},
	{c: '🌪️', g: 4, n: 'tornado'},
	{c: '🌫️', g: 4, n: 'fog'},
	{c: '🌬️', g: 4, n: 'wind face'},
	{c: '🌀', g: 4, n: 'cyclone'},
	{c: '🌈', g: 4, n: 'rainbow'},
	{c: '🌂', g: 4, n: 'closed umbrella'},
	{c: '☂️', g: 4, n: 'umbrella'},
	{c: '☔', g: 4, n: 'umbrella with rain drops'},
	{c: '⛱️', g: 4, n: 'umbrella on ground'},
	{c: '⚡', g: 4, n: 'high voltage'},
	{c: '❄️', g: 4, n: 'snowflake'},
	{c: '☃️', g: 4, n: 'snowman'},
	{c: '⛄', g: 4, n: 'snowman without snow'},
	{c: '☄️', g: 4, n: 'comet'},
	{c: '🔥', g: 4, n: 'fire'},
	{c: '💧', g: 4, n: 'droplet'},
	{c: '🌊', g: 4, n: 'water wave'},
	{c: '🎃', g: 5, n: 'jack-o-lantern'},
	{c: '🎄', g: 5, n: 'Christmas tree'},
	{c: '🎆', g: 5, n: 'fireworks'},
	{c: '🎇', g: 5, n: 'sparkler'},
	{c: '🧨', g: 5, n: 'firecracker'},
	{c: '✨', g: 5, n: 'sparkles'},
	{c: '🎈', g: 5, n: 'balloon'},
	{c: '🎉', g: 5, n: 'party popper'},
	{c: '🎊', g: 5, n: 'confetti ball'},
	{c: '🎋', g: 5, n: 'tanabata tree'},
	{c: '🎍', g: 5, n: 'pine decoration'},
	{c: '🎎', g: 5, n: 'Japanese dolls'},
	{c: '🎏', g: 5, n: 'carp streamer'},
	{c: '🎐', g: 5, n: 'wind chime'},
	{c: '🎑', g: 5, n: 'moon viewing ceremony'},
	{c: '🧧', g: 5, n: 'red envelope'},
	{c: '🎀', g: 5, n: 'ribbon'},
	{c: '🎁', g: 5, n: 'wrapped gift'},
	{c: '🎗️', g: 5, n: 'reminder ribbon'},
	{c: '🎟️', g: 5, n: 'admission tickets'},
	{c: '🎫', g: 5, n: 'ticket'},
	{c: '🎖️', g: 5, n: 'military medal'},
	{c: '🏆', g: 5, n: 'trophy'},
	{c: '🏅', g: 5, n: 'sports medal'},
	{c: '🥇', g: 5, n: '1st place medal'},
	{c: '🥈', g: 5, n: '2nd place medal'},
	{c: '🥉', g: 5, n: '3rd place medal'},
	{c: '⚽', g: 5, n: 'soccer ball'},
	{c: '⚾', g: 5, n: 'baseball'},
	{c: '🥎', g: 5, n: 'softball'},
	{c: '🏀', g: 5, n: 'basketball'},
	{c: '🏐', g: 5, n: 'volleyball'},
	{c: '🏈', g: 5, n: 'american football'},
	{c: '🏉', g: 5, n: 'rugby football'},
	{c: '🎾', g: 5, n: 'tennis'},
	{c: '🥏', g: 5, n: 'flying disc'},
	{c: '🎳', g: 5, n: 'bowling'},
	{c: '🏏', g: 5, n: 'cricket game'},
	{c: '🏑', g: 5, n: 'field hockey'},
	{c: '🏒', g: 5, n: 'ice hockey'},
	{c: '🥍', g: 5, n: 'lacrosse'},
	{c: '🏓', g: 5, n: 'ping pong'},
	{c: '🏸', g: 5, n: 'badminton'},
	{c: '🥊', g: 5, n: 'boxing glove'},
	{c: '🥋', g: 5, n: 'martial arts uniform'},
	{c: '🥅', g: 5, n: 'goal net'},
	{c: '⛳', g: 5, n: 'flag in hole'},
	{c: '⛸️', g: 5, n: 'ice skate'},
	{c: '🎣', g: 5, n: 'fishing pole'},
	{c: '🤿', g: 5, n: 'diving mask'},
	{c: '🎽', g: 5, n: 'running shirt'},
	{c: '🎿', g: 5, n: 'skis'},
	{c: '🛷', g: 5, n: 'sled'},
	{c: '🥌', g: 5, n: 'curling stone'},
	{c: '🎯', g: 5, n: 'bullseye'},
	{c: '🪀', g: 5, n: 'yo-yo'},
	{c: '🪁', g: 5, n: 'kite'},
	{c: '🔫', g: 5, n: 'water pistol'},
	{c: '🎱', g: 5, n: 'pool 8 ball'},
	{c: '🔮', g: 5, n: 'crystal ball'},
	{c: '🪄', g: 5, n: 'magic wand'},
	{c: '🎮', g: 5, n: 'video game'},
	{c: '🕹️', g: 5, n: 'joystick'},
	{c: '🎰', g: 5, n: 'slot machine'},
	{c: '🎲', g: 5, n: 'game die'},
	{c: '🧩', g: 5, n: 'puzzle piece'},
	{c: '🧸', g: 5, n: 'teddy bear'},
	{c: '🪅', g: 5, n: 'piñata'},
	{c: '🪩', g: 5, n: 'mirror ball'},
	{c: '🪆', g: 5, n: 'nesting dolls'},
	{c: '♠️', g: 5, n: 'spade suit'},
	{c: '♥️', g: 5, n: 'heart suit'},
	{c: '♦️', g: 5, n: 'diamond suit'},
	{c: '♣️', g: 5, n: 'club suit'},
	{c: '♟️', g: 5, n: 'chess pawn'},
	{c: '🃏', g: 5, n: 'joker'},
	{c: '🀄', g: 5, n: 'mahjong red dragon'},
	{c: '🎴', g: 5, n: 'flower playing cards'},
	{c: '🎭', g: 5, n: 'performing arts'},
	{c: '🖼️', g: 5, n: 'framed picture'},
	{c: '🎨', g: 5, n: 'artist palette'},
	{c: '🧵', g: 5, n: 'thread'},
	{c: '🪡', g: 5, n: 'sewing needle'},
	{c: '🧶', g: 5, n: 'yarn'},
	{c: '🪢', g: 5, n: 'knot'},
	{c: '👓', g: 6, n: 'glasses'},
	{c: '🕶️', g: 6, n: 'sunglasses'},
	{c: '🥽', g: 6, n: 'goggles'},
	{c: '🥼', g: 6, n: 'lab coat'},
	{c: '🦺', g: 6, n: 'safety vest'},
	{c: '👔', g: 6, n: 'necktie'},
	{c: '👕', g: 6, n: 't-shirt'},
	{c: '👖', g: 6, n: 'jeans'},
	{c: '🧣', g: 6, n: 'scarf'},
	{c: '🧤', g: 6, n: 'gloves'},
	{c: '🧥', g: 6, n: 'coat'},
	{c: '🧦', g: 6, n: 'socks'},
	{c: '👗', g: 6, n: 'dress'},
	{c: '👘', g: 6, n: 'kimono'},
	{c: '🥻', g: 6, n: 'sari'},
	{c: '🩱', g: 6, n: 'one-piece swimsuit'},
	{c: '🩲', g: 6, n: 'briefs'},
	{c: '🩳', g: 6, n: 'shorts'},
	{c: '👙', g: 6, n: 'bikini'},
	{c: '👚', g: 6, n: 'woman’s clothes'},
	{c: '🪭', g: 6, n: 'folding hand fan'},
	{c: '👛', g: 6, n: 'purse'},
	{c: '👜', g: 6, n: 'handbag'},
	{c: '👝', g: 6, n: 'clutch bag'},
	{c: '🛍️', g: 6, n: 'shopping bags'},
	{c: '🎒', g: 6, n: 'backpack'},
	{c: '🩴', g: 6, n: 'thong sandal'},
	{c: '👞', g: 6, n: 'man’s shoe'},
	{c: '👟', g: 6, n: 'running shoe'},
	{c: '🥾', g: 6, n: 'hiking boot'},
	{c: '🥿', g: 6, n: 'flat shoe'},
	{c: '👠', g: 6, n: 'high-heeled shoe'},
	{c: '👡', g: 6, n: 'woman’s sandal'},
	{c: '🩰', g: 6, n: 'ballet shoes'},
	{c: '👢', g: 6, n: 'woman’s boot'},
	{c: '🪮', g: 6, n: 'hair pick'},
	{c: '👑', g: 6, n: 'crown'},
	{c: '👒', g: 6, n: 'woman’s hat'},
	{c: '🎩', g: 6, n: 'top hat'},
	{c: '🎓', g: 6, n: 'graduation cap'},
	{c: '🧢', g: 6, n: 'billed cap'},
	{c: '🪖', g: 6, n: 'military helmet'},
	{c: '⛑️', g: 6, n: 'rescue worker’s helmet'},
	{c: '📿', g: 6, n: 'prayer beads'},
	{c: '💄', g: 6, n: 'lipstick'},
	{c: '💍', g: 6, n: 'ring'},
	{c: '💎', g: 6, n: 'gem stone'},
	{c: '🔇', g: 6, n: 'muted speaker'},
	{c: '🔈', g: 6, n: 'speaker low volume'},
	{c: '🔉', g: 6, n: 'speaker medium volume'},
	{c: '🔊', g: 6, n: 'speaker high volume'},
	{c: '📢', g: 6, n: 'loudspeaker'},
	{c: '📣', g: 6, n: 'megaphone'},
	{c: '📯', g: 6, n: 'postal horn'},
	{c: '🔔', g: 6, n: 'bell'},
	{c: '🔕', g: 6, n: 'bell with slash'},
	{c: '🎼', g: 6, n: 'musical score'},
	{c: '🎵', g: 6, n: 'musical note'},
	{c: '🎶', g: 6, n: 'musical notes'},
	{c: '🎙️', g: 6, n: 'studio microphone'},
	{c: '🎚️', g: 6, n: 'level slider'},
	{c: '🎛️', g: 6, n: 'control knobs'},
	{c: '🎤', g: 6, n: 'microphone'},
	{c: '🎧', g: 6, n: 'headphone'},
	{c: '📻', g: 6, n: 'radio'},
	{c: '🎷', g: 6, n: 'saxophone'},
	{c: '🎺', g: 6, n: 'trumpet'},
	{c: '🪊', g: 6, n: 'trombone'},
	{c: '🪗', g: 6, n: 'accordion'},
	{c: '🎸', g: 6, n: 'guitar'},
	{c: '🎹', g: 6, n: 'musical keyboard'},
	{c: '🎻', g: 6, n: 'violin'},
	{c: '🪕', g: 6, n: 'banjo'},
	{c: '🥁', g: 6, n: 'drum'},
	{c: '🪘', g: 6, n: 'long drum'},
	{c: '🪇', g: 6, n: 'maracas'},
	{c: '🪈', g: 6, n: 'flute'},
	{c: '🪉', g: 6, n: 'harp'},
	{c: '📱', g: 6, n: 'mobile phone'},
	{c: '📲', g: 6, n: 'mobile phone with arrow'},
	{c: '☎️', g: 6, n: 'telephone'},
	{c: '📞', g: 6, n: 'telephone receiver'},
	{c: '📟', g: 6, n: 'pager'},
	{c: '📠', g: 6, n: 'fax machine'},
	{c: '🔋', g: 6, n: 'battery'},
	{c: '🪫', g: 6, n: 'low battery'},
	{c: '🔌', g: 6, n: 'electric plug'},
	{c: '💻', g: 6, n: 'laptop'},
	{c: '🖥️', g: 6, n: 'desktop computer'},
	{c: '🖨️', g: 6, n: 'printer'},
	{c: '⌨️', g: 6, n: 'keyboard'},
	{c: '🖱️', g: 6, n: 'computer mouse'},
	{c: '🖲️', g: 6, n: 'trackball'},
	{c: '💽', g: 6, n: 'computer disk'},
	{c: '💾', g: 6, n: 'floppy disk'},
	{c: '💿', g: 6, n: 'optical disk'},
	{c: '📀', g: 6, n: 'dvd'},
	{c: '🧮', g: 6, n: 'abacus'},
	{c: '🎥', g: 6, n: 'movie camera'},
	{c: '🎞️', g: 6, n: 'film frames'},
	{c: '📽️', g: 6, n: 'film projector'},
	{c: '🎬', g: 6, n: 'clapper board'},
	{c: '📺', g: 6, n: 'television'},
	{c: '📷', g: 6, n: 'camera'},
	{c: '📸', g: 6, n: 'camera with flash'},
	{c: '📹', g: 6, n: 'video camera'},
	{c: '📼', g: 6, n: 'videocassette'},
	{c: '🔍', g: 6, n: 'magnifying glass tilted left'},
	{c: '🔎', g: 6, n: 'magnifying glass tilted right'},
	{c: '🕯️', g: 6, n: 'candle'},
	{c: '💡', g: 6, n: 'light bulb'},
	{c: '🔦', g: 6, n: 'flashlight'},
	{c: '🏮', g: 6, n: 'red paper lantern'},
	{c: '🪔', g: 6, n: 'diya lamp'},
	{c: '📔', g: 6, n: 'notebook with decorative cover'},
	{c: '📕', g: 6, n: 'closed book'},
	{c: '📖', g: 6, n: 'open book'},
	{c: '📗', g: 6, n: 'green book'},
	{c: '📘', g: 6, n: 'blue book'},
	{c: '📙', g: 6, n: 'orange book'},
	{c: '📚', g: 6, n: 'books'},
	{c: '📓', g: 6, n: 'notebook'},
	{c: '📒', g: 6, n: 'ledger'},
	{c: '📃', g: 6, n: 'page with curl'},
	{c: '📜', g: 6, n: 'scroll'},
	{c: '📄', g: 6, n: 'page facing up'},
	{c: '📰', g: 6, n: 'newspaper'},
	{c: '🗞️', g: 6, n: 'rolled-up newspaper'},
	{c: '📑', g: 6, n: 'bookmark tabs'},
	{c: '🔖', g: 6, n: 'bookmark'},
	{c: '🏷️', g: 6, n: 'label'},
	{c: '🪙', g: 6, n: 'coin'},
	{c: '💰', g: 6, n: 'money bag'},
	{c: '🪎', g: 6, n: 'treasure chest'},
	{c: '💴', g: 6, n: 'yen banknote'},
	{c: '💵', g: 6, n: 'dollar banknote'},
	{c: '💶', g: 6, n: 'euro banknote'},
	{c: '💷', g: 6, n: 'pound banknote'},
	{c: '💸', g: 6, n: 'money with wings'},
	{c: '💳', g: 6, n: 'credit card'},
	{c: '🧾', g: 6, n: 'receipt'},
	{c: '💹', g: 6, n: 'chart increasing with yen'},
	{c: '✉️', g: 6, n: 'envelope'},
	{c: '📧', g: 6, n: 'e-mail'},
	{c: '📨', g: 6, n: 'incoming envelope'},
	{c: '📩', g: 6, n: 'envelope with arrow'},
	{c: '📤', g: 6, n: 'outbox tray'},
	{c: '📥', g: 6, n: 'inbox tray'},
	{c: '📦', g: 6, n: 'package'},
	{c: '📫', g: 6, n: 'closed mailbox with raised flag'},
	{c: '📪', g: 6, n: 'closed mailbox with lowered flag'},
	{c: '📬', g: 6, n: 'open mailbox with raised flag'},
	{c: '📭', g: 6, n: 'open mailbox with lowered flag'},
	{c: '📮', g: 6, n: 'postbox'},
	{c: '🗳️', g: 6, n: 'ballot box with ballot'},
	{c: '✏️', g: 6, n: 'pencil'},
	{c: '✒️', g: 6, n: 'black nib'},
	{c: '🖋️', g: 6, n: 'fountain pen'},
	{c: '🖊️', g: 6, n: 'pen'},
	{c: '🖌️', g: 6, n: 'paintbrush'},
	{c: '🖍️', g: 6, n: 'crayon'},
	{c: '📝', g: 6, n: 'memo'},
	{c: '💼', g: 6, n: 'briefcase'},
	{c: '📁', g: 6, n: 'file folder'},
	{c: '📂', g: 6, n: 'open file folder'},
	{c: '🗂️', g: 6, n: 'card index dividers'},
	{c: '📅', g: 6, n: 'calendar'},
	{c: '📆', g: 6, n: 'tear-off calendar'},
	{c: '🗒️', g: 6, n: 'spiral notepad'},
	{c: '🗓️', g: 6, n: 'spiral calendar'},
	{c: '📇', g: 6, n: 'card index'},
	{c: '📈', g: 6, n: 'chart increasing'},
	{c: '📉', g: 6, n: 'chart decreasing'},
	{c: '📊', g: 6, n: 'bar chart'},
	{c: '📋', g: 6, n: 'clipboard'},
	{c: '📌', g: 6, n: 'pushpin'},
	{c: '📍', g: 6, n: 'round pushpin'},
	{c: '📎', g: 6, n: 'paperclip'},
	{c: '🖇️', g: 6, n: 'linked paperclips'},
	{c: '📏', g: 6, n: 'straight ruler'},
	{c: '📐', g: 6, n: 'triangular ruler'},
	{c: '✂️', g: 6, n: 'scissors'},
	{c: '🗃️', g: 6, n: 'card file box'},
	{c: '🗄️', g: 6, n: 'file cabinet'},
	{c: '🗑️', g: 6, n: 'wastebasket'},
	{c: '🔒', g: 6, n: 'locked'},
	{c: '🔓', g: 6, n: 'unlocked'},
	{c: '🔏', g: 6, n: 'locked with pen'},
	{c: '🔐', g: 6, n: 'locked with key'},
	{c: '🔑', g: 6, n: 'key'},
	{c: '🗝️', g: 6, n: 'old key'},
	{c: '🔨', g: 6, n: 'hammer'},
	{c: '🪓', g: 6, n: 'axe'},
	{c: '⛏️', g: 6, n: 'pick'},
	{c: '⚒️', g: 6, n: 'hammer and pick'},
	{c: '🛠️', g: 6, n: 'hammer and wrench'},
	{c: '🗡️', g: 6, n: 'dagger'},
	{c: '⚔️', g: 6, n: 'crossed swords'},
	{c: '💣', g: 6, n: 'bomb'},
	{c: '🪃', g: 6, n: 'boomerang'},
	{c: '🏹', g: 6, n: 'bow and arrow'},
	{c: '🛡️', g: 6, n: 'shield'},
	{c: '🪚', g: 6, n: 'carpentry saw'},
	{c: '🔧', g: 6, n: 'wrench'},
	{c: '🪛', g: 6, n: 'screwdriver'},
	{c: '🔩', g: 6, n: 'nut and bolt'},
	{c: '⚙️', g: 6, n: 'gear'},
	{c: '🗜️', g: 6, n: 'clamp'},
	{c: '⚖️', g: 6, n: 'balance scale'},
	{c: '🦯', g: 6, n: 'white cane'},
	{c: '🔗', g: 6, n: 'link'},
	{c: '⛓️‍💥', g: 6, n: 'broken chain'},
	{c: '⛓️', g: 6, n: 'chains'},
	{c: '🪝', g: 6, n: 'hook'},
	{c: '🧰', g: 6, n: 'toolbox'},
	{c: '🧲', g: 6, n: 'magnet'},
	{c: '🪜', g: 6, n: 'ladder'},
	{c: '🪏', g: 6, n: 'shovel'},
	{c: '⚗️', g: 6, n: 'alembic'},
	{c: '🧪', g: 6, n: 'test tube'},
	{c: '🧫', g: 6, n: 'petri dish'},
	{c: '🧬', g: 6, n: 'dna'},
	{c: '🔬', g: 6, n: 'microscope'},
	{c: '🔭', g: 6, n: 'telescope'},
	{c: '📡', g: 6, n: 'satellite antenna'},
	{c: '💉', g: 6, n: 'syringe'},
	{c: '🩸', g: 6, n: 'drop of blood'},
	{c: '💊', g: 6, n: 'pill'},
	{c: '🩹', g: 6, n: 'adhesive bandage'},
	{c: '🩼', g: 6, n: 'crutch'},
	{c: '🩺', g: 6, n: 'stethoscope'},
	{c: '🩻', g: 6, n: 'x-ray'},
	{c: '🚪', g: 6, n: 'door'},
	{c: '🛗', g: 6, n: 'elevator'},
	{c: '🪞', g: 6, n: 'mirror'},
	{c: '🪟', g: 6, n: 'window'},
	{c: '🛏️', g: 6, n: 'bed'},
	{c: '🛋️', g: 6, n: 'couch and lamp'},
	{c: '🪑', g: 6, n: 'chair'},
	{c: '🚽', g: 6, n: 'toilet'},
	{c: '🪠', g: 6, n: 'plunger'},
	{c: '🚿', g: 6, n: 'shower'},
	{c: '🛁', g: 6, n: 'bathtub'},
	{c: '🪤', g: 6, n: 'mouse trap'},
	{c: '🪒', g: 6, n: 'razor'},
	{c: '🧴', g: 6, n: 'lotion bottle'},
	{c: '🧷', g: 6, n: 'safety pin'},
	{c: '🧹', g: 6, n: 'broom'},
	{c: '🧺', g: 6, n: 'basket'},
	{c: '🧻', g: 6, n: 'roll of paper'},
	{c: '🪣', g: 6, n: 'bucket'},
	{c: '🧼', g: 6, n: 'soap'},
	{c: '🫧', g: 6, n: 'bubbles'},
	{c: '🪥', g: 6, n: 'toothbrush'},
	{c: '🧽', g: 6, n: 'sponge'},
	{c: '🧯', g: 6, n: 'fire extinguisher'},
	{c: '🛒', g: 6, n: 'shopping cart'},
	{c: '🚬', g: 6, n: 'cigarette'},
	{c: '⚰️', g: 6, n: 'coffin'},
	{c: '🪦', g: 6, n: 'headstone'},
	{c: '⚱️', g: 6, n: 'funeral urn'},
	{c: '🧿', g: 6, n: 'nazar amulet'},
	{c: '🪬', g: 6, n: 'hamsa'},
	{c: '🗿', g: 6, n: 'moai'},
	{c: '🪧', g: 6, n: 'placard'},
	{c: '🪪', g: 6, n: 'identification card'},
	{c: '🏧', g: 7, n: 'ATM sign'},
	{c: '🚮', g: 7, n: 'litter in bin sign'},
	{c: '🚰', g: 7, n: 'potable water'},
	{c: '♿', g: 7, n: 'wheelchair symbol'},
	{c: '🚹', g: 7, n: 'men’s room'},
	{c: '🚺', g: 7, n: 'women’s room'},
	{c: '🚻', g: 7, n: 'restroom'},
	{c: '🚼', g: 7, n: 'baby symbol'},
	{c: '🚾', g: 7, n: 'water closet'},
	{c: '🛂', g: 7, n: 'passport control'},
	{c: '🛃', g: 7, n: 'customs'},
	{c: '🛄', g: 7, n: 'baggage claim'},
	{c: '🛅', g: 7, n: 'left luggage'},
	{c: '⚠️', g: 7, n: 'warning'},
	{c: '🚸', g: 7, n: 'children crossing'},
	{c: '⛔', g: 7, n: 'no entry'},
	{c: '🚫', g: 7, n: 'prohibited'},
	{c: '🚳', g: 7, n: 'no bicycles'},
	{c: '🚭', g: 7, n: 'no smoking'},
	{c: '🚯', g: 7, n: 'no littering'},
	{c: '🚱', g: 7, n: 'non-potable water'},
	{c: '🚷', g: 7, n: 'no pedestrians'},
	{c: '📵', g: 7, n: 'no mobile phones'},
	{c: '🔞', g: 7, n: 'no one under eighteen'},
	{c: '☢️', g: 7, n: 'radioactive'},
	{c: '☣️', g: 7, n: 'biohazard'},
	{c: '⬆️', g: 7, n: 'up arrow'},
	{c: '↗️', g: 7, n: 'up-right arrow'},
	{c: '➡️', g: 7, n: 'right arrow'},
	{c: '↘️', g: 7, n: 'down-right arrow'},
	{c: '⬇️', g: 7, n: 'down arrow'},
	{c: '↙️', g: 7, n: 'down-left arrow'},
	{c: '⬅️', g: 7, n: 'left arrow'},
	{c: '↖️', g: 7, n: 'up-left arrow'},
	{c: '↕️', g: 7, n: 'up-down arrow'},
	{c: '↔️', g: 7, n: 'left-right arrow'},
	{c: '↩️', g: 7, n: 'right arrow curving left'},
	{c: '↪️', g: 7, n: 'left arrow curving right'},
	{c: '⤴️', g: 7, n: 'right arrow curving up'},
	{c: '⤵️', g: 7, n: 'right arrow curving down'},
	{c: '🔃', g: 7, n: 'clockwise vertical arrows'},
	{c: '🔄', g: 7, n: 'counterclockwise arrows button'},
	{c: '🔙', g: 7, n: 'BACK arrow'},
	{c: '🔚', g: 7, n: 'END arrow'},
	{c: '🔛', g: 7, n: 'ON! arrow'},
	{c: '🔜', g: 7, n: 'SOON arrow'},
	{c: '🔝', g: 7, n: 'TOP arrow'},
	{c: '🛐', g: 7, n: 'place of worship'},
	{c: '⚛️', g: 7, n: 'atom symbol'},
	{c: '🕉️', g: 7, n: 'om'},
	{c: '✡️', g: 7, n: 'star of David'},
	{c: '☸️', g: 7, n: 'wheel of dharma'},
	{c: '☯️', g: 7, n: 'yin yang'},
	{c: '✝️', g: 7, n: 'latin cross'},
	{c: '☦️', g: 7, n: 'orthodox cross'},
	{c: '☪️', g: 7, n: 'star and crescent'},
	{c: '☮️', g: 7, n: 'peace symbol'},
	{c: '🕎', g: 7, n: 'menorah'},
	{c: '🔯', g: 7, n: 'dotted six-pointed star'},
	{c: '🪯', g: 7, n: 'khanda'},
	{c: '♈', g: 7, n: 'Aries'},
	{c: '♉', g: 7, n: 'Taurus'},
	{c: '♊', g: 7, n: 'Gemini'},
	{c: '♋', g: 7, n: 'Cancer'},
	{c: '♌', g: 7, n: 'Leo'},
	{c: '♍', g: 7, n: 'Virgo'},
	{c: '♎', g: 7, n: 'Libra'},
	{c: '♏', g: 7, n: 'Scorpio'},
	{c: '♐', g: 7, n: 'Sagittarius'},
	{c: '♑', g: 7, n: 'Capricorn'},
	{c: '♒', g: 7, n: 'Aquarius'},
	{c: '♓', g: 7, n: 'Pisces'},
	{c: '⛎', g: 7, n: 'Ophiuchus'},
	{c: '🔀', g: 7, n: 'shuffle tracks button'},
	{c: '🔁', g: 7, n: 'repeat button'},
	{c: '🔂', g: 7, n: 'repeat single button'},
	{c: '▶️', g: 7, n: 'play button'},
	{c: '⏩', g: 7, n: 'fast-forward button'},
	{c: '⏭️', g: 7, n: 'next track button'},
	{c: '⏯️', g: 7, n: 'play or pause button'},
	{c: '◀️', g: 7, n: 'reverse button'},
	{c: '⏪', g: 7, n: 'fast reverse button'},
	{c: '⏮️', g: 7, n: 'last track button'},
	{c: '🔼', g: 7, n: 'upwards button'},
	{c: '⏫', g: 7, n: 'fast up button'},
	{c: '🔽', g: 7, n: 'downwards button'},
	{c: '⏬', g: 7, n: 'fast down button'},
	{c: '⏸️', g: 7, n: 'pause button'},
	{c: '⏹️', g: 7, n: 'stop button'},
	{c: '⏺️', g: 7, n: 'record button'},
	{c: '⏏️', g: 7, n: 'eject button'},
	{c: '🎦', g: 7, n: 'cinema'},
	{c: '🔅', g: 7, n: 'dim button'},
	{c: '🔆', g: 7, n: 'bright button'},
	{c: '📶', g: 7, n: 'antenna bars'},
	{c: '🛜', g: 7, n: 'wireless'},
	{c: '📳', g: 7, n: 'vibration mode'},
	{c: '📴', g: 7, n: 'mobile phone off'},
	{c: '♀️', g: 7, n: 'female sign'},
	{c: '♂️', g: 7, n: 'male sign'},
	{c: '⚧️', g: 7, n: 'transgender symbol'},
	{c: '✖️', g: 7, n: 'multiply'},
	{c: '➕', g: 7, n: 'plus'},
	{c: '➖', g: 7, n: 'minus'},
	{c: '➗', g: 7, n: 'divide'},
	{c: '🟰', g: 7, n: 'heavy equals sign'},
	{c: '♾️', g: 7, n: 'infinity'},
	{c: '‼️', g: 7, n: 'double exclamation mark'},
	{c: '⁉️', g: 7, n: 'exclamation question mark'},
	{c: '❓', g: 7, n: 'red question mark'},
	{c: '❔', g: 7, n: 'white question mark'},
	{c: '❕', g: 7, n: 'white exclamation mark'},
	{c: '❗', g: 7, n: 'red exclamation mark'},
	{c: '〰️', g: 7, n: 'wavy dash'},
	{c: '💱', g: 7, n: 'currency exchange'},
	{c: '💲', g: 7, n: 'heavy dollar sign'},
	{c: '⚕️', g: 7, n: 'medical symbol'},
	{c: '♻️', g: 7, n: 'recycling symbol'},
	{c: '⚜️', g: 7, n: 'fleur-de-lis'},
	{c: '🔱', g: 7, n: 'trident emblem'},
	{c: '📛', g: 7, n: 'name badge'},
	{c: '🔰', g: 7, n: 'Japanese symbol for beginner'},
	{c: '⭕', g: 7, n: 'hollow red circle'},
	{c: '✅', g: 7, n: 'check mark button'},
	{c: '☑️', g: 7, n: 'check box with check'},
	{c: '✔️', g: 7, n: 'check mark'},
	{c: '❌', g: 7, n: 'cross mark'},
	{c: '❎', g: 7, n: 'cross mark button'},
	{c: '➰', g: 7, n: 'curly loop'},
	{c: '➿', g: 7, n: 'double curly loop'},
	{c: '〽️', g: 7, n: 'part alternation mark'},
	{c: '✳️', g: 7, n: 'eight-spoked asterisk'},
	{c: '✴️', g: 7, n: 'eight-pointed star'},
	{c: '❇️', g: 7, n: 'sparkle'},
	{c: '©️', g: 7, n: 'copyright'},
	{c: '®️', g: 7, n: 'registered'},
	{c: '™️', g: 7, n: 'trade mark'},
	{c: '🫟', g: 7, n: 'splatter'},
	{c: '#️⃣', g: 7, n: 'keycap: #'},
	{c: '*️⃣', g: 7, n: 'keycap: *'},
	{c: '0️⃣', g: 7, n: 'keycap: 0'},
	{c: '1️⃣', g: 7, n: 'keycap: 1'},
	{c: '2️⃣', g: 7, n: 'keycap: 2'},
	{c: '3️⃣', g: 7, n: 'keycap: 3'},
	{c: '4️⃣', g: 7, n: 'keycap: 4'},
	{c: '5️⃣', g: 7, n: 'keycap: 5'},
	{c: '6️⃣', g: 7, n: 'keycap: 6'},
	{c: '7️⃣', g: 7, n: 'keycap: 7'},
	{c: '8️⃣', g: 7, n: 'keycap: 8'},
	{c: '9️⃣', g: 7, n: 'keycap: 9'},
	{c: '🔟', g: 7, n: 'keycap: 10'},
	{c: '🔠', g: 7, n: 'input latin uppercase'},
	{c: '🔡', g: 7, n: 'input latin lowercase'},
	{c: '🔢', g: 7, n: 'input numbers'},
	{c: '🔣', g: 7, n: 'input symbols'},
	{c: '🔤', g: 7, n: 'input latin letters'},
	{c: '🅰️', g: 7, n: 'A button (blood type)'},
	{c: '🆎', g: 7, n: 'AB button (blood type)'},
	{c: '🅱️', g: 7, n: 'B button (blood type)'},
	{c: '🆑', g: 7, n: 'CL button'},
	{c: '🆒', g: 7, n: 'COOL button'},
	{c: '🆓', g: 7, n: 'FREE button'},
	{c: 'ℹ️', g: 7, n: 'information'},
	{c: '🆔', g: 7, n: 'ID button'},
	{c: 'Ⓜ️', g: 7, n: 'circled M'},
	{c: '🆕', g: 7, n: 'NEW button'},
	{c: '🆖', g: 7, n: 'NG button'},
	{c: '🅾️', g: 7, n: 'O button (blood type)'},
	{c: '🆗', g: 7, n: 'OK button'},
	{c: '🅿️', g: 7, n: 'P button'},
	{c: '🆘', g: 7, n: 'SOS button'},
	{c: '🆙', g: 7, n: 'UP! button'},
	{c: '🆚', g: 7, n: 'VS button'},
	{c: '🈁', g: 7, n: 'Japanese “here” button'},
	{c: '🈂️', g: 7, n: 'Japanese “service charge” button'},
	{c: '🈷️', g: 7, n: 'Japanese “monthly amount” button'},
	{c: '🈶', g: 7, n: 'Japanese “not free of charge” button'},
	{c: '🈯', g: 7, n: 'Japanese “reserved” button'},
	{c: '🉐', g: 7, n: 'Japanese “bargain” button'},
	{c: '🈹', g: 7, n: 'Japanese “discount” button'},
	{c: '🈚', g: 7, n: 'Japanese “free of charge” button'},
	{c: '🈲', g: 7, n: 'Japanese “prohibited” button'},
	{c: '🉑', g: 7, n: 'Japanese “acceptable” button'},
	{c: '🈸', g: 7, n: 'Japanese “application” button'},
	{c: '🈴', g: 7, n: 'Japanese “passing grade” button'},
	{c: '🈳', g: 7, n: 'Japanese “vacancy” button'},
	{c: '㊗️', g: 7, n: 'Japanese “congratulations” button'},
	{c: '㊙️', g: 7, n: 'Japanese “secret” button'},
	{c: '🈺', g: 7, n: 'Japanese “open for business” button'},
	{c: '🈵', g: 7, n: 'Japanese “no vacancy” button'},
	{c: '🔴', g: 7, n: 'red circle'},
	{c: '🟠', g: 7, n: 'orange circle'},
	{c: '🟡', g: 7, n: 'yellow circle'},
	{c: '🟢', g: 7, n: 'green circle'},
	{c: '🔵', g: 7, n: 'blue circle'},
	{c: '🟣', g: 7, n: 'purple circle'},
	{c: '🟤', g: 7, n: 'brown circle'},
	{c: '⚫', g: 7, n: 'black circle'},
	{c: '⚪', g: 7, n: 'white circle'},
	{c: '🟥', g: 7, n: 'red square'},
	{c: '🟧', g: 7, n: 'orange square'},
	{c: '🟨', g: 7, n: 'yellow square'},
	{c: '🟩', g: 7, n: 'green square'},
	{c: '🟦', g: 7, n: 'blue square'},
	{c: '🟪', g: 7, n: 'purple square'},
	{c: '🟫', g: 7, n: 'brown square'},
	{c: '⬛', g: 7, n: 'black large square'},
	{c: '⬜', g: 7, n: 'white large square'},
	{c: '◼️', g: 7, n: 'black medium square'},
	{c: '◻️', g: 7, n: 'white medium square'},
	{c: '◾', g: 7, n: 'black medium-small square'},
	{c: '◽', g: 7, n: 'white medium-small square'},
	{c: '▪️', g: 7, n: 'black small square'},
	{c: '▫️', g: 7, n: 'white small square'},
	{c: '🔶', g: 7, n: 'large orange diamond'},
	{c: '🔷', g: 7, n: 'large blue diamond'},
	{c: '🔸', g: 7, n: 'small orange diamond'},
	{c: '🔹', g: 7, n: 'small blue diamond'},
	{c: '🔺', g: 7, n: 'red triangle pointed up'},
	{c: '🔻', g: 7, n: 'red triangle pointed down'},
	{c: '💠', g: 7, n: 'diamond with a dot'},
	{c: '🔘', g: 7, n: 'radio button'},
	{c: '🔳', g: 7, n: 'white square button'},
	{c: '🔲', g: 7, n: 'black square button'},
	{c: '🏁', g: 8, n: 'chequered flag'},
	{c: '🚩', g: 8, n: 'triangular flag'},
	{c: '🎌', g: 8, n: 'crossed flags'},
	{c: '🏴', g: 8, n: 'black flag'},
	{c: '🏳️', g: 8, n: 'white flag'},
	{c: '🏳️‍🌈', g: 8, n: 'rainbow flag'},
	{c: '🏳️‍⚧️', g: 8, n: 'transgender flag'},
	{c: '🏴‍☠️', g: 8, n: 'pirate flag'},
	{c: '🇦🇨', g: 8, n: 'flag: Ascension Island'},
	{c: '🇦🇩', g: 8, n: 'flag: Andorra'},
	{c: '🇦🇪', g: 8, n: 'flag: United Arab Emirates'},
	{c: '🇦🇫', g: 8, n: 'flag: Afghanistan'},
	{c: '🇦🇬', g: 8, n: 'flag: Antigua & Barbuda'},
	{c: '🇦🇮', g: 8, n: 'flag: Anguilla'},
	{c: '🇦🇱', g: 8, n: 'flag: Albania'},
	{c: '🇦🇲', g: 8, n: 'flag: Armenia'},
	{c: '🇦🇴', g: 8, n: 'flag: Angola'},
	{c: '🇦🇶', g: 8, n: 'flag: Antarctica'},
	{c: '🇦🇷', g: 8, n: 'flag: Argentina'},
	{c: '🇦🇸', g: 8, n: 'flag: American Samoa'},
	{c: '🇦🇹', g: 8, n: 'flag: Austria'},
	{c: '🇦🇺', g: 8, n: 'flag: Australia'},
	{c: '🇦🇼', g: 8, n: 'flag: Aruba'},
	{c: '🇦🇽', g: 8, n: 'flag: Åland Islands'},
	{c: '🇦🇿', g: 8, n: 'flag: Azerbaijan'},
	{c: '🇧🇦', g: 8, n: 'flag: Bosnia & Herzegovina'},
	{c: '🇧🇧', g: 8, n: 'flag: Barbados'},
	{c: '🇧🇩', g: 8, n: 'flag: Bangladesh'},
	{c: '🇧🇪', g: 8, n: 'flag: Belgium'},
	{c: '🇧🇫', g: 8, n: 'flag: Burkina Faso'},
	{c: '🇧🇬', g: 8, n: 'flag: Bulgaria'},
	{c: '🇧🇭', g: 8, n: 'flag: Bahrain'},
	{c: '🇧🇮', g: 8, n: 'flag: Burundi'},
	{c: '🇧🇯', g: 8, n: 'flag: Benin'},
	{c: '🇧🇱', g: 8, n: 'flag: St. Barthélemy'},
	{c: '🇧🇲', g: 8, n: 'flag: Bermuda'},
	{c: '🇧🇳', g: 8, n: 'flag: Brunei'},
	{c: '🇧🇴', g: 8, n: 'flag: Bolivia'},
	{c: '🇧🇶', g: 8, n: 'flag: Caribbean Netherlands'},
	{c: '🇧🇷', g: 8, n: 'flag: Brazil'},
	{c: '🇧🇸', g: 8, n: 'flag: Bahamas'},
	{c: '🇧🇹', g: 8, n: 'flag: Bhutan'},
	{c: '🇧🇻', g: 8, n: 'flag: Bouvet Island'},
	{c: '🇧🇼', g: 8, n: 'flag: Botswana'},
	{c: '🇧🇾', g: 8, n: 'flag: Belarus'},
	{c: '🇧🇿', g: 8, n: 'flag: Belize'},
	{c: '🇨🇦', g: 8, n: 'flag: Canada'},
	{c: '🇨🇨', g: 8, n: 'flag: Cocos (Keeling) Islands'},
	{c: '🇨🇩', g: 8, n: 'flag: Congo - Kinshasa'},
	{c: '🇨🇫', g: 8, n: 'flag: Central African Republic'},
	{c: '🇨🇬', g: 8, n: 'flag: Congo - Brazzaville'},
	{c: '🇨🇭', g: 8, n: 'flag: Switzerland'},
	{c: '🇨🇮', g: 8, n: 'flag: Côte d’Ivoire'},
	{c: '🇨🇰', g: 8, n: 'flag: Cook Islands'},
	{c: '🇨🇱', g: 8, n: 'flag: Chile'},
	{c: '🇨🇲', g: 8, n: 'flag: Cameroon'},
	{c: '🇨🇳', g: 8, n: 'flag: China'},
	{c: '🇨🇴', g: 8, n: 'flag: Colombia'},
	{c: '🇨🇵', g: 8, n: 'flag: Clipperton Island'},
	{c: '🇨🇶', g: 8, n: 'flag: Sark'},
	{c: '🇨🇷', g: 8, n: 'flag: Costa Rica'},
	{c: '🇨🇺', g: 8, n: 'flag: Cuba'},
	{c: '🇨🇻', g: 8, n: 'flag: Cape Verde'},
	{c: '🇨🇼', g: 8, n: 'flag: Curaçao'},
	{c: '🇨🇽', g: 8, n: 'flag: Christmas Island'},
	{c: '🇨🇾', g: 8, n: 'flag: Cyprus'},
	{c: '🇨🇿', g: 8, n: 'flag: Czechia'},
	{c: '🇩🇪', g: 8, n: 'flag: Germany'},
	{c: '🇩🇬', g: 8, n: 'flag: Diego Garcia'},
	{c: '🇩🇯', g: 8, n: 'flag: Djibouti'},
	{c: '🇩🇰', g: 8, n: 'flag: Denmark'},
	{c: '🇩🇲', g: 8, n: 'flag: Dominica'},
	{c: '🇩🇴', g: 8, n: 'flag: Dominican Republic'},
	{c: '🇩🇿', g: 8, n: 'flag: Algeria'},
	{c: '🇪🇦', g: 8, n: 'flag: Ceuta & Melilla'},
	{c: '🇪🇨', g: 8, n: 'flag: Ecuador'},
	{c: '🇪🇪', g: 8, n: 'flag: Estonia'},
	{c: '🇪🇬', g: 8, n: 'flag: Egypt'},
	{c: '🇪🇭', g: 8, n: 'flag: Western Sahara'},
	{c: '🇪🇷', g: 8, n: 'flag: Eritrea'},
	{c: '🇪🇸', g: 8, n: 'flag: Spain'},
	{c: '🇪🇹', g: 8, n: 'flag: Ethiopia'},
	{c: '🇪🇺', g: 8, n: 'flag: European Union'},
	{c: '🇫🇮', g: 8, n: 'flag: Finland'},
	{c: '🇫🇯', g: 8, n: 'flag: Fiji'},
	{c: '🇫🇰', g: 8, n: 'flag: Falkland Islands'},
	{c: '🇫🇲', g: 8, n: 'flag: Micronesia'},
	{c: '🇫🇴', g: 8, n: 'flag: Faroe Islands'},
	{c: '🇫🇷', g: 8, n: 'flag: France'},
	{c: '🇬🇦', g: 8, n: 'flag: Gabon'},
	{c: '🇬🇧', g: 8, n: 'flag: United Kingdom'},
	{c: '🇬🇩', g: 8, n: 'flag: Grenada'},
	{c: '🇬🇪', g: 8, n: 'flag: Georgia'},
	{c: '🇬🇫', g: 8, n: 'flag: French Guiana'},
	{c: '🇬🇬', g: 8, n: 'flag: Guernsey'},
	{c: '🇬🇭', g: 8, n: 'flag: Ghana'},
	{c: '🇬🇮', g: 8, n: 'flag: Gibraltar'},
	{c: '🇬🇱', g: 8, n: 'flag: Greenland'},
	{c: '🇬🇲', g: 8, n: 'flag: Gambia'},
	{c: '🇬🇳', g: 8, n: 'flag: Guinea'},
	{c: '🇬🇵', g: 8, n: 'flag: Guadeloupe'},
	{c: '🇬🇶', g: 8, n: 'flag: Equatorial Guinea'},
	{c: '🇬🇷', g: 8, n: 'flag: Greece'},
	{c: '🇬🇸', g: 8, n: 'flag: South Georgia & South Sandwich Islands'},
	{c: '🇬🇹', g: 8, n: 'flag: Guatemala'},
	{c: '🇬🇺', g: 8, n: 'flag: Guam'},
	{c: '🇬🇼', g: 8, n: 'flag: Guinea-Bissau'},
	{c: '🇬🇾', g: 8, n: 'flag: Guyana'},
	{c: '🇭🇰', g: 8, n: 'flag: Hong Kong SAR China'},
	{c: '🇭🇲', g: 8, n: 'flag: Heard & McDonald Islands'},
	{c: '🇭🇳', g: 8, n: 'flag: Honduras'},
	{c: '🇭🇷', g: 8, n: 'flag: Croatia'},
	{c: '🇭🇹', g: 8, n: 'flag: Haiti'},
	{c: '🇭🇺', g: 8, n: 'flag: Hungary'},
	{c: '🇮🇨', g: 8, n: 'flag: Canary Islands'},
	{c: '🇮🇩', g: 8, n: 'flag: Indonesia'},
	{c: '🇮🇪', g: 8, n: 'flag: Ireland'},
	{c: '🇮🇱', g: 8, n: 'flag: Israel'},
	{c: '🇮🇲', g: 8, n: 'flag: Isle of Man'},
	{c: '🇮🇳', g: 8, n: 'flag: India'},
	{c: '🇮🇴', g: 8, n: 'flag: British Indian Ocean Territory'},
	{c: '🇮🇶', g: 8, n: 'flag: Iraq'},
	{c: '🇮🇷', g: 8, n: 'flag: Iran'},
	{c: '🇮🇸', g: 8, n: 'flag: Iceland'},
	{c: '🇮🇹', g: 8, n: 'flag: Italy'},
	{c: '🇯🇪', g: 8, n: 'flag: Jersey'},
	{c: '🇯🇲', g: 8, n: 'flag: Jamaica'},
	{c: '🇯🇴', g: 8, n: 'flag: Jordan'},
	{c: '🇯🇵', g: 8, n: 'flag: Japan'},
	{c: '🇰🇪', g: 8, n: 'flag: Kenya'},
	{c: '🇰🇬', g: 8, n: 'flag: Kyrgyzstan'},
	{c: '🇰🇭', g: 8, n: 'flag: Cambodia'},
	{c: '🇰🇮', g: 8, n: 'flag: Kiribati'},
	{c: '🇰🇲', g: 8, n: 'flag: Comoros'},
	{c: '🇰🇳', g: 8, n: 'flag: St. Kitts & Nevis'},
	{c: '🇰🇵', g: 8, n: 'flag: North Korea'},
	{c: '🇰🇷', g: 8, n: 'flag: South Korea'},
	{c: '🇰🇼', g: 8, n: 'flag: Kuwait'},
	{c: '🇰🇾', g: 8, n: 'flag: Cayman Islands'},
	{c: '🇰🇿', g: 8, n: 'flag: Kazakhstan'},
	{c: '🇱🇦', g: 8, n: 'flag: Laos'},
	{c: '🇱🇧', g: 8, n: 'flag: Lebanon'},
	{c: '🇱🇨', g: 8, n: 'flag: St. Lucia'},
	{c: '🇱🇮', g: 8, n: 'flag: Liechtenstein'},
	{c: '🇱🇰', g: 8, n: 'flag: Sri Lanka'},
	{c: '🇱🇷', g: 8, n: 'flag: Liberia'},
	{c: '🇱🇸', g: 8, n: 'flag: Lesotho'},
	{c: '🇱🇹', g: 8, n: 'flag: Lithuania'},
	{c: '🇱🇺', g: 8, n: 'flag: Luxembourg'},
	{c: '🇱🇻', g: 8, n: 'flag: Latvia'},
	{c: '🇱🇾', g: 8, n: 'flag: Libya'},
	{c: '🇲🇦', g: 8, n: 'flag: Morocco'},
	{c: '🇲🇨', g: 8, n: 'flag: Monaco'},
	{c: '🇲🇩', g: 8, n: 'flag: Moldova'},
	{c: '🇲🇪', g: 8, n: 'flag: Montenegro'},
	{c: '🇲🇫', g: 8, n: 'flag: St. Martin'},
	{c: '🇲🇬', g: 8, n: 'flag: Madagascar'},
	{c: '🇲🇭', g: 8, n: 'flag: Marshall Islands'},
	{c: '🇲🇰', g: 8, n: 'flag: North Macedonia'},
	{c: '🇲🇱', g: 8, n: 'flag: Mali'},
	{c: '🇲🇲', g: 8, n: 'flag: Myanmar (Burma)'},
	{c: '🇲🇳', g: 8, n: 'flag: Mongolia'},
	{c: '🇲🇴', g: 8, n: 'flag: Macao SAR China'},
	{c: '🇲🇵', g: 8, n: 'flag: Northern Mariana Islands'},
	{c: '🇲🇶', g: 8, n: 'flag: Martinique'},
	{c: '🇲🇷', g: 8, n: 'flag: Mauritania'},
	{c: '🇲🇸', g: 8, n: 'flag: Montserrat'},
	{c: '🇲🇹', g: 8, n: 'flag: Malta'},
	{c: '🇲🇺', g: 8, n: 'flag: Mauritius'},
	{c: '🇲🇻', g: 8, n: 'flag: Maldives'},
	{c: '🇲🇼', g: 8, n: 'flag: Malawi'},
	{c: '🇲🇽', g: 8, n: 'flag: Mexico'},
	{c: '🇲🇾', g: 8, n: 'flag: Malaysia'},
	{c: '🇲🇿', g: 8, n: 'flag: Mozambique'},
	{c: '🇳🇦', g: 8, n: 'flag: Namibia'},
	{c: '🇳🇨', g: 8, n: 'flag: New Caledonia'},
	{c: '🇳🇪', g: 8, n: 'flag: Niger'},
	{c: '🇳🇫', g: 8, n: 'flag: Norfolk Island'},
	{c: '🇳🇬', g: 8, n: 'flag: Nigeria'},
	{c: '🇳🇮', g: 8, n: 'flag: Nicaragua'},
	{c: '🇳🇱', g: 8, n: 'flag: Netherlands'},
	{c: '🇳🇴', g: 8, n: 'flag: Norway'},
	{c: '🇳🇵', g: 8, n: 'flag: Nepal'},
	{c: '🇳🇷', g: 8, n: 'flag: Nauru'},
	{c: '🇳🇺', g: 8, n: 'flag: Niue'},
	{c: '🇳🇿', g: 8, n: 'flag: New Zealand'},
	{c: '🇴🇲', g: 8, n: 'flag: Oman'},
	{c: '🇵🇦', g: 8, n: 'flag: Panama'},
	{c: '🇵🇪', g: 8, n: 'flag: Peru'},
	{c: '🇵🇫', g: 8, n: 'flag: French Polynesia'},
	{c: '🇵🇬', g: 8, n: 'flag: Papua New Guinea'},
	{c: '🇵🇭', g: 8, n: 'flag: Philippines'},
	{c: '🇵🇰', g: 8, n: 'flag: Pakistan'},
	{c: '🇵🇱', g: 8, n: 'flag: Poland'},
	{c: '🇵🇲', g: 8, n: 'flag: St. Pierre & Miquelon'},
	{c: '🇵🇳', g: 8, n: 'flag: Pitcairn Islands'},
	{c: '🇵🇷', g: 8, n: 'flag: Puerto Rico'},
	{c: '🇵🇸', g: 8, n: 'flag: Palestinian Territories'},
	{c: '🇵🇹', g: 8, n: 'flag: Portugal'},
	{c: '🇵🇼', g: 8, n: 'flag: Palau'},
	{c: '🇵🇾', g: 8, n: 'flag: Paraguay'},
	{c: '🇶🇦', g: 8, n: 'flag: Qatar'},
	{c: '🇷🇪', g: 8, n: 'flag: Réunion'},
	{c: '🇷🇴', g: 8, n: 'flag: Romania'},
	{c: '🇷🇸', g: 8, n: 'flag: Serbia'},
	{c: '🇷🇺', g: 8, n: 'flag: Russia'},
	{c: '🇷🇼', g: 8, n: 'flag: Rwanda'},
	{c: '🇸🇦', g: 8, n: 'flag: Saudi Arabia'},
	{c: '🇸🇧', g: 8, n: 'flag: Solomon Islands'},
	{c: '🇸🇨', g: 8, n: 'flag: Seychelles'},
	{c: '🇸🇩', g: 8, n: 'flag: Sudan'},
	{c: '🇸🇪', g: 8, n: 'flag: Sweden'},
	{c: '🇸🇬', g: 8, n: 'flag: Singapore'},
	{c: '🇸🇭', g: 8, n: 'flag: St. Helena'},
	{c: '🇸🇮', g: 8, n: 'flag: Slovenia'},
	{c: '🇸🇯', g: 8, n: 'flag: Svalbard & Jan Mayen'},
	{c: '🇸🇰', g: 8, n: 'flag: Slovakia'},
	{c: '🇸🇱', g: 8, n: 'flag: Sierra Leone'},
	{c: '🇸🇲', g: 8, n: 'flag: San Marino'},
	{c: '🇸🇳', g: 8, n: 'flag: Senegal'},
	{c: '🇸🇴', g: 8, n: 'flag: Somalia'},
	{c: '🇸🇷', g: 8, n: 'flag: Suriname'},
	{c: '🇸🇸', g: 8, n: 'flag: South Sudan'},
	{c: '🇸🇹', g: 8, n: 'flag: São Tomé & Príncipe'},
	{c: '🇸🇻', g: 8, n: 'flag: El Salvador'},
	{c: '🇸🇽', g: 8, n: 'flag: Sint Maarten'},
	{c: '🇸🇾', g: 8, n: 'flag: Syria'},
	{c: '🇸🇿', g: 8, n: 'flag: Eswatini'},
	{c: '🇹🇦', g: 8, n: 'flag: Tristan da Cunha'},
	{c: '🇹🇨', g: 8, n: 'flag: Turks & Caicos Islands'},
	{c: '🇹🇩', g: 8, n: 'flag: Chad'},
	{c: '🇹🇫', g: 8, n: 'flag: French Southern Territories'},
	{c: '🇹🇬', g: 8, n: 'flag: Togo'},
	{c: '🇹🇭', g: 8, n: 'flag: Thailand'},
	{c: '🇹🇯', g: 8, n: 'flag: Tajikistan'},
	{c: '🇹🇰', g: 8, n: 'flag: Tokelau'},
	{c: '🇹🇱', g: 8, n: 'flag: Timor-Leste'},
	{c: '🇹🇲', g: 8, n: 'flag: Turkmenistan'},
	{c: '🇹🇳', g: 8, n: 'flag: Tunisia'},
	{c: '🇹🇴', g: 8, n: 'flag: Tonga'},
	{c: '🇹🇷', g: 8, n: 'flag: Türkiye'},
	{c: '🇹🇹', g: 8, n: 'flag: Trinidad & Tobago'},
	{c: '🇹🇻', g: 8, n: 'flag: Tuvalu'},
	{c: '🇹🇼', g: 8, n: 'flag: Taiwan'},
	{c: '🇹🇿', g: 8, n: 'flag: Tanzania'},
	{c: '🇺🇦', g: 8, n: 'flag: Ukraine'},
	{c: '🇺🇬', g: 8, n: 'flag: Uganda'},
	{c: '🇺🇲', g: 8, n: 'flag: U.S. Outlying Islands'},
	{c: '🇺🇳', g: 8, n: 'flag: United Nations'},
	{c: '🇺🇸', g: 8, n: 'flag: United States'},
	{c: '🇺🇾', g: 8, n: 'flag: Uruguay'},
	{c: '🇺🇿', g: 8, n: 'flag: Uzbekistan'},
	{c: '🇻🇦', g: 8, n: 'flag: Vatican City'},
	{c: '🇻🇨', g: 8, n: 'flag: St. Vincent & Grenadines'},
	{c: '🇻🇪', g: 8, n: 'flag: Venezuela'},
	{c: '🇻🇬', g: 8, n: 'flag: British Virgin Islands'},
	{c: '🇻🇮', g: 8, n: 'flag: U.S. Virgin Islands'},
	{c: '🇻🇳', g: 8, n: 'flag: Vietnam'},
	{c: '🇻🇺', g: 8, n: 'flag: Vanuatu'},
	{c: '🇼🇫', g: 8, n: 'flag: Wallis & Futuna'},
	{c: '🇼🇸', g: 8, n: 'flag: Samoa'},
	{c: '🇽🇰', g: 8, n: 'flag: Kosovo'},
	{c: '🇾🇪', g: 8, n: 'flag: Yemen'},
	{c: '🇾🇹', g: 8, n: 'flag: Mayotte'},
	{c: '🇿🇦', g: 8, n: 'flag: South Africa'},
	{c: '🇿🇲', g: 8, n: 'flag: Zambia'},
	{c: '🇿🇼', g: 8, n: 'flag: Zimbabwe'},
	{c: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', g: 8, n: 'flag: England'},
	{c: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', g: 8, n: 'flag: Scotland'},
	{c: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', g: 8, n: 'flag: Wales'},
];
