create table ExportImportReportEntry (
	mvccVersion LONG default 0 not null,
	exportImportReportEntryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	classExternalReferenceCode VARCHAR(75) null,
	classNameId LONG,
	classPK LONG,
	exportImportConfigurationId LONG,
	errorMessage TEXT null,
	errorStacktrace TEXT null,
	modelName VARCHAR(255) null,
	origin INTEGER,
	scope VARCHAR(75) null,
	scopeKey VARCHAR(75) null,
	type_ INTEGER,
	status INTEGER
);