modified.files.includes[relevant][asset-publisher-api-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][asset-publisher-api-java-rule]=\
    **/asset-publisher-test/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-publisher-api-java-rule]=\
    **/asset-publisher-test/**/*Test.java

relevant.rule.names=asset-publisher-api-java-rule

test.batch.names[relevant][asset-publisher-api-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Asset Publisher Widget