resource "kubernetes_manifest" "infrastructure_applicationset" {
	depends_on=[
		kubernetes_manifest.git_repo_credentials_external_secret,
		kubernetes_manifest.infrastructure_appproject,
	]
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="argoproj.io/v1alpha1"
		kind="ApplicationSet"
		metadata={
			finalizers=["resources-finalizer.argocd.argoproj.io"]
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="liferay-infrastructure-applicationset"
				})
			name="liferay-infrastructure-applicationset"
			namespace=var.argocd_namespace
		}
		spec={
			generators=[
				{
					git={
						files=[
							{
								path="${var.infrastructure_git_repo_config.source_paths.environments}/${var.infrastructure_git_repo_config.source_paths.values_filename}"
							},
						]
						repoURL=local.infrastructure_git_repo_url
						revision=var.infrastructure_git_repo_config.revision
					}
				},
			]
			template={
				metadata={
					annotations={
						"argocd.argoproj.io/compare-options"="IgnoreExtraneous"
					}
					labels=merge(
						local.common_labels,
						{
							"app.kubernetes.io/name"=var.infrastructure_git_repo_config.target.name
						})
					name=var.infrastructure_git_repo_config.target.name
				}
				spec={
					destination={
						namespace="liferay-${var.infrastructure_git_repo_config.target.namespaceSuffix}"
						server="https://kubernetes.default.svc"
					}
					project=local.infrastructure_appproject_name
					sources=[
						merge(
							{
								helm={
									parameters=[
										{
											name="environmentId"
											value=var.infrastructure_git_repo_config.target.slugEnvironmentId
										},
										{
											name="gateway.className"
											value=var.gateway_class_name
										},
										{
											name="gateway.name"
											value=local.gateway_name
										},
										{
											name="projectId"
											value=var.infrastructure_git_repo_config.target.slugProjectId
										},
										{
											name="secretStoreName"
											value=local.secret_store_name
										},
									]
									valueFiles=[
										"$values/${var.infrastructure_git_repo_config.source_paths.base}/${var.infrastructure_git_repo_config.source_paths.values_filename}",
										"$values/{{path}}/${var.infrastructure_git_repo_config.source_paths.values_filename}",
									]
								}
								repoURL=var.infrastructure_helm_chart_config.chart_url
								targetRevision=var.infrastructure_helm_chart_config.version
							},
							var.infrastructure_helm_chart_config.path == null ? {
								chart=var.infrastructure_helm_chart_config.chart_name
							} : {
								path=var.infrastructure_helm_chart_config.path
							}
						),
						{
							ref="values"
							repoURL=local.infrastructure_git_repo_url
							targetRevision=var.infrastructure_git_repo_config.revision
						},
					]
					syncPolicy={
						automated={
							prune=true
							selfHeal=true
						}
						syncOptions=[
							"CreateNamespace=true",
							"IgnoreExtraneous=true",
							"RespectIgnoreDifferences=true",
							"SkipDryRunOnMissingResource=true"
						]
					}
				}
			}
		}
	}
}
resource "kubernetes_manifest" "infrastructure_appproject" {
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="argoproj.io/v1alpha1"
		kind="AppProject"
		metadata={
			name=local.infrastructure_appproject_name
			namespace=var.argocd_namespace
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="infrastructure-appproject"
				})
		}
		spec={
			clusterResourceWhitelist=[
				{
					group="*"
					kind="*"
				},
			]
			description="ArgoCD Project for Liferay Cloud Native infrastructure."
			destinations=[
				{
					namespace="liferay-*"
					server="https://kubernetes.default.svc"
				},
				{
					namespace=var.crossplane_namespace
					server="https://kubernetes.default.svc"
				},
				{
					namespace=var.gateway_namespace
					server="https://kubernetes.default.svc"
				},
			]
			sourceRepos=[
				"${var.infrastructure_helm_chart_config.chart_url}",
				"${var.infrastructure_helm_chart_config.chart_url}/*",
				"${var.infrastructure_provider_helm_chart_config.chart_url}",
				"${var.infrastructure_provider_helm_chart_config.chart_url}/*",
				local.infrastructure_git_repo_url,
			]
		}
	}
}
resource "kubernetes_manifest" "infrastructure_provider_application" {
	depends_on=[
		kubernetes_manifest.git_repo_credentials_external_secret,
		kubernetes_manifest.infrastructure_appproject,
	]
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="argoproj.io/v1alpha1"
		kind="Application"
		metadata={
			annotations={
				"argocd.argoproj.io/compare-options"="IgnoreExtraneous"
			}
			finalizers=["resources-finalizer.argocd.argoproj.io"]
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="liferay-infrastructure-provider"
				})
			name="liferay-infrastructure-provider"
			namespace=var.argocd_namespace
		}
		spec={
			destination={
				namespace=var.crossplane_namespace
				server="https://kubernetes.default.svc"
			}
			project=local.infrastructure_appproject_name
			sources=[
				merge(
					{
						helm={
							parameters=[
								{
									name="aws.accountId"
									value=local.account_id
								},
								{
									name="aws.clusterName"
									value=local.cluster_name
								},
								{
									name="aws.nodesSecurityGroupId"
									value=data.aws_eks_cluster.cluster.vpc_config[0].cluster_security_group_id
								},
								{
									name="aws.oidcProvider"
									value=local.oidc_provider
								},
								{
									name="aws.privateSubnetIds"
									value=jsonencode(data.aws_subnets.private.ids)
								},
								{
									name="aws.vpcId"
									value=data.aws_vpc.current.id
								},
								{
									name="crossplaneNamespace"
									value=var.crossplane_namespace
								},
								{
									name="deploymentName"
									value=var.deployment_name
								},
								{
									name="gateway.className"
									value=var.gateway_class_name
								},
								{
									name="gateway.envoyProxyRoleArn"
									value=data.aws_iam_role.envoy_proxy_role.arn
								},
								{
									name="gateway.namespace"
									value=var.gateway_namespace
								},
								{
									name="liferayServiceAccountRoleName"
									value=local.liferay_service_account_role_name
								},
							]
							valueFiles=[
								"$values/${var.infrastructure_git_repo_config.source_paths.system}/${var.infrastructure_git_repo_config.source_paths.infrastructure_provider_values_filename}",
							]
						}
						repoURL=var.infrastructure_provider_helm_chart_config.chart_url
						targetRevision=var.infrastructure_provider_helm_chart_config.version
					},
					var.infrastructure_provider_helm_chart_config.path == null ? {
						chart=var.infrastructure_provider_helm_chart_config.chart_name
					} : {
						path=var.infrastructure_provider_helm_chart_config.path
					}
				),
				{
					ref="values"
					repoURL=local.infrastructure_git_repo_url
					targetRevision=var.infrastructure_git_repo_config.revision
				},
			]
			syncPolicy={
				automated={
					prune=true
					selfHeal=true
				}
				syncOptions=[
					"CreateNamespace=true",
					"SkipDryRunOnMissingResource=true",
				]
			}
		}
	}
}
resource "kubernetes_manifest" "liferay_applicationset" {
	depends_on=[
		kubernetes_manifest.git_repo_credentials_external_secret,
		kubernetes_manifest.liferay_appproject,
	]
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="argoproj.io/v1alpha1"
		kind="ApplicationSet"
		metadata={
			finalizers=["resources-finalizer.argocd.argoproj.io"]
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="liferay-applicationset"
				})
			name="liferay-applicationset"
			namespace=var.argocd_namespace
		}
		spec={
			generators=[
				{
					git={
						files=[
							{
								path="${var.liferay_git_repo_config.source_paths.environments}/${var.liferay_git_repo_config.source_paths.values_filename}"
							},
						]
						repoURL=var.liferay_git_repo_url
						revision=var.liferay_git_repo_config.revision
					}
				},
			]
			template={
				metadata={
					annotations={
						"argocd.argoproj.io/compare-options"="IgnoreExtraneous"
					}
					labels=merge(
						local.common_labels,
						{
							"app.kubernetes.io/name"=var.liferay_git_repo_config.target.name
						})
					name=var.liferay_git_repo_config.target.name
				}
				spec={
					destination={
						namespace="liferay-${var.liferay_git_repo_config.target.namespaceSuffix}"
						server="https://kubernetes.default.svc"
					}
					project=local.liferay_appproject_name
					sources=[
						merge(
							{
								helm={
									parameters=[
										{
											name="${local.liferay_helm_chart_config.values_scope_prefix}network.gatewayName"
											value=local.gateway_name
										},
										{
											name="${local.liferay_helm_chart_config.values_scope_prefix}serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
											value="arn:aws:iam::${local.account_id}:role/${var.deployment_name}-irsa"
										},
										{
											name="${local.liferay_helm_chart_config.values_scope_prefix}serviceAccount.create"
											value=true
										},
										{
											name="${local.liferay_helm_chart_config.values_scope_prefix}serviceAccount.name"
											value="liferay-default"
										},
										{
											name="global.aws.accountId"
											value=local.account_id
										},
										{
											name="global.deploymentName"
											value=var.deployment_name
										},
										{
											name="global.environmentId"
											value=var.infrastructure_git_repo_config.target.slugEnvironmentId
										},
										{
											name="global.projectId"
											value=var.infrastructure_git_repo_config.target.slugProjectId
										},
									]
									valueFiles=[
										"$values/${var.liferay_git_repo_config.source_paths.base}/${var.liferay_git_repo_config.source_paths.values_filename}",
										"$values/{{path}}/${var.liferay_git_repo_config.source_paths.values_filename}",
									]
								}
								repoURL=local.liferay_helm_chart_config.chart_url
								targetRevision=local.liferay_helm_chart_config.version
							},
							local.liferay_helm_chart_config.path == null ? {
								chart=local.liferay_helm_chart_config.chart_name
							} : {
								path=local.liferay_helm_chart_config.path
							}
						),
						{
							ref="values"
							repoURL=var.liferay_git_repo_url
							targetRevision=var.liferay_git_repo_config.revision
						},
					]
					ignoreDifferences=[
						{
							group=""
							jsonPointers=["/data"]
							kind="Secret"
							name="liferay-default"
						},
					]
					syncPolicy={
						automated={
							prune=true
							selfHeal=true
						}
						syncOptions=[
							"CreateNamespace=true",
							"RespectIgnoreDifferences=true",
						]
					}
				}
			}
		}
	}
}
resource "kubernetes_manifest" "liferay_appproject" {
	depends_on=[kubernetes_manifest.infrastructure_appproject]
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="argoproj.io/v1alpha1"
		kind="AppProject"
		metadata={
			annotations={
				"argocd.argoproj.io/compare-options"="IgnoreExtraneous"
			}
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="liferay-appproject"
				})
			name=local.liferay_appproject_name
			namespace=var.argocd_namespace
		}
		spec={
			clusterResourceWhitelist=[
				{
					group="*"
					kind="*"
				},
			]
			description="ArgoCD Project for Liferay Cloud Native applications."
			destinations=[
				{
					namespace="liferay-*"
					server="https://kubernetes.default.svc"
				},
			]
			sourceRepos=[
				"${local.liferay_helm_chart_config.chart_url}",
				"${local.liferay_helm_chart_config.chart_url}/*",
				var.liferay_git_repo_url,
			]
		}
	}
}