dependencies {
	compileOnly group: "com.liferay", name: "org.apache.commons.fileupload", version: "1.5.JAKARTA_LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "default"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly group: "xml-apis", name: "xml-apis", version: "1.4.01"
	compileOnly project(":apps:application-list:application-list-api")
	compileOnly project(":apps:frontend-taglib:frontend-taglib")
	compileOnly project(":apps:frontend-taglib:frontend-taglib-clay")
	compileOnly project(":apps:frontend-taglib:frontend-taglib-form-navigator")
	compileOnly project(":apps:layout:layout-seo-api")
	compileOnly project(":apps:static:osgi:osgi-util")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
	compileOnly project(":apps:static:portal:portal-upgrade-api")
	compileOnly project(":apps:upload:upload-api")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-sql-dsl-api")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:saml:saml-api")
	compileOnly project(":dxp:apps:saml:saml-opensaml-integration")
	compileOnly project(":dxp:apps:saml:saml-persistence-api")
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
}