modified.files.includes[relevant][saml-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][saml-web-playwright-rule]=\
    saml-web.main

relevant.rule.names=saml-web-playwright-rule

test.batch.names[relevant][saml-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57