modified.files.includes[relevant][dispatch-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][dispatch-web-playwright-rule]=\
    dispatch-web.main

relevant.rule.names=dispatch-web-playwright-rule

test.batch.names[relevant][dispatch-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163