modified.files.includes[relevant][item-selector-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][item-selector-java-rule]=\
    apps/item-selector/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][item-selector-java-rule]=\
    apps/item-selector/**/*Test.java

relevant.rule.names=item-selector-java-rule

test.batch.names[relevant][item-selector-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Item Selector