modified.files.includes[relevant][redirect-service-functional-rule]=**
relevant.rule.names=redirect-service-functional-rule

test.batch.names[relevant][redirect-service-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][redirect-service-functional-rule]=\
    (testray.main.component.name == "URL Redirections")

testray.main.component.name=URL Redirections