modified.files.includes[relevant][message-boards-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][message-boards-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][message-boards-java-rule]=\
    apps/message-boards/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][message-boards-java-rule]=\
    apps/message-boards/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][message-boards-playwright-rule]=\
    message-boards-web.main

relevant.rule.names=\
    message-boards-java-rule,\
    message-boards-playwright-rule

test.batch.names[relevant][message-boards-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][message-boards-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Message Boards