{{- if .Values.onlineActivationWorkflow.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        {{- include "dxp-operator.labels" . | nindent 8 }}
    name: online-activation-cluster-role
rules:
    -   apiGroups: [""]
        resources: ["secrets"]
        verbs: ["create", "get", "patch", "update"]
    -   apiGroups: ["argoproj.io"]
        resources: ["workflowtaskresults"]
        verbs: ["create", "patch"]
    -   apiGroups: ["licensing.liferay.com"]
        resources: ["liferayenvironments"]
        verbs: ["get", "patch"]
{{- end -}}