{{- if and .Values.rbac.create .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    labels:
        {{- include "dxp-operator.labels" . | nindent 8 }}
    name: {{ include "dxp-operator.fullname" . }}
rules:
    -   apiGroups:
            -   ""
        resources:
            -   namespaces
        verbs:
            -   get
            -   list
            -   patch
            -   update
            -   watch
    -   apiGroups:
            -   ""
        resources:
            -   persistentvolumeclaims
        verbs:
            -   create
            -   get
            -   list
            -   watch
    -   apiGroups:
            -   ""
        resources:
            -   secrets
        verbs:
            -   create
            -   get
            -   list
            -   patch
            -   update
            -   watch
    -   apiGroups:
            -   apps
        resources:
            -   statefulsets
        verbs:
            -   get
            -   list
            -   watch
    -   apiGroups:
            -   licensing.liferay.com
        resources:
            -   liferayenvironments
        verbs:
            -   get
            -   list
            -   patch
            -   update
            -   watch
    -   apiGroups:
            -   licensing.liferay.com
        resources:
            -   liferayenvironments/finalizers
        verbs:
            -   update
    -   apiGroups:
            -   licensing.liferay.com
        resources:
            -   liferayenvironments/status
        verbs:
            -   get
            -   patch
            -   update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        {{- include "dxp-operator.labels" . | nindent 8 }}
    name: {{ include "dxp-operator.fullname" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "dxp-operator.fullname" . }}
subjects:
    -   kind: ServiceAccount
        name: {{ include "dxp-operator.serviceAccountName" . }}
        namespace: {{ include "dxp-operator.namespace" . }}
{{- end }}
{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    {{- with .Values.serviceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "dxp-operator.labels" . | nindent 8 }}
    name: {{ include "dxp-operator.serviceAccountName" . }}
    namespace: {{ include "dxp-operator.namespace" . }}
{{- end }}