resource "aws_db_instance" "this" {
	allocated_storage=20
	backup_retention_period=7
	db_name="lportal"
	db_subnet_group_name=var.db_subnet_group_name
	engine="postgres"
	engine_version="14"
	identifier=var.identifier
	instance_class="db.t3.medium"
	multi_az=false
	password=var.password
	skip_final_snapshot=true
	snapshot_identifier=var.snapshot_identifier
	storage_type="gp2"
	tags=merge(
		{
			Backup="true"
			Name=var.identifier
		},
		var.tags)
	username=var.username
	vpc_security_group_ids=var.vpc_security_group_ids
}