modified.files.includes[relevant][export-import-service-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][export-import-service-playwright-rule]=\
    export-import-service.main

relevant.rule.names=export-import-service-playwright-rule

test.batch.names[relevant][export-import-service-playwright-rule]=\
    playwright-js-tomcat101-postgresql163