modified.files.includes[relevant][headless-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][headless-rule]=\
    apps/headless/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][headless-rule]=\
    apps/headless/**/*Test.java

relevant.rule.names=headless-rule

test.batch.names[relevant][headless-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Headless Object API