{{- $operatorApplication := dict
    "name" "argo-workflows"
    "syncWave" "-100"
-}}
{{- include "liferay-platform.operatorApplication" (list . (merge $operatorApplication .Values.operatorApplications.argoWorkflows)) }}