dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-string")
}

test {
	systemProperty "learn.resources.data.dir", new File(rootDir.parentFile, "learn-resources/data")
}