modified.files.includes[relevant][ai-creator-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][ai-creator-java-rule]=\
    apps/ai-creator/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][ai-creator-java-rule]=\
    apps/ai-creator/**/*Test.java

relevant.rule.names=ai-creator-java-rule

test.batch.names[relevant][ai-creator-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=AI-Creator