##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/integrations/mulesoft/LICENSE.md,\
        modules/integrations/mulesoft/target/**,\
        modules/integrations/talend/*/target/**

    run.outside.portal.excludes=\
        modules/integrations/mulesoft/**,\
        modules/integrations/talend/**