/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.patcher.model.impl;

import com.liferay.osb.patcher.model.PatcherFix;
import com.liferay.osb.patcher.service.PatcherFixLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the PatcherFix service. Represents a row in the &quot;OSB_PatcherFix&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatcherFixImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see PatcherFixImpl
 * @see com.liferay.osb.patcher.model.PatcherFix
 * @generated
 */
public abstract class PatcherFixBaseImpl extends PatcherFixModelImpl
	implements PatcherFix {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patcher fix model instance should use the {@link PatcherFix} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			PatcherFixLocalServiceUtil.addPatcherFix(this);
		}
		else {
			PatcherFixLocalServiceUtil.updatePatcherFix(this);
		}
	}
}