/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.patcher.model.impl;

import com.liferay.osb.patcher.model.PatcherFix;
import com.liferay.osb.patcher.model.PatcherFixModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.workflow.WorkflowConstants;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PatcherFix service. Represents a row in the &quot;OSB_PatcherFix&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.patcher.model.PatcherFixModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatcherFixImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see PatcherFixImpl
 * @see com.liferay.osb.patcher.model.PatcherFix
 * @see com.liferay.osb.patcher.model.PatcherFixModel
 * @generated
 */
public class PatcherFixModelImpl extends BaseModelImpl<PatcherFix>
	implements PatcherFixModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patcher fix model instance should use the {@link com.liferay.osb.patcher.model.PatcherFix} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_PatcherFix";
	public static final Object[][] TABLE_COLUMNS = {
			{ "patcherFixId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "patcherProductVersionId", Types.BIGINT },
			{ "patcherProjectVersionId", Types.BIGINT },
			{ "name", Types.CLOB },
			{ "key_", Types.VARCHAR },
			{ "keyVersion", Types.DOUBLE },
			{ "type_", Types.INTEGER },
			{ "latestFix", Types.BOOLEAN },
			{ "obsolete", Types.BOOLEAN },
			{ "committish", Types.VARCHAR },
			{ "gitHash", Types.VARCHAR },
			{ "gitRemoteURL", Types.VARCHAR },
			{ "dependencies", Types.VARCHAR },
			{ "requirements", Types.VARCHAR },
			{ "requestKey", Types.VARCHAR },
			{ "jenkinsResults", Types.CLOB },
			{ "comments", Types.CLOB },
			{ "fixPackStatus", Types.INTEGER },
			{ "notified", Types.BOOLEAN },
			{ "productVersion", Types.INTEGER },
			{ "status", Types.INTEGER },
			{ "statusByUserId", Types.BIGINT },
			{ "statusByUserName", Types.VARCHAR },
			{ "statusDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_PatcherFix (patcherFixId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,patcherProductVersionId LONG,patcherProjectVersionId LONG,name TEXT null,key_ VARCHAR(75) null,keyVersion DOUBLE,type_ INTEGER,latestFix BOOLEAN,obsolete BOOLEAN,committish VARCHAR(75) null,gitHash VARCHAR(75) null,gitRemoteURL VARCHAR(500) null,dependencies VARCHAR(500) null,requirements VARCHAR(75) null,requestKey VARCHAR(75) null,jenkinsResults TEXT null,comments TEXT null,fixPackStatus INTEGER,notified BOOLEAN,productVersion INTEGER,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table OSB_PatcherFix";
	public static final String ORDER_BY_JPQL = " ORDER BY patcherFix.patcherFixId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_PatcherFix.patcherFixId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.patcher.model.PatcherFix"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.patcher.model.PatcherFix"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final String MAPPING_TABLE_OSB_PATCHERBUILDS_PATCHERFIXES_NAME =
		"OSB_PatcherBuilds_PatcherFixes";
	public static final Object[][] MAPPING_TABLE_OSB_PATCHERBUILDS_PATCHERFIXES_COLUMNS =
		{
			{ "patcherBuildId", Types.BIGINT },
			{ "patcherFixId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_PATCHERBUILDS_PATCHERFIXES_SQL_CREATE =
		"create table OSB_PatcherBuilds_PatcherFixes (patcherBuildId LONG not null,patcherFixId LONG not null,primary key (patcherBuildId, patcherFixId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_PATCHERBUILDS_PATCHERFIXES =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_PatcherBuilds_PatcherFixes"),
			true);
	public static final String MAPPING_TABLE_OSB_PATCHERFIXES_PATCHERFIXPACKS_NAME =
		"OSB_PatcherFixes_PatcherFixPacks";
	public static final Object[][] MAPPING_TABLE_OSB_PATCHERFIXES_PATCHERFIXPACKS_COLUMNS =
		{
			{ "patcherFixId", Types.BIGINT },
			{ "patcherFixPackId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_PATCHERFIXES_PATCHERFIXPACKS_SQL_CREATE =
		"create table OSB_PatcherFixes_PatcherFixPacks (patcherFixId LONG not null,patcherFixPackId LONG not null,primary key (patcherFixId, patcherFixPackId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_PATCHERFIXES_PATCHERFIXPACKS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_PatcherFixes_PatcherFixPacks"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.patcher.model.PatcherFix"));

	public PatcherFixModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _patcherFixId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatcherFixId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _patcherFixId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PatcherFix.class;
	}

	@Override
	public String getModelClassName() {
		return PatcherFix.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("patcherFixId", getPatcherFixId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("patcherProductVersionId", getPatcherProductVersionId());
		attributes.put("patcherProjectVersionId", getPatcherProjectVersionId());
		attributes.put("name", getName());
		attributes.put("key", getKey());
		attributes.put("keyVersion", getKeyVersion());
		attributes.put("type", getType());
		attributes.put("latestFix", getLatestFix());
		attributes.put("obsolete", getObsolete());
		attributes.put("committish", getCommittish());
		attributes.put("gitHash", getGitHash());
		attributes.put("gitRemoteURL", getGitRemoteURL());
		attributes.put("dependencies", getDependencies());
		attributes.put("requirements", getRequirements());
		attributes.put("requestKey", getRequestKey());
		attributes.put("jenkinsResults", getJenkinsResults());
		attributes.put("comments", getComments());
		attributes.put("fixPackStatus", getFixPackStatus());
		attributes.put("notified", getNotified());
		attributes.put("productVersion", getProductVersion());
		attributes.put("status", getStatus());
		attributes.put("statusByUserId", getStatusByUserId());
		attributes.put("statusByUserName", getStatusByUserName());
		attributes.put("statusDate", getStatusDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long patcherFixId = (Long)attributes.get("patcherFixId");

		if (patcherFixId != null) {
			setPatcherFixId(patcherFixId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long patcherProductVersionId = (Long)attributes.get(
				"patcherProductVersionId");

		if (patcherProductVersionId != null) {
			setPatcherProductVersionId(patcherProductVersionId);
		}

		Long patcherProjectVersionId = (Long)attributes.get(
				"patcherProjectVersionId");

		if (patcherProjectVersionId != null) {
			setPatcherProjectVersionId(patcherProjectVersionId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String key = (String)attributes.get("key");

		if (key != null) {
			setKey(key);
		}

		Double keyVersion = (Double)attributes.get("keyVersion");

		if (keyVersion != null) {
			setKeyVersion(keyVersion);
		}

		Integer type = (Integer)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Boolean latestFix = (Boolean)attributes.get("latestFix");

		if (latestFix != null) {
			setLatestFix(latestFix);
		}

		Boolean obsolete = (Boolean)attributes.get("obsolete");

		if (obsolete != null) {
			setObsolete(obsolete);
		}

		String committish = (String)attributes.get("committish");

		if (committish != null) {
			setCommittish(committish);
		}

		String gitHash = (String)attributes.get("gitHash");

		if (gitHash != null) {
			setGitHash(gitHash);
		}

		String gitRemoteURL = (String)attributes.get("gitRemoteURL");

		if (gitRemoteURL != null) {
			setGitRemoteURL(gitRemoteURL);
		}

		String dependencies = (String)attributes.get("dependencies");

		if (dependencies != null) {
			setDependencies(dependencies);
		}

		String requirements = (String)attributes.get("requirements");

		if (requirements != null) {
			setRequirements(requirements);
		}

		String requestKey = (String)attributes.get("requestKey");

		if (requestKey != null) {
			setRequestKey(requestKey);
		}

		String jenkinsResults = (String)attributes.get("jenkinsResults");

		if (jenkinsResults != null) {
			setJenkinsResults(jenkinsResults);
		}

		String comments = (String)attributes.get("comments");

		if (comments != null) {
			setComments(comments);
		}

		Integer fixPackStatus = (Integer)attributes.get("fixPackStatus");

		if (fixPackStatus != null) {
			setFixPackStatus(fixPackStatus);
		}

		Boolean notified = (Boolean)attributes.get("notified");

		if (notified != null) {
			setNotified(notified);
		}

		Integer productVersion = (Integer)attributes.get("productVersion");

		if (productVersion != null) {
			setProductVersion(productVersion);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Long statusByUserId = (Long)attributes.get("statusByUserId");

		if (statusByUserId != null) {
			setStatusByUserId(statusByUserId);
		}

		String statusByUserName = (String)attributes.get("statusByUserName");

		if (statusByUserName != null) {
			setStatusByUserName(statusByUserName);
		}

		Date statusDate = (Date)attributes.get("statusDate");

		if (statusDate != null) {
			setStatusDate(statusDate);
		}
	}

	@Override
	public long getPatcherFixId() {
		return _patcherFixId;
	}

	@Override
	public void setPatcherFixId(long patcherFixId) {
		_patcherFixId = patcherFixId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getPatcherProductVersionId() {
		return _patcherProductVersionId;
	}

	@Override
	public void setPatcherProductVersionId(long patcherProductVersionId) {
		_patcherProductVersionId = patcherProductVersionId;
	}

	@Override
	public long getPatcherProjectVersionId() {
		return _patcherProjectVersionId;
	}

	@Override
	public void setPatcherProjectVersionId(long patcherProjectVersionId) {
		_patcherProjectVersionId = patcherProjectVersionId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getKey() {
		if (_key == null) {
			return StringPool.BLANK;
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		_key = key;
	}

	@Override
	public double getKeyVersion() {
		return _keyVersion;
	}

	@Override
	public void setKeyVersion(double keyVersion) {
		_keyVersion = keyVersion;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_type = type;
	}

	@Override
	public boolean getLatestFix() {
		return _latestFix;
	}

	@Override
	public boolean isLatestFix() {
		return _latestFix;
	}

	@Override
	public void setLatestFix(boolean latestFix) {
		_latestFix = latestFix;
	}

	@Override
	public boolean getObsolete() {
		return _obsolete;
	}

	@Override
	public boolean isObsolete() {
		return _obsolete;
	}

	@Override
	public void setObsolete(boolean obsolete) {
		_obsolete = obsolete;
	}

	@Override
	public String getCommittish() {
		if (_committish == null) {
			return StringPool.BLANK;
		}
		else {
			return _committish;
		}
	}

	@Override
	public void setCommittish(String committish) {
		_committish = committish;
	}

	@Override
	public String getGitHash() {
		if (_gitHash == null) {
			return StringPool.BLANK;
		}
		else {
			return _gitHash;
		}
	}

	@Override
	public void setGitHash(String gitHash) {
		_gitHash = gitHash;
	}

	@Override
	public String getGitRemoteURL() {
		if (_gitRemoteURL == null) {
			return StringPool.BLANK;
		}
		else {
			return _gitRemoteURL;
		}
	}

	@Override
	public void setGitRemoteURL(String gitRemoteURL) {
		_gitRemoteURL = gitRemoteURL;
	}

	@Override
	public String getDependencies() {
		if (_dependencies == null) {
			return StringPool.BLANK;
		}
		else {
			return _dependencies;
		}
	}

	@Override
	public void setDependencies(String dependencies) {
		_dependencies = dependencies;
	}

	@Override
	public String getRequirements() {
		if (_requirements == null) {
			return StringPool.BLANK;
		}
		else {
			return _requirements;
		}
	}

	@Override
	public void setRequirements(String requirements) {
		_requirements = requirements;
	}

	@Override
	public String getRequestKey() {
		if (_requestKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestKey;
		}
	}

	@Override
	public void setRequestKey(String requestKey) {
		_requestKey = requestKey;
	}

	@Override
	public String getJenkinsResults() {
		if (_jenkinsResults == null) {
			return StringPool.BLANK;
		}
		else {
			return _jenkinsResults;
		}
	}

	@Override
	public void setJenkinsResults(String jenkinsResults) {
		_jenkinsResults = jenkinsResults;
	}

	@Override
	public String getComments() {
		if (_comments == null) {
			return StringPool.BLANK;
		}
		else {
			return _comments;
		}
	}

	@Override
	public void setComments(String comments) {
		_comments = comments;
	}

	@Override
	public int getFixPackStatus() {
		return _fixPackStatus;
	}

	@Override
	public void setFixPackStatus(int fixPackStatus) {
		_fixPackStatus = fixPackStatus;
	}

	@Override
	public boolean getNotified() {
		return _notified;
	}

	@Override
	public boolean isNotified() {
		return _notified;
	}

	@Override
	public void setNotified(boolean notified) {
		_notified = notified;
	}

	@Override
	public int getProductVersion() {
		return _productVersion;
	}

	@Override
	public void setProductVersion(int productVersion) {
		_productVersion = productVersion;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getStatusByUserId(), "uuid",
			_statusByUserUuid);
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
		_statusByUserUuid = statusByUserUuid;
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return StringPool.BLANK;
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved}
	 */
	@Override
	public boolean getApproved() {
		return isApproved();
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PatcherFix.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PatcherFix toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PatcherFix)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatcherFixImpl patcherFixImpl = new PatcherFixImpl();

		patcherFixImpl.setPatcherFixId(getPatcherFixId());
		patcherFixImpl.setCompanyId(getCompanyId());
		patcherFixImpl.setUserId(getUserId());
		patcherFixImpl.setUserName(getUserName());
		patcherFixImpl.setCreateDate(getCreateDate());
		patcherFixImpl.setModifiedDate(getModifiedDate());
		patcherFixImpl.setPatcherProductVersionId(getPatcherProductVersionId());
		patcherFixImpl.setPatcherProjectVersionId(getPatcherProjectVersionId());
		patcherFixImpl.setName(getName());
		patcherFixImpl.setKey(getKey());
		patcherFixImpl.setKeyVersion(getKeyVersion());
		patcherFixImpl.setType(getType());
		patcherFixImpl.setLatestFix(getLatestFix());
		patcherFixImpl.setObsolete(getObsolete());
		patcherFixImpl.setCommittish(getCommittish());
		patcherFixImpl.setGitHash(getGitHash());
		patcherFixImpl.setGitRemoteURL(getGitRemoteURL());
		patcherFixImpl.setDependencies(getDependencies());
		patcherFixImpl.setRequirements(getRequirements());
		patcherFixImpl.setRequestKey(getRequestKey());
		patcherFixImpl.setJenkinsResults(getJenkinsResults());
		patcherFixImpl.setComments(getComments());
		patcherFixImpl.setFixPackStatus(getFixPackStatus());
		patcherFixImpl.setNotified(getNotified());
		patcherFixImpl.setProductVersion(getProductVersion());
		patcherFixImpl.setStatus(getStatus());
		patcherFixImpl.setStatusByUserId(getStatusByUserId());
		patcherFixImpl.setStatusByUserName(getStatusByUserName());
		patcherFixImpl.setStatusDate(getStatusDate());

		patcherFixImpl.resetOriginalValues();

		return patcherFixImpl;
	}

	@Override
	public int compareTo(PatcherFix patcherFix) {
		long primaryKey = patcherFix.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PatcherFix)) {
			return false;
		}

		PatcherFix patcherFix = (PatcherFix)obj;

		long primaryKey = patcherFix.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<PatcherFix> toCacheModel() {
		PatcherFixCacheModel patcherFixCacheModel = new PatcherFixCacheModel();

		patcherFixCacheModel.patcherFixId = getPatcherFixId();

		patcherFixCacheModel.companyId = getCompanyId();

		patcherFixCacheModel.userId = getUserId();

		patcherFixCacheModel.userName = getUserName();

		String userName = patcherFixCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			patcherFixCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			patcherFixCacheModel.createDate = createDate.getTime();
		}
		else {
			patcherFixCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			patcherFixCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			patcherFixCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		patcherFixCacheModel.patcherProductVersionId = getPatcherProductVersionId();

		patcherFixCacheModel.patcherProjectVersionId = getPatcherProjectVersionId();

		patcherFixCacheModel.name = getName();

		String name = patcherFixCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			patcherFixCacheModel.name = null;
		}

		patcherFixCacheModel.key = getKey();

		String key = patcherFixCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			patcherFixCacheModel.key = null;
		}

		patcherFixCacheModel.keyVersion = getKeyVersion();

		patcherFixCacheModel.type = getType();

		patcherFixCacheModel.latestFix = getLatestFix();

		patcherFixCacheModel.obsolete = getObsolete();

		patcherFixCacheModel.committish = getCommittish();

		String committish = patcherFixCacheModel.committish;

		if ((committish != null) && (committish.length() == 0)) {
			patcherFixCacheModel.committish = null;
		}

		patcherFixCacheModel.gitHash = getGitHash();

		String gitHash = patcherFixCacheModel.gitHash;

		if ((gitHash != null) && (gitHash.length() == 0)) {
			patcherFixCacheModel.gitHash = null;
		}

		patcherFixCacheModel.gitRemoteURL = getGitRemoteURL();

		String gitRemoteURL = patcherFixCacheModel.gitRemoteURL;

		if ((gitRemoteURL != null) && (gitRemoteURL.length() == 0)) {
			patcherFixCacheModel.gitRemoteURL = null;
		}

		patcherFixCacheModel.dependencies = getDependencies();

		String dependencies = patcherFixCacheModel.dependencies;

		if ((dependencies != null) && (dependencies.length() == 0)) {
			patcherFixCacheModel.dependencies = null;
		}

		patcherFixCacheModel.requirements = getRequirements();

		String requirements = patcherFixCacheModel.requirements;

		if ((requirements != null) && (requirements.length() == 0)) {
			patcherFixCacheModel.requirements = null;
		}

		patcherFixCacheModel.requestKey = getRequestKey();

		String requestKey = patcherFixCacheModel.requestKey;

		if ((requestKey != null) && (requestKey.length() == 0)) {
			patcherFixCacheModel.requestKey = null;
		}

		patcherFixCacheModel.jenkinsResults = getJenkinsResults();

		String jenkinsResults = patcherFixCacheModel.jenkinsResults;

		if ((jenkinsResults != null) && (jenkinsResults.length() == 0)) {
			patcherFixCacheModel.jenkinsResults = null;
		}

		patcherFixCacheModel.comments = getComments();

		String comments = patcherFixCacheModel.comments;

		if ((comments != null) && (comments.length() == 0)) {
			patcherFixCacheModel.comments = null;
		}

		patcherFixCacheModel.fixPackStatus = getFixPackStatus();

		patcherFixCacheModel.notified = getNotified();

		patcherFixCacheModel.productVersion = getProductVersion();

		patcherFixCacheModel.status = getStatus();

		patcherFixCacheModel.statusByUserId = getStatusByUserId();

		patcherFixCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = patcherFixCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			patcherFixCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			patcherFixCacheModel.statusDate = statusDate.getTime();
		}
		else {
			patcherFixCacheModel.statusDate = Long.MIN_VALUE;
		}

		return patcherFixCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(59);

		sb.append("{patcherFixId=");
		sb.append(getPatcherFixId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", patcherProductVersionId=");
		sb.append(getPatcherProductVersionId());
		sb.append(", patcherProjectVersionId=");
		sb.append(getPatcherProjectVersionId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", key=");
		sb.append(getKey());
		sb.append(", keyVersion=");
		sb.append(getKeyVersion());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", latestFix=");
		sb.append(getLatestFix());
		sb.append(", obsolete=");
		sb.append(getObsolete());
		sb.append(", committish=");
		sb.append(getCommittish());
		sb.append(", gitHash=");
		sb.append(getGitHash());
		sb.append(", gitRemoteURL=");
		sb.append(getGitRemoteURL());
		sb.append(", dependencies=");
		sb.append(getDependencies());
		sb.append(", requirements=");
		sb.append(getRequirements());
		sb.append(", requestKey=");
		sb.append(getRequestKey());
		sb.append(", jenkinsResults=");
		sb.append(getJenkinsResults());
		sb.append(", comments=");
		sb.append(getComments());
		sb.append(", fixPackStatus=");
		sb.append(getFixPackStatus());
		sb.append(", notified=");
		sb.append(getNotified());
		sb.append(", productVersion=");
		sb.append(getProductVersion());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", statusByUserId=");
		sb.append(getStatusByUserId());
		sb.append(", statusByUserName=");
		sb.append(getStatusByUserName());
		sb.append(", statusDate=");
		sb.append(getStatusDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(91);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.patcher.model.PatcherFix");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>patcherFixId</column-name><column-value><![CDATA[");
		sb.append(getPatcherFixId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>patcherProductVersionId</column-name><column-value><![CDATA[");
		sb.append(getPatcherProductVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>patcherProjectVersionId</column-name><column-value><![CDATA[");
		sb.append(getPatcherProjectVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>key</column-name><column-value><![CDATA[");
		sb.append(getKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>keyVersion</column-name><column-value><![CDATA[");
		sb.append(getKeyVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>latestFix</column-name><column-value><![CDATA[");
		sb.append(getLatestFix());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>obsolete</column-name><column-value><![CDATA[");
		sb.append(getObsolete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>committish</column-name><column-value><![CDATA[");
		sb.append(getCommittish());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gitHash</column-name><column-value><![CDATA[");
		sb.append(getGitHash());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>gitRemoteURL</column-name><column-value><![CDATA[");
		sb.append(getGitRemoteURL());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dependencies</column-name><column-value><![CDATA[");
		sb.append(getDependencies());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requirements</column-name><column-value><![CDATA[");
		sb.append(getRequirements());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestKey</column-name><column-value><![CDATA[");
		sb.append(getRequestKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jenkinsResults</column-name><column-value><![CDATA[");
		sb.append(getJenkinsResults());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comments</column-name><column-value><![CDATA[");
		sb.append(getComments());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fixPackStatus</column-name><column-value><![CDATA[");
		sb.append(getFixPackStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>notified</column-name><column-value><![CDATA[");
		sb.append(getNotified());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productVersion</column-name><column-value><![CDATA[");
		sb.append(getProductVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserId</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusByUserName</column-name><column-value><![CDATA[");
		sb.append(getStatusByUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusDate</column-name><column-value><![CDATA[");
		sb.append(getStatusDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PatcherFix.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PatcherFix.class
		};
	private long _patcherFixId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _patcherProductVersionId;
	private long _patcherProjectVersionId;
	private String _name;
	private String _key;
	private double _keyVersion;
	private int _type;
	private boolean _latestFix;
	private boolean _obsolete;
	private String _committish;
	private String _gitHash;
	private String _gitRemoteURL;
	private String _dependencies;
	private String _requirements;
	private String _requestKey;
	private String _jenkinsResults;
	private String _comments;
	private int _fixPackStatus;
	private boolean _notified;
	private int _productVersion;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserUuid;
	private String _statusByUserName;
	private Date _statusDate;
	private PatcherFix _escapedModel;
}