/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.patcher.model.impl;

import com.liferay.osb.patcher.model.PatcherFixPack;
import com.liferay.osb.patcher.model.PatcherFixPackModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PatcherFixPack service. Represents a row in the &quot;OSB_PatcherFixPack&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.osb.patcher.model.PatcherFixPackModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatcherFixPackImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see PatcherFixPackImpl
 * @see com.liferay.osb.patcher.model.PatcherFixPack
 * @see com.liferay.osb.patcher.model.PatcherFixPackModel
 * @generated
 */
public class PatcherFixPackModelImpl extends BaseModelImpl<PatcherFixPack>
	implements PatcherFixPackModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patcher fix pack model instance should use the {@link com.liferay.osb.patcher.model.PatcherFixPack} interface instead.
	 */
	public static final String TABLE_NAME = "OSB_PatcherFixPack";
	public static final Object[][] TABLE_COLUMNS = {
			{ "patcherFixPackId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "patcherBuildId", Types.BIGINT },
			{ "patcherFixComponentId", Types.BIGINT },
			{ "patcherProjectVersionId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "version", Types.INTEGER },
			{ "releasedDate", Types.TIMESTAMP },
			{ "requirements", Types.VARCHAR },
			{ "status", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table OSB_PatcherFixPack (patcherFixPackId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,patcherBuildId LONG,patcherFixComponentId LONG,patcherProjectVersionId LONG,name VARCHAR(75) null,version INTEGER,releasedDate DATE null,requirements VARCHAR(75) null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table OSB_PatcherFixPack";
	public static final String ORDER_BY_JPQL = " ORDER BY patcherFixPack.patcherFixPackId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OSB_PatcherFixPack.patcherFixPackId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.osb.patcher.model.PatcherFixPack"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.osb.patcher.model.PatcherFixPack"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.osb.patcher.model.PatcherFixPack"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long PATCHERFIXCOMPONENTID_COLUMN_BITMASK = 2L;
	public static long PATCHERPROJECTVERSIONID_COLUMN_BITMASK = 4L;
	public static long VERSION_COLUMN_BITMASK = 8L;
	public static long PATCHERFIXPACKID_COLUMN_BITMASK = 16L;
	public static final String MAPPING_TABLE_OSB_PATCHERFIXES_PATCHERFIXPACKS_NAME =
		"OSB_PatcherFixes_PatcherFixPacks";
	public static final Object[][] MAPPING_TABLE_OSB_PATCHERFIXES_PATCHERFIXPACKS_COLUMNS =
		{
			{ "patcherFixId", Types.BIGINT },
			{ "patcherFixPackId", Types.BIGINT }
		};
	public static final String MAPPING_TABLE_OSB_PATCHERFIXES_PATCHERFIXPACKS_SQL_CREATE =
		"create table OSB_PatcherFixes_PatcherFixPacks (patcherFixId LONG not null,patcherFixPackId LONG not null,primary key (patcherFixId, patcherFixPackId))";
	public static final boolean FINDER_CACHE_ENABLED_OSB_PATCHERFIXES_PATCHERFIXPACKS =
		GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.OSB_PatcherFixes_PatcherFixPacks"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.osb.patcher.model.PatcherFixPack"));

	public PatcherFixPackModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _patcherFixPackId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatcherFixPackId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _patcherFixPackId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PatcherFixPack.class;
	}

	@Override
	public String getModelClassName() {
		return PatcherFixPack.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("patcherFixPackId", getPatcherFixPackId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("patcherBuildId", getPatcherBuildId());
		attributes.put("patcherFixComponentId", getPatcherFixComponentId());
		attributes.put("patcherProjectVersionId", getPatcherProjectVersionId());
		attributes.put("name", getName());
		attributes.put("version", getVersion());
		attributes.put("releasedDate", getReleasedDate());
		attributes.put("requirements", getRequirements());
		attributes.put("status", getStatus());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long patcherFixPackId = (Long)attributes.get("patcherFixPackId");

		if (patcherFixPackId != null) {
			setPatcherFixPackId(patcherFixPackId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long patcherBuildId = (Long)attributes.get("patcherBuildId");

		if (patcherBuildId != null) {
			setPatcherBuildId(patcherBuildId);
		}

		Long patcherFixComponentId = (Long)attributes.get(
				"patcherFixComponentId");

		if (patcherFixComponentId != null) {
			setPatcherFixComponentId(patcherFixComponentId);
		}

		Long patcherProjectVersionId = (Long)attributes.get(
				"patcherProjectVersionId");

		if (patcherProjectVersionId != null) {
			setPatcherProjectVersionId(patcherProjectVersionId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		Integer version = (Integer)attributes.get("version");

		if (version != null) {
			setVersion(version);
		}

		Date releasedDate = (Date)attributes.get("releasedDate");

		if (releasedDate != null) {
			setReleasedDate(releasedDate);
		}

		String requirements = (String)attributes.get("requirements");

		if (requirements != null) {
			setRequirements(requirements);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@Override
	public long getPatcherFixPackId() {
		return _patcherFixPackId;
	}

	@Override
	public void setPatcherFixPackId(long patcherFixPackId) {
		_patcherFixPackId = patcherFixPackId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public long getPatcherBuildId() {
		return _patcherBuildId;
	}

	@Override
	public void setPatcherBuildId(long patcherBuildId) {
		_patcherBuildId = patcherBuildId;
	}

	@Override
	public long getPatcherFixComponentId() {
		return _patcherFixComponentId;
	}

	@Override
	public void setPatcherFixComponentId(long patcherFixComponentId) {
		_columnBitmask |= PATCHERFIXCOMPONENTID_COLUMN_BITMASK;

		if (!_setOriginalPatcherFixComponentId) {
			_setOriginalPatcherFixComponentId = true;

			_originalPatcherFixComponentId = _patcherFixComponentId;
		}

		_patcherFixComponentId = patcherFixComponentId;
	}

	public long getOriginalPatcherFixComponentId() {
		return _originalPatcherFixComponentId;
	}

	@Override
	public long getPatcherProjectVersionId() {
		return _patcherProjectVersionId;
	}

	@Override
	public void setPatcherProjectVersionId(long patcherProjectVersionId) {
		_columnBitmask |= PATCHERPROJECTVERSIONID_COLUMN_BITMASK;

		if (!_setOriginalPatcherProjectVersionId) {
			_setOriginalPatcherProjectVersionId = true;

			_originalPatcherProjectVersionId = _patcherProjectVersionId;
		}

		_patcherProjectVersionId = patcherProjectVersionId;
	}

	public long getOriginalPatcherProjectVersionId() {
		return _originalPatcherProjectVersionId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		_columnBitmask |= VERSION_COLUMN_BITMASK;

		if (!_setOriginalVersion) {
			_setOriginalVersion = true;

			_originalVersion = _version;
		}

		_version = version;
	}

	public int getOriginalVersion() {
		return _originalVersion;
	}

	@Override
	public Date getReleasedDate() {
		return _releasedDate;
	}

	@Override
	public void setReleasedDate(Date releasedDate) {
		_releasedDate = releasedDate;
	}

	@Override
	public String getRequirements() {
		if (_requirements == null) {
			return StringPool.BLANK;
		}
		else {
			return _requirements;
		}
	}

	@Override
	public void setRequirements(String requirements) {
		_requirements = requirements;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			PatcherFixPack.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PatcherFixPack toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PatcherFixPack)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatcherFixPackImpl patcherFixPackImpl = new PatcherFixPackImpl();

		patcherFixPackImpl.setPatcherFixPackId(getPatcherFixPackId());
		patcherFixPackImpl.setCompanyId(getCompanyId());
		patcherFixPackImpl.setUserId(getUserId());
		patcherFixPackImpl.setUserName(getUserName());
		patcherFixPackImpl.setCreateDate(getCreateDate());
		patcherFixPackImpl.setModifiedDate(getModifiedDate());
		patcherFixPackImpl.setPatcherBuildId(getPatcherBuildId());
		patcherFixPackImpl.setPatcherFixComponentId(getPatcherFixComponentId());
		patcherFixPackImpl.setPatcherProjectVersionId(getPatcherProjectVersionId());
		patcherFixPackImpl.setName(getName());
		patcherFixPackImpl.setVersion(getVersion());
		patcherFixPackImpl.setReleasedDate(getReleasedDate());
		patcherFixPackImpl.setRequirements(getRequirements());
		patcherFixPackImpl.setStatus(getStatus());

		patcherFixPackImpl.resetOriginalValues();

		return patcherFixPackImpl;
	}

	@Override
	public int compareTo(PatcherFixPack patcherFixPack) {
		long primaryKey = patcherFixPack.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PatcherFixPack)) {
			return false;
		}

		PatcherFixPack patcherFixPack = (PatcherFixPack)obj;

		long primaryKey = patcherFixPack.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PatcherFixPackModelImpl patcherFixPackModelImpl = this;

		patcherFixPackModelImpl._originalPatcherFixComponentId = patcherFixPackModelImpl._patcherFixComponentId;

		patcherFixPackModelImpl._setOriginalPatcherFixComponentId = false;

		patcherFixPackModelImpl._originalPatcherProjectVersionId = patcherFixPackModelImpl._patcherProjectVersionId;

		patcherFixPackModelImpl._setOriginalPatcherProjectVersionId = false;

		patcherFixPackModelImpl._originalName = patcherFixPackModelImpl._name;

		patcherFixPackModelImpl._originalVersion = patcherFixPackModelImpl._version;

		patcherFixPackModelImpl._setOriginalVersion = false;

		patcherFixPackModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PatcherFixPack> toCacheModel() {
		PatcherFixPackCacheModel patcherFixPackCacheModel = new PatcherFixPackCacheModel();

		patcherFixPackCacheModel.patcherFixPackId = getPatcherFixPackId();

		patcherFixPackCacheModel.companyId = getCompanyId();

		patcherFixPackCacheModel.userId = getUserId();

		patcherFixPackCacheModel.userName = getUserName();

		String userName = patcherFixPackCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			patcherFixPackCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			patcherFixPackCacheModel.createDate = createDate.getTime();
		}
		else {
			patcherFixPackCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			patcherFixPackCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			patcherFixPackCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		patcherFixPackCacheModel.patcherBuildId = getPatcherBuildId();

		patcherFixPackCacheModel.patcherFixComponentId = getPatcherFixComponentId();

		patcherFixPackCacheModel.patcherProjectVersionId = getPatcherProjectVersionId();

		patcherFixPackCacheModel.name = getName();

		String name = patcherFixPackCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			patcherFixPackCacheModel.name = null;
		}

		patcherFixPackCacheModel.version = getVersion();

		Date releasedDate = getReleasedDate();

		if (releasedDate != null) {
			patcherFixPackCacheModel.releasedDate = releasedDate.getTime();
		}
		else {
			patcherFixPackCacheModel.releasedDate = Long.MIN_VALUE;
		}

		patcherFixPackCacheModel.requirements = getRequirements();

		String requirements = patcherFixPackCacheModel.requirements;

		if ((requirements != null) && (requirements.length() == 0)) {
			patcherFixPackCacheModel.requirements = null;
		}

		patcherFixPackCacheModel.status = getStatus();

		return patcherFixPackCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(29);

		sb.append("{patcherFixPackId=");
		sb.append(getPatcherFixPackId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", patcherBuildId=");
		sb.append(getPatcherBuildId());
		sb.append(", patcherFixComponentId=");
		sb.append(getPatcherFixComponentId());
		sb.append(", patcherProjectVersionId=");
		sb.append(getPatcherProjectVersionId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", version=");
		sb.append(getVersion());
		sb.append(", releasedDate=");
		sb.append(getReleasedDate());
		sb.append(", requirements=");
		sb.append(getRequirements());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(46);

		sb.append("<model><model-name>");
		sb.append("com.liferay.osb.patcher.model.PatcherFixPack");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>patcherFixPackId</column-name><column-value><![CDATA[");
		sb.append(getPatcherFixPackId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>patcherBuildId</column-name><column-value><![CDATA[");
		sb.append(getPatcherBuildId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>patcherFixComponentId</column-name><column-value><![CDATA[");
		sb.append(getPatcherFixComponentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>patcherProjectVersionId</column-name><column-value><![CDATA[");
		sb.append(getPatcherProjectVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>version</column-name><column-value><![CDATA[");
		sb.append(getVersion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>releasedDate</column-name><column-value><![CDATA[");
		sb.append(getReleasedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requirements</column-name><column-value><![CDATA[");
		sb.append(getRequirements());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PatcherFixPack.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PatcherFixPack.class
		};
	private long _patcherFixPackId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _patcherBuildId;
	private long _patcherFixComponentId;
	private long _originalPatcherFixComponentId;
	private boolean _setOriginalPatcherFixComponentId;
	private long _patcherProjectVersionId;
	private long _originalPatcherProjectVersionId;
	private boolean _setOriginalPatcherProjectVersionId;
	private String _name;
	private String _originalName;
	private int _version;
	private int _originalVersion;
	private boolean _setOriginalVersion;
	private Date _releasedDate;
	private String _requirements;
	private int _status;
	private long _columnBitmask;
	private PatcherFixPack _escapedModel;
}