##
## Test Suites
##

    modified.files.includes[relevant][frontend-taglib-clay-playwright-rule]=**
    relevant.rule.names=frontend-taglib-clay-playwright-rule

    test.batch.names[relevant][frontend-taglib-clay-playwright-rule]=\
        playwright-js-tomcat101-mysql57

    #
    # Relevant
    #

    ignoreParents[relevant][frontend-taglib-clay-rule]=true

    playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][frontend-taglib-clay-playwright-rule]=\
        frontend-taglib-clay.main

##
## Testray
##

    testray.main.component.name=Frontend Taglib