dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly project(":core:petra:petra-string")
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testImplementation project(":core:petra:petra-function")
}