#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.object.admin.rest.dto.v1_0.ObjectDefinition
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=true
crud.item.delegate=true
entity.class.name=com.liferay.object.admin.rest.dto.v1_0.ObjectDefinition
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Object.Admin.REST)
osgi.jaxrs.resource=true