dependencies {
	compileInclude group: "com.drewnoakes", name: "metadata-extractor", version: "2.20.0"
	compileInclude group: "com.epam", name: "parso", version: "2.0.14"
	compileInclude group: "com.github.albfernandez", name: "juniversalchardet", version: "2.5.0"
	compileInclude group: "com.github.jai-imageio", name: "jai-imageio-core", version: "1.4.0"
	compileInclude group: "com.googlecode.plist", name: "dd-plist", version: "1.29"
	compileInclude group: "com.healthmarketscience.jackcess", name: "jackcess", version: "4.0.10"
	compileInclude group: "com.healthmarketscience.jackcess", name: "jackcess-encrypt", version: "4.0.3"
	compileInclude group: "com.liferay", name: "org.gagravarr.tika", version: "0.8.LIFERAY-PATCHED-1"
	compileInclude group: "com.pff", name: "java-libpst", version: "0.9.3"
	compileInclude group: "edu.ucar", name: "cdm", version: "4.5.5"
	compileInclude group: "edu.ucar", name: "netcdf4", version: "4.5.5"
	compileInclude group: "edu.ucar", name: "udunits", version: "4.5.5"
	compileInclude group: "net.java.dev.jna", name: "jna", version: "4.1.0"
	compileInclude group: "org.apache.james", name: "apache-mime4j-core", version: "0.8.14"
	compileInclude group: "org.apache.james", name: "apache-mime4j-dom", version: "0.8.14"
	compileInclude group: "org.apache.pdfbox", name: "jempbox", version: "1.8.17"
	compileInclude group: "org.apache.pdfbox", name: "xmpbox", version: "3.0.7"
	compileInclude group: "org.apache.poi", name: "poi-scratchpad", version: "5.4.1"
	compileInclude group: "org.apache.tika", name: "tika-core", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-apple-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-audiovideo-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-cad-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-code-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-font-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-html-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-image-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-mail-commons", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-mail-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-microsoft-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-miscoffice-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-pdf-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-pkg-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-scientific-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-text-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-xml-module", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-xmp-commons", version: "3.3.1"
	compileInclude group: "org.apache.tika", name: "tika-parser-zip-commons", version: "3.3.1"
	compileInclude group: "org.codelibs", name: "jhighlight", version: "1.1.1"
	compileInclude group: "org.gagravarr", name: "vorbis-java-core", version: "0.8"
	compileInclude group: "org.tallison", name: "jmatio", version: "1.5"
	compileOnly group: "com.adobe.xmp", name: "xmpcore", version: "6.1.11"
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "com.zaxxer", name: "SparseBitSet", version: "1.2"
	compileOnly group: "org.apache.commons", name: "commons-collections4", version: "4.5.0"
	compileOnly group: "org.apache.commons", name: "commons-lang3", version: "3.18.0"
	compileOnly group: "org.apache.commons", name: "commons-math3", version: "3.6.1"
	compileOnly group: "org.apache.poi", name: "poi", version: "5.4.1"
	compileOnly group: "org.apache.poi", name: "poi-ooxml", version: "5.4.1"
	compileOnly group: "org.apache.poi", name: "poi-ooxml-lite", version: "5.4.1"
	compileOnly group: "org.apache.xmlbeans", name: "xmlbeans", version: "5.3.0"
	compileOnly group: "org.jsoup", name: "jsoup", version: "1.23.1"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-persistence-api")
	compileOnly project(":core:petra:petra-concurrent")
	compileOnly project(":core:petra:petra-io")
	compileOnly project(":core:petra:petra-process")
	compileOnly project(":core:petra:petra-string")
}