dependencies {
	classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "5.3.103"
	classpath group: "com.liferay", name: "com.liferay.gradle.plugins.maven.plugin.builder", version: "1.2.0"
	classpath group: "de.undercouch", name: "gradle-download-task", version: "3.3.0"
	classpath group: "gradle.plugin.org.ysb33r.gradle", name: "gradletest", version: "1.1"
	classpath group: "xalan", name: "xalan", version: "2.7.2"
}

repositories {
	if (!Boolean.getBoolean("maven.local.ignore")) {
		mavenLocal()

		File tmpMavenRepositoryDir = null

		if (hasProperty("tmp.maven.repository.dir")) {
			tmpMavenRepositoryDir = file(properties["tmp.maven.repository.dir"])
		}
		else {
			tmpMavenRepositoryDir = file("../.m2-tmp")
		}

		if (tmpMavenRepositoryDir.exists()) {
			maven {
				url tmpMavenRepositoryDir
			}
		}
	}

	maven {
		url System.properties["repository.url"] ?: "https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public"
	}

	maven {
		url "https://plugins.gradle.org/m2"
	}
}