import org.eclipse.transformer.cli.JakartaTransformerCLI

buildscript {
	dependencies {
		classpath group: "org.eclipse.transformer", name: "org.eclipse.transformer.cli", version: "1.0.0"
	}

	repositories {
		maven {
			url System.properties["repository.url"] ?: "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

task jarTransformed

jar {
	enabled = true

	setActions([])

	finalizedBy jarTransformed
}

jarTransformed {
	doLast {
		JakartaTransformerCLI jakartaTransformerCLI = new JakartaTransformerCLI(System.out, System.out, new String[] {configurations.compileOnly.singleFile, jar.archivePath})

		Map<String, String> optionDefaults = jakartaTransformerCLI.getOptionDefaults()

		File file = new File(rootDir, "liferay-jakarta-renames.properties")

		optionDefaults.put("renames", String.valueOf(file.toURI()))

		file = new File(rootDir, "liferay-jakarta-versions.properties")

		optionDefaults.put("versions", String.valueOf(file.toURI()))

		JakartaTransformerCLI.runWith(jakartaTransformerCLI)
	}

	mustRunAfter generatePomFileForMavenPublication
}