jakarta.activation=[2.0,3);Export-Package=2.1.3
jakarta.annotation.security=[2.0,3);Export-Package=2.1.1
jakarta.annotation.sql=[2.0,3);Export-Package=2.1.1
jakarta.annotation=[2.0,3);Export-Package=2.1.1
jakarta.batch.api.chunk.listener=[2.0,3);Export-Package=2.0
jakarta.batch.api.chunk=[2.0,3);Export-Package=2.0
jakarta.batch.api.listener=[2.0,3);Export-Package=2.0
jakarta.batch.api.partition=[2.0,3);Export-Package=2.0
jakarta.batch.api=[2.0,3);Export-Package=2.0
jakarta.batch.operations=[2.0,3);Export-Package=2.0
jakarta.batch.runtime.context=[2.0,3);Export-Package=2.0
jakarta.batch.runtime=[2.0,3);Export-Package=2.0
jakarta.decorator=[4.0,5.0);Export-Package=4.1
jakarta.ejb.embeddable=[4.0,5);Export-Package=4.0
jakarta.ejb.spi=[4.0,5);Export-Package=4.0
jakarta.ejb=[4.0,5);Export-Package=4.0
jakarta.el=[6.0,7);Export-Package=6.0.1
jakarta.enterprise.concurrent=[2.0,4);Export-Package=2.0
jakarta.enterprise.context.control=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.context.spi=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.context=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.event=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.inject.literal=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.inject.spi.configurator=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.inject.spi=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.inject=[4.0,5.0);Export-Package=4.1
jakarta.enterprise.util=[4.0,5.0);Export-Package=4.1
jakarta.faces.application=[3.0,4.0);Export-Package=3.0
jakarta.faces.bean=[3.0,4.0);Export-Package=3.0
jakarta.faces.component.behavior=[3.0,4.0);Export-Package=3.0
jakarta.faces.component=[3.0,4.0);Export-Package=3.0
jakarta.faces.context=[3.0,4.0);Export-Package=3.0
jakarta.faces.convert=[3.0,4.0);Export-Package=3.0
jakarta.faces.event=[3.0,4.0);Export-Package=3.0
jakarta.faces.model=[3.0,4.0);Export-Package=3.0
jakarta.faces.render=[3.0,4.0);Export-Package=3.0
jakarta.faces.validator=[3.0,4.0);Export-Package=3.0
jakarta.faces.view.facelets=[3.0,4.0);Export-Package=3.0
jakarta.faces.webapp=[3.0,4.0);Export-Package=3.0
jakarta.faces=[3.0,4.0);Export-Package=3.0
jakarta.inject=[2.0,3.0);Export-Package=2.0.1
jakarta.interceptor=[2.0,3.0);Export-Package=2.2.0
jakarta.jms=[3.0,4);Export-Package=3.0
jakarta.json.bind.adapter=[3.0,4.0);Export-Package=3.0
jakarta.json.bind.annotation=[3.0,4.0);Export-Package=3.0
jakarta.json.bind.config=[3.0,4.0);Export-Package=3.0
jakarta.json.bind.serializer=[3.0,4.0);Export-Package=3.0
jakarta.json.bind.spi=[3.0,4.0);Export-Package=3.0
jakarta.json.bind=[3.0,4.0);Export-Package=3.0
jakarta.json.spi=[2.0,3.0);Export-Package=2.1.3
jakarta.json.stream=[2.0,3.0);Export-Package=2.1.3
jakarta.json=[2.0,3.0);Export-Package=2.1.3
jakarta.jws.soap=[3.0,4);Export-Package=3.0
jakarta.jws=[3.0,4);Export-Package=3.0
jakarta.persistence.criteria=[3.0,4);Export-Package=3.1
jakarta.persistence.metamodel=[3.0,4);Export-Package=3.1
jakarta.persistence.spi=[3.0,4);Export-Package=3.1
jakarta.persistence=[3.0,4);Export-Package=3.1
jakarta.resource.cci=[2.0,3);Export-Package=2.0
jakarta.resource.spi.endpoint=[2.0,3);Export-Package=2.0
jakarta.resource.spi.security=[2.0,3);Export-Package=2.0
jakarta.resource.spi.work=[2.0,3);Export-Package=2.0
jakarta.resource.spi=[2.0,3);Export-Package=2.0
jakarta.resource=[2.0,3);Export-Package=2.0
jakarta.security.auth.message.callback=[2.0,3);Export-Package=2.0
jakarta.security.auth.message.config=[2.0,3);Export-Package=2.0
jakarta.security.auth.message.module=[2.0,3);Export-Package=2.0
jakarta.security.auth.message=[2.0,3);Export-Package=2.0
jakarta.security.enterprise.authentication.mechanism.http=[2.0,3);Export-Package=2.0
jakarta.security.enterprise.credential=[2.0,3);Export-Package=2.0
jakarta.security.enterprise.identitystore=[2.0,3);Export-Package=2.0
jakarta.security.enterprise=[2.0,3);Export-Package=2.0
jakarta.security.jacc=[2.0,3);Export-Package=2.0
jakarta.servlet.annotation=[6.0,7);Export-Package=6.0
jakarta.servlet.descriptor=[6.0,7);Export-Package=6.0
jakarta.servlet.http=[6.0,7);Export-Package=6.0
jakarta.servlet.jsp.el=[3.0,4);Export-Package=3.1
jakarta.servlet.jsp.jstl.core=[3.0,4);Export-Package=3.0.2
jakarta.servlet.jsp.jstl.fmt=[3.0,4);Export-Package=3.0.2
jakarta.servlet.jsp.jstl.sql=[3.0,4);Export-Package=3.0.2
jakarta.servlet.jsp.jstl.tlv=[3.0,4);Export-Package=3.0.2
jakarta.servlet.jsp.jstl=[3.0,4);Export-Package=3.0.2
jakarta.servlet.jsp.resources=[3.0,4);Export-Package=3.1
jakarta.servlet.jsp.tagext=[3.0,4);Export-Package=3.1
jakarta.servlet.jsp=[3.0,4);Export-Package=3.1
jakarta.servlet.resources=[6.0,7);Export-Package=6.0
jakarta.servlet=[6.0,7);Export-Package=6.0
jakarta.transaction=[2.0,3);Export-Package=2.0.1
jakarta.validation.bootstrap=[3.0,4);Export-Package=3.1
jakarta.validation.constraints=[3.0,4);Export-Package=3.1
jakarta.validation.constraintvalidation=[3.0,4);Export-Package=3.1
jakarta.validation.executable=[3.0,4);Export-Package=3.1
jakarta.validation.groups=[3.0,4);Export-Package=3.1
jakarta.validation.metadata=[3.0,4);Export-Package=3.1
jakarta.validation.spi=[3.0,4);Export-Package=3.1
jakarta.validation.valueextraction=[3.0,4);Export-Package=3.1
jakarta.validation=[3.0,4);Export-Package=3.1
jakarta.websocket.server=[2.0,3);Export-Package=2.1
jakarta.websocket=[2.0,3);Export-Package=2.1
jakarta.ws.rs.client=[3.0,4.0);Export-Package=3.1
jakarta.ws.rs.container=[3.0,4.0);Export-Package=3.1
jakarta.ws.rs.core=[3.0,4.0);Export-Package=3.1
jakarta.ws.rs.ext=[3.0,4.0);Export-Package=3.1
jakarta.ws.rs.sse=[3.0,4.0);Export-Package=3.1
jakarta.ws.rs=[3.0,4.0);Export-Package=3.1
jakarta.xml.bind.annotation.adapters=[4.0,5);Export-Package=4.0.2
jakarta.xml.bind.annotation=[4.0,5);Export-Package=4.0.2
jakarta.xml.bind.attachment=[4.0,5);Export-Package=4.0.2
jakarta.xml.bind.helpers=[4.0,5);Export-Package=4.0.2
jakarta.xml.bind.util=[4.0,5);Export-Package=4.0.2
jakarta.xml.bind=[4.0,5);Export-Package=4.0.2
jakarta.xml.soap=[3.0,4);Export-Package=3.0.2
jakarta.xml.ws.handler.soap=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws.handler=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws.http=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws.soap=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws.spi.http=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws.spi=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws.wsaddressing=[3.0,4);Export-Package=3.0.1
jakarta.xml.ws=[3.0,4);Export-Package=3.0.1