/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

/** AUTO-GENERATED: DO NOT EDIT
 *
 * This is generated based on each module's `node-scripts.config.js`
 *
 */

module.exports = {
	hash: '3c6a6857aa1877f385424e720d0063b3cc106764518d4147d6dafa336f299846',
	imports: {
		'@liferay/accessibility-settings-state-web': [],
		'@liferay/address-web': [],
		'@liferay/analytics-reports-js-components-web': [],
		'@liferay/content-dashboard-web': [],
		'@liferay/cookies-banner-web': [],
		'@liferay/document-library-preview-css': [],
		'@liferay/document-library-web': [],
		'@liferay/flags-taglib': [],
		'@liferay/fragment-renderer-collection-filter-impl': [],
		'@liferay/frontend-data-set-web': [],
		'@liferay/frontend-icons-web': [],
		'@liferay/frontend-js-codemirror-web': [
			'codemirror/addon/fold/foldgutter.css',
			'codemirror/addon/hint/show-hint.css',
			'codemirror/lib/codemirror.css',
		],
		'@liferay/frontend-js-dependencies-web': [
			'html-to-image',
			'jspdf',
			'@liferay/js-api',
			'@liferay/js-api/data-set',
			'cropperjs/dist/cropper.css',
			'graphql-hooks-memcache',
			'graphql-hooks',
			'graphql',
			'highlight.js/styles/monokai-sublime.css',
			'qrcode',
			'react-dropzone',
			'react-transition-group',
			'uuid',
			'react-flow-renderer',
			'react-helmet',
			'react-router-dom',
			'graphiql',
			'graphiql/graphiql.css',
			'axe-core',
			'clipboard',
			'cropperjs',
			'dagre',
			'dom-align',
			'fuzzy',
			'highlight.js',
			'highlight.js/lib/core',
			'highlight.js/lib/languages/java',
			'highlight.js/lib/languages/javascript',
			'highlight.js/lib/languages/plaintext',
			'image-promise',
			'liferay-ckeditor',
			'lodash.groupby',
			'lodash.isequal',
			'moment',
			'moment/min/moment-with-locales',
			'numeral',
			'object-hash',
			'pkce-challenge',
			'qs',
			'react-text-mask',
			'text-mask-addons',
			'text-mask-core',
		],
		'@liferay/frontend-js-react-web': [
			'classnames',
			'formik',
			'prop-types',
			'react',
			'react-16',
			'react-18',
			'react-dnd-html5-backend',
			'react-dnd',
			'react-dom',
			'react-dom/client',
			'react-dom-16',
			'react-dom-18',
			'react-dom-18/client',
		],
		'@liferay/frontend-js-state-web': [],
		'@liferay/frontend-js-walkthrough-web': [],
		'@liferay/layout-js-components-web': [],
		'@liferay/map-common': [],
		'@liferay/map-google-maps': [],
		'@liferay/map-openstreetmap': [],
		'@liferay/marketplace-js-components-web': [],
		'@liferay/oauth2-provider-web': ['./client', './global'],
		'@liferay/object-js-components-web': [],
		'@liferay/portal-workflow-instance-tracker-web': [],
		'@liferay/template-web': [],
		'asset-taglib': [],
		'commerce-frontend-js': [],
		'data-engine-js-components-web': [],
		'data-engine-taglib': [],
		'dynamic-data-mapping-form-field-type': ['leaflet/dist/leaflet.css'],
		'frontend-editor-ckeditor-web': [
			'@ckeditor/ckeditor5-react',
			'ckeditor5',
			'ckeditor5/ckeditor5.css',
		],
		'frontend-js-components-web': [],
		'frontend-js-recharts': ['recharts'],
		'frontend-js-web': [],
		'frontend-taglib-clay': [
			'@clayui/alert',
			'@clayui/autocomplete',
			'@clayui/badge',
			'@clayui/breadcrumb',
			'@clayui/button',
			'@clayui/card',
			'@clayui/charts',
			'@clayui/color-picker',
			'@clayui/core',
			'@clayui/css/lib/css/atlas.css',
			'@clayui/css/lib/css/base.css',
			'@clayui/css/lib/css/cadmin.css',
			'@clayui/data-provider',
			'@clayui/date-picker',
			'@clayui/drop-down',
			'@clayui/empty-state',
			'@clayui/form',
			'@clayui/icon',
			'@clayui/label',
			'@clayui/layout',
			'@clayui/link',
			'@clayui/list',
			'@clayui/loading-indicator',
			'@clayui/localized-input',
			'@clayui/management-toolbar',
			'@clayui/modal',
			'@clayui/multi-select',
			'@clayui/multi-step-nav',
			'@clayui/nav',
			'@clayui/navigation-bar',
			'@clayui/pagination',
			'@clayui/pagination-bar',
			'@clayui/panel',
			'@clayui/popover',
			'@clayui/progress-bar',
			'@clayui/provider',
			'@clayui/shared',
			'@clayui/slider',
			'@clayui/sticker',
			'@clayui/table',
			'@clayui/tabs',
			'@clayui/time-picker',
			'@clayui/toolbar',
			'@clayui/tooltip',
			'@clayui/upper-toolbar',
		],
		'item-selector-taglib': [],
		'item-selector-web': [],
		'portal-search-web': ['./search-bar'],
		'social-bookmarks-taglib': [],
	},

	// The following symbols override the actual symbols that listed packages export. This is
	// sometimes necessary when:
	//
	// 1. The build cannot infer the exported symbols because the package cannot be required from
	//    Node.js (eg: if it references `window` or any other browser API not available).
	// 2. The inferred exported symbols are wrong (eg: polymorphic packages).
	// 3. The package must re-export everything as `default` so that it can be directly imported
	//    using ES syntax (eg: `react` since it can be imported as `import React from 'react';` even
	//    though it is a CJS package that doesn't really export any `default` symbol).
	//
	// For number 3 note that tools like `webpack` sometimes rely on the `__esModule` symbol to
	// mimic that behavior. However we prefer to make it explicit in this file due to how much
	// headaches the `__esModule` inferences usually cause when they don't work correctly.
	//
	// The way to obtain these symbols is different for each package but it usually starts with a
	// runtime error in the browser and a following investigation on what the package is really
	// exporting when used from a browser.
	//

	symbols: {
		'@clayui/charts': ['bb', 'default'],
		'axe-core': ['*', 'default'],
		'ckeditor5': [
			'Alignment',
			'BlockQuote',
			'Bold',
			'ClassicEditor',
			'EditorConfig',
			'Essentials',
			'Font',
			'GeneralHtmlSupport',
			'Heading',
			'HorizontalLine',
			'Indent',
			'IndentBlock',
			'Italic',
			'Link',
			'List',
			'MediaEmbed',
			'Paragraph',
			'RemoveFormat',
			'SourceEditing',
			'Strikethrough',
			'Style',
			'Table',
			'TableCaption',
			'TableProperties',
			'TableToolbar',
			'Underline',
		],
		'clipboard': ['*', 'default'],
		'cropperjs': ['*', 'default'],
		'dagre': ['*', 'default'],
		'fuzzy': ['*', 'default'],
		'graphql-hooks-memcache': ['*', 'default'],
		'highlight.js': ['*', 'default'],
		'highlight.js/lib/core': ['*', 'default'],
		'highlight.js/lib/languages/java': ['*', 'default'],
		'highlight.js/lib/languages/javascript': ['*', 'default'],
		'highlight.js/lib/languages/plaintext': ['*', 'default'],
		'image-promise': ['*', 'default'],
		'liferay-ckeditor': [],
		'lodash.groupby': ['*', 'default'],
		'lodash.isequal': ['*', 'default'],
		'moment': ['*', 'default'],
		'moment/min/moment-with-locales': ['*', 'default'],
		'numeral': ['*', 'default'],
		'object-hash': ['*', 'default'],
		'prop-types': ['*', 'default'],
		'qrcode': ['create', 'toCanvas', 'toString', 'toDataURL'],
		'qs': ['*', 'default'],
		'react': ['*', 'default'],
		'react-dnd': ['*', 'default'],
		'react-dom': ['*', 'default'],
		'text-mask-addons': ['*', 'default'],
		'text-mask-core': ['*', 'default'],
	},
};
