#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.bulk.rest.dto.v1_0.BulkAction
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Bulk.REST)
osgi.jaxrs.resource=true