/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export const ADD_REDO_ACTION = 'ADD_REDO_ACTION';
export const ADD_UNDO_ACTION = 'ADD_UNDO_ACTION';
export const LOADING = 'LOADING';
export const SET_CUSTOM_FRONTEND_TOKEN_DEFINITION =
	'SET_CUSTOM_FRONTEND_TOKEN_DEFINITION';
export const SET_DRAFT_STATUS = 'SET_DRAFT_STATUS';
export const SET_PREVIEW_LAYOUT = 'SET_PREVIEW_LAYOUT';
export const SET_PREVIEW_LAYOUT_TYPE = 'SET_PREVIEW_LAYOUT_TYPE';
export const SET_TOKEN_VALUES = 'SET_TOKEN_VALUES';
export const UPDATE_UNDO_REDO_HISTORY = 'UPDATE_UNDO_REDO_HISTORY';
