apiDir: ../headless-admin-user-api/src/main/java
apiPackagePath: com.liferay.headless.admin.user
application:
    baseURI: /headless-admin-user
    className: HeadlessAdminUserApplication
    name: Liferay.Headless.Admin.User
author: Javier Gamarra
clientDir: ../headless-admin-user-client/src/main/java
compatibilityVersion: 13
javaEEPackage: jakarta
testDir: ../headless-admin-user-test/src/testIntegration/java