apiDir: ../headless-portal-instances-api/src/main/java
apiPackagePath: com.liferay.headless.portal.instances
application:
    baseURI: /headless-portal-instances
    className: HeadlessPortalInstancesApplication
    name: Liferay.Headless.Portal.Instances
author: Alberto Chaparro
clientDir: ../headless-portal-instances-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateBatch: false
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../headless-portal-instances-test/src/testIntegration/java