modified.files.includes[relevant][batch-engine-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[batch-engine-java-rule][relevant][modules-integration-db-partition-postgresql163]=\
    apps/batch-engine/**/BatchEngineUnitProcessorImplDBPartitionTest.java

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][batch-engine-java-rule]=\
    apps/batch-engine/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][batch-engine-java-rule]=\
    apps/batch-engine/**/*Test.java

relevant.rule.names=batch-engine-java-rule

test.batch.names[relevant][batch-engine-java-rule]=\
    modules-integration-db-partition-postgresql163,\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Headless Batch Engine API