resource "kubernetes_manifest" "root_application" {
	field_manager {
		force_conflicts=true
		name=local.terraform_manager_name
	}
	manifest={
		apiVersion="argoproj.io/v1alpha1"
		kind="Application"
		metadata={
			finalizers=["resources-finalizer.argocd.argoproj.io"]
			labels=merge(
				local.common_labels,
				{
					"app.kubernetes.io/name"="liferay-platform"
				})
			name="liferay-platform"
			namespace=local.argocd_namespace
		}
		spec={
			destination={
				namespace=local.argocd_namespace
				server="https://kubernetes.default.svc"
			}
			project="default"
			sources=[
				merge(
					{
						helm={
							valuesObject=local.platform_helm_values
						}
					},
					local.chart_sources.platform
				),
			]
			syncPolicy={
				automated={
					prune=true
					selfHeal=true
				}
				retry={
					backoff={
						duration="30s"
						factor=2
						maxDuration="10m"
					}
					limit=10
				}
				syncOptions=["CreateNamespace=true"]
			}
		}
	}
}