include-and-override=portal-env.properties
upgrade.database.auto.run=true
enterprise.product.notification.enabled=false
javascript.single.page.application.enabled=false
company.security.strangers=false
company.security.strangers.verify=false
company.security.update.password.required=false
users.reminder.queries.enabled=false
terms.of.use.required=false

locales.enabled=\
    ar_SA,\
    ca_ES,\
    de_DE,\
    en_US,\
    es_AR,\
    es_ES,\
    fi_FI,\
    fr_FR,\
    hu_HU,\
    ja_JP,\
    nl_NL,\
    pt_BR,\
    pt_PT,\
    sv_SE,\
    zh_CN

session.timeout=600
passwords.default.policy.change.required=false
index.on.startup=true
index.on.startup.delay=60
feature.flag.LPS-164563=true
feature.flag.LPS-177027=true
feature.flag.LPS-178052=true
virtual.hosts.valid.hosts=*
admin.email.user.added.enabled=false

feature.flag.LPS-172903=true