modified.files.includes[relevant][bulk-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][bulk-java-rule]=\
    apps/bulk/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][bulk-java-rule]=\
    apps/bulk/**/*Test.java

relevant.rule.names=bulk-java-rule

test.batch.names[relevant][bulk-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Documents and Media