modified.files.includes[relevant][layout-set-prototype-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][layout-set-prototype-web-playwright-rule]=\
    layout-set-prototype-web.main

relevant.rule.names=layout-set-prototype-web-playwright-rule

test.batch.names[relevant][layout-set-prototype-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163