modified.files.includes[relevant][portal-tools-db-support-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-tools-db-support-java-rule]=\
    util/portal-tools-db-support/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-tools-db-support-java-rule]=\
    util/portal-tools-db-support/**/*Test.java

relevant.rule.names=portal-tools-db-support-java-rule

test.batch.names[relevant][portal-tools-db-support-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Dev Tools