modified.files.includes[relevant][bean-portlet-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][bean-portlet-java-rule]=\
    apps/bean-portlet/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][bean-portlet-java-rule]=\
    apps/bean-portlet/**/*Test.java

relevant.rule.names=bean-portlet-java-rule

test.batch.names[relevant][bean-portlet-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Bean Portlet