modified.files.includes[relevant][data-cleanup-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][data-cleanup-java-rule]=\
    apps/data-cleanup/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][data-cleanup-java-rule]=\
    apps/data-cleanup/**/*Test.java

relevant.rule.names=data-cleanup-java-rule

test.batch.names[relevant][data-cleanup-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Data Cleanup