modified.files.includes[relevant][salesforce-connector-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][salesforce-connector-java-rule]=\
    dxp/apps/salesforce-connector/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][salesforce-connector-java-rule]=\
    dxp/apps/salesforce-connector/**/*Test.java

relevant.rule.names=salesforce-connector-java-rule

test.batch.names[relevant][salesforce-connector-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Commerce