dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly project(":apps:portal-security:portal-security-fips-api")
	compileOnly project(":apps:portal:portal-instance-lifecycle-api")
	compileOnly project(":core:petra:petra-string")
}