modified.files.includes[relevant][rss-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][rss-web-playwright-rule]=\
    rss-web.main

relevant.rule.names=rss-web-playwright-rule

test.batch.names[relevant][rss-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=RSS Publisher Widget