modified.files.includes[relevant][websocket-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][websocket-java-rule]=\
    apps/websocket/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][websocket-java-rule]=\
    apps/websocket/**/*Test.java

relevant.rule.names=websocket-java-rule

test.batch.names[relevant][websocket-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services