/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.sso.openid.connect.persistence.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the OpenIdConnectUser service. Represents a row in the &quot;OpenIdConnectUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.sso.openid.connect.persistence.model.impl.OpenIdConnectUserModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.sso.openid.connect.persistence.model.impl.OpenIdConnectUserImpl</code>.
 * </p>
 *
 * @author Arthur Chan
 * @see OpenIdConnectUser
 * @generated
 */
@ProviderType
public interface OpenIdConnectUserModel
	extends BaseModel<OpenIdConnectUser>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a open ID connect user model instance should use the {@link OpenIdConnectUser} interface instead.
	 */

	/**
	 * Returns the primary key of this open ID connect user.
	 *
	 * @return the primary key of this open ID connect user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this open ID connect user.
	 *
	 * @param primaryKey the primary key of this open ID connect user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this open ID connect user.
	 *
	 * @return the mvcc version of this open ID connect user
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this open ID connect user.
	 *
	 * @param mvccVersion the mvcc version of this open ID connect user
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the open ID connect user ID of this open ID connect user.
	 *
	 * @return the open ID connect user ID of this open ID connect user
	 */
	public long getOpenIdConnectUserId();

	/**
	 * Sets the open ID connect user ID of this open ID connect user.
	 *
	 * @param openIdConnectUserId the open ID connect user ID of this open ID connect user
	 */
	public void setOpenIdConnectUserId(long openIdConnectUserId);

	/**
	 * Returns the open ID connect user uuid of this open ID connect user.
	 *
	 * @return the open ID connect user uuid of this open ID connect user
	 */
	public String getOpenIdConnectUserUuid();

	/**
	 * Sets the open ID connect user uuid of this open ID connect user.
	 *
	 * @param openIdConnectUserUuid the open ID connect user uuid of this open ID connect user
	 */
	public void setOpenIdConnectUserUuid(String openIdConnectUserUuid);

	/**
	 * Returns the company ID of this open ID connect user.
	 *
	 * @return the company ID of this open ID connect user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this open ID connect user.
	 *
	 * @param companyId the company ID of this open ID connect user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this open ID connect user.
	 *
	 * @return the user ID of this open ID connect user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this open ID connect user.
	 *
	 * @param userId the user ID of this open ID connect user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this open ID connect user.
	 *
	 * @return the user uuid of this open ID connect user
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this open ID connect user.
	 *
	 * @param userUuid the user uuid of this open ID connect user
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this open ID connect user.
	 *
	 * @return the create date of this open ID connect user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this open ID connect user.
	 *
	 * @param createDate the create date of this open ID connect user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the issuer of this open ID connect user.
	 *
	 * @return the issuer of this open ID connect user
	 */
	@AutoEscape
	public String getIssuer();

	/**
	 * Sets the issuer of this open ID connect user.
	 *
	 * @param issuer the issuer of this open ID connect user
	 */
	public void setIssuer(String issuer);

	/**
	 * Returns the subject of this open ID connect user.
	 *
	 * @return the subject of this open ID connect user
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this open ID connect user.
	 *
	 * @param subject the subject of this open ID connect user
	 */
	public void setSubject(String subject);

	@Override
	public OpenIdConnectUser cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}