#
# Application
#

liferay.testray.max.days.archived=30
liferay.testray.max.days.opened=60

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay-testray-etc-cron-oahs.oauth2.headless.server.client.secret=myfancypassword
liferay.oauth.application.external.reference.codes=liferay-testray-etc-cron-oahs