/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.faro.contacts.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.faro.contacts.model.ContactsCardTemplate;
import com.liferay.osb.faro.contacts.model.ContactsCardTemplateModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ContactsCardTemplate service. Represents a row in the &quot;OSBFaro_ContactsCardTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContactsCardTemplateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactsCardTemplateImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see ContactsCardTemplateImpl
 * @generated
 */
public class ContactsCardTemplateModelImpl
	extends BaseModelImpl<ContactsCardTemplate>
	implements ContactsCardTemplateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contacts card template model instance should use the <code>ContactsCardTemplate</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBFaro_ContactsCardTemplate";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"contactsCardTemplateId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createTime", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"modifiedTime", Types.BIGINT},
		{"name", Types.VARCHAR}, {"settings_", Types.VARCHAR},
		{"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactsCardTemplateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedTime", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("settings_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBFaro_ContactsCardTemplate (mvccVersion LONG default 0 not null,contactsCardTemplateId LONG not null primary key,groupId LONG,companyId LONG,createTime LONG,userId LONG,userName VARCHAR(75) null,modifiedTime LONG,name VARCHAR(75) null,settings_ STRING null,type_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBFaro_ContactsCardTemplate";

	public static final String ENTITY_ALIAS = "contactsCardTemplate";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contactsCardTemplate.contactsCardTemplateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBFaro_ContactsCardTemplate.contactsCardTemplateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTACTSCARDTEMPLATEID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ContactsCardTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _contactsCardTemplateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setContactsCardTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _contactsCardTemplateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ContactsCardTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return ContactsCardTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ContactsCardTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ContactsCardTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactsCardTemplate, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ContactsCardTemplate)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ContactsCardTemplate, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ContactsCardTemplate, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ContactsCardTemplate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ContactsCardTemplate, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ContactsCardTemplate, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ContactsCardTemplate, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ContactsCardTemplate, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ContactsCardTemplate, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", ContactsCardTemplate::getMvccVersion);
			attributeGetterFunctions.put(
				"contactsCardTemplateId",
				ContactsCardTemplate::getContactsCardTemplateId);
			attributeGetterFunctions.put(
				"groupId", ContactsCardTemplate::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ContactsCardTemplate::getCompanyId);
			attributeGetterFunctions.put(
				"createTime", ContactsCardTemplate::getCreateTime);
			attributeGetterFunctions.put(
				"userId", ContactsCardTemplate::getUserId);
			attributeGetterFunctions.put(
				"userName", ContactsCardTemplate::getUserName);
			attributeGetterFunctions.put(
				"modifiedTime", ContactsCardTemplate::getModifiedTime);
			attributeGetterFunctions.put("name", ContactsCardTemplate::getName);
			attributeGetterFunctions.put(
				"settings", ContactsCardTemplate::getSettings);
			attributeGetterFunctions.put("type", ContactsCardTemplate::getType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ContactsCardTemplate, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ContactsCardTemplate, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ContactsCardTemplate, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setMvccVersion);
			attributeSetterBiConsumers.put(
				"contactsCardTemplateId",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setContactsCardTemplateId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setCompanyId);
			attributeSetterBiConsumers.put(
				"createTime",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setCreateTime);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ContactsCardTemplate, String>)
					ContactsCardTemplate::setUserName);
			attributeSetterBiConsumers.put(
				"modifiedTime",
				(BiConsumer<ContactsCardTemplate, Long>)
					ContactsCardTemplate::setModifiedTime);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<ContactsCardTemplate, String>)
					ContactsCardTemplate::setName);
			attributeSetterBiConsumers.put(
				"settings",
				(BiConsumer<ContactsCardTemplate, String>)
					ContactsCardTemplate::setSettings);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<ContactsCardTemplate, Integer>)
					ContactsCardTemplate::setType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getContactsCardTemplateId() {
		return _contactsCardTemplateId;
	}

	@Override
	public void setContactsCardTemplateId(long contactsCardTemplateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactsCardTemplateId = contactsCardTemplateId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getCreateTime() {
		return _createTime;
	}

	@Override
	public void setCreateTime(long createTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createTime = createTime;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public long getModifiedTime() {
		return _modifiedTime;
	}

	@Override
	public void setModifiedTime(long modifiedTime) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedTime = modifiedTime;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getSettings() {
		if (_settings == null) {
			return "";
		}
		else {
			return _settings;
		}
	}

	@Override
	public void setSettings(String settings) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_settings = settings;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ContactsCardTemplate.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ContactsCardTemplate toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ContactsCardTemplate>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContactsCardTemplateImpl contactsCardTemplateImpl =
			new ContactsCardTemplateImpl();

		contactsCardTemplateImpl.setMvccVersion(getMvccVersion());
		contactsCardTemplateImpl.setContactsCardTemplateId(
			getContactsCardTemplateId());
		contactsCardTemplateImpl.setGroupId(getGroupId());
		contactsCardTemplateImpl.setCompanyId(getCompanyId());
		contactsCardTemplateImpl.setCreateTime(getCreateTime());
		contactsCardTemplateImpl.setUserId(getUserId());
		contactsCardTemplateImpl.setUserName(getUserName());
		contactsCardTemplateImpl.setModifiedTime(getModifiedTime());
		contactsCardTemplateImpl.setName(getName());
		contactsCardTemplateImpl.setSettings(getSettings());
		contactsCardTemplateImpl.setType(getType());

		contactsCardTemplateImpl.resetOriginalValues();

		return contactsCardTemplateImpl;
	}

	@Override
	public ContactsCardTemplate cloneWithOriginalValues() {
		ContactsCardTemplateImpl contactsCardTemplateImpl =
			new ContactsCardTemplateImpl();

		contactsCardTemplateImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		contactsCardTemplateImpl.setContactsCardTemplateId(
			this.<Long>getColumnOriginalValue("contactsCardTemplateId"));
		contactsCardTemplateImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		contactsCardTemplateImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		contactsCardTemplateImpl.setCreateTime(
			this.<Long>getColumnOriginalValue("createTime"));
		contactsCardTemplateImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		contactsCardTemplateImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		contactsCardTemplateImpl.setModifiedTime(
			this.<Long>getColumnOriginalValue("modifiedTime"));
		contactsCardTemplateImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		contactsCardTemplateImpl.setSettings(
			this.<String>getColumnOriginalValue("settings_"));
		contactsCardTemplateImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));

		return contactsCardTemplateImpl;
	}

	@Override
	public int compareTo(ContactsCardTemplate contactsCardTemplate) {
		long primaryKey = contactsCardTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ContactsCardTemplate)) {
			return false;
		}

		ContactsCardTemplate contactsCardTemplate =
			(ContactsCardTemplate)object;

		long primaryKey = contactsCardTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ContactsCardTemplate> toCacheModel() {
		ContactsCardTemplateCacheModel contactsCardTemplateCacheModel =
			new ContactsCardTemplateCacheModel();

		contactsCardTemplateCacheModel.mvccVersion = getMvccVersion();

		contactsCardTemplateCacheModel.contactsCardTemplateId =
			getContactsCardTemplateId();

		contactsCardTemplateCacheModel.groupId = getGroupId();

		contactsCardTemplateCacheModel.companyId = getCompanyId();

		contactsCardTemplateCacheModel.createTime = getCreateTime();

		contactsCardTemplateCacheModel.userId = getUserId();

		contactsCardTemplateCacheModel.userName = getUserName();

		String userName = contactsCardTemplateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			contactsCardTemplateCacheModel.userName = null;
		}

		contactsCardTemplateCacheModel.modifiedTime = getModifiedTime();

		contactsCardTemplateCacheModel.name = getName();

		String name = contactsCardTemplateCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			contactsCardTemplateCacheModel.name = null;
		}

		contactsCardTemplateCacheModel.settings = getSettings();

		String settings = contactsCardTemplateCacheModel.settings;

		if ((settings != null) && (settings.length() == 0)) {
			contactsCardTemplateCacheModel.settings = null;
		}

		contactsCardTemplateCacheModel.type = getType();

		return contactsCardTemplateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ContactsCardTemplate, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ContactsCardTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContactsCardTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ContactsCardTemplate)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ContactsCardTemplate>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ContactsCardTemplate.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _contactsCardTemplateId;
	private long _groupId;
	private long _companyId;
	private long _createTime;
	private long _userId;
	private String _userName;
	private long _modifiedTime;
	private String _name;
	private String _settings;
	private int _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ContactsCardTemplate, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ContactsCardTemplate)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"contactsCardTemplateId", _contactsCardTemplateId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createTime", _createTime);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("modifiedTime", _modifiedTime);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("settings_", _settings);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("settings_", "settings");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("contactsCardTemplateId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createTime", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("modifiedTime", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("settings_", 512L);

		columnBitmasks.put("type_", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ContactsCardTemplate _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-930379370