modified.files.includes[relevant][roles-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][roles-java-rule]=\
    apps/roles/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][roles-java-rule]=\
    apps/roles/**/*Test.java

relevant.rule.names=roles-java-rule

test.batch.names[relevant][roles-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Roles