resource "kubernetes_manifest" "function_auto_ready" {
	manifest={
		apiVersion="pkg.crossplane.io/v1beta1"
		kind="Function"
		metadata={
			name="function-auto-ready"
		}
		spec={
			package="xpkg.upbound.io/upbound/function-auto-ready:v0.6.0"
			runtimeConfigRef={
				name="function-auto-ready-runtime-config"
			}
		}
	}
	provider=kubernetes
}
resource "kubernetes_manifest" "function_auto_ready_runtime_config" {
	manifest={
		apiVersion="pkg.crossplane.io/v1beta1"
		kind="DeploymentRuntimeConfig"
		metadata={
			name="function-auto-ready-runtime-config"
		}
		spec={
			deploymentTemplate={
				metadata={
					annotations=local.deploymentruntimeconfig_opentelemetry_annotations
				}
				spec={
					selector={
						matchLabels={
							"pkg.crossplane.io/function"="function-auto-ready"
						}
					}
					template={
						metadata={
							annotations=local.deploymentruntimeconfig_opentelemetry_annotations
						}
						spec={
							containers=[
								{
									name="package-runtime"
									resources={
										limits={
											memory="256Mi"
										}
										requests={
											cpu="15m"
											memory="128Mi"
										}
									}
									securityContext=local.default_crossplane_container_security_context
								},
							],
							securityContext=local.default_crossplane_pod_security_context
						}
					}
				}
			}
		}
	}
	provider=kubernetes
}
resource "kubernetes_manifest" "function_environment_configs" {
	manifest={
		apiVersion="pkg.crossplane.io/v1beta1"
		kind="Function"
		metadata={
			name="function-environment-configs"
		}
		spec={
			package="xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.6.0"
			runtimeConfigRef={
				name="function-environment-configs-runtime-config"
			}
		}
	}
	provider=kubernetes
}
resource "kubernetes_manifest" "function_environment_configs_runtime_config" {
	manifest={
		apiVersion="pkg.crossplane.io/v1beta1"
		kind="DeploymentRuntimeConfig"
		metadata={
			name="function-environment-configs-runtime-config"
		}
		spec={
			deploymentTemplate={
				metadata={
					annotations=local.deploymentruntimeconfig_opentelemetry_annotations
				}
				spec={
					selector={
						matchLabels={
							"pkg.crossplane.io/function"="function-environment-configs"
						}
					}
					template={
						metadata={
							annotations=local.deploymentruntimeconfig_opentelemetry_annotations
						}
						spec={
							containers=[
								{
									name="package-runtime"
									resources={
										limits={
											memory="256Mi"
										}
										requests={
											cpu="15m"
											memory="128Mi"
										}
									}
									securityContext=local.default_crossplane_container_security_context
								},
							]
							securityContext=local.default_crossplane_pod_security_context
						}
					}
				}
			}
		}
	}
	provider=kubernetes
}
resource "kubernetes_manifest" "function_go_templating" {
	manifest={
		apiVersion="pkg.crossplane.io/v1beta1"
		kind="Function"
		metadata={
			name="function-go-templating"
		}
		spec={
			package="xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.11.3"
			runtimeConfigRef={
				name="function-go-templating-runtime-config"
			}
		}
	}
	provider=kubernetes
}
resource "kubernetes_manifest" "function_go_templating_runtime_config" {
	manifest={
		apiVersion="pkg.crossplane.io/v1beta1"
		kind="DeploymentRuntimeConfig"
		metadata={
			name="function-go-templating-runtime-config"
		}
		spec={
			deploymentTemplate={
				metadata={
					annotations=local.deploymentruntimeconfig_opentelemetry_annotations
				}
				spec={
					selector={
						matchLabels={
							"pkg.crossplane.io/function"="function-go-templating"
						}
					}
					template={
						metadata={
							annotations=local.deploymentruntimeconfig_opentelemetry_annotations
						}
						spec={
							containers=[
								{
									name="package-runtime"
									resources={
										limits={
											memory="512Mi"
										}
										requests={
											cpu="15m"
											memory="128Mi"
										}
									}
									securityContext=local.default_crossplane_container_security_context
								},
							],
							securityContext=local.default_crossplane_pod_security_context
						}
					}
				}
			}
		}
	}
	provider=kubernetes
}
