modified.files.includes[relevant][scim-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][scim-java-rule]=\
    dxp/apps/scim/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][scim-java-rule]=\
    dxp/apps/scim/**/*Test.java

relevant.rule.names=scim-java-rule

test.batch.names[relevant][scim-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=SCIM