##
## Test Suites
##

    modified.files.includes[relevant][portal-security-java-rule]=\
        **/*.java,\
        **/*.xml,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=portal-security-java-rule

    test.batch.names[relevant][portal-security-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-security-java-rule]=\
        apps/password-policy/**/*Test.java,\
        apps/portal-security/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-security-java-rule]=\
        apps/portal-security/**/*Test.java

##
## Testray
##

    testray.main.component.name=Security