test.base.dir.name=test/functional/com/liferay/portalweb/

test.dirs=\
    ../modules/apps/accessibility/accessibility-test/src/testFunctional,\
    ../modules/apps/account/account-test/src/testFunctional,\
    ../modules/apps/address/address-test/src/testFunctional,\
    ../modules/apps/asset/asset-auto-tagger-google-cloud-natural-language-test/src/testFunctional,\
    ../modules/apps/asset/asset-auto-tagger-test/src/testFunctional,\
    ../modules/apps/batch-engine/batch-engine-test/src/testFunctional,\
    ../modules/apps/batch-planner/batch-planner-test/src/testFunctional,\
    ../modules/apps/bulk/bulk-selection-test/src/testFunctional,\
    ../modules/apps/calendar/calendar-web-test/src/testFunctional,\
    ../modules/apps/click-to-chat/click-to-chat-test/src/testFunctional,\
    ../modules/apps/commerce/commerce-product-test/src/testFunctional,\
    ../modules/apps/configuration-admin/configuration-admin-test/src/testFunctional,\
    ../modules/apps/data-engine/data-engine-test/src/testFunctional,\
    ../modules/apps/depot/depot-test/src/testFunctional,\
    ../modules/apps/digital-signature/digital-signature-test/src/testFunctional,\
    ../modules/apps/dispatch/dispatch-test/src/testFunctional,\
    ../modules/apps/document-library-opener/document-library-opener-google-drive-test/src/testFunctional,\
    ../modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/testFunctional,\
    ../modules/apps/feature-flag/feature-flag-test/src/testFunctional/,\
    ../modules/apps/frontend-css/frontend-css-test/src/testFunctional,\
    ../modules/apps/frontend-js/frontend-js-test/src/testFunctional,\
    ../modules/apps/headless/headless-admin-taxonomy/headless-admin-taxonomy-test/src/testFunctional,\
    ../modules/apps/headless/headless-batch-engine/headless-batch-engine-test/src/testFunctional,\
    ../modules/apps/headless/headless-builder/headless-builder-test/src/testFunctional,\
    ../modules/apps/headless/headless-delivery/headless-delivery-test/src/testFunctional,\
    ../modules/apps/headless/headless-discovery/headless-discovery-test/src/testFunctional,\
    ../modules/apps/headless/headless-user-notification/headless-user-notification-test/src/testFunctional,\
    ../modules/apps/item-selector/item-selector-test/src/testFunctional,\
    ../modules/apps/layout/layout-seo-web-test/src/testFunctional,\
    ../modules/apps/mail/mail-outlook-auth-connector-provider/src/testFunctional,\
    ../modules/apps/object/object-rest-test/src/testFunctional,\
    ../modules/apps/object/object-test/src/testFunctional,\
    ../modules/apps/on-demand-admin/on-demand-admin-test/src/testFunctional,\
    ../modules/apps/portal/portal-upgrade-test/src/testFunctional,\
    ../modules/apps/portal-language/portal-language-override-test/src/testFunctional,\
    ../modules/apps/portal-workflow/portal-workflow-test/src/testFunctional,\
    ../modules/apps/ratings/ratings-test/src/testFunctional,\
    ../modules/apps/redirect/redirect-test/src/testFunctional,\
    ../modules/apps/site-initializer/site-initializer-liferay-marketplace/site-initializer-liferay-marketplace-test/src/testFunctional,\
    ../modules/apps/translation/translation-test/src/testFunctional,\
    ../modules/dxp/apps/antivirus/antivirus-clamd-scanner-test/testFunctional,\
    ../modules/dxp/apps/document-library-opener/document-library-opener-onedrive-test/src/testFunctional,\
    ../modules/dxp/apps/portal-reports-engine-console/portal-reports-engine-console-test/src/testFunctional,\
    ../modules/dxp/apps/portal-rules-engine-drools/portal-rules-engine-drools-test/src/testFunctional,\
    ../modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-test/src/testFunctional,\
    ../modules/dxp/apps/portal-workflow/portal-workflow-metrics-test/src/testFunctional,\
    ../modules/dxp/apps/portal-workflow-kaleo-forms/portal-workflow-kaleo-forms-test/src/testFunctional,\
    ../modules/util/portal-tools-db-migration-importer-test/src/testFunctional,\
    ../modules/util/portal-tools-db-partition-migration-validator-test/src/testFunctional,\
    ../modules/util/portal-tools-db-upgrade-client/src/testFunctional