modified.files.includes[relevant][social-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][social-java-rule]=\
    apps/social/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][social-java-rule]=\
    apps/social/**/*Test.java

relevant.rule.names=social-java-rule

test.batch.names[relevant][social-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Social Bookmarks