modified.files.includes[relevant][asset-entry-rel-service-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][asset-entry-rel-service-java-rule]=\
    **/asset-entry-rel-test/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-entry-rel-service-java-rule]=\
    **/asset-entry-rel-test/**/*Test.java

relevant.rule.names=asset-entry-rel-service-java-rule

test.batch.names[relevant][asset-entry-rel-service-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit