components:
    schemas:
        Chat:
            properties:
                externalReferenceCode:
                    type: string
            type: object
        Message:
            properties:
                chat:
                    $ref: "#/components/schemas/Chat"
                    readOnly: true
                context:
                    additionalProperties: true
                    type: object
                scope:
                    $ref: "#/components/schemas/Scope"
                text:
                    type: string
            type: object
        Scope:
            properties:
                externalReferenceCode:
                    type: string
            type: object
        Task:
            properties:
                context:
                    additionalProperties: true
                    type: object
                    writeOnly: true
                externalReferenceCode:
                    readOnly: true
                    type: string
                scope:
                    $ref: "#/components/schemas/Scope"
                sseEventSinkKey:
                    type: string
                type:
                    type: string
            type: object
        TaskDefinition:
            properties:
                actions:
                    additionalProperties:
                        additionalProperties:
                            type: string
                        type: object
                    readOnly: true
                    type: object
                description:
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                version:
                    type: integer
            type: object
        Token:
            properties:
                accessToken:
                    readOnly: true
                    type: string
                scope:
                    readOnly: true
                    type: string
            type: object
info:
    description:
        "A Java client JAR is available for use with the group ID 'com.liferay', artifact ID
        'com.liferay.ai.hub.rest.client', and version '1.0.5'."
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: ""
    version: v1.0
openapi: 3.0.1
paths:
    "/chats/by-external-reference-code/{externalReferenceCode}/messages":
        post:
            operationId: postChatByExternalReferenceCodeMessage
            parameters:
                -   in: path
                    name: externalReferenceCode
                    required: true
                    schema:
                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Message"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Message"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Message"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Message"
            tags: ["Message"]
    "/chats/subscribe":
        get:
            operationId: getChatSubscribe
            parameters:
                -   in: context
                    name: sseEventSink
                    schema:
                        type: sseEventSink
            responses:
                200:
                    content:
                        text/event-stream: {}
            tags: ["Chat"]
    "/task-definitions":
        get:
            operationId: getTaskDefinitionsPage
            parameters:
                -   in: query
                    name: filter
                    schema:
                        type: string
                -   in: query
                    name: page
                    schema:
                        type: integer
                -   in: query
                    name: pageSize
                    schema:
                        type: integer
                -   in: query
                    name: search
                    schema:
                        type: string
                -   in: query
                    name: sort
                    schema:
                        type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/TaskDefinition"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/TaskDefinition"
                                type: array
            tags: ["TaskDefinition"]
    "/task-definitions/{taskDefinitionId}":
        delete:
            operationId: deleteTaskDefinition
            parameters:
                -   in: path
                    name: taskDefinitionId
                    required: true
                    schema:
                        format: int64
                        type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
            tags: ["TaskDefinition"]
    "/tasks":
        post:
            operationId: postTask
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Task"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Task"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Task"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Task"
            tags: ["Task"]
    "/tasks/subscribe":
        get:
            operationId: getTaskSubscribe
            parameters:
                -   in: context
                    name: sseEventSink
                    schema:
                        type: sseEventSink
            responses:
                200:
                    content:
                        text/event-stream: {}
            tags: ["Task"]
    "/tokens":
        post:
            operationId: postToken
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Token"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Token"
            tags: ["Token"]