backup:
    enabled: false
    rules:
        -   retentionDays: 30
            ruleName: daily-backups
            schedule: cron(0 5 * * ? *)
            startWindow: 60
cmk:
    enabled: false
database:
    autoMinorVersionUpgrade: true
    databaseInsightsMode: standard
    deletionProtection: true
    engine: postgres
    engineVersion: "16.11"
    instanceClass: db.t3.medium
    iops: 12000
    multiAz: false
    storageGB: 20
    storageThroughput: 500
    username: liferay_database_admin
enabled: true
endpoints: {}
forceDestroy: false
gateway: {}
license: {}
orphanOnDelete: false
overlayAccess:
    enabled: false
overlayBucket:
    commonTags: {}
    enabled: false
    forceDestroy: false
    orphanOnDelete: false
search:
    elasticsearch:
        annotations:
            instrumentation.opentelemetry.io/inject-dotnet: "false"
            instrumentation.opentelemetry.io/inject-java: "false"
            instrumentation.opentelemetry.io/inject-nodejs: "false"
            instrumentation.opentelemetry.io/inject-python: "false"
            sidecar.opentelemetry.io/inject: "false"
        enabled: false
        nodeCount: 1
        podSecurityContext:
            fsGroup: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
                type: RuntimeDefault
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    -   ALL
            privileged: false
            readOnlyRootFilesystem: false
        version: 8.19.11
        volumeSize: 10Gi
    opensearch:
        autoSoftwareUpdateEnabled: true
        enabled: true
        engineVersion: OpenSearch_2.15
        instanceCount: 2
        instanceType: t3.small.search
        username: liferay_search_admin
        volumeSizeGB: 20
storage: {}