dependencies {
	testIntegrationImplementation group: "com.liferay", name: "org.apache.felix.configadmin", version: "1.9.26.LIFERAY-PATCHED-2"
	testIntegrationImplementation project(":apps:portal-configuration:portal-configuration-test-util")
	testIntegrationImplementation project(":apps:static:osgi:osgi-util")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}