modified.files.includes[relevant][flags-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][flags-java-rule]=\
    apps/flags/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][flags-java-rule]=\
    apps/flags/**/*Test.java

relevant.rule.names=flags-java-rule

test.batch.names[relevant][flags-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Page > Page Flags