dependencies {
	testCompileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testCompileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testIntegrationImplementation project(":apps:depot:depot-api")
	testIntegrationImplementation project(":apps:layout:layout-page-template-api")
	testIntegrationImplementation project(":apps:object:object-api")
	testIntegrationImplementation project(":apps:site:site-cmp-site-initializer-test-util")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}