modified.files.includes[relevant][portal-store-functional-rule]=**

modified.files.includes[relevant][portal-store-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-store-java-rule]=\
    apps/change-tracking/**/change-tracking-store-test/**/*Test.java,\
    apps/portal-store/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-store-java-rule]=\
    apps/change-tracking/**/change-tracking-store-test/**/*Test.java,\
    apps/portal-store/**/*Test.java

relevant.rule.names=\
    portal-store-functional-rule,\
    portal-store-java-rule

test.batch.names[relevant][portal-store-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][portal-store-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][portal-store-functional-rule]=\
    (portal.acceptance == true) AND \
    (testray.component.names ~ "Documents and Media") AND \
    (testray.main.component.name ~ "Upgrades Collaboration")

testray.main.component.name=Document Library Stores