modified.files.includes[relevant][segments-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][segments-web-playwright-rule]=\
    segments-web.main

relevant.rule.names=segments-web-playwright-rule

test.batch.names[relevant][segments-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163