apiDir: ../search-experiences-rest-api/src/main/java
apiPackagePath: com.liferay.search.experiences.rest
application:
    baseURI: /search-experiences-rest
    className: SearchExperiencesRESTApplication
    name: Liferay.Search.Experiences.REST
author: Brian Wing Shun Chan
clientDir: ../search-experiences-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../search-experiences-rest-test/src/testIntegration/java