global:
    gcp:
        projectId: ""
liferay-default:
    annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "false"
        instrumentation.opentelemetry.io/inject-java: "false"
        instrumentation.opentelemetry.io/inject-nodejs: "false"
        instrumentation.opentelemetry.io/inject-python: "false"
        sidecar.opentelemetry.io/inject: "false"
    autoscaling:
        keda:
            prometheusServerAddress: https://monitoring.googleapis.com/v1/projects/{{ .Values.global.gcp.projectId }}/location/global/prometheus
            triggerAuthentication:
                spec:
                    podIdentity:
                        provider: gcp
        type: keda
    configmap:
        data:
            com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config: |
                authenticationEnabled=B"true"
                httpSSLEnabled=B"false"
                networkHostAddresses=["$[env:SEARCH_URL]"]
                operationMode="REMOTE"
                password="$[env:SEARCH_PASSWORD]"
                productionModeEnabled=B"true"
                username="$[env:SEARCH_USERNAME]"
            com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.config: |
                authenticationEnabled=B"true"
                httpSSLEnabled=B"false"
                networkHostAddresses=["$[env:SEARCH_URL]"]
                password="$[env:SEARCH_PASSWORD]"
                productionModeEnabled=B"true"
                username="$[env:SEARCH_USERNAME]"
            com.liferay.portal.store.gcs.configuration.GCSStoreConfiguration.config: |
                bucketName="$[env:LIFERAY_GCS_BUCKET_NAME]"
    customEnv:
        x-liferay-gcp:
            -   name: LIFERAY_DISABLE_TRIAL_LICENSE
                value: "true"
            -   name: LIFERAY_DL_PERIOD_STORE_PERIOD_IMPL
                value: com.liferay.portal.store.gcs.GCSStore
            -   name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME
                value: org.postgresql.Driver
            -   name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
                value: jdbc:postgresql://localhost:${env.DATABASE_PORT}/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
            -   name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
                value: ${env.DATABASE_USERNAME}
            -   name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_PORT_PERIOD_ENABLED
                value: "true"
            -   name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_FORWARDED_PERIOD_PROTOCOL_PERIOD_ENABLED
                value: "true"
    customEnvFrom:
        x-liferay-gcp:
            -   secretRef:
                    name: search-connection-details
            -   secretRef:
                    name: managed-service-details
    customInitContainers:
        x-cloud-sql-auth-proxy-enabled:
            -   args:
                    -   "$(DATABASE_INSTANCE_NAME)"
                    -   "--auto-iam-authn"
                    -   "--port=$(DATABASE_PORT)"
                    -   "--private-ip"
                    -   "--structured-logs"
                env:
                    -   name: CSQL_PROXY_HEALTH_CHECK
                        value: "true"
                    -   name: CSQL_PROXY_HTTP_ADDRESS
                        value: 0.0.0.0
                    -   name: CSQL_PROXY_HTTP_PORT
                        value: "9801"
                envFrom:
                    -   secretRef:
                            name: managed-service-details
                image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.1
                name: cloud-sql-proxy
                restartPolicy: Always
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    seccompProfile:
                        type: RuntimeDefault
        x-wait-for-elasticsearch:
            -   command:
                    -   sh
                    -   /liferay-init-scripts/wait-for-elasticsearch.sh
                envFrom:
                    -   secretRef:
                            name: search-connection-details
                image: busybox:1.36
                name: wait-for-elasticsearch
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 1000
                    seccompProfile:
                        type: RuntimeDefault
                volumeMounts:
                    -   mountPath: /liferay-init-scripts/wait-for-elasticsearch.sh
                        name: liferay-init-scripts-gcp
                        subPath: wait-for-elasticsearch.sh
    customLabels:
        origin: liferay-gcp
    customVolumeMounts:
        x-liferay-gcp:
            -   mountPath: /opt/liferay/osgi/configs/com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config
                name: liferay-configmap
                subPath: com.liferay.portal.search.elasticsearch7.configuration.ElasticsearchConfiguration.config
            -   mountPath: /opt/liferay/osgi/configs/com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.config
                name: liferay-configmap
                subPath: com.liferay.portal.search.elasticsearch8.configuration.ElasticsearchConfiguration.config
            -   mountPath: /opt/liferay/osgi/configs/com.liferay.portal.store.gcs.configuration.GCSStoreConfiguration.config
                name: liferay-configmap
                subPath: com.liferay.portal.store.gcs.configuration.GCSStoreConfiguration.config
    customVolumes:
        x-liferay-init-scripts-gcp:
            -   configMap:
                    defaultMode: 0755
                    name: liferay-init-scripts-gcp
                name: liferay-init-scripts-gcp
    marketplace:
        csi:
            driver: filestore.csi.storage.gke.io
            volumeAttributes:
                protocol: NFS_V3
                volume: marketplace
        size: 10Gi
    network:
        enabled: true
        hostnames: []
        timeouts:
            backendRequest: 300s
            request: 300s
    overlay:
        copy: []
        enabled: false
        type: gcs
    persistence:
        defaultStorageClassName: standard-rwo
    podSecurityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
            type: RuntimeDefault
    resources:
        limits:
            cpu: 4000m
            memory: 12Gi
        requests:
            cpu: 2000m
            memory: 4Gi
    securityContext:
        allowPrivilegeEscalation: false
        capabilities:
            drop:
                -   ALL
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
            type: RuntimeDefault 
    startupProbe:
        exec:
            command:
                -   /bin/sh
                -   -c
                -   |
                        curl -f http://localhost:9801/startup && \
                        curl -f http://localhost:8080/c/portal/robots
        failureThreshold: 90
        httpGet: null
        periodSeconds: 10
        timeoutSeconds: 5
    volumeClaimTemplates:
        -   metadata:
                name: liferay-persistent-volume
            spec:
                accessModes:
                    -   ReadWriteOnce
                resources:
                    requests:
                        storage: 10Gi