modified.files.includes[relevant][asset-link-service-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][asset-link-service-java-rule]=\
    **/asset-link-test/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-link-service-java-rule]=\
    **/asset-link-test/**/*Test.java

relevant.rule.names=asset-link-service-java-rule

test.batch.names[relevant][asset-link-service-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit