modified.files.includes[relevant][users-admin-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][users-admin-java-rule]=\
    apps/users-admin/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][users-admin-java-rule]=\
    apps/users-admin/**/*Test.java

relevant.rule.names=users-admin-java-rule

test.batch.names[relevant][users-admin-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Users and Organizations