modified.files.includes[relevant][push-notifications-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][push-notifications-java-rule]=\
    apps/push-notifications/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][push-notifications-java-rule]=\
    apps/push-notifications/**/*Test.java

relevant.rule.names=push-notifications-java-rule

test.batch.names[relevant][push-notifications-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Notifications