sourceCompatibility = "1.8"
targetCompatibility = "1.8"

dependencies {
	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.adaptive.media.api", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.adaptive.media.image.api", version: "1.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.upgrade", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.0.0"

	testCompile group: "com.liferay.portal", name: "com.liferay.util.java", version: "2.0.0"
	testCompile(group: "easyconf", name: "easyconf", version: "0.9.5") {
		exclude group: "log4j", module: "log4j"
	}
}
