modified.files.includes[relevant][adaptive-media-document-library-thumbnails-functional-rule]=**
relevant.rule.names=adaptive-media-document-library-thumbnails-functional-rule

test.batch.names[relevant][adaptive-media-document-library-thumbnails-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][adaptive-media-document-library-thumbnails-functional-rule]=\
    (testray.component.names == "Adaptive Media") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Adaptive Media