create index IX_B498953F on StyleBookEntry (externalReferenceCode[$COLUMN_LENGTH:75$]);
create index IX_957FE3BD on StyleBookEntry (groupId, defaultStyleBookEntry);
create index IX_9EFBE469 on StyleBookEntry (groupId, head, defaultStyleBookEntry);
create unique index IX_8E48D09B on StyleBookEntry (groupId, head, externalReferenceCode[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_A5545D15 on StyleBookEntry (groupId, head, name[$COLUMN_LENGTH:75$], themeId[$COLUMN_LENGTH:255$]);
create unique index IX_28482235 on StyleBookEntry (groupId, head, styleBookEntryKey[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_BE1AA4F5 on StyleBookEntry (groupId, head, themeId[$COLUMN_LENGTH:255$], defaultStyleBookEntry);
create unique index IX_63D3F12 on StyleBookEntry (groupId, head, uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_1BA6F069 on StyleBookEntry (groupId, name[$COLUMN_LENGTH:75$], themeId[$COLUMN_LENGTH:255$]);
create index IX_9A76A32B on StyleBookEntry (groupId, styleBookEntryKey[$COLUMN_LENGTH:75$]);
create index IX_BABEA421 on StyleBookEntry (groupId, themeId[$COLUMN_LENGTH:255$], defaultStyleBookEntry);
create unique index IX_6ECDD86B on StyleBookEntry (headId, ctCollectionId);
create index IX_346515B6 on StyleBookEntry (uuid_[$COLUMN_LENGTH:75$]);

create index IX_E9CC1685 on StyleBookEntryVersion (groupId, defaultStyleBookEntry);
create index IX_5C966B31 on StyleBookEntryVersion (groupId, name[$COLUMN_LENGTH:75$], themeId[$COLUMN_LENGTH:255$]);
create index IX_8E1B79F3 on StyleBookEntryVersion (groupId, styleBookEntryKey[$COLUMN_LENGTH:75$]);
create index IX_AD6B1259 on StyleBookEntryVersion (groupId, themeId[$COLUMN_LENGTH:255$], defaultStyleBookEntry);
create index IX_D77F24C5 on StyleBookEntryVersion (groupId, version, defaultStyleBookEntry);
create index IX_F45BB971 on StyleBookEntryVersion (groupId, version, name[$COLUMN_LENGTH:75$], themeId[$COLUMN_LENGTH:255$]);
create unique index IX_2D01B891 on StyleBookEntryVersion (groupId, version, styleBookEntryKey[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_8FA40C19 on StyleBookEntryVersion (groupId, version, themeId[$COLUMN_LENGTH:255$], defaultStyleBookEntry);
create unique index IX_3EC07F6E on StyleBookEntryVersion (groupId, version, uuid_[$COLUMN_LENGTH:75$], ctCollectionId);
create index IX_6C02234D on StyleBookEntryVersion (styleBookEntryId);
create index IX_930691EE on StyleBookEntryVersion (uuid_[$COLUMN_LENGTH:75$]);
create unique index IX_2033C367 on StyleBookEntryVersion (version, styleBookEntryId, ctCollectionId);