create table StyleBookEntry (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	headId LONG,
	head BOOLEAN,
	styleBookEntryId LONG not null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	defaultStyleBookEntry BOOLEAN,
	frontendTokenDefinition TEXT null,
	frontendTokensValues TEXT null,
	name VARCHAR(75) null,
	previewFileEntryId LONG,
	styleBookEntryKey VARCHAR(75) null,
	themeId VARCHAR(255) null,
	primary key (styleBookEntryId, ctCollectionId)
);

create table StyleBookEntryVersion (
	mvccVersion LONG default 0 not null,
	ctCollectionId LONG default 0 not null,
	styleBookEntryVersionId LONG not null,
	version INTEGER,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	styleBookEntryId LONG,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	defaultStyleBookEntry BOOLEAN,
	frontendTokenDefinition TEXT null,
	frontendTokensValues TEXT null,
	name VARCHAR(75) null,
	previewFileEntryId LONG,
	styleBookEntryKey VARCHAR(75) null,
	themeId VARCHAR(255) null,
	primary key (styleBookEntryVersionId, ctCollectionId)
);