modified.files.includes[relevant][frontend-js-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][frontend-js-web-playwright-rule]=\
    frontend-js-web.main

relevant.rule.names=frontend-js-web-playwright-rule

test.batch.names[relevant][frontend-js-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163