dependencies {
	compileOnly group: "com.liferay", name: "com.liferay.petra.concurrent", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.memory", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.java", version: "2.0.0"
	compileOnly group: "ch.qos.reload4j", name: "reload4j", version: "1.2.26"
	compileOnly group: "org.osgi", name: "org.osgi.core", version: "5.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
}
