modified.files.includes[relevant][portal-impl-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][portal-impl-java-rule]=\
    apps/**/src/testIntegration/**/*Test.java

relevant.rule.names=portal-impl-java-rule

test.batch.names[relevant][portal-impl-java-rule]=\
    modules-integration-postgresql163

testray.main.component.name=Portal Services