apiDir: ../saml-admin-rest-api/src/main/java
apiPackagePath: com.liferay.saml.admin.rest
application:
    baseURI: /saml-admin
    className: SamlAdminRESTApplication
    name: Liferay.Saml.Admin.REST
author: Stian Sigvartsen
clientDir: ../saml-admin-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../saml-admin-rest-test/src/testIntegration/java