apiDir: ../headless-user-notification-api/src/main/java
apiPackagePath: com.liferay.headless.user.notification
application:
    baseURI: /headless-user-notification
    className: HeadlessUserNotificationApplication
    name: Liferay.Headless.User.Notification
author: Carlos Correa
clientDir: ../headless-user-notification-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../headless-user-notification-test/src/testIntegration/java