modified.files.includes[relevant][portal-cache-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-cache-java-rule]=\
    apps/portal-cache/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-cache-java-rule]=\
    apps/portal-cache/**/*Test.java

relevant.rule.names=portal-cache-java-rule

test.batch.names[relevant][portal-cache-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services