apiDir: ../bulk-rest-api/src/main/java
apiPackagePath: com.liferay.bulk.rest
application:
    baseURI: /bulk
    className: BulkRESTApplication
    name: Liferay.Bulk.REST
author: Alejandro Tardín
clientDir: ../bulk-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateBatch: false
javaEEPackage: jakarta
testDir: ../bulk-rest-test/src/testIntegration/java