##
## Test Suites
##

    modified.files.includes[relevant][multi-factor-authentication-web-playwright-rule]=**
    relevant.rule.names=multi-factor-authentication-web-playwright-rule

    test.batch.names[relevant][multi-factor-authentication-web-playwright-rule]=\
        playwright-js-tomcat90-postgresql163

    #
    # Relevant
    #

    playwright.projects.includes[playwright-js-tomcat90-postgresql163][relevant][multi-factor-authentication-web-playwright-rule]=\
        multi-factor-authentication-web.main