{{- $search := .Values.search.elasticsearch -}}
{{- $elasticsearchNamespace := printf "%s-elasticsearch" .Release.Namespace -}}
{{- if and .Values.enabled $search.enabled }}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-25"
        {{- $search.annotations | toYaml | nindent 8 }}
    name: {{ include "elasticsearch.name" . }}
    namespace: {{ $elasticsearchNamespace }}
spec:
    http:
        tls:
            selfSignedCertificate:
                disabled: true
    nodeSets:
        -   count: {{ $search.nodeCount }}
            name: default
            podTemplate:
                metadata:
                    annotations:
                        {{- $search.annotations | toYaml | nindent 24 }}
                spec:
                    containers:
                        -   env:
                            {{- if or $search.env $search.customEnv }}
                                {{- with $search.env }}
                                {{- toYaml . | nindent 32 }}
                                {{- end }}
                                    {{- range $k, $v := $search.customEnv }}
                                    {{- toYaml $v | nindent 32 }}
                                    {{- end }}
                                {{- else }}
                                -   name:   ES_JAVA_OPTS
                                    value: -Xms4g -Xmx4g
                                {{- end }}
                            name: elasticsearch
                            resources:
                                {{- if $search.resources -}}
                                {{ $search.resources | toYaml | nindent 32 }}
                                {{- else }}
                                limits:
                                    cpu: 1000m
                                    memory: 8Gi
                                requests:
                                    cpu: 500m
                                    memory: 4Gi
                                {{- end }}
                            securityContext:
                                {{- $search.securityContext | toYaml | nindent 32 }}
                    initContainers:
                        -   command:
                                -   sh
                                -   -c
                                -   |
                                    elasticsearch-plugin \
                                        install \
                                        --batch \
                                        analysis-icu \
                                        analysis-kuromoji \
                                        analysis-smartcn \
                                        analysis-stempel
                            name: install-plugins
                            securityContext:
                                {{- $search.securityContext | toYaml | nindent 32 }}
                    securityContext:
                        {{- $search.podSecurityContext | toYaml | nindent 24 }}
            volumeClaimTemplates:
                -   metadata:
                        name: elasticsearch-data
                    spec:
                        accessModes:
                            -   ReadWriteOnce
                        resources:
                            requests:
                                storage: {{ $search.volumeSize }}
                        storageClassName: {{ .Values.persistence.storageClassName }}
    version: {{ $search.version }}
---
apiVersion: v1
kind: Namespace
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-25"
    labels:
        name: {{ $elasticsearchNamespace }}
        pod-security.kubernetes.io/enforce: restricted
    name: {{ $elasticsearchNamespace }}
{{- end -}}