{{- range $secretName := .Values.secrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: {{ $secretName | quote }}
    namespace: {{ $.Release.Namespace }}
spec:
    data:
        -   remoteRef:
                key: {{ $secretName | quote }}
                metadataPolicy: Fetch
            secretKey: meta
        -   remoteRef:
                key: {{ $secretName | quote }}
            secretKey: raw
    refreshInterval: 1h0m0s
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ $.Values.secretStoreName | quote }}
    target:
        creationPolicy: {{ $.Values.externalSecretCreationPolicy | default "Owner" | quote }}
        deletionPolicy: Retain
        template:
            metadata:
                annotations:
                    eso.validated: |-
                        {{- $expectedNs := $.Release.Namespace }}
                        {{- printf " {{- $expectedNs := %q -}}" $expectedNs | nindent 24 }}
                        {{- (print " {{- $nsLabel := index ((.meta | toString | fromJson).labels | default dict) \"esm-app-destination-namespace\" -}}") | nindent 24 }}
                        {{- (print " {{- if ne $nsLabel $expectedNs -}}") | nindent 24 }}
                        {{- (print " {{- fail (printf \"GSM \\\"namespace\\\" label (%q) does not match the ExternalSecret namespace (%q)\" $nsLabel $expectedNs) -}}") | nindent 24 }}
                        {{- (print " {{- end -}}") | nindent 24 }}
                        {{- (print " true") | nindent 24 }}
            templateFrom:
                -   literal: |
                        {{ `{{- (.meta | toString | fromJson).labels | toYaml -}}` }}
                    target: Labels
                -   literal: |
                        {{ `{{- (.meta | toString | fromJson).annotations | toYaml -}}` }}
                    target: Annotations
                -   literal: |
                        {{ `{{- $raw := .raw | toString -}}` }}
                        {{ `{{- if and (hasPrefix "{" $raw) (hasSuffix "}" $raw) -}}` }}
                        {{ `{{- range $k, $v := ($raw | fromJson) }}` }}
                        {{ `{{ $k }}: {{ $v | toString | quote }}` }}
                        {{ `{{- end }}` }}
                        {{ `{{- else }}` }}
                        {{ `secret: {{ $raw | quote }}` }}
                        {{ `{{- end -}}` }}
                    target: Data
{{- end }}