{{- if and .Values.enabled .Values.gateway.className .Values.gateway.name }}
{{- if include "liferay.gateway.isEnvoy" . }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
    labels:
        app: liferay
        component: gateway
        environmentId: {{ .Values.environmentId }}
        projectId: {{ .Values.projectId }}
    name: {{ .Values.gateway.name }}-attachment
    namespace: {{ .Release.Namespace }}
spec:
    {{- if .Values.gateway.clientTrafficPolicySpec }}
    {{- toYaml .Values.gateway.clientTrafficPolicySpec | nindent 4 }}
    {{- end }}
    targetSelectors:
        -   group: gateway.networking.k8s.io
            kind: Gateway
            matchLabels:
                name: {{ .Values.gateway.name }}
---
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
        {{- with .Values.gateway.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    labels:
        app: liferay
        component: gateway
        environmentId: {{ .Values.environmentId }}
        projectId: {{ .Values.projectId }}
    name: {{ .Values.gateway.name }}
    namespace: {{ .Release.Namespace }}
spec:
    {{- if .Values.gateway.spec }}
    {{- toYaml .Values.gateway.spec | nindent 4 }}
    {{- else }}
    gatewayClassName: {{ .Values.gateway.className }}
    listeners:
        {{- if not (hasKey .Values.endpoints "http") }}
        -   allowedRoutes:
                namespaces:
                    from: Same
            name: http
            port: 80
            protocol: HTTP
        {{- end }}
        {{- range  $name, $config := .Values.endpoints }}
        {{- if $config.hostnames }}
        {{- range $hostname := $config.hostnames }}
        {{- $slug := include "liferay.hostnameSlug" $hostname }}
        -   allowedRoutes:
                namespaces:
                    from: Same
            hostname: {{ $hostname | quote }}
            name: {{ printf "%s-%s" $name $slug }}
            port: {{ $config.port }}
            protocol: {{ $config.protocol }}
            {{- with $config.tls }}
            tls:
                certificateRefs:
                    -   kind: Secret
                        name: {{ printf "%s-%s-tls" $.Values.gateway.name $slug }}
                mode: {{ .mode | default "Terminate" }}
            {{- end }}
        {{- end }}
        {{- else }}
        -   allowedRoutes:
                namespaces:
                    from: Same
            {{- if $config.hostname }}
            hostname: {{ $config.hostname | quote }}
            {{- end }}
            name: {{ $name }}
            port: {{ $config.port }}
            protocol: {{ $config.protocol }}
            {{- with $config.tls }}
            tls:
                {{- if or .externalSecretNames .certificateRefs }}
                certificateRefs:
                    {{- if .externalSecretNames }}
                    {{- range .externalSecretNames }}
                    -   kind: Secret
                        name: {{ include "liferay.k8sFriendlyString" . }}
                    {{- end }}
                    {{- end }}
                    {{- with .certificateRefs }}
                    {{- toYaml . | nindent 20 }}
                    {{- end }}
                {{- end }}
                mode: {{ .mode | default "Terminate" }}
            {{- end }}
        {{- end }}
        {{- end }}
    {{- end }}
{{- end -}}