dependencies {
	compileOnly group: "com.liferay", name: "jakarta.enterprise.cdi", version: "4.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "jakarta.ws.rs", version: "3.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.osgi.service.http.whiteboard", version: "1.1.1.JAKARTA_LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.annotation", name: "jakarta.annotation-api", version: "2.1.1"
	compileOnly group: "jakarta.enterprise", name: "jakarta.enterprise.cdi-el-api", version: "4.1.0"
	compileOnly group: "jakarta.inject", name: "jakarta.inject-api", version: "2.0.1"
	compileOnly group: "jakarta.interceptor", name: "jakarta.interceptor-api", version: "2.2.0"
	compileOnly group: "jakarta.mvc", name: "jakarta.mvc-api", version: "2.1.0"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "jakarta.validation", name: "jakarta.validation-api", version: "3.1.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:bean-portlet:bean-portlet-api")
	compileOnly project(":apps:bean-portlet:bean-portlet-extension-api")
	compileOnly project(":apps:bean-portlet:bean-portlet-registration-api")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-string")
}

deployDependencies {
	from configurations.compileOnly

	include "jakarta.mvc-api-*.jar"

	rename(/jakarta\.mvc-api-(.+)\.jar/, "jakarta.mvc-api" + renameSuffix)
}