modified.files.includes[relevant][lang-sanitizer-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][lang-sanitizer-java-rule]=\
    util/lang-sanitizer/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][lang-sanitizer-java-rule]=\
    util/lang-sanitizer/**/*Test.java

relevant.rule.names=lang-sanitizer-java-rule

test.batch.names[relevant][lang-sanitizer-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Core Infrastructure Util