modified.files.includes[relevant][static-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][static-java-rule]=\
    **/change-tracking/**/*Test.java,\
    apps/static/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][static-java-rule]=\
    apps/static/**/*Test.java

relevant.rule.names=static-java-rule

test.batch.names[relevant][static-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=File Install