/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.CompanyInfo;
import com.liferay.portal.kernel.model.CompanyInfoModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CompanyInfo service. Represents a row in the &quot;CompanyInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CompanyInfoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CompanyInfoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CompanyInfoImpl
 * @generated
 */
public class CompanyInfoModelImpl
	extends BaseModelImpl<CompanyInfo> implements CompanyInfoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a company info model instance should use the <code>CompanyInfo</code> interface instead.
	 */
	public static final String TABLE_NAME = "CompanyInfo";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"companyInfoId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"homeURL", Types.VARCHAR},
		{"indexNameCurrent", Types.VARCHAR}, {"indexNameNext", Types.VARCHAR},
		{"industry", Types.VARCHAR}, {"key_", Types.CLOB},
		{"legalId", Types.VARCHAR}, {"legalName", Types.VARCHAR},
		{"legalType", Types.VARCHAR}, {"logoId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"sicCode", Types.VARCHAR},
		{"size_", Types.VARCHAR}, {"tickerSymbol", Types.VARCHAR},
		{"type_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyInfoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("homeURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("indexNameCurrent", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("indexNameNext", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("industry", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("key_", Types.CLOB);
		TABLE_COLUMNS_MAP.put("legalId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("legalName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("legalType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sicCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("size_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tickerSymbol", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CompanyInfo (mvccVersion LONG default 0 not null,companyInfoId LONG not null primary key,companyId LONG,homeURL STRING null,indexNameCurrent VARCHAR(75) null,indexNameNext VARCHAR(75) null,industry VARCHAR(75) null,key_ TEXT null,legalId VARCHAR(75) null,legalName VARCHAR(75) null,legalType VARCHAR(75) null,logoId LONG,name VARCHAR(75) null,sicCode VARCHAR(75) null,size_ VARCHAR(75) null,tickerSymbol VARCHAR(75) null,type_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table CompanyInfo";

	public static final String ENTITY_ALIAS = "companyInfo";

	public static final String ORDER_BY_JPQL =
		" ORDER BY companyInfo.companyInfoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CompanyInfo.companyInfoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYINFOID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.kernel.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.portal.kernel.model.CompanyInfo"));

	public CompanyInfoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _companyInfoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCompanyInfoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _companyInfoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CompanyInfo.class;
	}

	@Override
	public String getModelClassName() {
		return CompanyInfo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CompanyInfo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CompanyInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CompanyInfo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CompanyInfo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CompanyInfo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CompanyInfo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CompanyInfo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CompanyInfo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CompanyInfo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<CompanyInfo, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<CompanyInfo, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<CompanyInfo, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", CompanyInfo::getMvccVersion);
			attributeGetterFunctions.put(
				"companyInfoId", CompanyInfo::getCompanyInfoId);
			attributeGetterFunctions.put(
				"companyId", CompanyInfo::getCompanyId);
			attributeGetterFunctions.put("homeURL", CompanyInfo::getHomeURL);
			attributeGetterFunctions.put(
				"indexNameCurrent", CompanyInfo::getIndexNameCurrent);
			attributeGetterFunctions.put(
				"indexNameNext", CompanyInfo::getIndexNameNext);
			attributeGetterFunctions.put("industry", CompanyInfo::getIndustry);
			attributeGetterFunctions.put("key", CompanyInfo::getKey);
			attributeGetterFunctions.put("legalId", CompanyInfo::getLegalId);
			attributeGetterFunctions.put(
				"legalName", CompanyInfo::getLegalName);
			attributeGetterFunctions.put(
				"legalType", CompanyInfo::getLegalType);
			attributeGetterFunctions.put("logoId", CompanyInfo::getLogoId);
			attributeGetterFunctions.put("name", CompanyInfo::getName);
			attributeGetterFunctions.put("sicCode", CompanyInfo::getSicCode);
			attributeGetterFunctions.put("size", CompanyInfo::getSize);
			attributeGetterFunctions.put(
				"tickerSymbol", CompanyInfo::getTickerSymbol);
			attributeGetterFunctions.put("type", CompanyInfo::getType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<CompanyInfo, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<CompanyInfo, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CompanyInfo, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<CompanyInfo, Long>)CompanyInfo::setMvccVersion);
			attributeSetterBiConsumers.put(
				"companyInfoId",
				(BiConsumer<CompanyInfo, Long>)CompanyInfo::setCompanyInfoId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<CompanyInfo, Long>)CompanyInfo::setCompanyId);
			attributeSetterBiConsumers.put(
				"homeURL",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setHomeURL);
			attributeSetterBiConsumers.put(
				"indexNameCurrent",
				(BiConsumer<CompanyInfo, String>)
					CompanyInfo::setIndexNameCurrent);
			attributeSetterBiConsumers.put(
				"indexNameNext",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setIndexNameNext);
			attributeSetterBiConsumers.put(
				"industry",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setIndustry);
			attributeSetterBiConsumers.put(
				"key", (BiConsumer<CompanyInfo, String>)CompanyInfo::setKey);
			attributeSetterBiConsumers.put(
				"legalId",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setLegalId);
			attributeSetterBiConsumers.put(
				"legalName",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setLegalName);
			attributeSetterBiConsumers.put(
				"legalType",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setLegalType);
			attributeSetterBiConsumers.put(
				"logoId",
				(BiConsumer<CompanyInfo, Long>)CompanyInfo::setLogoId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<CompanyInfo, String>)CompanyInfo::setName);
			attributeSetterBiConsumers.put(
				"sicCode",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setSicCode);
			attributeSetterBiConsumers.put(
				"size", (BiConsumer<CompanyInfo, String>)CompanyInfo::setSize);
			attributeSetterBiConsumers.put(
				"tickerSymbol",
				(BiConsumer<CompanyInfo, String>)CompanyInfo::setTickerSymbol);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<CompanyInfo, String>)CompanyInfo::setType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCompanyInfoId() {
		return _companyInfoId;
	}

	@Override
	public void setCompanyInfoId(long companyInfoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyInfoId = companyInfoId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public String getHomeURL() {
		if (_homeURL == null) {
			return "";
		}
		else {
			return _homeURL;
		}
	}

	@Override
	public void setHomeURL(String homeURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_homeURL = homeURL;
	}

	@Override
	public String getIndexNameCurrent() {
		if (_indexNameCurrent == null) {
			return "";
		}
		else {
			return _indexNameCurrent;
		}
	}

	@Override
	public void setIndexNameCurrent(String indexNameCurrent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_indexNameCurrent = indexNameCurrent;
	}

	@Override
	public String getIndexNameNext() {
		if (_indexNameNext == null) {
			return "";
		}
		else {
			return _indexNameNext;
		}
	}

	@Override
	public void setIndexNameNext(String indexNameNext) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_indexNameNext = indexNameNext;
	}

	@Override
	public String getIndustry() {
		if (_industry == null) {
			return "";
		}
		else {
			return _industry;
		}
	}

	@Override
	public void setIndustry(String industry) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_industry = industry;
	}

	@Override
	public String getKey() {
		if (_key == null) {
			return "";
		}
		else {
			return _key;
		}
	}

	@Override
	public void setKey(String key) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_key = key;
	}

	@Override
	public String getLegalId() {
		if (_legalId == null) {
			return "";
		}
		else {
			return _legalId;
		}
	}

	@Override
	public void setLegalId(String legalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_legalId = legalId;
	}

	@Override
	public String getLegalName() {
		if (_legalName == null) {
			return "";
		}
		else {
			return _legalName;
		}
	}

	@Override
	public void setLegalName(String legalName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_legalName = legalName;
	}

	@Override
	public String getLegalType() {
		if (_legalType == null) {
			return "";
		}
		else {
			return _legalType;
		}
	}

	@Override
	public void setLegalType(String legalType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_legalType = legalType;
	}

	@Override
	public long getLogoId() {
		return _logoId;
	}

	@Override
	public void setLogoId(long logoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_logoId = logoId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getSicCode() {
		if (_sicCode == null) {
			return "";
		}
		else {
			return _sicCode;
		}
	}

	@Override
	public void setSicCode(String sicCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sicCode = sicCode;
	}

	@Override
	public String getSize() {
		if (_size == null) {
			return "";
		}
		else {
			return _size;
		}
	}

	@Override
	public void setSize(String size) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_size = size;
	}

	@Override
	public String getTickerSymbol() {
		if (_tickerSymbol == null) {
			return "";
		}
		else {
			return _tickerSymbol;
		}
	}

	@Override
	public void setTickerSymbol(String tickerSymbol) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tickerSymbol = tickerSymbol;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CompanyInfo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CompanyInfo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CompanyInfo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CompanyInfoImpl companyInfoImpl = new CompanyInfoImpl();

		companyInfoImpl.setMvccVersion(getMvccVersion());
		companyInfoImpl.setCompanyInfoId(getCompanyInfoId());
		companyInfoImpl.setCompanyId(getCompanyId());
		companyInfoImpl.setHomeURL(getHomeURL());
		companyInfoImpl.setIndexNameCurrent(getIndexNameCurrent());
		companyInfoImpl.setIndexNameNext(getIndexNameNext());
		companyInfoImpl.setIndustry(getIndustry());
		companyInfoImpl.setKey(getKey());
		companyInfoImpl.setLegalId(getLegalId());
		companyInfoImpl.setLegalName(getLegalName());
		companyInfoImpl.setLegalType(getLegalType());
		companyInfoImpl.setLogoId(getLogoId());
		companyInfoImpl.setName(getName());
		companyInfoImpl.setSicCode(getSicCode());
		companyInfoImpl.setSize(getSize());
		companyInfoImpl.setTickerSymbol(getTickerSymbol());
		companyInfoImpl.setType(getType());

		companyInfoImpl.resetOriginalValues();

		return companyInfoImpl;
	}

	@Override
	public CompanyInfo cloneWithOriginalValues() {
		CompanyInfoImpl companyInfoImpl = new CompanyInfoImpl();

		companyInfoImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		companyInfoImpl.setCompanyInfoId(
			this.<Long>getColumnOriginalValue("companyInfoId"));
		companyInfoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		companyInfoImpl.setHomeURL(
			this.<String>getColumnOriginalValue("homeURL"));
		companyInfoImpl.setIndexNameCurrent(
			this.<String>getColumnOriginalValue("indexNameCurrent"));
		companyInfoImpl.setIndexNameNext(
			this.<String>getColumnOriginalValue("indexNameNext"));
		companyInfoImpl.setIndustry(
			this.<String>getColumnOriginalValue("industry"));
		companyInfoImpl.setKey(this.<String>getColumnOriginalValue("key_"));
		companyInfoImpl.setLegalId(
			this.<String>getColumnOriginalValue("legalId"));
		companyInfoImpl.setLegalName(
			this.<String>getColumnOriginalValue("legalName"));
		companyInfoImpl.setLegalType(
			this.<String>getColumnOriginalValue("legalType"));
		companyInfoImpl.setLogoId(this.<Long>getColumnOriginalValue("logoId"));
		companyInfoImpl.setName(this.<String>getColumnOriginalValue("name"));
		companyInfoImpl.setSicCode(
			this.<String>getColumnOriginalValue("sicCode"));
		companyInfoImpl.setSize(this.<String>getColumnOriginalValue("size_"));
		companyInfoImpl.setTickerSymbol(
			this.<String>getColumnOriginalValue("tickerSymbol"));
		companyInfoImpl.setType(this.<String>getColumnOriginalValue("type_"));

		return companyInfoImpl;
	}

	@Override
	public int compareTo(CompanyInfo companyInfo) {
		long primaryKey = companyInfo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CompanyInfo)) {
			return false;
		}

		CompanyInfo companyInfo = (CompanyInfo)object;

		long primaryKey = companyInfo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CompanyInfo> toCacheModel() {
		CompanyInfoCacheModel companyInfoCacheModel =
			new CompanyInfoCacheModel();

		companyInfoCacheModel.mvccVersion = getMvccVersion();

		companyInfoCacheModel.companyInfoId = getCompanyInfoId();

		companyInfoCacheModel.companyId = getCompanyId();

		companyInfoCacheModel.homeURL = getHomeURL();

		String homeURL = companyInfoCacheModel.homeURL;

		if ((homeURL != null) && (homeURL.length() == 0)) {
			companyInfoCacheModel.homeURL = null;
		}

		companyInfoCacheModel.indexNameCurrent = getIndexNameCurrent();

		String indexNameCurrent = companyInfoCacheModel.indexNameCurrent;

		if ((indexNameCurrent != null) && (indexNameCurrent.length() == 0)) {
			companyInfoCacheModel.indexNameCurrent = null;
		}

		companyInfoCacheModel.indexNameNext = getIndexNameNext();

		String indexNameNext = companyInfoCacheModel.indexNameNext;

		if ((indexNameNext != null) && (indexNameNext.length() == 0)) {
			companyInfoCacheModel.indexNameNext = null;
		}

		companyInfoCacheModel.industry = getIndustry();

		String industry = companyInfoCacheModel.industry;

		if ((industry != null) && (industry.length() == 0)) {
			companyInfoCacheModel.industry = null;
		}

		companyInfoCacheModel.key = getKey();

		String key = companyInfoCacheModel.key;

		if ((key != null) && (key.length() == 0)) {
			companyInfoCacheModel.key = null;
		}

		companyInfoCacheModel.legalId = getLegalId();

		String legalId = companyInfoCacheModel.legalId;

		if ((legalId != null) && (legalId.length() == 0)) {
			companyInfoCacheModel.legalId = null;
		}

		companyInfoCacheModel.legalName = getLegalName();

		String legalName = companyInfoCacheModel.legalName;

		if ((legalName != null) && (legalName.length() == 0)) {
			companyInfoCacheModel.legalName = null;
		}

		companyInfoCacheModel.legalType = getLegalType();

		String legalType = companyInfoCacheModel.legalType;

		if ((legalType != null) && (legalType.length() == 0)) {
			companyInfoCacheModel.legalType = null;
		}

		companyInfoCacheModel.logoId = getLogoId();

		companyInfoCacheModel.name = getName();

		String name = companyInfoCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			companyInfoCacheModel.name = null;
		}

		companyInfoCacheModel.sicCode = getSicCode();

		String sicCode = companyInfoCacheModel.sicCode;

		if ((sicCode != null) && (sicCode.length() == 0)) {
			companyInfoCacheModel.sicCode = null;
		}

		companyInfoCacheModel.size = getSize();

		String size = companyInfoCacheModel.size;

		if ((size != null) && (size.length() == 0)) {
			companyInfoCacheModel.size = null;
		}

		companyInfoCacheModel.tickerSymbol = getTickerSymbol();

		String tickerSymbol = companyInfoCacheModel.tickerSymbol;

		if ((tickerSymbol != null) && (tickerSymbol.length() == 0)) {
			companyInfoCacheModel.tickerSymbol = null;
		}

		companyInfoCacheModel.type = getType();

		String type = companyInfoCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			companyInfoCacheModel.type = null;
		}

		return companyInfoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CompanyInfo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CompanyInfo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CompanyInfo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((CompanyInfo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CompanyInfo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CompanyInfo.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _companyInfoId;
	private long _companyId;
	private String _homeURL;
	private String _indexNameCurrent;
	private String _indexNameNext;
	private String _industry;
	private String _key;
	private String _legalId;
	private String _legalName;
	private String _legalType;
	private long _logoId;
	private String _name;
	private String _sicCode;
	private String _size;
	private String _tickerSymbol;
	private String _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CompanyInfo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CompanyInfo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("companyInfoId", _companyInfoId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("homeURL", _homeURL);
		_columnOriginalValues.put("indexNameCurrent", _indexNameCurrent);
		_columnOriginalValues.put("indexNameNext", _indexNameNext);
		_columnOriginalValues.put("industry", _industry);
		_columnOriginalValues.put("key_", _key);
		_columnOriginalValues.put("legalId", _legalId);
		_columnOriginalValues.put("legalName", _legalName);
		_columnOriginalValues.put("legalType", _legalType);
		_columnOriginalValues.put("logoId", _logoId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("sicCode", _sicCode);
		_columnOriginalValues.put("size_", _size);
		_columnOriginalValues.put("tickerSymbol", _tickerSymbol);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("key_", "key");
		attributeNames.put("size_", "size");
		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("companyInfoId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("homeURL", 8L);

		columnBitmasks.put("indexNameCurrent", 16L);

		columnBitmasks.put("indexNameNext", 32L);

		columnBitmasks.put("industry", 64L);

		columnBitmasks.put("key_", 128L);

		columnBitmasks.put("legalId", 256L);

		columnBitmasks.put("legalName", 512L);

		columnBitmasks.put("legalType", 1024L);

		columnBitmasks.put("logoId", 2048L);

		columnBitmasks.put("name", 4096L);

		columnBitmasks.put("sicCode", 8192L);

		columnBitmasks.put("size_", 16384L);

		columnBitmasks.put("tickerSymbol", 32768L);

		columnBitmasks.put("type_", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CompanyInfo _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1174498965