apiDir: ../headless-admin-list-type-api/src/main/java
apiPackagePath: com.liferay.headless.admin.list.type
application:
    baseURI: /headless-admin-list-type
    className: HeadlessAdminListTypeApplication
    name: Liferay.Headless.Admin.List.Type
author: Gabriel Albuquerque
clientDir: ../headless-admin-list-type-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../headless-admin-list-type-test/src/testIntegration/java