modified.files.includes[relevant][iframe-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][iframe-web-playwright-rule]=\
    iframe-web.main

relevant.rule.names=iframe-web-playwright-rule

test.batch.names[relevant][iframe-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=IFrame Portlet