resource "helm_release" "argocd" {
	chart="argo-cd"
	depends_on=[
		kubernetes_namespace_v1.argocd,
		kubernetes_secret_v1.argocd_secret,
	]
	name="argocd"
	namespace=local.argocd_namespace
	repository="https://argoproj.github.io/argo-helm"
	values=concat(
		[
			yamlencode(
				{
					applicationSet={
						resources={
							limits={
								memory="768Mi"
							}
							requests={
								cpu="15m"
								memory="128Mi"
							}
						}
					}
					configs={
						cm={
							"admin.enabled"=var.argocd_admin_login_enabled
							"kustomize.buildOptions"="--enable-helm"
							"resource.customizations.health.${var.infrastructure_api_group}_LiferayInfrastructure"=file("${path.module}/health-LiferayInfrastructure.lua")
							"resource.customizations.health.argoproj.io_Application"=file("${path.module}/health-argoproj.io_Application.lua")
							"resource.customizations.ignoreDifferences.${var.infrastructure_api_group}_LiferayInfrastructure"=yamlencode(
								{
									managedFieldsManagers=["liferay-backup-restore"]
								})
							"resource.customizations.ignoreDifferences.all"=yamlencode(
								{
									managedFieldsManagers=[
										"admissionsenforcer",
										"apiextensions.crossplane.io/composite",
										"crossplane",
										"kube-controller-manager",
									]
								})
							"resource.exclusions"=yamlencode(
								[
									{
										apiGroups=[
											"",
											"discovery.k8s.io",
										]
										kinds=[
											"EndpointSlice",
											"Endpoints",
										]
									},
									{
										apiGroups=["*"]
										kinds=["ProviderConfigUsage"]
									},
									{
										apiGroups=["apiextensions.crossplane.io"]
										kinds=["ManagedResourceDefinition"]
									},
									{
										apiGroups=[
											"authentication.k8s.io",
											"authorization.k8s.io",
										]
										kinds=[
											"LocalSubjectAccessReview",
											"SelfSubjectAccessReview",
											"SelfSubjectReview",
											"SelfSubjectRulesReview",
											"SubjectAccessReview",
											"TokenReview",
										]
									},
									{
										apiGroups=["cert-manager.io"]
										kinds=["CertificateRequest"]
									},
									{
										apiGroups=["certificates.k8s.io"]
										kinds=["CertificateSigningRequest"]
									},
									{
										apiGroups=["cilium.io"]
										kinds=[
											"CiliumEndpoint",
											"CiliumEndpointSlice",
											"CiliumIdentity",
										]
									},
									{
										apiGroups=["coordination.k8s.io"]
										kinds=["Lease"]
									},
									{
										apiGroups=[
											"kyverno.io",
											"reports.kyverno.io",
											"wgpolicyk8s.io",
										]
										kinds=[
											"AdmissionReport",
											"BackgroundScanReport",
											"ClusterAdmissionReport",
											"ClusterBackgroundScanReport",
											"ClusterEphemeralReport",
											"ClusterPolicyReport",
											"EphemeralReport",
											"PolicyReport",
											"UpdateRequest",
										]
									},
								])
						}
						params={
							"controller.sync.timeout.seconds"="900"
							"server.insecure"="true"
						}
					}
					controller={
						resources={
							limits={
								memory="8Gi"
							}
							requests={
								cpu="109m"
								memory="1.5Gi"
							}
						}
					}
					dex={
						resources={
							limits={
								memory="768Mi"
							}
							requests={
								cpu="15m"
								memory="128Mi"
							}
						}
					}
					extraObjects=[
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-application-controller"
							}
							spec={
								ingress=local.observability_metrics_ingress
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-application-controller"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-applicationset-controller-ingress"
							}
							spec={
								ingress=local.observability_metrics_ingress
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-applicationset-controller"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-dex-server"
							}
							spec={
								ingress=concat(
									[
										{
											from=[
												{
													podSelector={
														matchLabels={
															"app.kubernetes.io/instance"="argocd"
															"app.kubernetes.io/name"="argocd-server"
														}
													}
												},
											]
											ports=[
												{
													port="grpc"
												},
												{
													port="http"
												},
											]
										},
									],
									local.observability_metrics_ingress)
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-dex-server"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-notifications-controller-ingress"
							}
							spec={
								ingress=local.observability_metrics_ingress
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-notifications-controller"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-redis"
							}
							spec={
								ingress=[
									{
										from=[
											{
												podSelector={
													matchLabels={
														"app.kubernetes.io/instance"="argocd"
														"app.kubernetes.io/name"="argocd-application-controller"
													}
												}
											},
											{
												podSelector={
													matchLabels={
														"app.kubernetes.io/instance"="argocd"
														"app.kubernetes.io/name"="argocd-repo-server"
													}
												}
											},
											{
												podSelector={
													matchLabels={
														"app.kubernetes.io/instance"="argocd"
														"app.kubernetes.io/name"="argocd-server"
													}
												}
											},
										]
										ports=[
											{
												port="redis"
											},
										]
									},
								]
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-redis"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-repo-server"
							}
							spec={
								ingress=concat(
									[
										{
											from=[
												{
													podSelector={
														matchLabels={
															"app.kubernetes.io/instance"="argocd"
															"app.kubernetes.io/name"="argocd-application-controller"
														}
													}
												},
												{
													podSelector={
														matchLabels={
															"app.kubernetes.io/instance"="argocd"
															"app.kubernetes.io/name"="argocd-applicationset-controller"
														}
													}
												},
												{
													podSelector={
														matchLabels={
															"app.kubernetes.io/instance"="argocd"
															"app.kubernetes.io/name"="argocd-notifications-controller"
														}
													}
												},
												{
													podSelector={
														matchLabels={
															"app.kubernetes.io/instance"="argocd"
															"app.kubernetes.io/name"="argocd-server"
														}
													}
												},
											]
											ports=[
												{
													port="repo-server"
												},
											]
										},
									],
									local.observability_metrics_ingress)
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-repo-server"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="argocd-server-ingress"
							}
							spec={
								ingress=concat(
									[
										{
											from=[
												{
													namespaceSelector={
														matchLabels={
															"kubernetes.io/metadata.name"="envoy-gateway-system"
														}
													}
													podSelector={
														matchLabels={
															"app.kubernetes.io/managed-by"="envoy-gateway"
															"app.kubernetes.io/name"="envoy"
															"gateway.envoyproxy.io/owning-gateway-namespace"=local.argocd_namespace
														}
													}
												},
											]
											ports=[
												{
													port="server"
												},
											]
										},
									],
									local.observability_metrics_ingress)
								podSelector={
									matchLabels={
										"app.kubernetes.io/instance"="argocd"
										"app.kubernetes.io/name"="argocd-server"
									}
								}
							}
						},
						{
							apiVersion="networking.k8s.io/v1"
							kind="NetworkPolicy"
							metadata={
								labels=local.common_labels
								name="default-deny-ingress"
							}
							spec={
								podSelector={}
							}
						},
					]
					global={
						networkPolicy={
							create=false
						}
					}
					notifications={
						resources={
							limits={
								memory="256Mi"
							}
							requests={
								cpu="15m"
								memory="128Mi"
							}
						}
					}
					redis={
						resources={
							limits={
								memory="256Mi"
							}
							requests={
								cpu="15m"
								memory="128Mi"
							}
						}
					}
					repoServer={
						livenessProbe={
							failureThreshold=6
							periodSeconds=15
							timeoutSeconds=10
						}
						readinessProbe={
							periodSeconds=15
							timeoutSeconds=10
						}
						resources={
							limits={
								memory="1.5Gi"
							}
							requests={
								cpu="250m"
								memory="128Mi"
							}
						}
					}
					server={
						livenessProbe={
							initialDelaySeconds=90
							timeoutSeconds=5
						}
						readinessProbe={
							initialDelaySeconds=60
							timeoutSeconds=5
						}
						resources={
							limits={
								memory="768Mi"
							}
							requests={
								cpu="15m"
								memory="128Mi"
							}
						}
					}
				}),
		],
		local.argocd_external_url != null ? [
			yamlencode(
				{
					configs={
						cm={
							url=local.argocd_external_url
						}
					}
				}),
		] : [],
		local.argocd_sso_enabled ? [
			yamlencode(
				{
					configs={
						cm={
							"dex.config"=yamlencode(
								{
									connectors=[
										{
											config={
												caData="$customer-idp-saml:caData"
												emailAttr="email"
												entityIssuer="$customer-idp-saml:entityIssuer"
												groupsAttr="groups"
												redirectURI="$customer-idp-saml:redirectURI"
												ssoURL="$customer-idp-saml:ssoURL"
												usernameAttr="name"
											}
											id="customer-idp"
											name="SAML"
											type="saml"
										},
									]
								})
						}
						rbac={
							"policy.csv"=join("\n", [
								"g, customer-idp:liferay-argocd-role-admin, role:liferay-admin",
								"g, customer-idp:liferay-argocd-role-guest, role:liferay-guest",
								"p, role:liferay-admin, accounts, *, *, allow",
								"p, role:liferay-admin, applications, *, */*, allow",
								"p, role:liferay-admin, clusters, *, *, allow",
								"p, role:liferay-admin, projects, *, *, allow",
								"p, role:liferay-admin, repositories, *, *, allow",
								"p, role:liferay-guest, applications, get, */*, allow",
								"p, role:liferay-guest, clusters, get, *, allow",
								"p, role:liferay-guest, projects, get, *, allow",
								"p, role:liferay-guest, repositories, get, *, allow",
							])
							"policy.default"="role:liferay-guest"
						}
					}
				}),
		] : [],
		var.additional_values,
	)
	version=var.argocd_helm_chart_version
}
resource "kubernetes_namespace_v1" "argocd" {
	metadata {
		labels=merge(
			local.common_labels,
			{
				"pod-security.kubernetes.io/enforce"="restricted"
			})
		name=local.argocd_namespace
	}
}
resource "kubernetes_secret_v1" "argocd_secret" {
	data={
		"server.secretkey"=random_password.argocd_server_secretkey.result
	}
	lifecycle {
		ignore_changes=[
			data,
			metadata[0].labels,
		]
	}
	metadata {
		annotations={
			"meta.helm.sh/release-name"="argocd"
			"meta.helm.sh/release-namespace"=kubernetes_namespace_v1.argocd.metadata[0].name
		}
		labels=merge(
			local.common_labels,
			{
				"app.kubernetes.io/managed-by"="Helm"
			})
		name="argocd-secret"
		namespace=kubernetes_namespace_v1.argocd.metadata[0].name
	}
}
resource "random_password" "argocd_server_secretkey" {
	length=32
	special=false
}