resource "kubernetes_manifest" "karpenter_node_pool" {
	manifest={
		apiVersion="karpenter.sh/v1"
		kind="NodePool"
		metadata={
			name="general-purpose"
		}
		spec={
			disruption={
				consolidateAfter="1m"
				consolidationPolicy="WhenEmptyOrUnderutilized"
			}
			template={
				spec={
					expireAfter="Never"
					nodeClassRef={
						group="karpenter.azure.com"
						kind="AKSNodeClass"
						name="default"
					}
					requirements=[
						{
							key="karpenter.azure.com/sku-name"
							operator="In"
							values=[var.machine_type]
						},
						{
							key="karpenter.sh/capacity-type"
							operator="In"
							values=["on-demand"]
						},
						{
							key="kubernetes.io/arch"
							operator="In"
							values=["amd64"]
						},
						{
							key="kubernetes.io/os"
							operator="In"
							values=["linux"]
						},
					]
				}
			}
			weight=100
		}
	}
}