resource "kubernetes_manifest" "karpenter_node_class" {
	manifest={
		apiVersion="karpenter.azure.com/v1beta1"
		kind="AKSNodeClass"
		metadata={
			name="general-purpose"
		}
		spec={
			imageFamily="Ubuntu"
			osDiskSizeGB=128
		}
	}
}
resource "kubernetes_manifest" "karpenter_node_pool" {
	manifest={
		apiVersion="karpenter.sh/v1"
		kind="NodePool"
		metadata={
			name="general-purpose"
		}
		spec={
			disruption={
				consolidateAfter="1m"
				consolidationPolicy="WhenEmptyOrUnderutilized"
			}
			template={
				spec={
					expireAfter="Never"
					nodeClassRef={
						group="karpenter.azure.com"
						kind="AKSNodeClass"
						name=kubernetes_manifest.karpenter_node_class.manifest.metadata.name
					}
					requirements=[
						{
							key="karpenter.azure.com/sku-name"
							operator="In"
							values=[local.system_node_pool_vm_size]
						},
						{
							key="karpenter.sh/capacity-type"
							operator="In"
							values=["on-demand"]
						},
						{
							key="kubernetes.io/arch"
							operator="In"
							values=["amd64"]
						},
						{
							key="kubernetes.io/os"
							operator="In"
							values=["linux"]
						},
					]
				}
			}
			weight=100
		}
	}
}