apiVersion: apiextensions.crossplane.io/v1beta1
data:
    deploymentName: {{ $.Values.deploymentName | quote }}
    projectId: {{ $.Values.global.gcp.projectId | quote }}
    projectNumber: {{ $.Values.global.gcp.projectNumber | quote }}
    vpcName: {{ $.Values.global.gcp.vpcName | quote }}
kind: EnvironmentConfig
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-40"
    name: environment-config