{{- if and .Values.filestore.enabled .Values.filestore.storageClassName .Values.global.gcp.vpcName }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-110"
    labels:
        app: liferay
        component: storage
    name: {{ .Values.filestore.storageClassName }}
parameters:
    network: {{ .Values.global.gcp.vpcName | quote }}
    tier: {{ .Values.filestore.tier | quote }}
provisioner: filestore.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end -}}