apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-60"
    name: liferayoverlays.gcp.liferay.com
spec:
    group: gcp.liferay.com
    names:
        kind: LiferayOverlay
        plural: liferayoverlays
        shortNames:
            -   lfroverlay
            -   lro
        singular: liferayoverlay
    versions:
        -   name: v1alpha1
            referenceable: true
            schema:
                openAPIV3Schema:
                    properties:
                        spec:
                            properties:
                                commonTags:
                                    additionalProperties:
                                        type: string
                                    default: {}
                                    type: object
                                forceDestroy:
                                    default: false
                                    type: boolean
                                orphanOnDelete:
                                    type: boolean
                                projectId:
                                    type: string
                                region:
                                    type: string
                            required:
                                -   forceDestroy
                                -   orphanOnDelete
                                -   projectId
                                -   region
                            type: object
                        status:
                            properties:
                                bucketReady:
                                    default: false
                                    type: boolean
                            type: object
                    type: object
            served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-50"
    name: liferay-gcp-overlay.gcp.liferay.com
spec:
    compositeTypeRef:
        apiVersion: gcp.liferay.com/v1alpha1
        kind: LiferayOverlay
    mode: Pipeline
    pipeline:
        -   functionRef:
                name: function-environment-configs
            input:
                apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
                kind: Input
                spec:
                    environmentConfigs:
                        -   ref:
                                name: environment-config
                            type: Reference
                        -   ref:
                                name: liferay-template-store
                            type: Reference
            step: environment-configs
        -   functionRef:
                name: function-go-templating
            input:
                apiVersion: gotemplating.fn.crossplane.io/v1beta1
                inline:
                    template: |
                        {{- .Files.Get "liferayoverlay-composition/00-globals.gotmpl" | nindent 24 }}
                        {{- range $path, $_ := .Files.Glob "liferayoverlay-composition/[1-9]*" }}
                        ---
                        {{ $.Files.Get $path | nindent 24 }}
                        {{- end }}
                kind: Input
                source: Inline
            step: go-templating
        -   functionRef:
                name: function-auto-ready
            step: auto-detect-ready-composed-resources