apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
    annotations:
        argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-60"
    name: liferayinfrastructures.gcp.liferay.com
spec:
    group: gcp.liferay.com
    names:
        kind: LiferayInfrastructure
        plural: liferayinfrastructures
        shortNames:
            -   lfrinfra
            -   lri
        singular: liferayinfrastructure
    versions:
        -   name: v1alpha1
            referenceable: true
            schema:
                openAPIV3Schema:
                    properties:
                        spec:
                            properties:
                                backup:
                                    properties:
                                        enabled:
                                            type: boolean
                                        region:
                                            type: string
                                        retentionDays:
                                            type: integer
                                        storageClass:
                                            type: string
                                    type: object
                                cmk:
                                    default:
                                        enabled: false
                                    properties:
                                        enabled:
                                            default: false
                                            type: boolean
                                    type: object
                                commonTags:
                                    additionalProperties:
                                        type: string
                                    default: {}
                                    type: object
                                database:
                                    properties:
                                        databaseVersion:
                                            type: string
                                        deletionProtection:
                                            type: boolean
                                        instanceType:
                                            type: string
                                        queryInsightsEnabled:
                                            type: boolean
                                        region:
                                            type: string
                                        rootPasswordSecretName:
                                            type: string
                                        storageGB:
                                            type: integer
                                    type: object
                                environmentId:
                                    type: string
                                forceDestroy:
                                    default: false
                                    type: boolean
                                orphanOnDelete:
                                    default: false
                                    type: boolean
                                overlayAccess:
                                    properties:
                                        enabled:
                                            default: false
                                            type: boolean
                                    type: object
                                projectId:
                                    type: string
                                region:
                                    type: string
                                restorePhase:
                                    enum:
                                        -   none
                                        -   promoting
                                        -   provisioning
                                        -   provisioning-database-user
                                    type: string
                                storage:
                                    properties:
                                        enableVersioning:
                                            default: true
                                            type: boolean
                                        region:
                                            type: string
                                    type: object
                                targetActiveDataPlane:
                                    enum:
                                        -   blue
                                        -   green
                                    type: string
                            required:
                                -   database
                                -   environmentId
                                -   projectId
                                -   region
                                -   storage
                            type: object
                        status:
                            properties:
                                managedServiceDetailsReady:
                                    default: false
                                    type: boolean
                            type: object
                    type: object
            served: true
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-50"
    name: liferay-gcp-infrastructure-provider.gcp.liferay.com
spec:
    compositeTypeRef:
        apiVersion: gcp.liferay.com/v1alpha1
        kind: LiferayInfrastructure
    mode: Pipeline
    pipeline:
        -   functionRef:
                name: function-environment-configs
            input:
                apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
                kind: Input
                spec:
                    environmentConfigs:
                        -   ref:
                                name: environment-config
                            type: Reference
                        -   ref:
                                name: liferay-template-store
                            type: Reference
            step: environment-configs
        -   functionRef:
                name: function-go-templating
            input:
                apiVersion: gotemplating.fn.crossplane.io/v1beta1
                inline:
                    template: |
                        {{- .Files.Get "liferayinfrastructure-composition/00-globals.gotmpl" | nindent 24 }}
                        {{- range $path, $_ := .Files.Glob "liferayinfrastructure-composition/[1-9]*" }}
                        ---
                        {{ $.Files.Get $path | nindent 24 }}
                        {{- end }}
                kind: Input
                source: Inline
            step: go-templating
        -   functionRef:
                name: function-auto-ready
            step: auto-detect-ready-composed-resources