{{- $accessControl := .Values.gateway.accessControl -}}

{{- if $accessControl.enabled }}
{{- if not $accessControl.allowedCIDRs }}
{{- fail (printf "The value %q must not be empty when %q is true" "gateway.accessControl.allowedCIDRs" "gateway.accessControl.enabled") }}
{{- end }}

{{- if not $accessControl.gateways }}
{{- fail (printf "The value %q must not be empty when %q is true" "gateway.accessControl.gateways" "gateway.accessControl.enabled") }}
{{- end }}
{{- end }}

{{- range $gateway := $accessControl.gateways }}
{{- $name := required (printf "The value %q is required for every entry of %q" "name" "gateway.accessControl.gateways") $gateway.name }}
{{- $namespace := required (printf "The value %q is required for every entry of %q" "namespace" "gateway.accessControl.gateways") $gateway.namespace }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-110"
    labels:
        app: liferay
        component: security-policy
    name: {{ $name }}-security-policy
    namespace: {{ $namespace }}
spec:
    authorization:
        {{- if $accessControl.enabled }}
        defaultAction: Deny
        rules:
            -   action: Allow
                name: allowed-cidrs
                principal:
                    clientCIDRs:
                        {{- range $accessControl.allowedCIDRs }}
                        -   {{ . | quote }}
                        {{- end }}
        {{- else }}
        defaultAction: Allow
        {{- end }}
    targetRefs:
        -   group: gateway.networking.k8s.io
            kind: Gateway
            name: {{ $name }}
{{- end -}}