{{- if and .Values.enabled (eq .Values.database.authentication "password") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
        helm.sh/resource-policy: keep
    name: database-app-password
    namespace: {{ .Release.Namespace }}
spec:
    dataFrom:
        -   sourceRef:
                generatorRef:
                    apiVersion: generators.external-secrets.io/v1alpha1
                    kind: Password
                    name: database-app-password-generator
    refreshInterval: 0s
    target:
        name: database-app-password
        template:
            data:
                DATABASE_PASSWORD: "{{ `{{ .password }}` }}"
            type: Opaque
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-40"
        helm.sh/resource-policy: keep
    name: database-app-password-generator
    namespace: {{ .Release.Namespace }}
spec:
    allowRepeat: false
    digits: 5
    length: 24
    noUpper: false
    symbolCharacters: -_$@
    symbols: 2
{{- end -}}