{{- if and .Values.enabled .Values.license.externalSecretKey }}
{{- with .Values.license.targetSecretName -}}
{{- include "liferay.validateDNS1123Name" . -}}
{{- end -}}
{{- include "liferay.validateSecretKey" (dict "key" .Values.license.externalSecretKey "prefix" "liferay-licenses-") -}}
{{- include "liferay.validateSecretNameSuffix" .Values.license.externalSecretKey -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-40"
    labels:
        app: liferay
        component: license
    name: liferay-license
    namespace: {{ .Release.Namespace }}
spec:
    data:
        -   remoteRef:
                decodingStrategy: Auto
                key: {{ .Values.license.externalSecretKey | quote }}
                property: {{ .Values.license.externalSecretProperty | quote }}
            secretKey: license.xml
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ required "The value \"clusterSecretStoreName\" is required to synchronize the license" .Values.clusterSecretStoreName | quote }}
    {{- with .Values.license.targetSecretName }}
    target:
        name: {{ . | quote }}
    {{- end }}
{{- end -}}