{{- if .Values.enabled }}
{{- $externalSecretKeys := list -}}
{{- range $endpoint := .Values.endpoints }}
{{- $externalSecretKeys = concat $externalSecretKeys (dig "tls" "externalSecretKeys" (list) $endpoint) -}}
{{- end }}
{{- range $externalSecretKey := uniq $externalSecretKeys }}
{{- include "liferay.validateDNS1123Name" $externalSecretKey }}
{{- include "liferay.validateSecretKey" (dict "key" $externalSecretKey "prefix" "liferay-certificates-") }}
{{- include "liferay.validateSecretNameSuffix" $externalSecretKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-40"
    labels:
        app: liferay
        component: certificate
    name: {{ $externalSecretKey | quote }}
    namespace: {{ $.Release.Namespace }}
spec:
    dataFrom:
        -   extract:
                decodingStrategy: Auto
                key: {{ $externalSecretKey | quote }}
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ required "The value \"clusterSecretStoreName\" is required to synchronize certificates" $.Values.clusterSecretStoreName | quote }}
    target:
        template:
            type: kubernetes.io/tls
{{- end }}
{{- end -}}