{{- if and .Values.enabled .Values.gateway.className .Values.gateway.name }}
{{- $gateway := .Values.gateway }}
{{- with $gateway.clientTrafficPolicySpec }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
    labels:
        app: liferay
        component: gateway
        environmentId: {{ $.Values.environmentId | quote }}
        projectId: {{ $.Values.projectId | quote }}
    name: {{ $gateway.name }}-attachment
    namespace: {{ $.Release.Namespace }}
spec:
    {{- toYaml . | nindent 4 }}
    targetRefs:
        -   group: gateway.networking.k8s.io
            kind: Gateway
            name: {{ $gateway.name | quote }}
---
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
        {{- with $gateway.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    labels:
        app: liferay
        component: gateway
        environmentId: {{ .Values.environmentId | quote }}
        projectId: {{ .Values.projectId | quote }}
    name: {{ $gateway.name | quote }}
    namespace: {{ .Release.Namespace }}
spec:
    gatewayClassName: {{ $gateway.className | quote }}
    listeners:
        {{- if not (hasKey .Values.endpoints "http") }}
        -   allowedRoutes:
                namespaces:
                    from: Same
            name: http
            port: 80
            protocol: HTTP
        {{- end }}
        {{- range $name, $endpoint := .Values.endpoints }}
        -   allowedRoutes:
                namespaces:
                    from: Same
            {{- with $endpoint.hostname }}
            hostname: {{ . | quote }}
            {{- end }}
            name: {{ $name | quote }}
            port: {{ $endpoint.port }}
            protocol: {{ $endpoint.protocol | quote }}
            {{- with $endpoint.tls }}
            {{- $mode := .mode | default "Terminate" }}
            {{- if and (eq $mode "Terminate") (not .externalSecretKeys) }}
            {{- fail (printf "The %s endpoint terminates TLS and must set tls.externalSecretKeys" $name) }}
            {{- end }}
            {{- if and (eq $mode "Passthrough") .externalSecretKeys }}
            {{- fail (printf "The %s endpoint passes TLS through and must not set tls.externalSecretKeys" $name) }}
            {{- end }}
            tls:
                {{- with .externalSecretKeys }}
                certificateRefs:
                    {{- range . }}
                    -   kind: Secret
                        name: {{ . | quote }}
                    {{- end }}
                {{- end }}
                mode: {{ $mode }}
            {{- end }}
        {{- end }}
{{- end -}}