modified.files.includes[relevant][template-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][template-web-playwright-rule]=\
    template-web.main

relevant.rule.names=template-web-playwright-rule

test.batch.names[relevant][template-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Templates