modified.files.includes[relevant][frontend-js-aui-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][frontend-js-aui-web-playwright-rule]=\
    frontend-js-aui-web.main

relevant.rule.names=frontend-js-aui-web-playwright-rule

test.batch.names[relevant][frontend-js-aui-web-playwright-rule]=\
    playwright-js-tomcat90-mysql57

testray.main.component.name=Frontend JS