#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/seo-studio
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.SEO.Studio.REST)
osgi.jaxrs.resource=true