apply plugin: "war"

dependencies {
	compileOnly group: "com.liferay", name: "jakarta.enterprise.cdi", version: "4.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "jakarta.faces", name: "jakarta.faces-api", version: "4.1.2"
	implementation group: "com.liferay", name: "com.liferay.faces.bridge.api", version: "4.3.0.JAKARTA_LIFERAY-PATCHED-1"
	implementation group: "com.liferay", name: "com.liferay.faces.bridge.ext", version: "6.1.1.JAKARTA_LIFERAY-PATCHED-1"
	implementation group: "com.liferay", name: "com.liferay.faces.bridge.impl", version: "4.3.0.JAKARTA_LIFERAY-PATCHED-1"
	implementation group: "com.liferay", name: "com.liferay.faces.util", version: "3.4.1.JAKARTA_LIFERAY-PATCHED-1"
	implementation group: "com.liferay", name: "jakarta.faces", version: "2.2.20.LIFERAY-PATCHED-1.JAKARTA_LIFERAY-PATCHED-1"
}

deploy {
	from war

	rename {
		"bean-portlet-cdi-extension-sample-test.war"
	}
}

liferay {
	deployDir = file("${liferayHome}/osgi/war")
}