modified.files.includes[relevant][commerce-demo-pack-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][commerce-demo-pack-java-rule]=\
    dxp/apps/commerce-demo-pack/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][commerce-demo-pack-java-rule]=\
    dxp/apps/commerce-demo-pack/**/*Test.java

relevant.rule.names=commerce-demo-pack-java-rule

test.batch.names[relevant][commerce-demo-pack-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Commerce