modified.files.includes[relevant][adaptive-media-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][adaptive-media-java-rule]=\
    apps/adaptive-media/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][adaptive-media-java-rule]=\
    apps/adaptive-media/**/*Test.java

relevant.rule.names=adaptive-media-java-rule

test.batch.names[relevant][adaptive-media-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Adaptive Media