modified.files.includes[relevant][accessibility-menu-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][accessibility-menu-web-playwright-rule]=\
    accessibility-menu-web.main

relevant.rule.names=accessibility-menu-web-playwright-rule

test.batch.names[relevant][accessibility-menu-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Accessibility Menu