dependencies {
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	testImplementation group: "com.liferay.portal", name: "com.liferay.util.java", version: "default"
	testImplementation group: "commons-io", name: "commons-io", version: "2.15.1"
	testImplementation group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	testImplementation group: "org.osgi", name: "osgi.core", version: "6.0.0"
	testImplementation project(":apps:static:portal-lpkg-deployer:portal-lpkg-deployer-test-util")
	testImplementation project(":core:petra:petra-lang")
	testImplementation project(":core:petra:petra-string")
	testIntegrationImplementation project(":apps:static:portal-lpkg-deployer:portal-lpkg-deployer-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}

test {
	systemProperty "liferay.home", System.getProperty("liferay.home")
}