modified.files.includes[relevant][asset-functional-rule]=**

modified.files.includes[relevant][asset-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][asset-java-rule]=\
    apps/asset/**/*Test.java,\
    apps/document-library/**/src/testIntegration/**/*Test.java,\
    apps/fragment/**/src/testIntegration/**/*Test.java,\
    apps/segments/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-java-rule]=\
    apps/asset/**/*Test.java,\
    apps/document-library/**/src/test/**/*Test.java,\
    apps/fragment/**/src/test/**/*Test.java,\
    apps/segments/**/*Test.java

relevant.rule.names=\
    asset-functional-rule,\
    asset-java-rule

test.batch.names[relevant][asset-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][asset-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][asset-functional-rule]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Documents and Media") AND \
        (testray.main.component.name ~ "Upgrades Collaboration")\
    )

testray.main.component.name=Asset Framework