apiDir: ../headless-form-api/src/main/java
apiPackagePath: com.liferay.headless.form
application:
    baseURI: /headless-form
    className: HeadlessFormApplication
    name: Liferay.Headless.Form
author: Javier Gamarra
clientDir: ../headless-form-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../headless-form-test/src/testIntegration/java