modified.files.includes[relevant][microsoft-translator-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][microsoft-translator-java-rule]=\
    apps/microsoft-translator/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][microsoft-translator-java-rule]=\
    apps/microsoft-translator/**/*Test.java

relevant.rule.names=microsoft-translator-java-rule

test.batch.names[relevant][microsoft-translator-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Translations Management