argocd:
    gateway:
        enabled: false
        envoyProxy:
            podAnnotations: {}
            replicas: 2
            serviceAnnotations: {}
        hostname: ""
        tls:
            externalSecretKey: ""
    sso:
        credentialsSecretKey: ""
        enabled: false
clusterBootstrap:
    enabled: true
    image: alpine:3
    resources:
        limits:
            cpu: 3m
            memory: 16Mi
        requests:
            cpu: 1m
            memory: 8Mi
clusterSecretStore:
    enabled: false
    name: ""
    provider: {}
deploymentContext:
    deploymentName: ""
    region: ""
gateway:
    envoyProxy:
        podAnnotations: {}
        serviceAnnotations: {}
gitops:
    infrastructureRepository:
        credentialsSecretName: liferay-credentials-gitops
        githubAppIdProperty: github_app_id
        githubAppInstallationIdProperty: github_app_installation_id
        githubAppPrivateKeyProperty: github_app_private_key
        internalSecretName: git-repo-infrastructure-credentials
        method: https
        registerCredentials: true
        revision: ""
        sshPrivateKeyProperty: git_ssh_private_key
        tokenProperty: git_access_token
        url: ""
        usernameProperty: git_machine_user_id
    layout:
        base: liferay/projects/{{path[2]}}/base
        environmentId: "{{path[4]}}"
        environments: liferay/projects/*/environments/*
        infrastructureProviderValuesFilename: infrastructure-provider.yaml
        infrastructureValuesFilename: infrastructure.yaml
        liferayValuesFilename: liferay.yaml
        observabilityValuesFilename: observability.yaml
        projectId: "{{path[2]}}"
        projectValuesFilename: project.yaml
        projects: liferay/projects/*
        system: liferay/system
    repository:
        credentialsSecretName: liferay-credentials-gitops
        githubAppIdProperty: github_app_id
        githubAppInstallationIdProperty: github_app_installation_id
        githubAppPrivateKeyProperty: github_app_private_key
        internalSecretName: git-repo-gitops-credentials
        method: https
        registerCredentials: true
        revision: HEAD
        sshPrivateKeyProperty: git_ssh_private_key
        tokenProperty: git_access_token
        url: ""
        usernameProperty: git_machine_user_id
infrastructure:
    enabled: true
    path: ""
    repoURL: ""
    targetRevision: ""
infrastructureProvider:
    enabled: true
    path: ""
    repoURL: ""
    targetRevision: ""
liferay:
    enabled: true
    parameters: []
    path: ""
    repoURL: ""
    targetRevision: ""
observability:
    enabled: false
    namespace: observability
    parameters: []
    repoURL: oci://us-central1-docker.pkg.dev/external-assets-prd/liferay-helm-chart/observability
    targetRevision: 1.1.0
operatorApplications:
    ackPrometheusService:
        enabled: false
        name: ack-prometheusservice
        namespace: ack-system
        repoURL: oci://public.ecr.aws/aws-controllers-k8s/prometheusservice-chart
        requiresObservability: true
        targetRevision: 1.4.1
        values: {}
    argoWorkflows:
        chart: argo-workflows
        enabled: true
        name: argo-workflows
        namespace: argo-workflows-system
        repoURL: https://argoproj.github.io/argo-helm
        targetRevision: 1.0.10
        values:
            controller:
                resources:
                    limits:
                        memory: 512Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
                workflowDefaults:
                    spec:
                        securityContext:
                            runAsNonRoot: true
                            runAsUser: 8737
                            seccompProfile:
                                type: RuntimeDefault
            executor:
                image:
                    tag: v4.0.4-nonroot
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 8737
                    seccompProfile:
                        type: RuntimeDefault
            mainContainer:
                securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                        drop:
                            -   ALL
                    runAsNonRoot: true
                    runAsUser: 8737
                    seccompProfile:
                        type: RuntimeDefault
            server:
                resources:
                    limits:
                        memory: 256Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
            workflow:
                rbac:
                    create: false
    crossplane:
        chart: crossplane
        enabled: true
        functions:
            function-auto-ready:
                package: xpkg.upbound.io/upbound/function-auto-ready:v0.6.0
                resources:
                    limits:
                        memory: 256Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
            function-environment-configs:
                package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.6.0
                resources:
                    limits:
                        memory: 256Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
            function-go-templating:
                package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.11.3
                resources:
                    limits:
                        memory: 512Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
            function-tag-manager:
                package: xpkg.upbound.io/crossplane-contrib/function-tag-manager:v0.6.0
                resources:
                    limits:
                        memory: 256Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
        name: crossplane
        namespace: crossplane-system
        namespaceLabels:
            pod-security.kubernetes.io/enforce: restricted
        providers:
            provider-kubernetes:
                package: xpkg.upbound.io/upbound/provider-kubernetes:v1.2.0
                resources:
                    limits:
                        cpu: 1000m
                        memory: 2Gi
                    requests:
                        cpu: 250m
                        memory: 512Mi
                serviceAccountName: provider-kubernetes
        repoURL: https://charts.crossplane.io/stable
        targetRevision: 2.1.3
        values:
            podSecurityContextCrossplane:
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
            podSecurityContextRBACManager:
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
            resourcesCrossplane:
                limits:
                    memory: 2Gi
                requests:
                    cpu: 63m
                    memory: 768Mi
            resourcesRBACManager:
                limits:
                    memory: 512Mi
                requests:
                    cpu: 15m
                    memory: 256Mi
            securityContextCrossplane:
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                        -   ALL
                readOnlyRootFilesystem: true
                runAsGroup: 65532
                runAsUser: 65532
            securityContextRBACManager:
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                        -   ALL
                readOnlyRootFilesystem: true
                runAsGroup: 65532
                runAsUser: 65532
    dxpOperator:
        enabled: true
        name: dxp-operator
        namespace: dxp-operator-system
        namespaceLabels:
            pod-security.kubernetes.io/enforce: restricted
        repoURL: oci://us-central1-docker.pkg.dev/external-assets-prd/liferay-helm-chart/liferay-dxp-operator
        targetRevision: 0.1.0
        values:
            fullnameOverride: dxp-operator
    eckOperator:
        chart: eck-operator
        enabled: true
        name: eck-operator
        namespace: elastic-system
        namespaceLabels:
            pod-security.kubernetes.io/enforce: restricted
        repoURL: https://helm.elastic.co
        targetRevision: 3.2.0
        values:
            installCRDs: true
            podSecurityContext:
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
            resources:
                limits:
                    cpu: 1
                    memory: 512Mi
                requests:
                    cpu: 100m
                    memory: 128Mi
            securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                        -   ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
    envoyGateway:
        enabled: true
        name: envoy-gateway
        namespace: envoy-gateway-system
        repoURL: oci://docker.io/envoyproxy/gateway-helm
        targetRevision: 1.6.3
        values:
            config:
                envoyGateway:
                    extensionApis:
                        enableBackend: false
            deployment:
                replicas: 2
            podDisruptionBudget:
                maxUnavailable: 1
    externalSecrets:
        chart: external-secrets
        enabled: true
        name: external-secrets
        namespace: external-secrets-system
        repoURL: https://charts.external-secrets.io
        targetRevision: 2.9.0
        values:
            certController:
                resources:
                    limits:
                        memory: 512Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
            installCRDs: true
            resources:
                limits:
                    memory: 512Mi
                requests:
                    cpu: 15m
                    memory: 128Mi
            webhook:
                resources:
                    limits:
                        memory: 256Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
    keda:
        chart: keda
        enabled: false
        extraDestinationNamespaces:
            -   kube-system
        name: keda
        namespace: keda-system
        repoURL: https://kedacore.github.io/charts
        targetRevision: 2.19.0
        values:
            resources:
                metricServer:
                    limits:
                        memory: 512Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
                operator:
                    limits:
                        memory: 512Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi
                webhooks:
                    limits:
                        memory: 256Mi
                    requests:
                        cpu: 15m
                        memory: 128Mi