modified.files.includes[relevant][wiki-web-functional-rule]=**
modified.files.includes[relevant][wiki-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][wiki-web-playwright-rule]=\
    wiki-web.main

relevant.rule.names=\
    wiki-web-functional-rule,\
    wiki-web-playwright-rule

test.batch.names[relevant][wiki-web-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][wiki-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][wiki-web-functional-rule]=\
    (testray.component.names == "Wiki") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Wiki