export namespace Modal {
	export enum actionTypes {
		CLOSE_ALL_MODALS = 'CLOSE_ALL_MODALS',
		CLOSE_MODAL = 'CLOSE_MODAL',
		OPEN_MODAL = 'OPEN_MODAL',
	}

	export enum modalTypes {
		ADD_CHANNEL_MODAL = 'ADD_CHANNEL_MODAL',
		BATCH_ACTION_MODAL = 'BATCH_ACTION_MODAL',
		CONFIRMATION_MODAL = 'CONFIRMATION_MODAL',
		CONNECT_DXP_MODAL = 'CONNECT_DXP_MODAL',
		CONTACT_SALES_MODAL = 'CONTACT_SALES_MODAL',
		CREATE_MAPPING_MODAL = 'CREATE_MAPPING_MODAL',
		CSV_PREVIEW_MODAL = 'CSV_PREVIEW_MODAL',
		DELETE_CHANNEL_MODAL = 'DELETE_CHANNEL_MODAL',
		DELETE_CONFIRMATION_MODAL = 'DELETE_CONFIRMATION_MODAL',
		EDIT_ATTRIBUTE_EVENT_MODAL = 'EDIT_ATTRIBUTE_EVENT_MODAL',
		EDIT_EMAIL_REPORTS = 'EDIT_EMAIL_REPORTS',
		ENTITY_LIST_MODAL = 'ENTITY_LIST_MODAL',
		EXPORT_LOG_MODAL = 'EXPORT_LOG_MODAL',
		FIELD_PREVIEW_MODAL = 'FIELD_PREVIEW_MODAL',
		HELP_WIDGET_MODAL = 'HELP_WIDGET_MODAL',
		INDIVIDUAL_ATTRIBUTES_MODAL = 'INDIVIDUAL_ATTRIBUTES_MODAL',
		INPUT_MODAL = 'INPUT_MODAL',
		INSERT_BLOCKED_KEYWORDS = 'INSERT_BLOCKED_KEYWORDS',
		INVITE_USERS_MODAL = 'INVITE_USERS_MODAL',
		LOADING_MODAL = 'LOADING_MODAL',
		MANAGE_LIFECYCLE_NOTIFICATIONS_MODAL = 'MANAGE_LIFECYCLE_NOTIFICATIONS_MODAL',
		MANAGE_SEGMENT_NOTIFICATIONS_MODAL = 'MANAGE_SEGMENT_NOTIFICATIONS_MODAL',
		MANUALLY_RETRAIN_MODEL_MODAL = 'MANUALLY_RETRAIN_MODEL_MODAL',
		MATCHING_PAGES_MODAL = 'MATCHING_PAGES_MODAL',
		NEW_REQUEST_MODAL = 'NEW_REQUEST_MODAL',
		NEW_RULE_MODAL = 'NEW_RULE_MODAL',
		ONBOARDING_MODAL = 'ONBOARDING_MODAL',
		SEARCHABLE_ENTITIES_TABLE_MODAL = 'SEARCHABLE_ENTITIES_TABLE_MODAL',
		SEARCHABLE_TABLE_MODAL = 'SEARCHABLE_TABLE_MODAL',
		SEARCHABLE_TABLE_MODAL_GRAPHQL = 'SEARCHABLE_TABLE_MODAL_GRAPHQL',
		SELECT_CHANNELS_MODAL = 'SELECT_CHANNELS_MODAL',
		SELECT_ITEMS_MODAL = 'SELECT_ITEMS_MODAL',
		TEST = 'TEST',
		TIME_ZONE_SELECTION_MODAL = 'TIME_ZONE_SELECTION_MODAL',
		UNABLE_DELETE_PROPERTY_MODAL = 'UNABLE_DELETE_PROPERTY_MODAL',
		UNASSIGNED_SEGMENTS_MODAL = 'UNASSIGNED_SEGMENTS_MODAL',
	}

	export type close = () => {type: actionTypes};

	export type open = (
		type: string,
		props?: {[key: string]: any},
		options?: {closeOnBlur?: boolean}
	) => {
		payload: {
			closeOnBlur: boolean;
			props: {[key: string]: any};
			type: string;
		};
		type: actionTypes;
	};
}
