dependencies {
	testIntegrationImplementation project(":apps:asset:asset-link-api")
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-test-util")
	testIntegrationImplementation project(":apps:expando:expando-api")
	testIntegrationImplementation project(":apps:expando:expando-test-util")
	testIntegrationImplementation project(":apps:export-import:export-import-api")
	testIntegrationImplementation project(":apps:export-import:export-import-test-util")
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}