ARG FARO_ENVIRONMENT_NAME=local
ARG LABEL_BUILD_DATE
ARG LABEL_VCS_REF

ENV CATALINA_OPTS="${CATALINA_OPTS} -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true" \
    FARO_ENVIRONMENT_NAME=${FARO_ENVIRONMENT_NAME} \
    LIFERAY_WORKSPACE_ENVIRONMENT=cloud

USER liferay

RUN mkdir -p $LIFERAY_HOME/tomcat/lib/org/apache/catalina/util && \
    echo "server.info=" > $LIFERAY_HOME/tomcat/lib/org/apache/catalina/util/ServerInfo.properties

COPY --chown=liferay:liferay docker/configs/osgi/configs $LIFERAY_HOME/osgi/configs/
COPY --chown=liferay:liferay docker/resources/context.xml $LIFERAY_HOME/tomcat/conf/
COPY --chown=liferay:liferay docker/resources/log4j $LIFERAY_HOME/osgi/log4j/
COPY --chown=liferay:liferay docker/resources/log4j-layout-template-json.jar $LIFERAY_HOME/tomcat/webapps/ROOT/WEB-INF/shielded-container-lib/
COPY --chown=liferay:liferay docker/resources/log_layout.json $LIFERAY_HOME/tomcat/webapps/ROOT/WEB-INF/classes/META-INF/
COPY --chown=liferay:liferay docker/resources/portal-log4j-ext.xml $LIFERAY_HOME/tomcat/webapps/ROOT/WEB-INF/classes/META-INF/
COPY --chown=liferay:liferay docker/resources/rewrite.config $LIFERAY_HOME/tomcat/webapps/ROOT/WEB-INF/
COPY --chown=liferay:liferay docker/resources/system-ext.properties $LIFERAY_HOME/tomcat/webapps/ROOT/WEB-INF/classes/

RUN sed -i '/<!-- APR library loader/i \ <Listener className="org.apache.catalina.security.SecurityListener" checkedOsUsers="root" minimumUmask="0007" \/>\n' $LIFERAY_HOME/tomcat/conf/server.xml && \
    sed -i '/<Connector.*port="8080"/,/\/>/c \<Connector\n acceptorThreadCount="2"\n bindOnInit="false"\n connectionTimeout="20000"\n enableLookups="false"\n encodedSolidusHandling="decode"\n maxHttpHeaderSize="65536"\n maxPostSize="4194304"\n maxThreads="200"\n minSpareThreads="50"\n port="8080"\n protocol="org.apache.coyote.http11.Http11Nio2Protocol"\n server=""\n URIEncoding="UTF-8"\n \/>\n' $LIFERAY_HOME/tomcat/conf/server.xml && \
    sed -i '/<\/Host>/i \ <Valve className="org.apache.catalina.valves.RemoteIpValve" remoteIpHeader="X-Forwarded-For" protocolHeader="X-Forwarded-Proto" \/>' $LIFERAY_HOME/tomcat/conf/server.xml && \
    sed -i 's/<Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" \/>/<Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="off" \/>/' $LIFERAY_HOME/tomcat/conf/server.xml
