task runGradleTest

dependencies {
	providedModules group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.18.6"
	providedModules group: "com.thoughtworks.qdox", name: "qdox"
}

runGradleTest {
	dependsOn initBundle

	doLast {
		File expectedFile = new File(initBundle.destinationDir, "osgi/modules/jackson-annotations-2.18.9.jar")

		assert expectedFile.exists()

		expectedFile = new File(initBundle.destinationDir, "osgi/modules/qdox-1.12.1.jar")

		assert expectedFile.exists()
	}
}