buildService {
	apiDir = "../client-extension-api/src/main/java"
	testDir = "../client-extension-test/src/testIntegration/java"
}

dependencies {
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component", version: "1.4.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:change-tracking:change-tracking-spi")
	compileOnly project(":apps:client-extension:client-extension-api")
	compileOnly project(":apps:client-extension:client-extension-type-api")
	compileOnly project(":apps:portal-vulcan:portal-vulcan-api")
	compileOnly project(":apps:portal:portal-aop-api")
	compileOnly project(":apps:static:portal:portal-upgrade-api")
	compileOnly project(":apps:xstream:xstream-configurator-api")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-reflect")
	compileOnly project(":core:petra:petra-sql-dsl-api")
	compileOnly project(":core:petra:petra-string")
}