dependencies {
	compileInclude group: "com.liferay", name: "com.artofsolving.jodconverter", version: "2.2.2"
	compileInclude group: "org.openoffice", name: "juh", version: "2.3.0"
	compileInclude group: "org.openoffice", name: "jurt", version: "2.3.0"
	compileInclude group: "org.openoffice", name: "ridl", version: "2.3.0"
	compileInclude group: "org.openoffice", name: "unoil", version: "2.3.0"
	compileOnly group: "com.google.code.gson", name: "gson", version: "2.9.0"
	compileOnly group: "com.google.collections", name: "google-collections", version: "1.0"
	compileOnly group: "com.googlecode.jsontoken", name: "jsontoken", version: "1.1"
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "joda-time", name: "joda-time", version: "2.12.1"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:document-library:document-library-api")
	compileOnly project(":apps:document-library:document-library-preview-api")
	compileOnly project(":apps:portal-configuration:portal-configuration-upgrade-api")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
	compileOnly project(":apps:static:portal:portal-upgrade-api")
	compileOnly project(":core:petra:petra-concurrent")
	compileOnly project(":core:petra:petra-executor")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-io")
	compileOnly project(":core:petra:petra-process")
	compileOnly project(":core:petra:petra-string")
	testImplementation group: "commons-io", name: "commons-io", version: "2.15.1"
}