modified.files.includes[relevant][akismet-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][akismet-java-rule]=\
    dxp/apps/akismet/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][akismet-java-rule]=\
    dxp/apps/akismet/**/*Test.java

relevant.rule.names=akismet-java-rule

test.batch.names[relevant][akismet-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Akismet