modified.files.includes[relevant][export-import-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][export-import-java-rule]=\
    **/src/testIntegration/**/exportimport/**/*Test.java,\
    apps/export-import/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][export-import-java-rule]=\
    **/portal-security-ldap-impl/**/LDAPUserImporterImplTest.java,\
    apps/export-import/**/*Test.java

relevant.rule.names=export-import-java-rule

test.batch.names[relevant][export-import-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Export/Import