modified.files.includes[relevant][account-functional-rule]=**

modified.files.includes[relevant][account-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][account-java-rule]=\
    apps/account/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][account-java-rule]=\
    apps/account/**/*Test.java

relevant.rule.names=\
    account-functional-rule,\
    account-java-rule

test.batch.names[relevant][account-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][account-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][account-functional-rule]=\
    (portal.acceptance == true) AND \
    (testray.component.names ~ "Account")

testray.main.component.name=Account