modified.files.includes[relevant][password-policies-admin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][password-policies-admin-web-playwright-rule]=\
    password-policies-admin-web.main

relevant.rule.names=password-policies-admin-web-playwright-rule

test.batch.names[relevant][password-policies-admin-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163