dependencies {
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.apache.pdfbox", name: "pdfbox", version: "3.0.7"
	compileOnly group: "org.apache.pdfbox", name: "pdfbox-io", version: "3.0.7"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:document-library:document-library-api")
	compileOnly project(":apps:document-library:document-library-preview-api")
	compileOnly project(":apps:image:image-api")
	compileOnly project(":core:petra:petra-concurrent")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-process")
	compileOnly project(":core:petra:petra-string")
}