modified.files.includes[relevant][expando-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][expando-java-rule]=\
    apps/expando/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][expando-java-rule]=\
    apps/expando/**/*Test.java

relevant.rule.names=expando-java-rule

test.batch.names[relevant][expando-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Custom Fields