modified.files.includes[relevant][portlet-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portlet-java-rule]=\
    apps/portlet/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portlet-java-rule]=\
    apps/portlet/**/*Test.java

relevant.rule.names=portlet-java-rule

test.batch.names[relevant][portlet-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services