modified.files.includes[relevant][click-to-chat-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][click-to-chat-java-rule]=\
    apps/click-to-chat/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][click-to-chat-java-rule]=\
    apps/click-to-chat/**/*Test.java

relevant.rule.names=click-to-chat-java-rule

test.batch.names[relevant][click-to-chat-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Click to Chat