apiDir: ../portal-tools-rest-builder-test-api/src/main/java
apiPackagePath: com.liferay.portal.tools.rest.builder.test
application:
    baseURI: /test
    className: PortalToolsRESTBuilderTestApplication
    name: Liferay.Portal.Tools.REST.Builder.Test
author: Alejandro Tardín
changeTrackingEnabled: true
clientDir: ../portal-tools-rest-builder-test-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateClientJS: true
generateGraphQL: true
generatePermissions: true
javaEEPackage: jakarta
testDir: ../portal-tools-rest-builder-test-test/src/testIntegration/java