modified.files.includes[relevant][notification-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][notification-web-playwright-rule]=\
    notification-web.main

relevant.rule.names=notification-web-playwright-rule

test.batch.names[relevant][notification-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Notifications Framework