#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.ai.hub.rest.dto.v1_0.Chatbot
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.AI.Hub.REST)
osgi.jaxrs.resource=true