components:
    schemas:
        Autofix:
            properties:
                insightType:
                    type: string
                pageURL:
                    type: string
                value:
                    type: string
            required:
                -   insightType
                -   pageURL
                -   value
            type: object
        CrawlHit:
            properties:
                canonicalUrl:
                    type: string
                links:
                    items:
                        type: string
                    type: array
                title:
                    type: string
                url:
                    type: string
            required:
                -   url
            type: object
        PageContent:
            properties:
                content:
                    type: string
            type: object
info:
    description:
        "Liferay SEO Studio REST API. A Java client JAR is available for use with the group ID 'com.liferay', artifact ID 'com.liferay.seo.studio.rest.client', and version '1.0.0'."
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    title: SEO Studio
    version: v1.0
openapi: 3.0.1
paths:
    "/autofix":
        post:
            operationId: postAutofix
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Autofix"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Autofix"
            responses:
                204: {}
            tags: ["Autofix"]
    "/page-content":
        get:
            operationId: getPageContent
            parameters:
                -   in: query
                    name: pageURL
                    required: true
                    schema:
                        type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PageContent"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/PageContent"
            tags: ["PageContent"]
    "/seo-studio-domains/{seoStudioDomainId}/crawl-hits":
        get:
            operationId: getSeoStudioDomainCrawlHitsPage
            parameters:
                -   in: path
                    name: seoStudioDomainId
                    required: true
                    schema:
                        format: int64
                        type: integer
                -   in: query
                    name: lastURL
                    required: false
                    schema:
                        type: string
                -   in: query
                    name: pageSize
                    required: false
                    schema:
                        default: 500
                        format: int32
                        type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CrawlHit"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/CrawlHit"
                                type: array
            tags: ["CrawlHit"]