export default () => ({
	__typename: 'EventsByUserSession',
	totalEvents: 10,
	userSessions: [
		{
			__typename: 'UserSession',
			becameKnown: false,
			browserName: 'Default Browser',
			completeDate: 'Fri May 08 18:00:15 GMT 2026',
			contentLanguageId: null,
			createDate: 'Fri May 08 17:59:59 GMT 2026',
			devicePixelRatio: '',
			deviceType: 'Unknown',
			events: [
				{
					__typename: 'Event',
					applicationId: 'HubSpot',
					assetTitle: null,
					canonicalUrl: 'https://hubspot.com',
					createDate: 'Fri May 08 18:00:15 GMT 2026',
					eventDate: '2026-05-08T18:00:15.000Z',
					eventId: 'emailView',
					name: 'emailView',
					pageDescription: null,
					pageKeywords: null,
					pageTitle: null,
					properties: [
						{name: 'email', value: 'john.doe@example.com'},
						{name: 'subject', value: 'Welcome Newsletter'},
					],
					referrer: 'https://hubspot.com',
					url: 'https://hubspot.com',
				},
				{
					__typename: 'Event',
					applicationId: 'HubSpot',
					assetTitle: null,
					canonicalUrl: 'https://hubspot.com',
					createDate: 'Fri May 08 17:59:59 GMT 2026',
					eventDate: '2026-05-08T17:59:59.000Z',
					eventId: 'formSubmit',
					name: 'formSubmit',
					pageDescription: null,
					pageKeywords: null,
					pageTitle: null,
					properties: [
						{name: 'formId', value: 'abc123'},
						{
							name: 'pageUrl',
							value: 'https://hubspot.com/landing-page',
						},
					],
					referrer: 'https://hubspot.com',
					url: 'https://hubspot.com',
				},
			],
			languageId: null,
			screenHeight: '',
			screenWidth: '',
			timezoneOffset: null,
			userAgent: 'HubSpot Webhook',
		},
		{
			__typename: 'UserSession',
			becameKnown: true,
			browserName: 'Chrome Mobile',
			completeDate: 'Thu May 07 20:15:10 GMT 2026',
			contentLanguageId: 'en-US',
			createDate: 'Thu May 07 20:10:05 GMT 2026',
			devicePixelRatio: '3',
			deviceType: 'Smartphone',
			events: [
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle: 'Home - learn-dev.lxc.liferay.com',
					canonicalUrl: 'https://learn-dev.liferay.com/home',
					createDate: 'Thu May 07 20:15:05 GMT 2026',
					eventDate: '2026-05-07T20:15:05.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle: 'Home - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer: '',
					url: 'https://learn-dev.liferay.com/home',
				},
			],
			languageId: 'en-US',
			screenHeight: '844',
			screenWidth: '390',
			timezoneOffset: '-03:00',
			userAgent:
				'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/121.0.0.0 Mobile/15E148 Safari/604.1',
		},
		{
			__typename: 'UserSession',
			becameKnown: false,
			browserName: 'Chrome',
			completeDate: 'Thu May 07 19:57:32 GMT 2026',
			contentLanguageId: 'en-US',
			createDate: 'Thu May 07 19:37:32 GMT 2026',
			devicePixelRatio: '1.5',
			deviceType: 'Desktop',
			events: [
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle:
						'Content Management System - learn-dev.lxc.liferay.com',
					canonicalUrl:
						'https://learn-dev.liferay.com/capabilities/content-management-system',
					createDate: 'Thu May 07 19:57:21 GMT 2026',
					eventDate: '2026-05-07T19:57:21.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle:
						'Content Management System - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer: 'https://learn-dev.liferay.com/home',
					url: 'https://learn-dev.liferay.com/capabilities/content-management-system',
				},
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle: 'Home - learn-dev.lxc.liferay.com',
					canonicalUrl: 'https://learn-dev.liferay.com/home',
					createDate: 'Thu May 07 19:56:55 GMT 2026',
					eventDate: '2026-05-07T19:56:55.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle: 'Home - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer: 'https://learn-dev.liferay.com/c/portal/logout',
					url: 'https://learn-dev.liferay.com/home',
				},
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle: 'Home - learn-dev.lxc.liferay.com',
					canonicalUrl: 'https://learn-dev.liferay.com',
					createDate: 'Thu May 07 19:56:21 GMT 2026',
					eventDate: '2026-05-07T19:56:21.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle: 'Home - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer: '',
					url: 'https://learn-dev.liferay.com/',
				},
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle: 'Home - learn-dev.lxc.liferay.com',
					canonicalUrl: 'https://learn-dev.liferay.com',
					createDate: 'Thu May 07 19:38:43 GMT 2026',
					eventDate: '2026-05-07T19:38:43.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle: 'Home - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer:
						'https://learn-dev.liferay.com/capabilities/security',
					url: 'https://learn-dev.liferay.com/',
				},
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle: 'Security - learn-dev.lxc.liferay.com',
					canonicalUrl:
						'https://learn-dev.liferay.com/capabilities/security',
					createDate: 'Thu May 07 19:38:36 GMT 2026',
					eventDate: '2026-05-07T19:38:36.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle: 'Security - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer: 'https://learn-dev.liferay.com/',
					url: 'https://learn-dev.liferay.com/capabilities/security',
				},
				{
					__typename: 'Event',
					applicationId: 'Page',
					assetTitle: 'Home - learn-dev.lxc.liferay.com',
					canonicalUrl: 'https://learn-dev.liferay.com',
					createDate: 'Thu May 07 19:37:43 GMT 2026',
					eventDate: '2026-05-07T19:37:43.000Z',
					eventId: 'pageViewed',
					name: 'pageViewed',
					pageDescription: '',
					pageKeywords: '',
					pageTitle: 'Home - learn-dev.lxc.liferay.com',
					properties: [
						{
							name: 'externalReferenceCode',
							value: '2d420977-ed76-97d2-4478-379f03130595',
						},
					],
					referrer:
						'https://learn-dev.liferay.com/group/control_panel/manage?p_p_id=com_liferay_configuration_admin_web_portlet_InstanceSettingsPortlet&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_com_liferay_configuration_admin_web_portlet_InstanceSettingsPortlet_mvcRenderCommandName=%2Fconfiguration_admin%2Fview_configuration_screen&_com_liferay_configuration_admin_web_portlet_InstanceSettingsPortlet_configurationScreenKey=analytics-cloud-connection',
					url: 'https://learn-dev.liferay.com/',
				},
			],
			languageId: 'en-US',
			screenHeight: '1321',
			screenWidth: '2560',
			timezoneOffset: '-03:00',
			userAgent:
				'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36',
		},
		{
			__typename: 'UserSession',
			becameKnown: false,
			browserName: 'Default Browser',
			completeDate: 'Thu May 07 21:15:44 GMT 2026',
			contentLanguageId: null,
			createDate: 'Thu May 07 21:15:44 GMT 2026',
			devicePixelRatio: '',
			deviceType: 'Unknown',
			events: [
				{
					__typename: 'Event',
					applicationId: 'HubSpot',
					assetTitle: null,
					canonicalUrl: 'https://hubspot.com',
					createDate: 'Thu May 07 21:15:44 GMT 2026',
					eventDate: '2026-05-07T21:15:44.000Z',
					eventId: 'emailOpen',
					name: 'emailOpen',
					pageDescription: null,
					pageKeywords: null,
					pageTitle: null,
					properties: [
						{name: 'email', value: 'john.doe@example.com'},
						{name: 'subject', value: 'May Product Updates'},
					],
					referrer: 'https://hubspot.com',
					url: 'https://hubspot.com',
				},
				{
					__typename: 'Event',
					applicationId: 'HubSpot',
					assetTitle: null,
					canonicalUrl: 'https://hubspot.com',
					createDate: 'Thu May 07 21:15:44 GMT 2026',
					eventDate: '2026-05-07T21:15:44.000Z',
					eventId: 'linkClick',
					name: 'linkClick',
					pageDescription: null,
					pageKeywords: null,
					pageTitle: null,
					properties: [
						{
							name: 'linkUrl',
							value: 'https://liferay.com/products',
						},
						{name: 'email', value: 'john.doe@example.com'},
					],
					referrer: 'https://hubspot.com',
					url: 'https://hubspot.com',
				},
			],
			languageId: null,
			screenHeight: '',
			screenWidth: '',
			timezoneOffset: null,
			userAgent: 'HubSpot Webhook',
		},
	],
});
