modified.files.includes[relevant][knowledge-base-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][knowledge-base-java-rule]=\
    apps/knowledge-base/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][knowledge-base-java-rule]=\
    apps/knowledge-base/**/*Test.java

relevant.rule.names=knowledge-base-java-rule

test.batch.names[relevant][knowledge-base-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Knowledge Base