modified.files.includes[relevant][analytics-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][analytics-web-playwright-rule]=\
    analytics-web.main

relevant.rule.names=analytics-web-playwright-rule

test.batch.names[relevant][analytics-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57