modified.files.includes[relevant][sharing-web-functional-rule]=**
relevant.rule.names=sharing-web-functional-rule

test.batch.names[relevant][sharing-web-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][sharing-web-functional-rule]=\
    (testray.component.names == "Asset Sharing") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Asset Sharing