modified.files.includes[relevant][invitation-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][invitation-java-rule]=\
    apps/invitation/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][invitation-java-rule]=\
    apps/invitation/**/*Test.java

relevant.rule.names=invitation-java-rule

test.batch.names[relevant][invitation-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Invite Members