com.liferay:org.glassfish.jaxb.runtime:2.3.1.LIFERAY-PATCHED-2=org.glassfish.jaxb:jaxb-runtime:4.0.5
com.sun.mail:jakarta.mail:1.6.6=jakarta.mail:jakarta.mail-api:2.1.3
javax.activation:activation:1.1=jakarta.activation:jakarta.activation-api:2.1.3
javax.persistence:javax.persistence-api:2.2=jakarta.persistence:jakarta.persistence-api:3.1.0
javax.portlet:portlet-api:3.0.1=com.liferay:javax.portlet:3.0.1.JAKARTA_LIFERAY-PATCHED-1
javax.servlet.jsp:javax.servlet.jsp-api:2.3.1=jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1
javax.transaction:javax.transaction-api:1.3=jakarta.transaction:jakarta.transaction-api:2.0.1
javax.validation:validation-api:2.0.1.Final=jakarta.validation:jakarta.validation-api:3.1.0
javax.ws.rs:javax.ws.rs-api:2.1=jakarta.ws.rs:jakarta.ws.rs-api:3.1.0
javax.xml.bind:jaxb-api:2.3.0=jakarta.xml.bind:jakarta.xml.bind-api:4.0.2
javax.xml.ws:jaxws-api:2.3.1=jakarta.xml.ws:jakarta.xml.ws-api:4.0.2
org.apache.felix:org.apache.felix.http.servlet-api:1.1.2=jakarta.servlet:jakarta.servlet-api:6.0.0
org.apache.geronimo.specs:geronimo-annotation_1.3_spec:1.1=jakarta.annotation:jakarta.annotation-api:2.1.1
org.apache.geronimo.specs:geronimo-atinject_1.0_spec:1.1=jakarta.inject:jakarta.inject-api:2.0.1
org.apache.geronimo.specs:geronimo-interceptor_1.2_spec:1.1=jakarta.interceptor:jakarta.interceptor-api:2.2.0
org.apache.geronimo.specs:geronimo-jaxrs_2.1_spec:1.1=jakarta.ws.rs:jakarta.ws.rs-api:3.1.0
org.apache.geronimo.specs:geronimo-jcdi_2.0_spec:1.3=jakarta.enterprise:jakarta.enterprise.cdi-api:4.1.0
org.apache.geronimo.specs:geronimo-json_1.1_spec:1.5=jakarta.json:jakarta.json-api:2.1.3
org.apache.geronimo.specs:geronimo-jsonb_1.0_spec:1.4=jakarta.json.bind:jakarta.json.bind-api:3.0.0
org.apache.johnzon:johnzon-core:1.2.21=org.apache.johnzon:johnzon-core:2.0.1
org.apache.johnzon:johnzon-jsonb:1.2.21=org.apache.johnzon:johnzon-jsonb:2.0.1
org.apache.johnzon:johnzon-mapper:1.2.21=org.apache.johnzon:johnzon-mapper:2.0.1
org.apache.tomcat:tomcat-annotations-api:9.0.97=org.apache.tomcat:tomcat-annotations-api:10.1.33
org.apache.tomcat:tomcat-api:9.0.97=org.apache.tomcat:tomcat-api:10.1.33
org.apache.tomcat:tomcat-coyote:9.0.97=org.apache.tomcat:tomcat-coyote:10.1.33
org.apache.tomcat:tomcat-el-api:9.0.97=org.apache.tomcat:tomcat-el-api:10.1.33
org.apache.tomcat:tomcat-jasper-el:9.0.97=org.apache.tomcat:tomcat-jasper-el:10.1.33
org.apache.tomcat:tomcat-jasper:9.0.97=org.apache.tomcat:tomcat-jasper:10.1.33
org.apache.tomcat:tomcat-jsp-api:9.0.97=org.apache.tomcat:tomcat-jsp-api:10.1.33
org.apache.tomcat:tomcat-juli:9.0.97=org.apache.tomcat:tomcat-juli:10.1.33
org.apache.tomcat:tomcat-servlet-api:9.0.97=org.apache.tomcat:tomcat-servlet-api:10.1.33
org.apache.tomcat:tomcat-tribes:9.0.97=org.apache.tomcat:tomcat-tribes:10.1.33
org.apache.tomcat:tomcat-util-scan:9.0.97=org.apache.tomcat:tomcat-util-scan:10.1.33
org.apache.tomcat:tomcat-util:9.0.97=org.apache.tomcat:tomcat-util:10.1.33
org.apache.tomcat:tomcat-websocket-api:9.0.97=org.apache.tomcat:tomcat-websocket-api:10.1.33