modified.files.includes[relevant][digital-signature-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][digital-signature-java-rule]=\
    apps/digital-signature/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-signature-java-rule]=\
    apps/digital-signature/**/*Test.java

relevant.rule.names=digital-signature-java-rule

test.batch.names[relevant][digital-signature-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Digital Signature