modified.files.includes[relevant][xstream-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][xstream-java-rule]=\
    apps/xstream/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][xstream-java-rule]=\
    apps/xstream/**/*Test.java

relevant.rule.names=xstream-java-rule

test.batch.names[relevant][xstream-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services