#
# Application
#

liferay.seo.studio.crawler.elasticsearch.host=
liferay.seo.studio.crawler.elasticsearch.pipeline=
liferay.seo.studio.crawler.elasticsearch.port=
liferay.seo.studio.crawler.max.crawl.depth=1
liferay.seo.studio.crawler.max.duration=30
liferay.seo.studio.crawler.url.queue.size.limit=50000

#
# LXC
#

com.liferay.lxc.dxp.domains=localhost:8080
com.liferay.lxc.dxp.mainDomain=localhost:8080
com.liferay.lxc.dxp.server.protocol=http

#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-seostudio-crawler-oaua
liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081