modified.files.includes[relevant][marketplace-app-manager-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][marketplace-app-manager-web-playwright-rule]=\
    marketplace-app-manager-web.main

relevant.rule.names=marketplace-app-manager-web-playwright-rule

test.batch.names[relevant][marketplace-app-manager-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=App Management