apiDir: ../headless-admin-taxonomy-api/src/main/java
apiPackagePath: com.liferay.headless.admin.taxonomy
application:
    baseURI: /headless-admin-taxonomy
    className: HeadlessAdminTaxonomyApplication
    name: Liferay.Headless.Admin.Taxonomy
author: Javier Gamarra
clientDir: ../headless-admin-taxonomy-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateActionProviders: true
generatePermissions: true
javaEEPackage: jakarta
testDir: ../headless-admin-taxonomy-test/src/testIntegration/java