modified.files.includes[relevant][asset-publisher-web-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][asset-publisher-web-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][asset-publisher-web-java-rule]=\
    **/asset-publisher-test/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-publisher-web-java-rule]=\
    **/asset-publisher-test/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][asset-publisher-web-playwright-rule]=\
    asset-publisher-web.main

relevant.rule.names=\
    asset-publisher-web-java-rule,\
    asset-publisher-web-playwright-rule

test.batch.names[relevant][asset-publisher-web-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][asset-publisher-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Asset Publisher Widget