apiDir: ../analytics-reports-rest-api/src/main/java
apiPackagePath: com.liferay.analytics.reports.rest
application:
    baseURI: /analytics-reports-rest
    className: AnalyticsReportsRESTApplication
    name: Liferay.Analytics.Reports.REST
author: Marcos Martins
clientDir: ../analytics-reports-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateBatch: false
javaEEPackage: jakarta
testDir: ../analytics-reports-rest-test/src/testIntegration/java