modified.files.includes[relevant][my-subscriptions-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][my-subscriptions-java-rule]=\
    apps/my-subcriptions/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][my-subscriptions-java-rule]=\
    apps/my-subcriptions/**/*Test.java

relevant.rule.names=my-subscriptions-java-rule

test.batch.names[relevant][my-subscriptions-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=My Subscriptions Widget