modified.files.includes[relevant][fragment-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][fragment-web-playwright-rule]=\
    fragment-web.main

relevant.rule.names=fragment-web-playwright-rule

test.batch.names[relevant][fragment-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Fragment Administration