dependencies {
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.18.6"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.18.6"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.18.6"

	compileInclude(group: "com.github.javafaker", name: "javafaker", version: "1.0.2") {
		exclude group: "org.yaml", module: "snakeyaml"
	}

	compileInclude group: "commons-codec", name: "commons-codec", version: "1.15"
	compileInclude group: "user-agent-utils", name: "user-agent-utils", version: "1.2.3"
	compileOnly group: "com.liferay.portal", name: "release.dxp.api", version: "2026.q1.5"
	compileOnly project(":modules:osb-faro-api")
	compileOnly project(":modules:osb-faro-contacts-api")
	compileOnly project(":modules:osb-faro-engine-client")
	compileOnly project(":modules:osb-faro-provisioning-client")
}