modified.files.includes[relevant][frontend-css-cadmin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][frontend-css-cadmin-web-playwright-rule]=\
    frontend-css-cadmin-web.main

relevant.rule.names=frontend-css-cadmin-web-playwright-rule

test.batch.names[relevant][frontend-css-cadmin-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Liferay Themes