modified.files.includes[relevant][rss-functional-rule]=**

modified.files.includes[relevant][rss-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][rss-java-rule]=\
    apps/asset/**/src/testIntegration/**/*Test.java,\
    apps/rss/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][rss-java-rule]=\
    apps/asset/**/src/test/**/*Test.java,\
    apps/rss/**/src/test/**/*Test.java

relevant.rule.names=\
    rss-functional-rule,\
    rss-java-rule

test.batch.names[relevant][rss-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][rss-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][rss-functional-rule]=\
    (portal.acceptance == true)

testray.main.component.name=RSS Publisher Widget