modified.files.includes[relevant][analytics-settings-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][analytics-settings-web-playwright-rule]=\
    analytics-settings-web.main

relevant.rule.names=analytics-settings-web-playwright-rule

test.batch.names[relevant][analytics-settings-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57