modified.files.includes[relevant][site-navigation-menu-web-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][site-navigation-menu-web-rule]=\
    site-navigation-menu-web.main

relevant.rule.names=site-navigation-menu-web-rule

test.batch.names[relevant][site-navigation-menu-web-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Navigation Menus