modified.files.includes[relevant][calendar-functional-rule]=**

modified.files.includes[relevant][calendar-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][calendar-java-rule]=\
    apps/calendar/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][calendar-java-rule]=\
    apps/calendar/**/*Test.java

relevant.rule.names=\
    calendar-functional-rule,\
    calendar-java-rule

test.batch.names[relevant][calendar-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][calendar-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade-tomcat*-mysql*][relevant][calendar-functional-rule]=\
    (testray.main.component.name == "Upgrades Calendar")

testray.main.component.name=Calendar