#
# This is a generated file.
#

api.version=v2.0
entity.class.name=com.liferay.search.experiences.rest.dto.v2_0.SearchResponse
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Search.Experiences.REST)
osgi.jaxrs.resource=true