#
# This is a generated file.
#

api.version=v2.0
batch.engine.entity.class.name=com.liferay.search.experiences.rest.dto.v2_0.SXPParameterContributorDefinition
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=false
entity.class.name=com.liferay.search.experiences.rest.dto.v2_0.SXPParameterContributorDefinition
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Search.Experiences.REST)
osgi.jaxrs.resource=true