sourceCompatibility = "1.8"
targetCompatibility = "1.8"

String elasticsearchVersion = "6.1.3"
String luceneVersion = "7.1.0"

configurations {
	elasticsearchPlugins {
		transitive = false
	}
}

dependencies {
	compileInclude group: "com.carrotsearch", name: "hppc", version: "0.7.1"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.8.10"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-cbor", version: "2.8.10"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-smile", version: "2.8.10"
	compileInclude group: "com.fasterxml.jackson.dataformat", name: "jackson-dataformat-yaml", version: "2.8.10"
	compileInclude group: "com.liferay", name: "org.elasticsearch.client.xpack.transport", version: elasticsearchVersion
	compileInclude group: "com.liferay", name: "org.elasticsearch.plugin.cli", version: elasticsearchVersion
	compileInclude group: "com.liferay", name: "org.elasticsearch.plugin.xpack.api", version: elasticsearchVersion
	compileInclude group: "com.tdunning", name: "t-digest", version: "3.0"
	compileInclude group: "com.twitter", name: "jsr166e", version: "1.1.0"
	compileInclude group: "com.unboundid", name: "unboundid-ldapsdk", version: "4.0.2"
	compileInclude group: "com.vividsolutions", name: "jts", version: "1.13"
	compileInclude group: "commons-io", name: "commons-io", version: "2.6"
	compileInclude group: "commons-lang", name: "commons-lang", version: "2.6"
	compileInclude group: "io.netty", name: "netty-all", version: "4.1.11.Final"
	compileInclude group: "joda-time", name: "joda-time", version: "2.9.5"
	compileInclude group: "net.sf.jopt-simple", name: "jopt-simple", version: "5.0.2"
	compileInclude group: "net.sf.supercsv", name: "super-csv", version: "2.1.0"
	compileInclude group: "org.antlr", name: "antlr-runtime", version: "3.5"
	compileInclude group: "org.apache.httpcomponents", name: "httpasyncclient", version: "4.1.3"
	compileInclude group: "org.apache.httpcomponents", name: "httpclient", version: "4.4"
	compileInclude group: "org.apache.logging.log4j", name: "log4j-api", version: "2.7"
	compileInclude group: "org.apache.logging.log4j", name: "log4j-core", version: "2.7"
	compileInclude group: "org.apache.lucene", name: "lucene-analyzers-common", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-core", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-grouping", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-highlighter", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-join", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-memory", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-misc", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-queries", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-queryparser", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-sandbox", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-spatial", version: luceneVersion
	compileInclude group: "org.apache.lucene", name: "lucene-suggest", version: luceneVersion
	compileInclude group: "org.bouncycastle", name: "bcpkix-jdk15on", version: "1.49"
	compileInclude group: "org.bouncycastle", name: "bcprov-jdk15on", version: "1.49"
	compileInclude group: "org.elasticsearch", name: "elasticsearch", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch", name: "elasticsearch-cli", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch.client", name: "sniffer", version: "5.5.3"
	compileInclude group: "org.elasticsearch.client", name: "transport", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch.plugin", name: "lang-mustache-client", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch.plugin", name: "parent-join-client", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch.plugin", name: "percolator-client", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch.plugin", name: "reindex-client", version: elasticsearchVersion
	compileInclude group: "org.elasticsearch.plugin", name: "transport-netty4-client", version: elasticsearchVersion
	compileInclude group: "org.hdrhistogram", name: "HdrHistogram", version: "2.1.9"
	compileInclude group: "org.locationtech.spatial4j", name: "spatial4j", version: "0.6"
	compileInclude group: "org.yaml", name: "snakeyaml", version: "1.17"

	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.1.0"
	compileOnly group: "com.ibm.icu", name: "icu4j", version: "54.1.1"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.search.api", version: "1.1.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.search.elasticsearch6.api", version: "1.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.49.0"
	compileOnly group: "commons-collections", name: "commons-collections", version: "3.1"
	compileOnly group: "org.osgi", name: "org.osgi.core", version: "5.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"

	elasticsearchPlugins ext: "zip", group: "com.liferay", name: "org.elasticsearch.plugin.analysis.icu", version: elasticsearchVersion
	elasticsearchPlugins ext: "zip", group: "com.liferay", name: "org.elasticsearch.plugin.analysis.kuromoji", version: elasticsearchVersion
	elasticsearchPlugins ext: "zip", group: "com.liferay", name: "org.elasticsearch.plugin.analysis.smartcn", version: elasticsearchVersion
	elasticsearchPlugins ext: "zip", group: "com.liferay", name: "org.elasticsearch.plugin.analysis.stempel", version: elasticsearchVersion

	testCompile group: "ch.qos.reload4j", name: "reload4j", version: "1.2.26"
	testCompile group: "com.liferay", name: "com.liferay.petra.concurrent", version: "1.0.0"
	testCompile group: "com.liferay", name: "com.liferay.petra.lang", version: "1.0.0"
	testCompile group: "com.liferay", name: "com.liferay.petra.memory", version: "1.0.0"
	testCompile group: "com.liferay", name: "com.liferay.petra.reflect", version: "1.1.0"
	testCompile group: "com.liferay.portal", name: "com.liferay.util.java", version: "2.0.0"
	testCompile(group: "easyconf", name: "easyconf", version: "0.9.5") {
		exclude group: "log4j", module: "log4j"
	}
	testCompile group: "javax.servlet", name: "javax.servlet-api", version: "3.0.1"
	testCompile group: "net.java.dev.jna", name: "jna", version: "4.1.0"
	testCompile group: "org.apache.tika", name: "tika-core", version: "1.14"
	testCompile group: "org.jabsorb", name: "jabsorb", version: "1.3.1"
	testCompile group: "org.jodd", name: "jodd-bean", version: "3.6.4"
	testCompile group: "org.jodd", name: "jodd-json", version: "3.6.4"
	testCompile group: "org.slf4j", name: "slf4j-api", version: "1.7.22"
	testCompile project(":apps:foundation:portal-search:portal-search")
	testCompile project(":apps:foundation:portal-search:portal-search-test-util")
}

processResources {
	into("plugins") {
		from configurations.elasticsearchPlugins
	}
}
