apiDir: ../headless-admin-content-api/src/main/java
apiPackagePath: com.liferay.headless.admin.content
application:
    baseURI: /headless-admin-content
    className: HeadlessAdminContentApplication
    name: Liferay.Headless.Admin.Content
author: Javier Gamarra
changeTrackingEnabled: true
clientDir: ../headless-admin-content-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateBatch: false
graphQLNamespace: admin
javaEEPackage: jakarta
testDir: ../headless-admin-content-test/src/testIntegration/java