modified.files.includes[relevant][portal-search-elasticsearch7-functional-rule]=**

modified.files.includes[relevant][portal-search-elasticsearch7-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-search-elasticsearch7-java-rule]=\
    apps/portal-search-elasticsearch7/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-search-elasticsearch7-java-rule]=\
    apps/portal-search-elasticsearch7/**/*Test.java

relevant.rule.names=\
    portal-search-elasticsearch7-functional-rule,\
    portal-search-elasticsearch7-java-rule

test.batch.names[relevant][portal-search-elasticsearch7-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][portal-search-elasticsearch7-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade-tomcat*-mysql*][relevant][portal-search-elasticsearch7-functional-rule]=\
    (portal.suite.search.engine ~ "elasticsearch7") AND \
    (testray.main.component.name ~ "Upgrades Search")

testray.main.component.name=Search Infrastructure > Elasticsearch Connector