create table SXPBlueprint (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	sxpBlueprintId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	collectionProvider BOOLEAN,
	compatibility INTEGER,
	configurationJSON TEXT null,
	description STRING null,
	elementInstancesJSON TEXT null,
	fallbackDescription VARCHAR(75) null,
	fallbackTitle VARCHAR(75) null,
	schemaVersion VARCHAR(75) null,
	title STRING null,
	version VARCHAR(75) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table SXPElement (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	sxpElementId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	compatibility INTEGER,
	description STRING null,
	elementDefinitionJSON TEXT null,
	fallbackDescription STRING null,
	fallbackTitle VARCHAR(500) null,
	hidden_ BOOLEAN,
	readOnly BOOLEAN,
	schemaVersion VARCHAR(75) null,
	title STRING null,
	type_ INTEGER,
	version VARCHAR(75) null
);