modified.files.includes[relevant][list-type-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][list-type-java-rule]=\
    apps/list-type/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][list-type-java-rule]=\
    apps/list-type/**/*Test.java

relevant.rule.names=list-type-java-rule

test.batch.names[relevant][list-type-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Object