modified.files.includes[relevant][analytics-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][analytics-java-rule]=\
    apps/analytics/**/*Test.java,\
    apps/segments/**/*Test.java,\
    dxp/apps/analytics/**/*Test.java,\
    dxp/apps/segments/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][analytics-java-rule]=\
    apps/analytics/**/*Test.java,\
    apps/segments/**/*Test.java,\
    dxp/apps/analytics/**/*Test.java,\
    dxp/apps/segments/**/*Test.java

relevant.rule.names=analytics-java-rule

test.batch.names[relevant][analytics-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Analytics Cloud