modified.files.includes[relevant][announcements-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][announcements-web-playwright-rule]=\
    announcements-web.main

relevant.rule.names=announcements-web-playwright-rule

test.batch.names[relevant][announcements-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Announcements