modified.files.includes[relevant][headless-admin-site-functional-rule]=**

modified.files.includes[relevant][headless-admin-site-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][headless-admin-site-java-rule]=\
    apps/headless/headless-admin-site/**/*Test.java

relevant.rule.names=headless-admin-site-java-rule

test.batch.names[relevant][headless-admin-site-java-rule]=\
    modules-integration-postgresql163

testray.main.component.name=Page Administration