##
## Test Suites
##

    modified.files.includes[relevant][client-extension-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    modified.files.includes[relevant][client-extension-playwright-rule]=**

    relevant.rule.names=\
        client-extension-java-rule,\
        client-extension-playwright-rule

    test.batch.names[relevant][client-extension-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    test.batch.names[relevant][client-extension-playwright-rule]=\
        playwright-js-tomcat101-mysql57

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][client-extension-java-rule]=\
        apps/client-extension/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][client-extension-java-rule]=\
        apps/client-extension/**/*Test.java

    playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][client-extension-playwright-rule]=\
        client-extension-web

##
## Testray
##

    testray.main.component.name=Frontend Client Extensions