modified.files.includes[relevant][site-navigation-language-web-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][site-navigation-language-web-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][site-navigation-language-web-java-rule]=\
    apps/site-navigation/site-navigation-language/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][site-navigation-language-web-java-rule]=\
    apps/site-navigation/site-navigation-language/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][site-navigation-language-web-playwright-rule]=\
    site-navigation-language-web.main

relevant.rule.names=\
    site-navigation-language-web-java-rule,\
    site-navigation-language-web-playwright-rule

test.batch.names[relevant][site-navigation-language-web-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][site-navigation-language-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Language Widget