modified.files.includes[relevant][product-analytics-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][product-analytics-web-playwright-rule]=\
    product-analytics-web.main

relevant.rule.names=product-analytics-web-playwright-rule

test.batch.names[relevant][product-analytics-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57