{{- if .Values.network.gke.enabled }}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
    labels:
        app: {{ include "liferay.name" . }}
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
spec:
    default:
        timeoutSec: {{ .Values.network.gke.backendConfig.timeoutSec }}
    targetRef:
        group: ""
        kind: Service
        name: {{ include "liferay.name" . }}
{{- end }}