apiVersion: licensing.liferay.com/v1alpha1
kind: LiferayEnvironment
metadata:
    labels:
        app: {{ include "liferay.name" . }}
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
spec:
    activationCodeSecretRef:
        key: {{ .Values.license.activationCodeSecretKey }}
        name: {{ .Values.license.activationCodeSecretName | default (printf "%s-activation" (include "liferay.name" .)) }}
    {{- if not .Values.autoscaling.enabled }}
    desiredReplicas: {{ .Values.replicaCount }}
    {{- end }}
    marketplaceVolume:
        enabled: {{ .Values.marketplace.enabled }}
        size: {{ .Values.marketplace.size }}
        storageClassName: {{ .Values.marketplace.storageClassName | quote }}
    workloadRef:
        name: {{ include "liferay.name" . }}