{{- $liferayServiceAccount := .Values.global.liferayServiceAccount -}}
{{- if $liferayServiceAccount.role.rules -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    {{- with $liferayServiceAccount.role.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
rules:
    {{- toYaml $liferayServiceAccount.role.rules | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.name" . }}
    namespace: {{ include "liferay.namespace" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "liferay.name" . }}
subjects:
    -   kind: ServiceAccount
        name: {{ include "liferay.serviceAccountName" . }}
        namespace: {{ include "liferay.namespace" . }}
{{- end }}
{{- if $liferayServiceAccount.create }}
---
apiVersion: v1
automountServiceAccountToken: {{ $liferayServiceAccount.automount }}
kind: ServiceAccount
metadata:
    {{- with $liferayServiceAccount.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.serviceAccountName" . }}
    namespace: {{ include "liferay.namespace" . }}
{{- end }}