/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.faro.provisioning.client.constants;

import com.liferay.portal.kernel.util.HashMapBuilder;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * @author Matthew Kong
 */
public class ProductConstants {

	public static final int OSB_OFFERING_ENTRY_STATUS_ACTIVE = 1;

	public static final String PRODUCT_ENTRY_ID_BASIC = "KOR-36421";

	public static final String PRODUCT_ENTRY_ID_BUSINESS = "KOR-36425";

	public static final String PRODUCT_ENTRY_ID_BUSINESS_CONTACTS = "KOR-36431";

	public static final String PRODUCT_ENTRY_ID_BUSINESS_TRACKED_PAGES =
		"KOR-36434";

	public static final String PRODUCT_ENTRY_ID_DATA_PLATFORM = "KOR-17691626";

	public static final String PRODUCT_ENTRY_ID_DATA_PLATFORM_ENTERPRISE =
		"KOR-17350391";

	public static final String PRODUCT_ENTRY_ID_DATA_PLATFORM_PRIVATE_BETA =
		"KOR-17035332";

	public static final String PRODUCT_ENTRY_ID_DIGITAL_SALES_ROOM =
		"KOR-17676139";

	public static final String PRODUCT_ENTRY_ID_ENTERPRISE = "KOR-36428";

	public static final String PRODUCT_ENTRY_ID_ENTERPRISE_CONTACTS =
		"KOR-36437";

	public static final String PRODUCT_ENTRY_ID_ENTERPRISE_TRACKED_PAGES =
		"KOR-36440";

	public static final String PRODUCT_ENTRY_ID_LXC_BUSINESS = "KOR-6218594";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS =
		"KOR-4891509";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS_EXTRA_USER =
		"KOR-4891653";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS =
		"KOR-4891533";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS_EXTRA_USER =
		"KOR-4891677";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS =
		"KOR-4891557";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS_EXTRA_USER =
		"KOR-4891701";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS =
		"KOR-4891581";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS_EXTRA_USER =
		"KOR-4891725";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_100_USERS =
		"KOR-4891461";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_100_USERS_EXTRA_USER =
		"KOR-4891605";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_500_USERS =
		"KOR-4891485";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_500_USERS_EXTRA_USER =
		"KOR-4891629";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM = "KOR-4891749";

	public static final String PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM_EXTRA_USER =
		"KOR-4891773";

	public static final String PRODUCT_ENTRY_ID_LXC_ENTERPRISE = "KOR-6218822";

	public static final String PRODUCT_ENTRY_ID_LXC_PRO = "KOR-6218566";

	public static final String PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_ENGAGE_SITE =
		"KOR-4891133";

	public static final String PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_SUPPORT_SITE =
		"KOR-4891161";

	public static final String PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_TRANSACT_SITE =
		"KOR-4891189";

	public static final String PRODUCT_ENTRY_NAME_BASIC =
		"Liferay Analytics Cloud Basic";

	public static final String PRODUCT_ENTRY_NAME_BUSINESS =
		"Liferay Analytics Cloud Business";

	public static final String PRODUCT_ENTRY_NAME_BUSINESS_CONTACTS =
		"Liferay Analytics Cloud Business Contacts";

	public static final String PRODUCT_ENTRY_NAME_BUSINESS_TRACKED_PAGES =
		"Liferay Analytics Cloud Business Tracked Pages";

	public static final String PRODUCT_ENTRY_NAME_DATA_PLATFORM =
		"Liferay Data Platform";

	public static final String PRODUCT_ENTRY_NAME_DATA_PLATFORM_ENTERPRISE =
		"Liferay Data Platform Enterprise";

	public static final String PRODUCT_ENTRY_NAME_DATA_PLATFORM_PRIVATE_BETA =
		"Liferay Data Platform (Private Beta)";

	public static final String PRODUCT_ENTRY_NAME_DIGITAL_SALES_ROOM =
		"Liferay Digital Sales Room";

	public static final String PRODUCT_ENTRY_NAME_ENTERPRISE =
		"Liferay Analytics Cloud Enterprise";

	public static final String PRODUCT_ENTRY_NAME_ENTERPRISE_CONTACTS =
		"Liferay Analytics Cloud Enterprise Contacts";

	public static final String PRODUCT_ENTRY_NAME_ENTERPRISE_TRACKED_PAGES =
		"Liferay Analytics Cloud Enterprise Tracked Pages";

	public static final String PRODUCT_ENTRY_NAME_LXC_BUSINESS =
		"Liferay SaaS - Business Plan";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_1K_USERS =
		"Liferay SaaS - CSP - Up to 1K Users";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_1K_USERS_EXTRA_USER =
		"Liferay SaaS - CSP - Up to 1K Users - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_5K_USERS =
		"Liferay SaaS - CSP - Up to 5K Users";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_5K_USERS_EXTRA_USER =
		"Liferay SaaS - CSP - Up to 5K Users - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_10K_USERS =
		"Liferay SaaS - CSP - Up to 10K Users";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_10K_USERS_EXTRA_USER =
		"Liferay SaaS - CSP - Up to 10K Users - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_20K_USERS =
		"Liferay SaaS - CSP - Up to 20K Users";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_20K_USERS_EXTRA_USER =
		"Liferay SaaS - CSP - Up to 20K Users - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_100_USERS =
		"Liferay SaaS - CSP - Up to 100 Users";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_100_USERS_EXTRA_USER =
		"Liferay SaaS - CSP - Up to 100 Users - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_500_USERS =
		"Liferay SaaS - CSP - Up to 500 Users";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_500_USERS_EXTRA_USER =
		"Liferay SaaS - CSP - Up to 500 Users - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_CUSTOM =
		"Liferay SaaS - CSP - Custom User Tier";

	public static final String PRODUCT_ENTRY_NAME_LXC_CSP_CUSTOM_EXTRA_USER =
		"Liferay SaaS - CSP - Custom User Tier - Extra User";

	public static final String PRODUCT_ENTRY_NAME_LXC_ENTERPRISE =
		"Liferay SaaS - Enterprise Plan";

	public static final String PRODUCT_ENTRY_NAME_LXC_PRO =
		"Liferay SaaS - Pro Plan";

	public static final String PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_ENGAGE_SITE =
		"Liferay SaaS Subscription - Engage Site";

	public static final String
		PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_SUPPORT_SITE =
			"Liferay SaaS Subscription - Support Site";

	public static final String
		PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_TRANSACT_SITE =
			"Liferay SaaS Subscription - Transact Site";

	public static List<String> getBaseProductEntryIds() {
		return _baseProductEntryIds;
	}

	public static String getProductEntryId(String productName) {
		return _productEntryIds.get(productName);
	}

	public static String[] getProductEntryIds() {
		Set<String> keys = _productNames.keySet();

		return keys.toArray(new String[0]);
	}

	public static String getProductName(String productEntryId) {
		return _productNames.get(productEntryId);
	}

	private static final List<String> _baseProductEntryIds = Arrays.asList(
		PRODUCT_ENTRY_ID_BASIC, PRODUCT_ENTRY_ID_BUSINESS,
		PRODUCT_ENTRY_ID_DATA_PLATFORM,
		PRODUCT_ENTRY_ID_DATA_PLATFORM_ENTERPRISE,
		PRODUCT_ENTRY_ID_DATA_PLATFORM_PRIVATE_BETA,
		PRODUCT_ENTRY_ID_DIGITAL_SALES_ROOM, PRODUCT_ENTRY_ID_ENTERPRISE,
		PRODUCT_ENTRY_ID_LXC_BUSINESS, PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS,
		PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS, PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS,
		PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS, PRODUCT_ENTRY_ID_LXC_CSP_100_USERS,
		PRODUCT_ENTRY_ID_LXC_CSP_500_USERS, PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM,
		PRODUCT_ENTRY_ID_LXC_ENTERPRISE, PRODUCT_ENTRY_ID_LXC_PRO,
		PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_ENGAGE_SITE,
		PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_SUPPORT_SITE,
		PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_TRANSACT_SITE);
	private static final Map<String, String> _productEntryIds =
		HashMapBuilder.put(
			PRODUCT_ENTRY_NAME_BASIC, PRODUCT_ENTRY_ID_BASIC
		).put(
			PRODUCT_ENTRY_NAME_BUSINESS, PRODUCT_ENTRY_ID_BUSINESS
		).put(
			PRODUCT_ENTRY_NAME_BUSINESS_CONTACTS,
			PRODUCT_ENTRY_ID_BUSINESS_CONTACTS
		).put(
			PRODUCT_ENTRY_NAME_BUSINESS_TRACKED_PAGES,
			PRODUCT_ENTRY_ID_BUSINESS_TRACKED_PAGES
		).put(
			PRODUCT_ENTRY_NAME_DATA_PLATFORM, PRODUCT_ENTRY_ID_DATA_PLATFORM
		).put(
			PRODUCT_ENTRY_NAME_DATA_PLATFORM_ENTERPRISE,
			PRODUCT_ENTRY_ID_DATA_PLATFORM_ENTERPRISE
		).put(
			PRODUCT_ENTRY_NAME_DATA_PLATFORM_PRIVATE_BETA,
			PRODUCT_ENTRY_ID_DATA_PLATFORM_PRIVATE_BETA
		).put(
			PRODUCT_ENTRY_NAME_DIGITAL_SALES_ROOM,
			PRODUCT_ENTRY_ID_DIGITAL_SALES_ROOM
		).put(
			PRODUCT_ENTRY_NAME_ENTERPRISE, PRODUCT_ENTRY_ID_ENTERPRISE
		).put(
			PRODUCT_ENTRY_NAME_ENTERPRISE_CONTACTS,
			PRODUCT_ENTRY_ID_ENTERPRISE_CONTACTS
		).put(
			PRODUCT_ENTRY_NAME_ENTERPRISE_TRACKED_PAGES,
			PRODUCT_ENTRY_ID_ENTERPRISE_TRACKED_PAGES
		).put(
			PRODUCT_ENTRY_NAME_LXC_BUSINESS, PRODUCT_ENTRY_ID_LXC_BUSINESS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_1K_USERS,
			PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_1K_USERS_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_5K_USERS,
			PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_5K_USERS_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_10K_USERS,
			PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_10K_USERS_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_20K_USERS,
			PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_20K_USERS_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_100_USERS,
			PRODUCT_ENTRY_ID_LXC_CSP_100_USERS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_100_USERS_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_100_USERS_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_500_USERS,
			PRODUCT_ENTRY_ID_LXC_CSP_500_USERS
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_500_USERS_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_500_USERS_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_CUSTOM, PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM
		).put(
			PRODUCT_ENTRY_NAME_LXC_CSP_CUSTOM_EXTRA_USER,
			PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM_EXTRA_USER
		).put(
			PRODUCT_ENTRY_NAME_LXC_ENTERPRISE, PRODUCT_ENTRY_ID_LXC_ENTERPRISE
		).put(
			PRODUCT_ENTRY_NAME_LXC_PRO, PRODUCT_ENTRY_ID_LXC_PRO
		).put(
			PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_ENGAGE_SITE,
			PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_ENGAGE_SITE
		).put(
			PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_SUPPORT_SITE,
			PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_SUPPORT_SITE
		).put(
			PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_TRANSACT_SITE,
			PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_TRANSACT_SITE
		).build();
	private static final Map<String, String> _productNames = HashMapBuilder.put(
		PRODUCT_ENTRY_ID_BASIC, PRODUCT_ENTRY_NAME_BASIC
	).put(
		PRODUCT_ENTRY_ID_BUSINESS, PRODUCT_ENTRY_NAME_BUSINESS
	).put(
		PRODUCT_ENTRY_ID_BUSINESS_CONTACTS, PRODUCT_ENTRY_NAME_BUSINESS_CONTACTS
	).put(
		PRODUCT_ENTRY_ID_BUSINESS_TRACKED_PAGES,
		PRODUCT_ENTRY_NAME_BUSINESS_TRACKED_PAGES
	).put(
		PRODUCT_ENTRY_ID_DATA_PLATFORM, PRODUCT_ENTRY_NAME_DATA_PLATFORM
	).put(
		PRODUCT_ENTRY_ID_DATA_PLATFORM_ENTERPRISE,
		PRODUCT_ENTRY_NAME_DATA_PLATFORM_ENTERPRISE
	).put(
		PRODUCT_ENTRY_ID_DATA_PLATFORM_PRIVATE_BETA,
		PRODUCT_ENTRY_NAME_DATA_PLATFORM_PRIVATE_BETA
	).put(
		PRODUCT_ENTRY_ID_DIGITAL_SALES_ROOM,
		PRODUCT_ENTRY_NAME_DIGITAL_SALES_ROOM
	).put(
		PRODUCT_ENTRY_ID_ENTERPRISE, PRODUCT_ENTRY_NAME_ENTERPRISE
	).put(
		PRODUCT_ENTRY_ID_ENTERPRISE_CONTACTS,
		PRODUCT_ENTRY_NAME_ENTERPRISE_CONTACTS
	).put(
		PRODUCT_ENTRY_ID_ENTERPRISE_TRACKED_PAGES,
		PRODUCT_ENTRY_NAME_ENTERPRISE_TRACKED_PAGES
	).put(
		PRODUCT_ENTRY_ID_LXC_BUSINESS, PRODUCT_ENTRY_NAME_LXC_BUSINESS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS, PRODUCT_ENTRY_NAME_LXC_CSP_1K_USERS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_1K_USERS_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_1K_USERS_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS, PRODUCT_ENTRY_NAME_LXC_CSP_5K_USERS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_5K_USERS_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_5K_USERS_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS, PRODUCT_ENTRY_NAME_LXC_CSP_10K_USERS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_10K_USERS_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_10K_USERS_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS, PRODUCT_ENTRY_NAME_LXC_CSP_20K_USERS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_20K_USERS_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_20K_USERS_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_100_USERS, PRODUCT_ENTRY_NAME_LXC_CSP_100_USERS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_100_USERS_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_100_USERS_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_500_USERS, PRODUCT_ENTRY_NAME_LXC_CSP_500_USERS
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_500_USERS_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_500_USERS_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM, PRODUCT_ENTRY_NAME_LXC_CSP_CUSTOM
	).put(
		PRODUCT_ENTRY_ID_LXC_CSP_CUSTOM_EXTRA_USER,
		PRODUCT_ENTRY_NAME_LXC_CSP_CUSTOM_EXTRA_USER
	).put(
		PRODUCT_ENTRY_ID_LXC_ENTERPRISE, PRODUCT_ENTRY_NAME_LXC_ENTERPRISE
	).put(
		PRODUCT_ENTRY_ID_LXC_PRO, PRODUCT_ENTRY_NAME_LXC_PRO
	).put(
		PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_ENGAGE_SITE,
		PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_ENGAGE_SITE
	).put(
		PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_SUPPORT_SITE,
		PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_SUPPORT_SITE
	).put(
		PRODUCT_ENTRY_ID_LXC_SUBSCRIPTION_TRANSACT_SITE,
		PRODUCT_ENTRY_NAME_LXC_SUBSCRIPTION_TRANSACT_SITE
	).build();

}