modified.files.includes[relevant][accessibility-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][accessibility-java-rule]=\
    apps/accessibility/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][accessibility-java-rule]=\
    apps/accessibility/**/*Test.java

relevant.rule.names=accessibility-java-rule

test.batch.names[relevant][accessibility-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Accessibility Menu