dependencies {
	compileInclude group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jsr310", version: "2.18.2"
	compileInclude group: "com.liferay", name: "com.twilio.sdk.twilio", version: "8.3.0.JAKARTA_LIFERAY-PATCHED-1"
	compileInclude group: "io.jsonwebtoken", name: "jjwt-api", version: "0.11.2"
	compileInclude group: "io.jsonwebtoken", name: "jjwt-impl", version: "0.11.2"
	compileInclude group: "io.jsonwebtoken", name: "jjwt-jackson", version: "0.11.2"
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.13"
	compileOnly group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.14"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly project(":apps:push-notifications:push-notifications-api")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
}