query getWorkspaceGroupChannelAssetSummariesPage(
	$accountIds: [String]
	$channelId: String
	$individualIds: [String]
	$keywords: String
	$rangeEnd: String
	$rangeKey: Int
	$rangeStart: String
	$segmentIds: [String]
	$size: Int!
	$sort: Sort!
	$start: Int!
) {
	assetSummaryMetricBag: assetSummaries(
		accountIds: $accountIds
		channelId: $channelId
		individualIds: $individualIds
		keywords: $keywords
		rangeEnd: $rangeEnd
		rangeKey: $rangeKey
		rangeStart: $rangeStart
		segmentIds: $segmentIds
		size: $size
		sort: $sort
		start: $start
	) {
		assetSummaryMetrics {
			assetId
			assetTitle
			assetType
			downloadsMetric {
				trend {
					percentage
				}
				value
			}
			impressionsMetric {
				trend {
					percentage
				}
				value
			}
			readsMetric {
				trend {
					percentage
				}
				value
			}
			viewsMetric {
				trend {
					percentage
				}
				value
			}
		}
		total
	}
}
