modified.files.includes[relevant][osb-faro-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][osb-faro-web-playwright-rule]=\
    osb-faro-web.main

relevant.rule.names=osb-faro-web-playwright-rule

test.batch.names[relevant][osb-faro-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Analytics Cloud