modified.files.includes[relevant][sass-compiler-dart-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][sass-compiler-dart-java-rule]=\
    util/sass-compiler-dart/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][sass-compiler-dart-java-rule]=\
    util/sass-compiler-dart/**/*Test.java

relevant.rule.names=sass-compiler-dart-java-rule

test.batch.names[relevant][sass-compiler-dart-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Dev Tools