apiDir: ../scim-rest-api/src/main/java
apiPackagePath: com.liferay.scim.rest
application:
    baseURI: /scim
    className: ScimRESTApplication
    name: Liferay.Scim.REST
author: Olivér Kecskeméty
clientDir: ../scim-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: false
generateGraphQL: false
javaEEPackage: jakarta
testDir: ../scim-rest-test/src/testIntegration/java