configurations {
	bndOnly
}

dependencies {
	bndOnly classifier: "bin", ext: "bin", group: "com.liferay", name: "org.apache.opennlp.model.en.ner.location", version: "1.5.0"
	bndOnly classifier: "bin", ext: "bin", group: "com.liferay", name: "org.apache.opennlp.model.en.ner.organization", version: "1.5.0"
	bndOnly classifier: "bin", ext: "bin", group: "com.liferay", name: "org.apache.opennlp.model.en.ner.person", version: "1.5.0"
	bndOnly classifier: "bin", ext: "bin", group: "com.liferay", name: "org.apache.opennlp.model.en.sent", version: "1.5.0"
	bndOnly classifier: "bin", ext: "bin", group: "com.liferay", name: "org.apache.opennlp.model.en.token", version: "1.5.0"
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.apache.opennlp", name: "opennlp-tools", version: "2.5.11"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:asset:asset-auto-tagger-api")
	compileOnly project(":apps:portal-configuration:portal-configuration-module-configuration-api")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
	compileOnly project(":core:osgi-service-tracker-collections")
	compileOnly project(":core:petra:petra-concurrent")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-reflect")
}

tasks.named("jar") {
	Task jarTask ->

	bundle {
		classpath jarTask.project.configurations.bndOnly
	}
}