##
## Test Suites
##

    modified.files.includes[relevant][password-policies-admin-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=password-policies-admin-java-rule

    test.batch.names[relevant][password-policies-admin-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][password-policies-admin-java-rule]=\
        apps/password-policies-admin/**/*Test.java,\
        apps/password-policy/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][password-policies-admin-java-rule]=\
        apps/password-policies-admin/**/*Test.java

##
## Testray
##

    testray.main.component.name=Password Policies