dependencies {
	compileOnly group: "com.liferay", name: "org.apache.felix.configadmin", version: "1.9.26.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:static:portal-file-install:portal-file-install-api")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-string")
}