modified.files.includes[relevant][asset-auto-tagger-api-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][asset-auto-tagger-api-java-rule]=\
    **/asset-auto-tagger-google-cloud-natural-language-impl/**/*Test.java,\
    **/asset-auto-tagger-google-cloud-natural-language-test/**/*Test.java,\
    **/asset-auto-tagger-opennlp-test/**/*Test.java,\
    **/asset-auto-tagger-test/**/*Test.java,\
    **/document-library-asset-auto-tagger-google-cloud-vision/**/*Test.java,\
    **/document-library-asset-auto-tagger-opennlp-test/**/*Test.java,\
    **/document-library-asset-auto-tagger-tensorflow-test/**/*Test.java,\
    **/journal-asset-auto-tagger-opennlp-test/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][asset-auto-tagger-api-java-rule]=\
    **/asset-auto-tagger-google-cloud-natural-language-impl/**/*Test.java,\
    **/asset-auto-tagger-google-cloud-natural-language-test/**/*Test.java,\
    **/asset-auto-tagger-opennlp-test/**/*Test.java,\
    **/asset-auto-tagger-test/**/*Test.java,\
    **/document-library-asset-auto-tagger-google-cloud-vision/**/*Test.java,\
    **/document-library-asset-auto-tagger-opennlp-test/**/*Test.java,\
    **/document-library-asset-auto-tagger-tensorflow-test/**/*Test.java,\
    **/journal-asset-auto-tagger-opennlp-test/**/*Test.java

relevant.rule.names=asset-auto-tagger-api-java-rule

test.batch.names[relevant][asset-auto-tagger-api-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Auto Tagging