modified.files.includes[relevant][redirect-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][redirect-java-rule]=\
    apps/redirect/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][redirect-java-rule]=\
    apps/redirect/**/*Test.java

relevant.rule.names=redirect-java-rule

test.batch.names[relevant][redirect-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=URL Redirections