author=Liferay, Inc.
change-log=
licenses=LGPL
liferay-versions=7.4.0+
long-description=
module-group-id=liferay
module-incremental-version=1
name=Classic 2
page-url=http://www.liferay.com
required-for-startup=true
short-description=
tags=