import com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer
import com.bmuschko.gradle.docker.tasks.container.DockerRemoveContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStartContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStopContainer
import com.bmuschko.gradle.docker.tasks.container.extras.DockerWaitHealthyContainer

buildscript {
	dependencies {
		classpath group: "com.bmuschko", name: "gradle-docker-plugin", version: "6.7.0"
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.app.docker", version: "1.0.14"
	}

	repositories {
		File dir = rootProject.projectDir

		while (dir != null) {
			File tmpMavenRepositoryDir = new File(dir, ".m2-tmp")

			if (tmpMavenRepositoryDir.exists()) {
				maven {
					url tmpMavenRepositoryDir

					println tmpMavenRepositoryDir
				}
			}

			dir = dir.getParentFile();
		}

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.app.docker"
apply plugin: "com.liferay.root.defaults.plugin"
apply plugin: "com.liferay.yarn.defaults.plugin"

task buildNexusCredentials(type: Exec)
task checkDocker(type: DockerWaitHealthyContainer)
task copyDatabaseConnector(type: Copy)
task copyDockerResources(type: Copy)
task createDocker(type: DockerCreateContainer)
task removeDocker(type: DockerRemoveContainer)
task startDocker(type: DockerStartContainer)
task stopDocker(type: DockerStopContainer)

def dockerContainerId = "faro"

ext.faroEnvironmentName = System.getenv().get("FARO_ENVIRONMENT_NAME") ?: "local"
ext.faroImageTag = project.hasProperty("docker.image.tag") ? project.getProperty("docker.image.tag") : "latest"

appDocker {
	imageName "liferay/com-liferay-osb-faro"
	imageTags = [faroEnvironmentName.equals("prd") ? "prd-" + new Date().format("yyyyMMdd") : faroImageTag]
	inputDir = faroEnvironmentName.equals("local") ? (System.getProperty("liferay.ci") != "true") ? "osb-faro-docker/local/dev" : "osb-faro-docker/local/test" : "osb-faro-docker/" + faroEnvironmentName

	onlyIf {
		false
	}
}

buildAppDockerImage {
	mustRunAfter copyDockerResources
}

buildNexusCredentials {
	commandLine("/bin/sh", "-c", "./set_nexus_credentials.sh")

	onlyIf {
		faroEnvironmentName.equals("local") && (System.getProperty("liferay.ci") != "true")
	}
}

checkDocker {
	targetContainerId {
		dockerContainerId
	}
}

copyDatabaseConnector {
	from "../../../../../lib/development/mysql.jar"
	into "osb-faro-docker/local/common/resources/lib"

	onlyIf {
		faroEnvironmentName.equals("local")
	}
}

copyDockerResources {
	from "osb-faro-docker/" + faroEnvironmentName + "/common"
	into "${buildDir}/docker/common"
}

createDocker {
	dependsOn buildAppDockerImage, removeDocker

	containerName = dockerContainerId
	hostConfig.portBindings = ["8000:8000", "8080:8080", "11311:11311"]

	targetImageId {
		appDocker.imageName
	}

	def envFile = file("${rootDir}/local.env")

	if (envFile.exists()) {
		def props = new Properties()

		envFile.withInputStream {
			props.load(it)
		}

		props.each{
			withEnvVar(it.key, it.value)
		}
	}
}

buildAppDockerImage {
	images.add(appDocker.imageName + ":" + appDocker.imageTags[0])

	def LABEL_BUILD_DATE = ('git log -1 --format=%cd').execute().text.trim()
	def LABEL_VCS_REF = ('git rev-parse --short=7 HEAD').execute().text.trim()
	buildArgs = ['LABEL_BUILD_DATE': LABEL_BUILD_DATE, 'LABEL_VCS_REF': LABEL_VCS_REF]
}

docker {
	registryCredentials {
		password = System.getenv("DOCKER_PASSWORD")
		username = System.getenv("DOCKER_USERNAME")
	}
}

prepareAppDockerImageInputDir {
	dependsOn buildNexusCredentials, copyDatabaseConnector
	finalizedBy copyDockerResources

	rename {
		String fileName ->

		if (fileName.endsWith(".jar")) {
			int pos = fileName.indexOf('-')

			if (pos != -1) {
				fileName = fileName.substring(0, pos) + ".jar"
			}
		}

		fileName
	}
}

pushAppDockerImage {
	enabled = false
}

removeDocker {
	force = true

	onError {
	}

	targetContainerId {
		dockerContainerId
	}
}

startDocker {
	finalizedBy {
		checkDocker
	}

	targetContainerId {
		dockerContainerId
	}
}

stopDocker {
	onError {
	}

	targetContainerId {
		dockerContainerId
	}
}

def deployToDocker = providers.gradleProperty("deployToDocker")

if (deployToDocker.present) {
	configure(project(":dxp:apps:osb:osb-faro:osb-faro-dependencies")) {
		task copyCloudResources(type: Copy)

		String deployDir = "../osb-faro-docker/cloud/modules"

		copyCloudResources {
			doFirst {
				delete file(deployDir)
			}

			from configurations.compileOnly
			into deployDir
		}
	}

	configure(project(":dxp:apps:osb:osb-faro:osb-faro-dependencies")) {
		task copyWedeployResources(type: Copy)
		task wedeploy(type: Exec)

		String deployDir = "../wedeploy/" + faroEnvironmentName + "/deploy"

		copyWedeployResources {
			doFirst {
				delete file(deployDir)
			}

			from configurations.compileOnly
			into deployDir
		}

		wedeploy {
			args "deploy", "--project", "ac-" + faroEnvironmentName
			dependsOn copyWedeployResources
			executable = "lcp"
			workingDir "../wedeploy/".concat(faroEnvironmentName)
		}
	}
}

subprojects {
	if (deployToDocker.present) {
		afterEvaluate {
			task moveToDocker(type: Exec)

			deploy {
				doFirst {
					delete file(liferay.deployDir)
				}

				finalizedBy moveToDocker

				liferay {
					deployDir = new File("${rootDir}/dxp/apps/osb/osb-faro/build/deploy")
				}
			}

			moveToDocker {
				commandLine "docker", "cp", "-a", liferay.deployDir, dockerContainerId + ":/opt/liferay"
			}
		}
	}

	tasks.all {
		Task task ->

		if (task.name == "baseline") {
			enabled = false
		}
		else if (deployToDocker.present && task.name == "deployDependencies") {
			prepareAppDockerImageInputDir {
				from task.inputs.files
			}
		}
	}

	tasks.withType(Test) {
		maxHeapSize = "4096m"
	}
}