modified.files.includes[relevant][commerce-channel-web-functional-rule]=**
modified.files.includes[relevant][commerce-channel-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][commerce-channel-web-playwright-rule]=\
    commerce-channel-web.main

relevant.rule.names=\
    commerce-channel-web-functional-rule,\
    commerce-channel-web-playwright-rule

test.batch.names[relevant][commerce-channel-web-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][commerce-channel-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][commerce-channel-web-functional-rule]=\
    (testray.main.component.name == "Commerce")

testray.main.component.name=Commerce