#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/headless-asset-library
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Asset.Library)
osgi.jaxrs.resource=true