#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.headless.asset.library.dto.v1_0.UserGroup
batch.engine.task.item.delegate=true
batch.planner.export.enabled=true
batch.planner.import.enabled=false
entity.class.name=com.liferay.headless.asset.library.dto.v1_0.UserGroup
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Headless.Asset.Library)
osgi.jaxrs.resource=true