modified.files.includes[relevant][contacts-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][contacts-java-rule]=\
    apps/contacts/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][contacts-java-rule]=\
    apps/contacts/**/*Test.java

relevant.rule.names=contacts-java-rule

test.batch.names[relevant][contacts-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Contacts Center