modified.files.includes[relevant][subscription-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][subscription-java-rule]=\
    apps/subscription/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][subscription-java-rule]=\
    apps/subscription/**/*Test.java

relevant.rule.names=subscription-java-rule

test.batch.names[relevant][subscription-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=My Subscriptions Widget