modified.files.includes[relevant][segments-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][segments-java-rule]=\
    apps/analytics/**/*Test.java,\
    apps/asset/asset-list-web/**/*Test.java,\
    apps/fragment/fragment-entry-processor/fragment-entry-processor-editable/**/*Test.java,\
    apps/headless/headless-admin-user/**/*Test.java,\
    apps/layout/layout-content-page-editor-web/**/*Test.java,\
    dxp/apps/segments/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][segments-java-rule]=\
    apps/analytics/**/*Test.java,\
    apps/asset/asset-list-web/**/*Test.java,\
    apps/fragment/fragment-entry-processor/fragment-entry-processor-editable/**/*Test.java,\
    apps/headless/headless-admin-user/**/*Test.java,\
    apps/layout/layout-content-page-editor-web/**/*Test.java,\
    dxp/apps/segments/**/*Test.java

relevant.rule.names=segments-java-rule

test.batch.names[relevant][segments-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Segmentation