##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/sdk/ant-bnd/src/test/resources/com/liferay/ant/bnd/jsp/dependencies/*.jsp,\
        modules/sdk/gradle-plugins*/.generated-src/**,\
        modules/sdk/gradle-plugins/src/gradleTest/**/bnd.bnd,\
        modules/sdk/gradle-plugins-baseline/src/gradleTest/**/bnd.bnd,\
        modules/sdk/gradle-plugins-defaults/src/gradleTest/**/bnd.bnd,\
        modules/sdk/gradle-plugins-javadoc-formatter/src/gradleTest/smoke/src/main/java/com/liferay/sample/GreetingBuilder.java,\
        modules/sdk/gradle-plugins-theme-builder/src/gradleTest/**/*.scss,\
        modules/sdk/gradle-plugins-tld-formatter/src/gradleTest/smoke/src/main/resources/sample.tld,\
        modules/sdk/gradle-plugins-workspace/src/gradleTest/designPack/result/*.css,\
        modules/sdk/gradle-plugins-workspace/src/gradleTest/distBundleZip/plugins-sdk/*/**,\
        modules/sdk/project-templates/project-templates/src/test/resources/com/liferay/project/templates/internal/util/templates/*/**,\
        modules/sdk/project-templates/project-templates-*/src/main/resources/archetype-resources/*/**,\
        modules/sdk/project-templates/project-templates-*/src/main/resources/archetype-resources/bnd.bnd,\
        modules/sdk/project-templates/project-templates-*/src/main/resources/archetype-resources/build.gradle,\
        modules/sdk/project-templates/project-templates-form-field/src/main/resources/archetype-resources/package.json

    run.outside.portal.excludes=\
        modules/sdk/**

##
## Source Check Properties
##

    #
    # Source checks will read the values below in addition to the ones set in
    # the sourcechecks.xml configuration file. See
    # https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/sourcechecks.xml
    #
    source.check.JavaComponentAnnotationsCheck.checkConfigurationPidAttribute=false