modified.files.includes[relevant][message-boards-service-functional-rule]=**
relevant.rule.names=message-boards-service-functional-rule

test.batch.names[relevant][message-boards-service-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][message-boards-service-functional-rule]=\
    (testray.component.names == "Message Boards") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Message Boards