{{- range $i, $dataPlane := $dataPlanes }}
{{- if $i }}
---
{{- end }}
apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: Bucket
metadata:
    annotations:
        gotemplating.fn.crossplane.io/composition-resource-name: liferay-gcs-bucket-{{ $dataPlane }}
    labels:
        {{- $labels | toYaml | nindent 8 }}
        dataPlane: {{ $dataPlane }}
    name: {{ $baseName }}-dl-{{ $dataPlane }}
spec:
    forProvider:
        {{- if $cmkEnabled }}
        encryption:
            defaultKmsKeyName: {{ $cmkKeyName }}
        {{- end }}
        forceDestroy: {{ or $forceDestroy (ne $dataPlane $activeDataPlane) }}
        labels:
            {{- merge (dict) $backupTargetLabels ($storage.tags | default dict) | toYaml | nindent 12 }}
            active: {{ printf "%t" (eq $dataPlane $activeDataPlane) | quote }}
        location: {{ $storage.region | default $region }}
        storageClass: STANDARD
        uniformBucketLevelAccess: true
        versioning:
            enabled: {{ $storage.enableVersioning | default true }}
    managementPolicies: {{ $managementPolicies }}
---
apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
    annotations:
        gotemplating.fn.crossplane.io/composition-resource-name: liferay-gcs-iam-{{ $dataPlane }}
    labels:
        {{- $labels | toYaml | nindent 8 }}
        dataPlane: {{ $dataPlane }}
spec:
    forProvider:
        bucketSelector:
            matchLabels:
                dataPlane: {{ $dataPlane }}
        member: serviceAccount:{{ $gsaEmail }}
        role: roles/storage.admin
    managementPolicies: {{ $managementPolicies }}
{{- end }}