{{- if .Values.clusterSecretStore.enabled -}}
{{- $name := required "The value \"clusterSecretStore.name\" is required to create the cluster secret store." .Values.clusterSecretStore.name -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-90"
    labels:
        {{- include "liferay-platform.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ $name | quote }}
    name: {{ $name | quote }}
spec:
    provider:
        {{- toYaml .Values.clusterSecretStore.provider | nindent 8 }}
{{- end -}}