{{- if .Values.clusterSecretStore.enabled -}}
{{- $clusterSecretStoreName := include "liferay-platform.clusterSecretStoreName" . -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-90"
    labels:
        {{- include "liferay-platform.labels" . | nindent 8 }}
        app.kubernetes.io/name: {{ $clusterSecretStoreName | quote }}
    name: {{ $clusterSecretStoreName | quote }}
spec:
    provider:
        {{- toYaml .Values.clusterSecretStore.provider | nindent 8 }}
{{- end -}}