{{- if .Values.argocd.sso.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "-85"
    labels:
        {{- include "liferay-platform.labels" . | nindent 8 }}
        app.kubernetes.io/name: customer-idp-saml
    name: customer-idp-saml
    namespace: {{ .Release.Namespace }}
spec:
    data:
    {{- range $property := list "caData" "entityIssuer" "redirectURI" "ssoURL" }}
    -   remoteRef:
            key: {{ $.Values.argocd.sso.credentialsSecretKey }}
            property: {{ $property }}
        secretKey: {{ $property }}
    {{- end }}
    refreshInterval: 1h0m0s
    secretStoreRef:
        kind: ClusterSecretStore
        name: {{ include "liferay-platform.clusterSecretStoreName" . }}
    target:
        creationPolicy: Owner
        name: customer-idp-saml
        template:
            metadata:
                labels:
                    app.kubernetes.io/name: customer-idp-saml
                    app.kubernetes.io/part-of: argocd
            type: Opaque
{{- end -}}