{{- if .Values.operatorApplications.envoyGateway.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-90"
    labels:
        {{- include "liferay-platform.labels" . | nindent 8 }}
        app.kubernetes.io/name: envoy-proxy-pdb
    name: envoy-proxy-pdb
    namespace: {{ .Values.operatorApplications.envoyGateway.namespace }}
spec:
    maxUnavailable: 1
    selector:
        matchLabels:
            app.kubernetes.io/component: proxy
            app.kubernetes.io/name: envoy
{{- end -}}