/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.patcher.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PatcherBuildRel service. Represents a row in the &quot;OSB_PatcherBuildRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.patcher.model.impl.PatcherBuildRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.patcher.model.impl.PatcherBuildRelImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see PatcherBuildRel
 * @see com.liferay.osb.patcher.model.impl.PatcherBuildRelImpl
 * @see com.liferay.osb.patcher.model.impl.PatcherBuildRelModelImpl
 * @generated
 */
public interface PatcherBuildRelModel extends BaseModel<PatcherBuildRel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patcher build rel model instance should use the {@link PatcherBuildRel} interface instead.
	 */

	/**
	 * Returns the primary key of this patcher build rel.
	 *
	 * @return the primary key of this patcher build rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patcher build rel.
	 *
	 * @param primaryKey the primary key of this patcher build rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patcher build rel ID of this patcher build rel.
	 *
	 * @return the patcher build rel ID of this patcher build rel
	 */
	public long getPatcherBuildRelId();

	/**
	 * Sets the patcher build rel ID of this patcher build rel.
	 *
	 * @param patcherBuildRelId the patcher build rel ID of this patcher build rel
	 */
	public void setPatcherBuildRelId(long patcherBuildRelId);

	/**
	 * Returns the child patcher build ID of this patcher build rel.
	 *
	 * @return the child patcher build ID of this patcher build rel
	 */
	public long getChildPatcherBuildId();

	/**
	 * Sets the child patcher build ID of this patcher build rel.
	 *
	 * @param childPatcherBuildId the child patcher build ID of this patcher build rel
	 */
	public void setChildPatcherBuildId(long childPatcherBuildId);

	/**
	 * Returns the parent patcher build ID of this patcher build rel.
	 *
	 * @return the parent patcher build ID of this patcher build rel
	 */
	public long getParentPatcherBuildId();

	/**
	 * Sets the parent patcher build ID of this patcher build rel.
	 *
	 * @param parentPatcherBuildId the parent patcher build ID of this patcher build rel
	 */
	public void setParentPatcherBuildId(long parentPatcherBuildId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.osb.patcher.model.PatcherBuildRel patcherBuildRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.osb.patcher.model.PatcherBuildRel> toCacheModel();

	@Override
	public com.liferay.osb.patcher.model.PatcherBuildRel toEscapedModel();

	@Override
	public com.liferay.osb.patcher.model.PatcherBuildRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}