/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.patcher.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.WorkflowedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PatcherFix service. Represents a row in the &quot;OSB_PatcherFix&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.patcher.model.impl.PatcherFixModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.patcher.model.impl.PatcherFixImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see PatcherFix
 * @see com.liferay.osb.patcher.model.impl.PatcherFixImpl
 * @see com.liferay.osb.patcher.model.impl.PatcherFixModelImpl
 * @generated
 */
public interface PatcherFixModel extends AuditedModel, BaseModel<PatcherFix>,
	WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patcher fix model instance should use the {@link PatcherFix} interface instead.
	 */

	/**
	 * Returns the primary key of this patcher fix.
	 *
	 * @return the primary key of this patcher fix
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patcher fix.
	 *
	 * @param primaryKey the primary key of this patcher fix
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patcher fix ID of this patcher fix.
	 *
	 * @return the patcher fix ID of this patcher fix
	 */
	public long getPatcherFixId();

	/**
	 * Sets the patcher fix ID of this patcher fix.
	 *
	 * @param patcherFixId the patcher fix ID of this patcher fix
	 */
	public void setPatcherFixId(long patcherFixId);

	/**
	 * Returns the company ID of this patcher fix.
	 *
	 * @return the company ID of this patcher fix
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this patcher fix.
	 *
	 * @param companyId the company ID of this patcher fix
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this patcher fix.
	 *
	 * @return the user ID of this patcher fix
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this patcher fix.
	 *
	 * @param userId the user ID of this patcher fix
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this patcher fix.
	 *
	 * @return the user uuid of this patcher fix
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this patcher fix.
	 *
	 * @param userUuid the user uuid of this patcher fix
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this patcher fix.
	 *
	 * @return the user name of this patcher fix
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this patcher fix.
	 *
	 * @param userName the user name of this patcher fix
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this patcher fix.
	 *
	 * @return the create date of this patcher fix
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this patcher fix.
	 *
	 * @param createDate the create date of this patcher fix
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this patcher fix.
	 *
	 * @return the modified date of this patcher fix
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this patcher fix.
	 *
	 * @param modifiedDate the modified date of this patcher fix
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the patcher product version ID of this patcher fix.
	 *
	 * @return the patcher product version ID of this patcher fix
	 */
	public long getPatcherProductVersionId();

	/**
	 * Sets the patcher product version ID of this patcher fix.
	 *
	 * @param patcherProductVersionId the patcher product version ID of this patcher fix
	 */
	public void setPatcherProductVersionId(long patcherProductVersionId);

	/**
	 * Returns the patcher project version ID of this patcher fix.
	 *
	 * @return the patcher project version ID of this patcher fix
	 */
	public long getPatcherProjectVersionId();

	/**
	 * Sets the patcher project version ID of this patcher fix.
	 *
	 * @param patcherProjectVersionId the patcher project version ID of this patcher fix
	 */
	public void setPatcherProjectVersionId(long patcherProjectVersionId);

	/**
	 * Returns the name of this patcher fix.
	 *
	 * @return the name of this patcher fix
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this patcher fix.
	 *
	 * @param name the name of this patcher fix
	 */
	public void setName(String name);

	/**
	 * Returns the key of this patcher fix.
	 *
	 * @return the key of this patcher fix
	 */
	@AutoEscape
	public String getKey();

	/**
	 * Sets the key of this patcher fix.
	 *
	 * @param key the key of this patcher fix
	 */
	public void setKey(String key);

	/**
	 * Returns the key version of this patcher fix.
	 *
	 * @return the key version of this patcher fix
	 */
	public double getKeyVersion();

	/**
	 * Sets the key version of this patcher fix.
	 *
	 * @param keyVersion the key version of this patcher fix
	 */
	public void setKeyVersion(double keyVersion);

	/**
	 * Returns the type of this patcher fix.
	 *
	 * @return the type of this patcher fix
	 */
	public int getType();

	/**
	 * Sets the type of this patcher fix.
	 *
	 * @param type the type of this patcher fix
	 */
	public void setType(int type);

	/**
	 * Returns the latest fix of this patcher fix.
	 *
	 * @return the latest fix of this patcher fix
	 */
	public boolean getLatestFix();

	/**
	 * Returns <code>true</code> if this patcher fix is latest fix.
	 *
	 * @return <code>true</code> if this patcher fix is latest fix; <code>false</code> otherwise
	 */
	public boolean isLatestFix();

	/**
	 * Sets whether this patcher fix is latest fix.
	 *
	 * @param latestFix the latest fix of this patcher fix
	 */
	public void setLatestFix(boolean latestFix);

	/**
	 * Returns the obsolete of this patcher fix.
	 *
	 * @return the obsolete of this patcher fix
	 */
	public boolean getObsolete();

	/**
	 * Returns <code>true</code> if this patcher fix is obsolete.
	 *
	 * @return <code>true</code> if this patcher fix is obsolete; <code>false</code> otherwise
	 */
	public boolean isObsolete();

	/**
	 * Sets whether this patcher fix is obsolete.
	 *
	 * @param obsolete the obsolete of this patcher fix
	 */
	public void setObsolete(boolean obsolete);

	/**
	 * Returns the committish of this patcher fix.
	 *
	 * @return the committish of this patcher fix
	 */
	@AutoEscape
	public String getCommittish();

	/**
	 * Sets the committish of this patcher fix.
	 *
	 * @param committish the committish of this patcher fix
	 */
	public void setCommittish(String committish);

	/**
	 * Returns the git hash of this patcher fix.
	 *
	 * @return the git hash of this patcher fix
	 */
	@AutoEscape
	public String getGitHash();

	/**
	 * Sets the git hash of this patcher fix.
	 *
	 * @param gitHash the git hash of this patcher fix
	 */
	public void setGitHash(String gitHash);

	/**
	 * Returns the git remote u r l of this patcher fix.
	 *
	 * @return the git remote u r l of this patcher fix
	 */
	@AutoEscape
	public String getGitRemoteURL();

	/**
	 * Sets the git remote u r l of this patcher fix.
	 *
	 * @param gitRemoteURL the git remote u r l of this patcher fix
	 */
	public void setGitRemoteURL(String gitRemoteURL);

	/**
	 * Returns the dependencies of this patcher fix.
	 *
	 * @return the dependencies of this patcher fix
	 */
	@AutoEscape
	public String getDependencies();

	/**
	 * Sets the dependencies of this patcher fix.
	 *
	 * @param dependencies the dependencies of this patcher fix
	 */
	public void setDependencies(String dependencies);

	/**
	 * Returns the requirements of this patcher fix.
	 *
	 * @return the requirements of this patcher fix
	 */
	@AutoEscape
	public String getRequirements();

	/**
	 * Sets the requirements of this patcher fix.
	 *
	 * @param requirements the requirements of this patcher fix
	 */
	public void setRequirements(String requirements);

	/**
	 * Returns the request key of this patcher fix.
	 *
	 * @return the request key of this patcher fix
	 */
	@AutoEscape
	public String getRequestKey();

	/**
	 * Sets the request key of this patcher fix.
	 *
	 * @param requestKey the request key of this patcher fix
	 */
	public void setRequestKey(String requestKey);

	/**
	 * Returns the jenkins results of this patcher fix.
	 *
	 * @return the jenkins results of this patcher fix
	 */
	@AutoEscape
	public String getJenkinsResults();

	/**
	 * Sets the jenkins results of this patcher fix.
	 *
	 * @param jenkinsResults the jenkins results of this patcher fix
	 */
	public void setJenkinsResults(String jenkinsResults);

	/**
	 * Returns the comments of this patcher fix.
	 *
	 * @return the comments of this patcher fix
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this patcher fix.
	 *
	 * @param comments the comments of this patcher fix
	 */
	public void setComments(String comments);

	/**
	 * Returns the fix pack status of this patcher fix.
	 *
	 * @return the fix pack status of this patcher fix
	 */
	public int getFixPackStatus();

	/**
	 * Sets the fix pack status of this patcher fix.
	 *
	 * @param fixPackStatus the fix pack status of this patcher fix
	 */
	public void setFixPackStatus(int fixPackStatus);

	/**
	 * Returns the notified of this patcher fix.
	 *
	 * @return the notified of this patcher fix
	 */
	public boolean getNotified();

	/**
	 * Returns <code>true</code> if this patcher fix is notified.
	 *
	 * @return <code>true</code> if this patcher fix is notified; <code>false</code> otherwise
	 */
	public boolean isNotified();

	/**
	 * Sets whether this patcher fix is notified.
	 *
	 * @param notified the notified of this patcher fix
	 */
	public void setNotified(boolean notified);

	/**
	 * Returns the product version of this patcher fix.
	 *
	 * @return the product version of this patcher fix
	 */
	public int getProductVersion();

	/**
	 * Sets the product version of this patcher fix.
	 *
	 * @param productVersion the product version of this patcher fix
	 */
	public void setProductVersion(int productVersion);

	/**
	 * Returns the status of this patcher fix.
	 *
	 * @return the status of this patcher fix
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this patcher fix.
	 *
	 * @param status the status of this patcher fix
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this patcher fix.
	 *
	 * @return the status by user ID of this patcher fix
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this patcher fix.
	 *
	 * @param statusByUserId the status by user ID of this patcher fix
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this patcher fix.
	 *
	 * @return the status by user uuid of this patcher fix
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this patcher fix.
	 *
	 * @param statusByUserUuid the status by user uuid of this patcher fix
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this patcher fix.
	 *
	 * @return the status by user name of this patcher fix
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this patcher fix.
	 *
	 * @param statusByUserName the status by user name of this patcher fix
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this patcher fix.
	 *
	 * @return the status date of this patcher fix
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this patcher fix.
	 *
	 * @param statusDate the status date of this patcher fix
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated As of 6.1.0, replaced by {@link #isApproved()}
	 */
	@Override
	public boolean getApproved();

	/**
	 * Returns <code>true</code> if this patcher fix is approved.
	 *
	 * @return <code>true</code> if this patcher fix is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this patcher fix is denied.
	 *
	 * @return <code>true</code> if this patcher fix is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this patcher fix is a draft.
	 *
	 * @return <code>true</code> if this patcher fix is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this patcher fix is expired.
	 *
	 * @return <code>true</code> if this patcher fix is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this patcher fix is inactive.
	 *
	 * @return <code>true</code> if this patcher fix is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this patcher fix is incomplete.
	 *
	 * @return <code>true</code> if this patcher fix is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this patcher fix is pending.
	 *
	 * @return <code>true</code> if this patcher fix is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this patcher fix is scheduled.
	 *
	 * @return <code>true</code> if this patcher fix is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.osb.patcher.model.PatcherFix patcherFix);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.osb.patcher.model.PatcherFix> toCacheModel();

	@Override
	public com.liferay.osb.patcher.model.PatcherFix toEscapedModel();

	@Override
	public com.liferay.osb.patcher.model.PatcherFix toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}