/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.osb.patcher.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PatcherFixPack service. Represents a row in the &quot;OSB_PatcherFixPack&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.osb.patcher.model.impl.PatcherFixPackModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.osb.patcher.model.impl.PatcherFixPackImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see PatcherFixPack
 * @see com.liferay.osb.patcher.model.impl.PatcherFixPackImpl
 * @see com.liferay.osb.patcher.model.impl.PatcherFixPackModelImpl
 * @generated
 */
public interface PatcherFixPackModel extends AuditedModel,
	BaseModel<PatcherFixPack> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patcher fix pack model instance should use the {@link PatcherFixPack} interface instead.
	 */

	/**
	 * Returns the primary key of this patcher fix pack.
	 *
	 * @return the primary key of this patcher fix pack
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patcher fix pack.
	 *
	 * @param primaryKey the primary key of this patcher fix pack
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patcher fix pack ID of this patcher fix pack.
	 *
	 * @return the patcher fix pack ID of this patcher fix pack
	 */
	public long getPatcherFixPackId();

	/**
	 * Sets the patcher fix pack ID of this patcher fix pack.
	 *
	 * @param patcherFixPackId the patcher fix pack ID of this patcher fix pack
	 */
	public void setPatcherFixPackId(long patcherFixPackId);

	/**
	 * Returns the company ID of this patcher fix pack.
	 *
	 * @return the company ID of this patcher fix pack
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this patcher fix pack.
	 *
	 * @param companyId the company ID of this patcher fix pack
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this patcher fix pack.
	 *
	 * @return the user ID of this patcher fix pack
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this patcher fix pack.
	 *
	 * @param userId the user ID of this patcher fix pack
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this patcher fix pack.
	 *
	 * @return the user uuid of this patcher fix pack
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this patcher fix pack.
	 *
	 * @param userUuid the user uuid of this patcher fix pack
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this patcher fix pack.
	 *
	 * @return the user name of this patcher fix pack
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this patcher fix pack.
	 *
	 * @param userName the user name of this patcher fix pack
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this patcher fix pack.
	 *
	 * @return the create date of this patcher fix pack
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this patcher fix pack.
	 *
	 * @param createDate the create date of this patcher fix pack
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this patcher fix pack.
	 *
	 * @return the modified date of this patcher fix pack
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this patcher fix pack.
	 *
	 * @param modifiedDate the modified date of this patcher fix pack
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the patcher build ID of this patcher fix pack.
	 *
	 * @return the patcher build ID of this patcher fix pack
	 */
	public long getPatcherBuildId();

	/**
	 * Sets the patcher build ID of this patcher fix pack.
	 *
	 * @param patcherBuildId the patcher build ID of this patcher fix pack
	 */
	public void setPatcherBuildId(long patcherBuildId);

	/**
	 * Returns the patcher fix component ID of this patcher fix pack.
	 *
	 * @return the patcher fix component ID of this patcher fix pack
	 */
	public long getPatcherFixComponentId();

	/**
	 * Sets the patcher fix component ID of this patcher fix pack.
	 *
	 * @param patcherFixComponentId the patcher fix component ID of this patcher fix pack
	 */
	public void setPatcherFixComponentId(long patcherFixComponentId);

	/**
	 * Returns the patcher project version ID of this patcher fix pack.
	 *
	 * @return the patcher project version ID of this patcher fix pack
	 */
	public long getPatcherProjectVersionId();

	/**
	 * Sets the patcher project version ID of this patcher fix pack.
	 *
	 * @param patcherProjectVersionId the patcher project version ID of this patcher fix pack
	 */
	public void setPatcherProjectVersionId(long patcherProjectVersionId);

	/**
	 * Returns the name of this patcher fix pack.
	 *
	 * @return the name of this patcher fix pack
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this patcher fix pack.
	 *
	 * @param name the name of this patcher fix pack
	 */
	public void setName(String name);

	/**
	 * Returns the version of this patcher fix pack.
	 *
	 * @return the version of this patcher fix pack
	 */
	public int getVersion();

	/**
	 * Sets the version of this patcher fix pack.
	 *
	 * @param version the version of this patcher fix pack
	 */
	public void setVersion(int version);

	/**
	 * Returns the released date of this patcher fix pack.
	 *
	 * @return the released date of this patcher fix pack
	 */
	public Date getReleasedDate();

	/**
	 * Sets the released date of this patcher fix pack.
	 *
	 * @param releasedDate the released date of this patcher fix pack
	 */
	public void setReleasedDate(Date releasedDate);

	/**
	 * Returns the requirements of this patcher fix pack.
	 *
	 * @return the requirements of this patcher fix pack
	 */
	@AutoEscape
	public String getRequirements();

	/**
	 * Sets the requirements of this patcher fix pack.
	 *
	 * @param requirements the requirements of this patcher fix pack
	 */
	public void setRequirements(String requirements);

	/**
	 * Returns the status of this patcher fix pack.
	 *
	 * @return the status of this patcher fix pack
	 */
	public int getStatus();

	/**
	 * Sets the status of this patcher fix pack.
	 *
	 * @param status the status of this patcher fix pack
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.osb.patcher.model.PatcherFixPack patcherFixPack);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.osb.patcher.model.PatcherFixPack> toCacheModel();

	@Override
	public com.liferay.osb.patcher.model.PatcherFixPack toEscapedModel();

	@Override
	public com.liferay.osb.patcher.model.PatcherFixPack toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}