modified.files.includes[relevant][portal-upload-servlet-request-filter-functional-rule]=**

modified.files.includes[relevant][portal-upload-servlet-request-filter-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-upload-servlet-request-filter-java-rule]=\
    apps/headless/headless-delivery/headless-delivery-test/**/BaseDocument*Test.java,\
    apps/headless/headless-delivery/headless-delivery-test/**/Document*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-upload-servlet-request-filter-java-rule]=\
    apps/headless/headless-delivery/headless-delivery-test/**/BaseDocument*Test.java,\
    apps/headless/headless-delivery/headless-delivery-test/**/Document*Test.java

relevant.rule.names=\
    portal-upload-servlet-request-filter-functional-rule,\
    portal-upload-servlet-request-filter-java-rule

test.batch.names[relevant][portal-upload-servlet-request-filter-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][portal-upload-servlet-request-filter-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][portal-upload-servlet-request-filter-functional-rule]=\
    (portal.acceptance == true) AND \
    (testray.component.names ~ "Documents and Media") AND \
    (testray.main.component.name ~ "Upgrades Collaboration")