modified.files.includes[relevant][frontend-data-set-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][frontend-data-set-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][frontend-data-set-java-rule]=\
    apps/frontend-data-set/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][frontend-data-set-java-rule]=\
    apps/frontend-data-set/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][frontend-data-set-playwright-rule]=\
    frontend-data-set-admin-web.main,\
    frontend-data-set-web.main

relevant.rule.names=\
    frontend-data-set-java-rule,\
    frontend-data-set-playwright-rule

test.batch.names[relevant][frontend-data-set-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][frontend-data-set-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Frontend Data Set