load("ext://restart_process", "docker_build_with_restart")
load("ext://uibutton", "cmd_button", "text_input")

ARGO_WORKFLOWS_CHART_VERSION = "2.0.3"

context = k8s_context()

if not context.startswith("k3d-"):
	fail(
	    (
	        "This Tiltfile targets a local k3d cluster, but the current " +
	        "kube context is '{}'. Switch with: " +
	        "kubectl config use-context k3d-<name>"
	    ).format(context)
	)

allow_k8s_contexts(context)

docker_build_with_restart(
    "liferay/liferay-dxp-operator",
    context="resources/build",
    dockerfile="Dockerfile",
    entrypoint="/home/nonroot/manager",
    live_update=[
        sync("resources/build/manager", "/home/nonroot/manager"),
    ],
    target="dev",
)

environments = {
    "non-production": {"desired_replicas": 1},
    "production": {"desired_replicas": 3},
    "uat": {"desired_replicas": 1},
}

def environment_yaml(name, desired_replicas):
	namespace = "liferay-" + name
	workload = name + "-liferay"

	return "\n".join(
	    [
	        "apiVersion: v1",
	        "kind: Namespace",
	        "metadata:",
	        "    labels:",
	        "        licensing.liferay.com/environment: \"true\"",
	        "    name: " + namespace,
	        "---",
	        "apiVersion: licensing.liferay.com/v1alpha1",
	        "kind: LiferayEnvironment",
	        "metadata:",
	        "    name: " + name,
	        "    namespace: " + namespace,
	        "spec:",
	        "    activationCodeSecretRef:",
	        "        key: activationCode",
	        "        name: " + name + "-activation",
	        "    desiredReplicas: " + str(desired_replicas),
	        "    dxpVersion: 2026.q3.0",
	        "    environmentName: \"" + name + "\"",
	        "    workloadRef:",
	        "        name: " + workload,
	        "---",
	        "apiVersion: apps/v1",
	        "kind: StatefulSet",
	        "metadata:",
	        "    name: " + workload,
	        "    namespace: " + namespace,
	        "spec:",
	        "    replicas: " + str(desired_replicas),
	        "    selector:",
	        "        matchLabels:",
	        "            app: " + workload,
	        "    serviceName: " + workload,
	        "    template:",
	        "        metadata:",
	        "            labels:",
	        "                app: " + workload,
	        "        spec:",
	        "            containers:",
	        "                -   image: registry.k8s.io/pause:3.9",
	        "                    name: liferay",
	        "---",
	        "apiVersion: v1",
	        "kind: ServiceAccount",
	        "metadata:",
	        "    name: online-activation-service-account",
	        "    namespace: " + namespace,
	        "---",
	        "apiVersion: rbac.authorization.k8s.io/v1",
	        "kind: RoleBinding",
	        "metadata:",
	        "    name: online-activation-role-binding",
	        "    namespace: " + namespace,
	        "roleRef:",
	        "    apiGroup: rbac.authorization.k8s.io",
	        "    kind: ClusterRole",
	        "    name: online-activation-cluster-role",
	        "subjects:",
	        "    -   kind: ServiceAccount",
	        "        name: online-activation-service-account",
	        "        namespace: " + namespace,
	    ]
	)

for name, values in environments.items():
	namespace = "liferay-" + name
	workload = name + "-liferay"

	cmd_button(
	    namespace + ":activate",
	    argv=[
	        "sh",
	        "-c",
	        "kubectl create secret generic " + name + "-activation" +
	        " --dry-run=client" +
	        " --from-literal=activationCode=\"$ACTIVATION_CODE\"" +
	        " --namespace " + namespace + " -o yaml | kubectl apply -f - && " +
	        "kubectl annotate --namespace " + namespace +
	        " --overwrite liferayenvironment " + name +
	        " tilt.dev/activate-requested=\"$(date +%s)\"",
	    ],
	    icon_name="key",
	    inputs=[
	        text_input("ACTIVATION_CODE", label="Activation code"),
	    ],
	    resource=namespace,
	    text="Activate with a new code",
	)

	k8s_resource(
	    labels=["environments"],
	    new_name=namespace,
	    objects=[
	        name + ":liferayenvironment",
	        namespace + ":namespace",
	        "online-activation-role-binding:rolebinding:" + namespace,
	        "online-activation-service-account:serviceaccount:" + namespace,
	    ],
	    resource_deps=[
	        "liferay-dxp-operator",
	        "online-activation",
	        "operator-infra",
	    ],
	)

	k8s_resource(
	    labels=["environments"],
	    resource_deps=[namespace],
	    workload=workload,
	)

	k8s_yaml(blob(environment_yaml(name, values["desired_replicas"])))

k8s_resource(
    labels=["activation"],
    links=[
        link(
            "http://localhost:2746/cluster-workflow-templates",
            "Submit online activation",
        ),
    ],
    new_name="online-activation",
    objects=[
        "online-activation-cluster-role:clusterrole",
        "online-activation-cluster-workflow-template:clusterworkflowtemplate",
    ],
    resource_deps=["argo-workflows"],
)

k8s_resource(
    labels=["activation"],
    new_name="argo-workflows-login",
    objects=[
        "argo-workflows-ui:clusterrole",
        "argo-workflows-ui:clusterrolebinding",
        "argo-workflows-ui:serviceaccount:argo-workflows-system",
        "argo-workflows-ui.service-account-token:secret:argo-workflows-system",
    ],
    resource_deps=["argo-workflows"],
)

k8s_resource(
    labels=["operator"],
    port_forwards=["8080:8080", "8081:8081"],
    resource_deps=["operator-build"],
    workload="liferay-dxp-operator",
)

k8s_resource(
    labels=["operator"],
    new_name="marketplace-dev",
    objects=[
        "marketplace-dev:persistentvolumeclaim",
    ],
    resource_deps=["operator-infra"],
)

k8s_resource(
    labels=["operator"],
    new_name="operator-infra",
    objects=[
        "liferay-dxp-operator-statefulset-scale:validatingadmissionpolicy",
        "liferay-dxp-operator-statefulset-scale:validatingadmissionpolicybinding",
        "liferay-dxp-operator:clusterrole",
        "liferay-dxp-operator:clusterrolebinding",
        "liferay-dxp-operator:serviceaccount",
        "liferay-system:namespace",
        "liferayenvironments.licensing.liferay.com:customresourcedefinition",
    ],
)

k8s_yaml(
    blob(
        "\n".join(
            [
                "apiVersion: v1",
                "kind: Namespace",
                "metadata:",
                "    name: liferay-system",
            ]
        )
    )
)

k8s_yaml(
    blob(
        "\n".join(
            [
                "apiVersion: v1",
                "kind: PersistentVolumeClaim",
                "metadata:",
                "    name: marketplace-dev",
                "    namespace: liferay-system",
                "spec:",
                "    accessModes:",
                "    -   ReadWriteOnce",
                "    resources:",
                "        requests:",
                "            storage: 1Gi",
                "    storageClassName: local-path",
            ]
        )
    )
)

k8s_yaml(
    helm(
        "../helm/dxp-operator",
        name="liferay-dxp-operator",
        namespace="liferay-system",
        set=[
            "debug=true",
            "gracePeriod=10m",
            "heartbeatInterval=30s",
            "image.repository=liferay/liferay-dxp-operator",
            "marketplace.claimName=marketplace-dev",
            "marketplace.enabled=true",
            "onlineActivationWorkflow.enabled=true",
            "podSecurityContext.fsGroup=65532",
            "provisioning.baseURL=https://api.one-uat.liferay.com",
            "retry.maxDelay=1m",
            "securityContext.readOnlyRootFilesystem=false",
        ],
    )
)

k8s_yaml(
    blob(
        "\n".join(
            [
                "apiVersion: v1",
                "kind: ServiceAccount",
                "metadata:",
                "    name: argo-workflows-ui",
                "    namespace: argo-workflows-system",
                "---",
                "apiVersion: v1",
                "kind: Secret",
                "metadata:",
                "    annotations:",
                "        kubernetes.io/service-account.name: argo-workflows-ui",
                "    name: argo-workflows-ui.service-account-token",
                "    namespace: argo-workflows-system",
                "type: kubernetes.io/service-account-token",
                "---",
                "apiVersion: rbac.authorization.k8s.io/v1",
                "kind: ClusterRole",
                "metadata:",
                "    name: argo-workflows-ui",
                "rules:",
                "    -   apiGroups: [\"\"]",
                "        resources: [\"namespaces\"]",
                "        verbs: [\"get\", \"list\", \"watch\"]",
                "    -   apiGroups: [\"\"]",
                "        resources: [\"pods\", \"pods/log\"]",
                "        verbs: [\"get\", \"list\", \"watch\"]",
                "    -   apiGroups: [\"argoproj.io\"]",
                "        resources: [\"clusterworkflowtemplates\", \"workflowtemplates\"]",
                "        verbs: [\"get\", \"list\", \"watch\"]",
                "    -   apiGroups: [\"argoproj.io\"]",
                "        resources: [\"workflows\"]",
                "        verbs: [\"create\", \"delete\", \"get\", \"list\", \"watch\"]",
                "---",
                "apiVersion: rbac.authorization.k8s.io/v1",
                "kind: ClusterRoleBinding",
                "metadata:",
                "    name: argo-workflows-ui",
                "roleRef:",
                "    apiGroup: rbac.authorization.k8s.io",
                "    kind: ClusterRole",
                "    name: argo-workflows-ui",
                "subjects:",
                "    -   kind: ServiceAccount",
                "        name: argo-workflows-ui",
                "        namespace: argo-workflows-system",
            ]
        )
    )
)

local_resource(
    "argo-workflows",
    cmd=" ".join(
        [
            "helm upgrade argo-workflows argo-workflows",
            "--create-namespace",
            "--install",
            "--namespace argo-workflows-system",
            "--repo https://argoproj.github.io/argo-helm",
            "--set executor.image.tag=v4.1.2-nonroot",
            "--version " + ARGO_WORKFLOWS_CHART_VERSION,
            "--wait",
        ]
    ),
    deps=["argo-workflows-values.yaml"],
    labels=["activation"],
)

local_resource(
    "argo-workflows-token",
    cmd=" ".join(
        [
            "until kubectl get secret argo-workflows-ui.service-account-token",
            "--namespace argo-workflows-system",
            "--output jsonpath=\"{.data.token}\" 2> /dev/null | grep --quiet .;",
            "do sleep 1; done;",
            "printf \"\\nPaste this into the Argo UI login:\\n\\nBearer %s\\n\\n\"",
            "\"$(kubectl get secret argo-workflows-ui.service-account-token",
            "--namespace argo-workflows-system",
            "--output jsonpath=\"{.data.token}\" | base64 --decode)\"",
        ]
    ),
    labels=["activation"],
    resource_deps=["argo-workflows-login"],
)

local_resource(
    "argo-workflows-ui",
    labels=["activation"],
    links=[link("http://localhost:2746", "Argo Workflows UI")],
    resource_deps=["argo-workflows"],
    serve_cmd=" ".join(
        [
            "kubectl port-forward",
            "--namespace argo-workflows-system",
            "service/argo-workflows-server",
            "2746:2746",
        ]
    ),
)

local_resource(
    "operator-build",
    cmd="./go_build.sh fast",
    deps=["resources"],
    ignore=[
        "resources/api/licensing/v1alpha1/zz_generated.deepcopy.go",
        "resources/build",
    ],
    labels=["operator"],
)