modified.files.includes[relevant][portal-workflow-kaleo-metrics-integration-functional-rule]=**

modified.files.includes[relevant][portal-workflow-kaleo-metrics-integration-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-workflow-kaleo-metrics-integration-java-rule]=\
    apps/portal-workflow/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-workflow-kaleo-metrics-integration-java-rule]=\
    apps/portal-workflow/**/*Test.java

relevant.rule.names=\
    portal-workflow-kaleo-metrics-integration-functional-rule,\
    portal-workflow-kaleo-metrics-integration-java-rule

test.batch.names[relevant][portal-workflow-kaleo-metrics-integration-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][portal-workflow-kaleo-metrics-integration-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade-tomcat*-mysql*][relevant][portal-workflow-kaleo-metrics-integration-functional-rule]=\
    (testray.main.component.name == "Upgrades Workflow")