<?xml version="1.0"?>

<project basedir="." default="compile" name="util-taglib">
	<import file="../build-common-java.xml" />

	<property name="deploy.dir" value="${app.server.lib.portal.dir}" />
	<property name="jar.file" value="${ant.project.name}" />
	<property name="manifest.bundle.name" value="Liferay Util Taglib" />
	<property name="manifest.bundle.symbolic.name" value="com.liferay.util.taglib" />

	<target name="build-taglibs">
		<java
			classname="com.liferay.alloy.tools.tagbuilder.TagBuilder"
			classpathref="project.classpath"
			fork="true"
			maxmemory="256m"
			newenvironment="true"
		>
			<jvmarg value="-Dtagbuilder.components.xml=${project.dir}/util-taglib/src/com/liferay/taglib/aui.xml,${project.dir}/util-taglib/src/com/liferay/taglib/liferay-aui.xml" />
			<jvmarg value="-Dtagbuilder.copyright.year=present" />
			<jvmarg value="-Dtagbuilder.java.dir=${project.dir}/util-taglib/src/com/liferay/taglib/" />
			<jvmarg value="-Dtagbuilder.java.package=com.liferay.taglib" />
			<jvmarg value="-Dtagbuilder.jsp.common.init.path=/html/taglib/taglib-init.jsp" />
			<jvmarg value="-Dtagbuilder.jsp.dir=/html/taglib/" />
			<jvmarg value="-Dtagbuilder.jsp.parent.dir=${project.dir}/portal-web/docroot/" />
			<jvmarg value="-Dtagbuilder.templates.dir=com/liferay/alloy/tools/tagbuilder/templates/" />
			<jvmarg value="-Dtagbuilder.tld.dir=${project.dir}/util-taglib/src/META-INF/" />
		</java>
	</target>

	<target depends="build-common-java.clean" name="clean">
		<delete failonerror="false" file="${liferay.home}/osgi/portal/${jar.file}.jar" />
	</target>

	<target depends="build-common-java.compile,download-latest-artifact,init-compile" name="compile" unless="${compile.uptodate}">
		<copy
			file="classes/META-INF/liferay-portlet_1_0.tld"
			preservelastmodified="true"
			tofile="classes/META-INF/liferay-portlet_1_0.tld"
		/>

		<replace
			file="classes/META-INF/liferay-portlet_1_0.tld"
		>
			<replacetoken><![CDATA[<short-name>portlet_1_0</short-name>]]></replacetoken>
			<replacevalue><![CDATA[<short-name>portlet</short-name>]]></replacevalue>
		</replace>

		<copy
			file="classes/META-INF/liferay-portlet.tld"
			preservelastmodified="true"
			tofile="classes/META-INF/liferay-portlet_2_0.tld"
		/>

		<replace
			file="classes/META-INF/liferay-portlet_2_0.tld"
		>
			<replacetoken><![CDATA[<uri>http://java.sun.com/portlet</uri>]]></replacetoken>
			<replacevalue><![CDATA[<uri>http://java.sun.com/portlet_2_0</uri>]]></replacevalue>
		</replace>
	</target>

	<target depends="build-common-java.deploy" name="deploy">
		<if>
			<equals arg1="${build.profile}" arg2="slim" />
			<then>
			</then>
			<elseif>
				<equals arg1="${app.server.type}" arg2="tomcat" />
				<then>
					<copy
						file="${jar.file}.jar"
						preservelastmodified="true"
						todir="${deploy.dir}"
					/>

					<copy
						preservelastmodified="true"
						todir="${app.server.portal.dir}/WEB-INF/tld"
					>
						<fileset
							dir="classes/META-INF"
							includes="*.tld"
						/>
					</copy>
				</then>
			</elseif>
		</if>
	</target>

	<target depends="build-common-java.init-jar" name="init-jar">
		<for param="file">
			<path>
				<fileset
					dir="classes/META-INF"
					includes="*.tld"
				/>
			</path>

			<sequential>
				<local name="filename" />

				<basename file="@{file}" property="filename" suffix=".tld" />

				<if>
					<available file="../modules/core/util-taglib-compat/tld/${filename}-compat" />
					<then>
						<local name="content" />

						<loadfile
							property="content"
							srcFile="../modules/core/util-taglib-compat/tld/${filename}-compat"
						/>

						<replace
							file="@{file}"
							value="${content}"
						>
							<replacetoken><![CDATA[</taglib>]]></replacetoken>
						</replace>

						<concat append="true" destfile="@{file}"><![CDATA[</taglib>]]></concat>
					</then>
				</if>
			</sequential>
		</for>
	</target>

	<target depends="build-common-java.jar" name="jar">
		<copy
			file="${jar.file}.jar"
			preservelastmodified="true"
			todir="${portal-impl.classes.dir}/com/liferay/portal/deploy/dependencies"
		/>

		<copy
			preservelastmodified="true"
			todir="${portal-impl.classes.dir}/com/liferay/portal/deploy/dependencies"
		>
			<fileset
				dir="classes/META-INF"
			/>
		</copy>

		<copy
			file="${jar.file}.jar"
			preservelastmodified="true"
			todir="${project.dir}/portal-web/docroot/WEB-INF/lib"
		/>

		<copy
			overwrite="true"
			preservelastmodified="true"
			todir="${project.dir}/portal-web/docroot/WEB-INF/tld"
		>
			<fileset
				dir="classes/META-INF"
				includes="*.tld"
			/>
		</copy>
	</target>

	<target depends="taglibdoc" name="jar-tlddoc">
		<zip
			destfile="util-taglib-tlddoc.jar"
		>
			<zipfileset
				dir="${doc.dir}/taglibs/util-taglib"
			/>
		</zip>
	</target>

	<target name="publish-portal-release">
		<publish-portal-artifact targets="jar,jar-javadoc,jar-sources,jar-tlddoc">
			<attach classifier="javadoc" file="${artifact.name}-javadoc.jar" />
			<attach classifier="sources" file="${artifact.name}-sources.jar" />
			<attach classifier="tlddoc" file="${artifact.name}-tlddoc.jar" />
		</publish-portal-artifact>
	</target>

	<target name="publish-portal-snapshot">
		<publish-portal-artifact snapshot="true" targets="jar,jar-javadoc,jar-sources,jar-tlddoc">
			<attach classifier="javadoc" file="${artifact.name}-javadoc.jar" />
			<attach classifier="sources" file="${artifact.name}-sources.jar" />
			<attach classifier="tlddoc" file="${artifact.name}-tlddoc.jar" />
		</publish-portal-artifact>
	</target>

	<target depends="validate-tld" name="taglibdoc">
		<property name="doc.taglibs.dir" value="${doc.dir}/taglibs/util-taglib" />

		<mkdir dir="${doc.taglibs.dir}" />

		<pathconvert pathsep=" " property="tld.files">
			<path>
				<fileset
					dir="${project.dir}/util-taglib/src/META-INF"
				>
					<include name="*.tld" />
				</fileset>
			</path>
		</pathconvert>

		<java
			classname="com.sun.tlddoc.TLDDoc"
			classpathref="project.classpath"
			failonerror="true"
			fork="true"
			maxmemory="256m"
		>
			<arg line="-d ${doc.taglibs.dir}" />
			<arg line="${tld.files}" />
			<arg line="-xslt ${project.dir}/tools/styles/taglibs" />
		</java>

		<copy
			overwrite="true"
			preservelastmodified="true"
			todir="${doc.taglibs.dir}/images"
		>
			<fileset
				dir="${project.dir}/util-taglib/src/META-INF/images"
			/>
		</copy>
	</target>

	<target name="validate-tld">
		<schemavalidate classname="org.xmlresolver.tools.ResolvingXMLReader" classpathref="lib.classpath">
			<fileset
				dir="${project.dir}/util-taglib/src/META-INF"
			>
				<include name="*.tld" />
				<exclude name="liferay-aui.tld" />
			</fileset>
		</schemavalidate>
	</target>
</project>
