modified.files.includes[relevant][server-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][server-java-rule]=\
    apps/server/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][server-java-rule]=\
    apps/server/**/*Test.java

relevant.rule.names=server-java-rule

test.batch.names[relevant][server-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Server Administration