modified.files.includes[relevant][journal-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][journal-web-playwright-rule]=\
    journal-web.main

relevant.rule.names=journal-web-playwright-rule

test.batch.names[relevant][journal-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Web Content