modified.files.includes[relevant][message-boards-web-functional-rule]=**
modified.files.includes[relevant][message-boards-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][message-boards-web-playwright-rule]=\
    message-boards-web.main

relevant.rule.names=\
    message-boards-web-functional-rule,\
    message-boards-web-playwright-rule

test.batch.names[relevant][message-boards-web-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][message-boards-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][message-boards-web-functional-rule]=\
    (testray.component.names == "Message Boards") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Message Boards