modified.files.includes[relevant][commerce-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][commerce-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][commerce-java-rule]=\
    apps/commerce/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][commerce-java-rule]=\
    apps/commerce/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][commerce-playwright-rule]=\
    commerce

relevant.rule.names=\
    commerce-java-rule,\
    commerce-playwright-rule

test.batch.names[relevant][commerce-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][commerce-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Commerce