modified.files.includes[relevant][on-demand-admin-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][on-demand-admin-java-rule]=\
    apps/on-demand-admin/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][on-demand-admin-java-rule]=\
    apps/on-demand-admin/**/*Test.java

relevant.rule.names=on-demand-admin-java-rule

test.batch.names[relevant][on-demand-admin-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=On Demand Admin