modified.files.includes[relevant][object-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][object-web-playwright-rule]=\
    object-web.main

relevant.rule.names=object-web-playwright-rule

test.batch.names[relevant][object-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Object