dependencies {
	testImplementation group: "com.liferay", name: "org.apache.commons.configuration", version: "1.10.LIFERAY-PATCHED-2"
	testImplementation group: "com.liferay.portal", name: "release.dxp.api", version: "2026.q1.5"

	testImplementation(group: "easyconf", name: "easyconf", version: "0.9.5") {
		exclude group: "struts"
		exclude group: "xdoclet"
		exclude group: "xpp3"
	}

	testImplementation group: "junit", name: "junit", version: "4.13.1"
	testImplementation group: "org.jabsorb", name: "jabsorb", version: "1.3.1"
	testImplementation group: "org.slf4j", name: "slf4j-api", version: "1.7.26"
	testImplementation project(":modules:osb-faro-api")
	testImplementation project(":modules:osb-faro-service")
	testIntegrationImplementation group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge", version: "1.0.21"
	testIntegrationImplementation group: "com.liferay.portal", name: "release.dxp.api", version: "2026.q1.5"
	testIntegrationImplementation group: "org.apache.logging.log4j", name: "log4j-api", version: "2.19.0"
	testIntegrationImplementation group: "org.apache.logging.log4j", name: "log4j-core", version: "2.19.0"
	testIntegrationImplementation project(":modules:osb-faro-api")
	testModules group: "com.liferay", name: "com.liferay.arquillian.extension.junit.bridge.connector", version: "1.0.1"
	testImplementation group: "com.liferay.portal", name: "com.liferay.portal.test", version: "32.6.2"
	testModules group: "com.liferay.portal", name: "com.liferay.portal.test", version: "32.6.2"
}

deploy {
	enabled = false
}