affinity: {}
customLabels: {}
fullnameOverride: ""
heartbeatInterval: 10m
image:
    pullPolicy: IfNotPresent
    pullSecrets: []
    repository: us-central1-docker.pkg.dev/external-assets-nonprd/liferay-cloud-native/liferay-dxp-operator
    tag: 0.0.1
metrics:
    port: 8080
nameOverride: ""
namespaceOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
        type: RuntimeDefault
probes:
    port: 8081
provisioning:
    baseURL: https://webserver-lrprovisioning.lfr.cloud
rbac:
    create: true
replicaCount: 1
resources:
    limits:
        cpu: 500m
        memory: 256Mi
    requests:
        cpu: 100m
        memory: 128Mi
securityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            -   ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
serviceAccount:
    annotations: {}
    create: true
    name: ""
tolerations: []