modified.files.includes[relevant][view-count-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][view-count-java-rule]=\
    apps/view-count/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][view-count-java-rule]=\
    apps/view-count/**/*Test.java

relevant.rule.names=view-count-java-rule

test.batch.names[relevant][view-count-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Util