buildService {
	apiDir = "../audiences-api/src/main/java"
	testDir = "../audiences-test/src/testIntegration/java"
}

dependencies {
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly project(":apps:audiences:audiences-api")
	compileOnly project(":apps:client-extension:client-extension-api")
	compileOnly project(":apps:client-extension:client-extension-type-api")
	compileOnly project(":apps:portal-url-builder:portal-url-builder-api")
	compileOnly project(":apps:portal-vulcan:portal-vulcan-api")
	compileOnly project(":apps:portal:portal-aop-api")
	compileOnly project(":apps:portal:portal-dao-orm-custom-sql-api")
	compileOnly project(":apps:portal:portal-json-validator")
	compileOnly project(":apps:segments:segments-api")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-sql-dsl-api")
	compileOnly project(":core:petra:petra-string")
}