apiDir: ../dispatch-rest-api/src/main/java
apiPackagePath: com.liferay.dispatch.rest
application:
    baseURI: /dispatch-rest
    className: DispatchRESTApplication
    name: Liferay.Dispatch.REST
author: Nilton Vieira
clientDir: ../dispatch-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../dispatch-rest-test/src/testIntegration/java