modified.files.includes[relevant][sanitizer-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][sanitizer-java-rule]=\
    apps/sanitizer/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][sanitizer-java-rule]=\
    apps/sanitizer/**/*Test.java

relevant.rule.names=sanitizer-java-rule

test.batch.names[relevant][sanitizer-java-rule]=\
    modules-integration-postgresql163

testray.main.component.name=AntiSamy