##
## Test Suites
##

    modified.files.includes[relevant][cookie-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=cookie-java-rule

    test.batch.names[relevant][cookie-java-rule]=\
        modules-integration-postgresql163,\
        modules-unit

    #
    # Relevant
    #

    ignoreParents[relevant][cookie-rule]=true

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][cookie-java-rule]=\
        **/cookies/**/src/test/**/*Test.java,\
        **/cookies/**/src/testIntegration/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][cookie-java-rule]=\
        **/cookies/**/src/test/**/*Test.java,\
        **/cookies/**/src/testIntegration/**/*Test.java

##
## Testray
##

    testray.main.component.name=Frontend JS