apiDir: ../headless-delivery-api/src/main/java
apiPackagePath: com.liferay.headless.delivery
application:
    baseURI: /headless-delivery
    className: HeadlessDeliveryApplication
    name: Liferay.Headless.Delivery
author: Javier Gamarra
changeTrackingEnabled: true
clientDir: ../headless-delivery-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../headless-delivery-test/src/testIntegration/java