modified.files.includes[relevant][portal-security-script-management-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][portal-security-script-management-web-playwright-rule]=\
    portal-security-script-management-web.main

relevant.rule.names=portal-security-script-management-web-playwright-rule

test.batch.names[relevant][portal-security-script-management-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Object