##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/apps/journal/journal-test/src/testIntegration/resources/com/liferay/journal/dependencies/test-journal-content-link-to-page-field-compatibility-expected-results.xml