modified.files.includes[relevant][journal-functional-rule]=**

modified.files.includes[relevant][journal-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][journal-java-rule]=\
    apps/headless/headless-delivery/**/src/testIntegration/**/*Test.java,\
    apps/journal/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][journal-java-rule]=\
    apps/headless/headless-delivery/**/src/test/**/*Test.java,\
    apps/journal/**/*Test.java

relevant.rule.names=\
    journal-functional-rule,\
    journal-java-rule

test.batch.names[relevant][journal-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][journal-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][journal-functional-rule]=\
    (portal.acceptance == true) AND \
    (testray.main.component.name ~ "Upgrades Content Management")

testray.main.component.name=Web Content