{{- if .Values.subscription.enabled -}}
apiVersion: v1
data:
    license.xml: ""
kind: Secret
metadata:
    annotations:
        helm.sh/resource-policy: keep
    labels:
        {{- include "liferay.labels" . | nindent 8 }}
    name: {{ include "liferay.licenseSecretName" . }}
    namespace: {{ include "liferay.namespace" . }}
type: Opaque
{{- end -}}