modified.files.includes[relevant][organizations-functional-rule]=**

modified.files.includes[relevant][organizations-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][organizations-java-rule]=\
    apps/organizations/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][organizations-java-rule]=\
    apps/organizations/**/*Test.java

relevant.rule.names=\
    organizations-functional-rule,\
    organizations-java-rule

test.batch.names[relevant][organizations-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][organizations-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][organizations-functional-rule]=\
    (portal.acceptance == true) AND \
    (testray.component.names ~ "Users and Organizations") AND \
    (testray.main.component.name ~ "Upgrades Foundation")

testray.main.component.name=Users and Organizations