modified.files.includes[relevant][portal-security-content-security-policy-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][portal-security-content-security-policy-playwright-rule]=\
    portal-security-content-security-policy.main

relevant.rule.names=portal-security-content-security-policy-playwright-rule

test.batch.names[relevant][portal-security-content-security-policy-playwright-rule]=\
    playwright-js-tomcat101-postgresql163

testray.main.component.name=Content Security Policy