modified.files.includes[relevant][client-extension-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][client-extension-web-playwright-rule]=\
    client-extension-web.cluster,\
    client-extension-web.main

relevant.rule.names=client-extension-web-playwright-rule

test.batch.names[relevant][client-extension-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57