modified.files.includes[relevant][portal-workflow-metrics-rest-spi-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-workflow-metrics-rest-spi-java-rule]=\
    apps/portal-workflow/**/*Test.java,\
    dxp/portal-workflow/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-workflow-metrics-rest-spi-java-rule]=\
    apps/portal-workflow/**/*Test.java,\
    dxp/portal-workflow/**/*Test.java

relevant.rule.names=portal-workflow-metrics-rest-spi-java-rule

test.batch.names[relevant][portal-workflow-metrics-rest-spi-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit