dependencies {
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "1.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "2.10.0"
	compileOnly group: "dom4j", name: "dom4j", version: "1.6.1"
	compileOnly group: "ch.qos.reload4j", name: "reload4j", version: "1.2.26"
}
