#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.portal.security.fips.rest.dto.v1_0.FIPSHealthVerification
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Crypto.Health.REST)
osgi.jaxrs.resource=true