modified.files.includes[relevant][notification-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][notification-java-rule]=\
    apps/notification/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][notification-java-rule]=\
    apps/notification/**/*Test.java

relevant.rule.names=notification-java-rule

test.batch.names[relevant][notification-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Notifications Framework