modified.files.includes[relevant][user-associated-data-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][user-associated-data-java-rule]=\
    apps/user-associated-data/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][user-associated-data-java-rule]=\
    apps/user-associated-data/**/*Test.java

relevant.rule.names=user-associated-data-java-rule

test.batch.names[relevant][user-associated-data-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Personal Data