modified.files.includes[relevant][reading-time-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][reading-time-java-rule]=\
    apps/reading-time/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][reading-time-java-rule]=\
    apps/reading-time/**/*Test.java

relevant.rule.names=reading-time-java-rule

test.batch.names[relevant][reading-time-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Blogs