apiDir: ../analytics-dxp-entity-rest-api/src/main/java
apiPackagePath: com.liferay.analytics.dxp.entity.rest
author: Marcos Martins, Rachael Koestartyo, Riccardo Ferrari
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
liferayEnterpriseApp: true