modified.files.includes[relevant][analytics-client-js-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat90-mysql57][relevant][analytics-client-js-playwright-rule]=\
    analytics-client-js.main

relevant.rule.names=analytics-client-js-playwright-rule

test.batch.names[relevant][analytics-client-js-playwright-rule]=\
    playwright-js-tomcat90-mysql57

testray.main.component.name=Analytics Cloud