##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.formatter.excludes=\
        modules/third-party/**/wsdl/**,\
        modules/third-party/org-apache-felix-scr/src/main/java/org/apache/felix/scr/impl/inject/ReflectionUtil.java,\
        modules/third-party/org-eclipse-osgi/src/main/java/**