##
## Test Suites
##

    modified.files.includes[relevant][portal-remote-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=portal-remote-java-rule

    test.batch.names[relevant][portal-remote-java-rule]=\
        modules-integration-postgresql155,\
        modules-unit

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql155][relevant][portal-remote-java-rule]=\
        apps/portal-remote/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-remote-java-rule]=\
        apps/portal-remote/**/*Test.java

##
## Testray
##

    testray.main.component.name=Web Services