modified.files.includes[relevant][portal-remote-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-remote-java-rule]=\
    apps/portal-remote/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-remote-java-rule]=\
    apps/portal-remote/**/*Test.java

relevant.rule.names=portal-remote-java-rule

test.batch.names[relevant][portal-remote-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Web Services