modified.files.includes[relevant][company-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][company-java-rule]=\
    apps/company/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][company-java-rule]=\
    apps/company/**/*Test.java

relevant.rule.names=company-java-rule

test.batch.names[relevant][company-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Virtual Instances