modified.files.includes[relevant][layout-locked-layouts-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][layout-locked-layouts-web-playwright-rule]=\
    layout-locked-layouts-web.main

relevant.rule.names=layout-locked-layouts-web-playwright-rule

test.batch.names[relevant][layout-locked-layouts-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Content Pages