apiDir: ../digital-signature-rest-api/src/main/java
apiPackagePath: com.liferay.digital.signature.rest
application:
    baseURI: /digital-signature-rest
    className: DigitalSignatureRESTApplication
    name: Liferay.Digital.Signature.REST
author: José Abelenda
clientDir: ../digital-signature-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
javaEEPackage: jakarta
testDir: ../digital-signature-rest-test/src/testIntegration/java