dependencies {
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-annotations", version: "2.18.6"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-core", version: "2.18.6"
	compileInclude group: "com.fasterxml.jackson.core", name: "jackson-databind", version: "2.18.6"
	compileInclude group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jdk8", version: "2.18.6"
	compileInclude group: "com.fasterxml.jackson.datatype", name: "jackson-datatype-jsr310", version: "2.18.6"
	compileInclude group: "com.google.api", name: "api-common", version: "2.43.0"
	compileInclude group: "com.google.api", name: "gax", version: "2.60.0"
	compileInclude group: "com.google.api", name: "gax-grpc", version: "2.60.0"
	compileInclude group: "com.google.api", name: "gax-httpjson", version: "2.60.0"
	compileInclude group: "com.google.api.grpc", name: "proto-google-cloud-modelarmor-v1", version: "0.23.0"
	compileInclude group: "com.google.api.grpc", name: "proto-google-cloud-modelarmor-v1beta", version: "0.23.0"
	compileInclude group: "com.google.api.grpc", name: "proto-google-common-protos", version: "2.51.0"
	compileInclude group: "com.google.api.grpc", name: "proto-google-iam-v1", version: "1.46.0"
	compileInclude group: "com.google.auth", name: "google-auth-library-credentials", version: "1.31.0"
	compileInclude group: "com.google.auth", name: "google-auth-library-oauth2-http", version: "1.31.0"
	compileInclude group: "com.google.cloud", name: "google-cloud-modelarmor", version: "0.23.0"
	compileInclude group: "com.google.code.gson", name: "gson", version: "2.9.0"
	compileInclude group: "com.google.genai", name: "google-genai", version: "1.59.0"
	compileInclude group: "com.google.guava", name: "failureaccess", version: "1.0.3"
	compileInclude group: "com.google.guava", name: "guava", version: "32.0.1-jre"
	compileInclude group: "com.google.guava", name: "listenablefuture", version: "9999.0-empty-to-avoid-conflict-with-guava"
	compileInclude group: "com.google.http-client", name: "google-http-client", version: "1.45.3"
	compileInclude group: "com.google.http-client", name: "google-http-client-gson", version: "1.45.3"
	compileInclude group: "com.google.j2objc", name: "j2objc-annotations", version: "3.1"
	compileInclude group: "com.google.protobuf", name: "protobuf-java", version: "3.25.5"
	compileInclude group: "com.google.protobuf", name: "protobuf-java-util", version: "3.25.5"
	compileInclude group: "com.google.re2j", name: "re2j", version: "1.8"
	compileInclude group: "com.squareup.okhttp3", name: "okhttp", version: "4.12.0"
	compileInclude group: "com.squareup.okhttp3", name: "okhttp-sse", version: "4.12.0"
	compileInclude group: "com.squareup.okio", name: "okio", version: "3.6.0"
	compileInclude group: "com.squareup.okio", name: "okio-jvm", version: "3.6.0"
	compileInclude group: "commons-codec", name: "commons-codec", version: "1.15"
	compileInclude group: "dev.langchain4j", name: "langchain4j", version: "1.17.1"
	compileInclude group: "dev.langchain4j", name: "langchain4j-agentic", version: "1.17.1-beta27"
	compileInclude group: "dev.langchain4j", name: "langchain4j-core", version: "1.17.1"
	compileInclude group: "dev.langchain4j", name: "langchain4j-google-genai", version: "1.17.1-beta27"
	compileInclude group: "dev.langchain4j", name: "langchain4j-guardrails", version: "1.17.1-beta27"
	compileInclude group: "dev.langchain4j", name: "langchain4j-http-client", version: "1.17.1"
	compileInclude group: "dev.langchain4j", name: "langchain4j-mcp", version: "1.17.1-beta27"
	compileInclude group: "io.grpc", name: "grpc-alts", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-api", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-auth", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-context", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-core", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-googleapis", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-grpclb", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-inprocess", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-netty-shaded", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-protobuf", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-protobuf-lite", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-services", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-stub", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-util", version: "1.75.0"
	compileInclude group: "io.grpc", name: "grpc-xds", version: "1.75.0"
	compileInclude group: "io.opencensus", name: "opencensus-api", version: "0.31.1"
	compileInclude group: "io.opencensus", name: "opencensus-contrib-http-util", version: "0.31.1"
	compileInclude group: "io.perfmark", name: "perfmark-api", version: "0.27.0"
	compileInclude group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.13"
	compileInclude group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.14"
	compileInclude group: "org.apache.opennlp", name: "opennlp-tools", version: "2.5.9"
	compileInclude group: "org.java-websocket", name: "Java-WebSocket", version: "1.6.0"
	compileInclude group: "org.jetbrains", name: "annotations", version: "13.0"
	compileInclude group: "org.jetbrains.kotlin", name: "kotlin-stdlib", version: "1.8.21"
	compileInclude group: "org.jetbrains.kotlin", name: "kotlin-stdlib-common", version: "1.8.21"
	compileInclude group: "org.jetbrains.kotlin", name: "kotlin-stdlib-jdk7", version: "1.8.21"
	compileInclude group: "org.jetbrains.kotlin", name: "kotlin-stdlib-jdk8", version: "1.8.21"
	compileInclude group: "org.jspecify", name: "jspecify", version: "1.0.0"
	compileInclude group: "org.threeten", name: "threetenbp", version: "1.7.0"
	compileOnly group: "com.liferay", name: "biz.aQute.bnd.annotation", version: "4.2.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay", name: "jakarta.ws.rs", version: "3.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.cm", version: "1.6.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:account:account-api")
	compileOnly project(":apps:batch-engine:batch-engine-api")
	compileOnly project(":apps:configuration-admin:configuration-admin-api")
	compileOnly project(":apps:layout:layout-utility-page-api")
	compileOnly project(":apps:oauth2-provider:oauth2-provider-api")
	compileOnly project(":apps:object:object-admin-rest-api")
	compileOnly project(":apps:object:object-api")
	compileOnly project(":apps:object:object-rest-api")
	compileOnly project(":apps:portal-configuration:portal-configuration-module-configuration-api")
	compileOnly project(":apps:portal-odata:portal-odata-api")
	compileOnly project(":apps:portal-search:portal-search-api")
	compileOnly project(":apps:portal-search:portal-search-engine-adapter-api")
	compileOnly project(":apps:portal-search:portal-search-rest-api")
	compileOnly project(":apps:portal-search:portal-search-spi")
	compileOnly project(":apps:portal-security:portal-security-service-access-policy-api")
	compileOnly project(":apps:portal-vulcan:portal-vulcan-api")
	compileOnly project(":apps:portal-workflow:portal-workflow-api")
	compileOnly project(":apps:portal-workflow:portal-workflow-kaleo-api")
	compileOnly project(":apps:portal-workflow:portal-workflow-kaleo-definition-api")
	compileOnly project(":apps:portal-workflow:portal-workflow-kaleo-runtime-api")
	compileOnly project(":apps:portal:portal-instance-lifecycle-api")
	compileOnly project(":apps:site:site-api")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
	compileOnly project(":core:osgi-service-tracker-collections")
	compileOnly project(":core:petra:petra-concurrent")
	compileOnly project(":core:petra:petra-executor")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-reflect")
	compileOnly project(":core:petra:petra-string")
	compileOnly project(":dxp:apps:ai-hub:ai-hub-api")
	compileOnly project(":dxp:apps:ai-hub:ai-hub-rest-api")
}