modified.files.includes[relevant][sharing-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][sharing-java-rule]=\
    apps/sharing/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][sharing-java-rule]=\
    apps/sharing/**/*Test.java

relevant.rule.names=sharing-java-rule

test.batch.names[relevant][sharing-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Asset Sharing