modified.files.includes[relevant][portal-language-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][portal-language-rule]=\
    apps/portal-language/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][portal-language-rule]=\
    apps/portal-language/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant]=\
    portal-language-override-web.client-extension,\
    portal-language-override-web.main

relevant.rule.names=portal-language-rule

test.batch.names[relevant][portal-language-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
    (portal.acceptance == true) AND \
    (\
        (testray.component.names ~ "Language Override") OR \
        (testray.main.component.name ~ "Language Override")\
    )

testray.main.component.name=Language Override