dependencies {
	compileOnly group: "com.liferay", name: "jakarta.ws.rs", version: "3.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.osgi.service.jaxrs", version: "1.0.0.JAKARTA_LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.jakarta.portlet", name: "com.liferay.jakarta.portlet-api", version: "4.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib", version: "default"
	compileOnly group: "jakarta.servlet", name: "jakarta.servlet-api", version: "6.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.4.0"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
	compileOnly project(":apps:account:account-api")
	compileOnly project(":apps:application-list:application-list-api")
	compileOnly project(":apps:asset:asset-taglib")
	compileOnly project(":apps:expando:expando-api")
	compileOnly project(":apps:expando:expando-taglib")
	compileOnly project(":apps:frontend-taglib:frontend-taglib")
	compileOnly project(":apps:frontend-taglib:frontend-taglib-clay")
	compileOnly project(":apps:frontend-taglib:frontend-taglib-react")
	compileOnly project(":apps:login:login-web-api")
	compileOnly project(":apps:oauth2-provider:oauth2-provider-scope-api")
	compileOnly project(":apps:portal-configuration:portal-configuration-module-configuration-api")
	compileOnly project(":apps:portal:portal-aop-api")
	compileOnly project(":apps:portal:portal-instance-lifecycle-api")
	compileOnly project(":apps:product-navigation:product-navigation-personal-menu-api")
	compileOnly project(":apps:roles:roles-admin-api")
	compileOnly project(":apps:site-navigation:site-navigation-taglib")
	compileOnly project(":apps:static:portal-configuration:portal-configuration-metatype-api")
	compileOnly project(":apps:text-localizer:text-localizer-taglib")
	compileOnly project(":apps:user:user-taglib")
	compileOnly project(":apps:users-admin:users-admin-api")
	compileOnly project(":core:petra:petra-function")
	compileOnly project(":core:petra:petra-lang")
	compileOnly project(":core:petra:petra-sql-dsl-api")
	compileOnly project(":core:petra:petra-string")
}