modified.files.includes[relevant][account-admin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][account-admin-web-playwright-rule]=\
    account-admin-web.main

relevant.rule.names=account-admin-web-playwright-rule

test.batch.names[relevant][account-admin-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57