modified.files.includes[relevant][password-policy-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][password-policy-java-rule]=\
    apps/password-policy/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][password-policy-java-rule]=\
    apps/password-policy/**/*Test.java

relevant.rule.names=password-policy-java-rule

test.batch.names[relevant][password-policy-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Password Policies