dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation group: "org.hibernate.orm", name: "hibernate-core", version: "7.1.4.Final"
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-api")
	testIntegrationImplementation project(":apps:object:object-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
	testIntegrationImplementation project(":util:portal-tools-service-builder-test-api")
}