dependencies {
	testIntegrationImplementation group: "com.liferay", name: "org.hibernate.core", version: "5.6.7.LIFERAY-PATCHED-2.JAKARTA_LIFERAY-PATCHED-1"
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-api")
	testIntegrationImplementation project(":apps:object:object-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
	testIntegrationImplementation project(":util:portal-tools-service-builder-test-api")
}