modified.files.includes[relevant][depot-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][depot-java-rule]=\
    apps/depot/**/*Test.java,\
    apps/portal-security/portal-security-permission-test/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][depot-java-rule]=\
    apps/depot/**/*Test.java,\
    apps/portal-security/portal-security-permission-test/**/*Test.java

relevant.rule.names=depot-java-rule

test.batch.names[relevant][depot-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Asset Libraries