<?xml version="1.0"?>
<!DOCTYPE project>

<project basedir="." default="deploy" name="opensocial-portlet">
	<property name="compile.jsp.docroot.dir" value="tmp" />
	<property name="original.war.file" value="shindig-server-2.0.2.war" />

	<import file="../../../../tools/sdk/portlets/build-common-portlet.xml" />

	<target name="merge">

		<!-- Delete unused Shindig directories -->

		<delete dir="tmp/editor" />
		<delete dir="tmp/samplecontainer" />
		<delete dir="tmp/sampledata" />

		<!-- Merge -->

		<merge
			module.dir="${basedir}"
		/>

		<!-- Configure Modules -->

		<copy
			file="tmp/WEB-INF/web.xml.original"
			overwrite="true"
			tofile="tmp/WEB-INF/web.xml"
		/>

		<replace
			file="tmp/WEB-INF/web.xml"
		>
			<replacefilter
				token="org.apache.shindig.common.servlet.GuiceServletContextListener"
				value="com.liferay.opensocial.shindig.servlet.GuiceServletContextListener"
			/>
			<replacefilter
				token="org.apache.shindig.gadgets.oauth.OAuthModule"
				value="com.liferay.opensocial.shindig.oauth.LiferayOAuthModule"
			/>
			<replacefilter
				token="org.apache.shindig.sample.container.SampleContainerGuiceModule:"
				value=""
			/>
			<replacefilter
				token="org.apache.shindig.sample.shiro.ShiroGuiceModule:"
				value=""
			/>
			<replacefilter
				token="org.apache.shindig.social.sample.SampleModule"
				value="com.liferay.opensocial.shindig.guice.LiferayModule"
			/>
		</replace>

		<!-- Replace Servlet -->

		<replace
			file="tmp/WEB-INF/web.xml"
		>
			<replacefilter
				token="org.apache.shindig.gadgets.servlet.JsServlet"
				value="com.liferay.opensocial.shindig.servlet.JsServlet"
			/>
		</replace>

		<!-- Remove system.properties -->

		<replaceregexp
			file="tmp/WEB-INF/web.xml"
			flags="gs"
			match="&lt;context-param&gt;(\s*?)&lt;param-name&gt;system.properties(.*?)context-param&gt;"
			replace=""
		/>

		<!-- Remove Shiro Filter -->

		<replaceregexp
			file="tmp/WEB-INF/web.xml"
			flags="gs"
			match="&lt;filter&gt;(\s*?)&lt;filter-name&gt;ShiroFilter(.*?)filter&gt;"
			replace=""
		/>

		<replaceregexp
			file="tmp/WEB-INF/web.xml"
			flags="gs"
			match="&lt;filter-mapping&gt;(\s*?)&lt;filter-name&gt;ShiroFilter(.*?)filter-mapping&gt;"
			replace=""
		/>

		<!-- Convert Mappings for Servlet 2.4 Compliance -->

		<replace
			file="tmp/WEB-INF/web.xml"
		>
			<replacefilter
				token="http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
				value="http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
			/>
			<replacefilter
				token="http://java.sun.com/xml/ns/javaee"
				value="http://java.sun.com/xml/ns/j2ee"
			/>
			<replacefilter
				token="id=&quot;Shindig&quot;"
				value=""
			/>
			<replacefilter
				token="version=&quot;2.5&quot;"
				value="version=&quot;2.4&quot;"
			/>
		</replace>

		<replaceregexp
			file="tmp/WEB-INF/web.xml"
			flags="gs"
			match="&lt;filter-mapping&gt;(\s*?)&lt;filter-name&gt;authFilter(.*?)filter-mapping&gt;"
			replace="@AUTH_FILTER_TOKEN@"
		/>

		<replaceregexp
			file="tmp/WEB-INF/web.xml"
			flags="gs"
			match="&lt;servlet-mapping&gt;(\s*?)&lt;servlet-name&gt;jsonRpcServlet(.*?)servlet-mapping&gt;"
			replace="@JSON_RPC_SERVLET_TOKEN@"
		/>

		<replaceregexp
			file="tmp/WEB-INF/web.xml"
			flags="gs"
			match="&lt;servlet-mapping&gt;(\s*?)&lt;servlet-name&gt;restapiServlet(.*?)servlet-mapping&gt;"
			replace="@REST_API_SERVLET_TOKEN@"
		/>

		<replace
			file="tmp/WEB-INF/web.xml"
			propertyFile="docroot/WEB-INF/web.xml.properties"
		>
			<replacefilter
				property="auth.filter.replace"
				token="@AUTH_FILTER_TOKEN@"
			/>
			<replacefilter
				property="json.rpc.servlet.replace"
				token="@JSON_RPC_SERVLET_TOKEN@"
			/>
			<replacefilter
				property="rest.api.servlet.replace"
				token="@REST_API_SERVLET_TOKEN@"
			/>
		</replace>

		<!-- Merge web.xml -->

		<java
			classname="com.liferay.portal.tools.WebXMLBuilder"
			classpathref="portal.classpath"
			fork="true"
			newenvironment="true"
		>
			<jvmarg value="-Dexternal-properties=com/liferay/portal/tools/dependencies/portal-tools.properties" />
			<arg value="tmp/WEB-INF/web.xml" />
			<arg value="docroot/WEB-INF/web.xml" />
			<arg value="tmp/WEB-INF/web.xml" />
		</java>

		<!-- Configure container.js -->

		<antcall target="merge-backup-file">
			<param name="backup.file.name" value="tmp/WEB-INF/classes/containers/default/container.js" />
		</antcall>

		<replace
			file="tmp/WEB-INF/classes/containers/default/container.js"
		>
			<replacefilter
				token="${SERVER_HOST}:${SERVER_PORT}"
				value="%host%"
			/>
			<replacefilter
				token="/gadgets/"
				value="/o/opensocial-portlet/gadgets/"
			/>
			<replacefilter
				token="/rpc"
				value="/o/opensocial-portlet/rpc"
			/>
		</replace>

		<replace
			file="tmp/WEB-INF/classes/containers/default/container.js"
		>
			<replacetoken>"profile" : {</replacetoken>
			<replacevalue><![CDATA[
				"home" : {
					"isOnlyVisible" : true,
					"urlTemplate" : "http://%host%/o/opensocial-portlet/gadgets/home{var}"
				},
				"profile" : {]]>
			</replacevalue>
		</replace>

		<antcall target="strip-comments">
			<param name="strip.comments.file" value="tmp/WEB-INF/classes/containers/default/container.js" />
			<param name="strip.comments.encoding" value="utf-8" />
		</antcall>

		<replace
			file="tmp/WEB-INF/classes/containers/default/container.js"
		>
			<replacetoken>"gadgets.uri.iframe.lockedDomainSuffix" :  "-a.example.com:8080",</replacetoken>
			<replacevalue></replacevalue>
		</replace>

		<replace
			file="tmp/WEB-INF/classes/containers/default/container.js"
		>
			<replacetoken>"gadgets.uri.iframe.unlockedDomain" : "www.example.com:8080",</replacetoken>
			<replacevalue></replacevalue>
		</replace>

		<replace
			file="tmp/WEB-INF/classes/containers/default/container.js"
		>
			<replacetoken>"gadgets.uri.js.host" : "http://www.example.com/",</replacetoken>
			<replacevalue></replacevalue>
		</replace>

		<replace
			file="tmp/WEB-INF/classes/containers/default/container.js"
		>
			<replacetoken>"gadgets.uri.js.path" : "/o/opensocial-portlet/gadgets/js",</replacetoken>
			<replacevalue></replacevalue>
		</replace>

		<replaceregexp
			byline="false"
			flags="g"
			match="(&quot;gadgets\.uri\.iframe\.basePath&quot; : &quot;.*?&quot;[\s\S]*)&quot;gadgets\.uri\.iframe\.basePath&quot; : &quot;.*?&quot;,"
			replace="\1"
		>
			<fileset
				dir="tmp/WEB-INF/classes/containers/default/"
				includes="container.js"
			/>
		</replaceregexp>

		<!-- Configure oauth.json -->

		<antcall target="merge-backup-file">
			<param name="backup.file.name" value="tmp/WEB-INF/classes/config/oauth.json" />
		</antcall>

		<replace
			file="tmp/WEB-INF/classes/config/oauth.json"
		>
			<replacefilter
				token="http://localhost:8080/"
				value="http://localhost:8080/o/opensocial-portlet/"
			/>
		</replace>

		<!-- Configure shindig.properties -->

		<if>
			<not>
				<available file="tmp/WEB-INF/classes/shindig.properties.original" />
			</not>
			<then>
				<unzip
					dest="tmp/WEB-INF/classes"
					src="tmp/WEB-INF/lib/shindig-common-2.0.2.jar"
				>
					<patternset
						includes="**/shindig.properties"
					/>
					<chainedmapper>
						<flattenmapper />
						<globmapper
							from="shindig.properties"
							to="shindig.properties.original"
						/>
					</chainedmapper>
				</unzip>
			</then>
		</if>

		<copy
			file="tmp/WEB-INF/classes/shindig.properties.original"
			overwrite="true"
			tofile="tmp/WEB-INF/classes/shindig.properties"
		/>

		<replace
			file="tmp/WEB-INF/classes/shindig.properties"
		>
			<replacefilter
				token="/gadgets/"
				value="/o/opensocial-portlet/gadgets/"
			/>
			<replacefilter
				token="shindig.signing.viewer-access-tokens-enabled=false"
				value="shindig.signing.viewer-access-tokens-enabled=true"
			/>
		</replace>

		<!-- Delete Xerces -->

		<delete file="tmp/WEB-INF/lib/xercesImpl-2.9.1.jar" />
		<delete file="tmp/WEB-INF/lib/xml-apis-1.3.04.jar" />

		<!-- Delete XStream -->

		<delete file="tmp/WEB-INF/lib/xstream-1.3.1.jar" />

		<!-- Delete Shiro (filter and module already stripped above; CVE-2010-3863, CVE-2014-0074) -->

		<delete file="tmp/WEB-INF/lib/shiro-core-1.0.0-incubating.jar" />
		<delete file="tmp/WEB-INF/lib/shiro-web-1.0.0-incubating.jar" />
		<delete dir="tmp/WEB-INF/classes/org/apache/shindig/sample/shiro" />

		<!-- Fix canonicaldb.json -->

		<tstamp>
			<format pattern="yyyyMMddkkmmssSSS" property="tstamp.value" />
		</tstamp>

		<unjar
			dest="${tstamp.value}"
			src="tmp/WEB-INF/lib/shindig-social-api-2.0.2.jar"
		/>

		<antcall target="strip-comments">
			<param name="strip.comments.file" value="${tstamp.value}/sampledata/canonicaldb.json" />
			<param name="strip.comments.encoding" value="utf-8" />
		</antcall>

		<delete file="tmp/WEB-INF/lib/shindig-social-api-2.0.2.jar" />

		<jar
			basedir="${tstamp.value}"
			destfile="tmp/WEB-INF/lib/shindig-social-api-2.0.2.jar"
		/>

		<delete dir="${tstamp.value}" />

		<!-- OpenAjax Hub -->

		<if>
			<not>
				<available file="tmp/gadget/js/OpenAjax_Hub_2.0.5_r1293" />
			</not>
			<then>
				<unzip
					dest="tmp/gadget/js"
					src="OpenAjax_Hub_2.0.5_r1293.zip"
				/>
			</then>
		</if>

		<!-- LPS-14616 -->

		<antcall target="patch">
			<param name="patch.destination" value="org/apache/shindig/social/opensocial/model/MediaItem.java" />
			<param name="patch.original.lib.name" value="shindig-social-api" />
			<param name="patch.original.lib.url" value="http://search.maven.org/remotecontent?filepath=org/apache/shindig" />
			<param name="patch.original.lib.version" value="2.0.2" />
			<param name="patch.source" value="patches/LPS-14616.patch" />
		</antcall>

		<!-- LPS-15003 -->

		<antcall target="patch">
			<param name="patch.destination" value="features/rpc/rpc.js" />
			<param name="patch.original.lib.name" value="shindig-features" />
			<param name="patch.original.lib.url" value="http://search.maven.org/remotecontent?filepath=org/apache/shindig" />
			<param name="patch.original.lib.version" value="2.0.2" />
			<param name="patch.source" value="patches/LPS-15003.patch" />
		</antcall>

		<!-- LPS-21488 -->

		<antcall target="patch">
			<param name="patch.destination" value="org/apache/shindig/gadgets/oauth/OAuthRequest.java" />
			<param name="patch.original.lib.name" value="shindig-gadgets" />
			<param name="patch.original.lib.url" value="http://search.maven.org/remotecontent?filepath=org/apache/shindig" />
			<param name="patch.original.lib.version" value="2.0.2" />
			<param name="patch.source" value="patches/LPS-21488.patch" />
		</antcall>
	</target>

	<target name="merge-backup-file">
		<if>
			<not>
				<available file="${backup.file.name}.original" />
			</not>
			<then>
				<copy
					file="${backup.file.name}"
					tofile="${backup.file.name}.original"
				/>
			</then>
		</if>

		<copy
			file="${backup.file.name}.original"
			overwrite="true"
			tofile="${backup.file.name}"
		/>
	</target>

	<target name="merge-unzip">
		<merge-unzip
			module.dir="${basedir}"
		/>

		<copy
			file="tmp/WEB-INF/web.xml"
			overwrite="true"
			tofile="tmp/WEB-INF/web.xml.original"
		/>
	</target>

	<target name="strip-comments">
		<replaceregexp
			encoding="${strip.comments.encoding}"
			file="${strip.comments.file}"
			flags="gs"
			match="\s*/[*].*?[*]/\s*"
			replace=""
		/>

		<replaceregexp
			byline="true"
			encoding="${strip.comments.encoding}"
			file="${strip.comments.file}"
			match="^\s*(//)(.*)$$"
			replace=""
		/>
	</target>
</project>