create table CommerceCurrency (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	commerceCurrencyId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	code_ VARCHAR(75) null,
	name STRING null,
	symbol VARCHAR(75) null,
	rate BIGDECIMAL null,
	formatPattern STRING null,
	maxFractionDigits INTEGER,
	minFractionDigits INTEGER,
	roundingMode VARCHAR(75) null,
	primary_ BOOLEAN,
	priority DOUBLE,
	active_ BOOLEAN,
	lastPublishDate DATE null,
	status INTEGER
);