configurations {
	compileOnly {
		transitive = false
	}
}

dependencies {
	compileOnly group: "com.fasterxml", name: "classmate", version: "1.5.1"
	compileOnly group: "net.bytebuddy", name: "byte-buddy", version: "1.15.11"
	compileOnly group: "org.antlr", name: "antlr4-runtime", version: "4.13.2"
	compileOnly group: "org.hibernate.models", name: "hibernate-models", version: "1.0.1"
	compileOnly group: "org.jboss.logging", name: "jboss-logging", version: "3.6.1.Final"
}

deploy {
	setActions([])

	dependsOn = []
}

deployDependencies {
	from configurations.compileOnly
	rename(/antlr-(.+)\.jar/, "antlr" + renameSuffix)
}