#
# This is a generated file.
#

api.version=v1.0
openapi.resource=true
openapi.resource.path=/site-dsr-analytics-rest
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Site.DSR.Analytics.REST)
osgi.jaxrs.resource=true