include-and-override=portal-upgrade-ext.properties
liferay.home=../../
schema.run.enabled=false
hibernate.jdbc.batch_size=250
index.on.startup=false
dependency.manager.thread.pool.enabled=false
initial.system.check.enabled=false
module.framework.properties.blacklist.portal.profile.names=com.liferay.portal.properties.swapper
module.framework.properties.osgi.console=localhost:11311
scheduler.enabled=false