modified.files.includes[relevant][info-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][info-java-rule]=\
    apps/info/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][info-java-rule]=\
    apps/info/**/*Test.java

relevant.rule.names=info-java-rule

test.batch.names[relevant][info-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Info Framework