modified.files.includes[relevant][document-library-opener-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][document-library-opener-java-rule]=\
    apps/document-library-opener/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][document-library-opener-java-rule]=\
    apps/document-library-opener/**/*Test.java

relevant.rule.names=document-library-opener-java-rule

test.batch.names[relevant][document-library-opener-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=External Document Repositories