modified.files.includes[relevant][questions-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][questions-web-playwright-rule]=\
    questions-web.main

relevant.rule.names=questions-web-playwright-rule

test.batch.names[relevant][questions-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57