/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.oauth.client.persistence.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.oauth.client.persistence.model.OAuthClientPRLocalMetadata;
import com.liferay.oauth.client.persistence.model.OAuthClientPRLocalMetadataModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OAuthClientPRLocalMetadata service. Represents a row in the &quot;OAuthClientPRLocalMetadata&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OAuthClientPRLocalMetadataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OAuthClientPRLocalMetadataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OAuthClientPRLocalMetadataImpl
 * @generated
 */
@JSON(strict = true)
public class OAuthClientPRLocalMetadataModelImpl
	extends BaseModelImpl<OAuthClientPRLocalMetadata>
	implements OAuthClientPRLocalMetadataModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o auth client pr local metadata model instance should use the <code>OAuthClientPRLocalMetadata</code> interface instead.
	 */
	public static final String TABLE_NAME = "OAuthClientPRLocalMetadata";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"externalReferenceCode", Types.VARCHAR},
		{"oAuthClientPRLocalMetadataId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"localWellKnownEnabled", Types.BOOLEAN},
		{"localWellKnownURI", Types.VARCHAR}, {"metadataJSON", Types.CLOB},
		{"resource", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oAuthClientPRLocalMetadataId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("localWellKnownEnabled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("localWellKnownURI", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("metadataJSON", Types.CLOB);
		TABLE_COLUMNS_MAP.put("resource", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OAuthClientPRLocalMetadata (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,externalReferenceCode VARCHAR(75) null,oAuthClientPRLocalMetadataId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,localWellKnownEnabled BOOLEAN,localWellKnownURI VARCHAR(256) null,metadataJSON TEXT null,resource VARCHAR(256) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OAuthClientPRLocalMetadata";

	public static final String ENTITY_ALIAS = "oAuthClientPRLocalMetadata";

	public static final String ORDER_BY_JPQL =
		" ORDER BY oAuthClientPRLocalMetadata.oAuthClientPRLocalMetadataId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OAuthClientPRLocalMetadata.oAuthClientPRLocalMetadataId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXTERNALREFERENCECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCALWELLKNOWNENABLED_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LOCALWELLKNOWNURI_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RESOURCE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OAUTHCLIENTPRLOCALMETADATAID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OAuthClientPRLocalMetadataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _oAuthClientPRLocalMetadataId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOAuthClientPRLocalMetadataId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _oAuthClientPRLocalMetadataId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OAuthClientPRLocalMetadata.class;
	}

	@Override
	public String getModelClassName() {
		return OAuthClientPRLocalMetadata.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OAuthClientPRLocalMetadata, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OAuthClientPRLocalMetadata, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OAuthClientPRLocalMetadata, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(OAuthClientPRLocalMetadata)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OAuthClientPRLocalMetadata, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OAuthClientPRLocalMetadata, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OAuthClientPRLocalMetadata)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OAuthClientPRLocalMetadata, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OAuthClientPRLocalMetadata, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<OAuthClientPRLocalMetadata, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<OAuthClientPRLocalMetadata, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<OAuthClientPRLocalMetadata, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", OAuthClientPRLocalMetadata::getMvccVersion);
			attributeGetterFunctions.put(
				"uuid", OAuthClientPRLocalMetadata::getUuid);
			attributeGetterFunctions.put(
				"externalReferenceCode",
				OAuthClientPRLocalMetadata::getExternalReferenceCode);
			attributeGetterFunctions.put(
				"oAuthClientPRLocalMetadataId",
				OAuthClientPRLocalMetadata::getOAuthClientPRLocalMetadataId);
			attributeGetterFunctions.put(
				"companyId", OAuthClientPRLocalMetadata::getCompanyId);
			attributeGetterFunctions.put(
				"userId", OAuthClientPRLocalMetadata::getUserId);
			attributeGetterFunctions.put(
				"userName", OAuthClientPRLocalMetadata::getUserName);
			attributeGetterFunctions.put(
				"createDate", OAuthClientPRLocalMetadata::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", OAuthClientPRLocalMetadata::getModifiedDate);
			attributeGetterFunctions.put(
				"localWellKnownEnabled",
				OAuthClientPRLocalMetadata::getLocalWellKnownEnabled);
			attributeGetterFunctions.put(
				"localWellKnownURI",
				OAuthClientPRLocalMetadata::getLocalWellKnownURI);
			attributeGetterFunctions.put(
				"metadataJSON", OAuthClientPRLocalMetadata::getMetadataJSON);
			attributeGetterFunctions.put(
				"resource", OAuthClientPRLocalMetadata::getResource);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<OAuthClientPRLocalMetadata, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<OAuthClientPRLocalMetadata, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<OAuthClientPRLocalMetadata, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<OAuthClientPRLocalMetadata, Long>)
					OAuthClientPRLocalMetadata::setMvccVersion);
			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<OAuthClientPRLocalMetadata, String>)
					OAuthClientPRLocalMetadata::setUuid);
			attributeSetterBiConsumers.put(
				"externalReferenceCode",
				(BiConsumer<OAuthClientPRLocalMetadata, String>)
					OAuthClientPRLocalMetadata::setExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"oAuthClientPRLocalMetadataId",
				(BiConsumer<OAuthClientPRLocalMetadata, Long>)
					OAuthClientPRLocalMetadata::
						setOAuthClientPRLocalMetadataId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<OAuthClientPRLocalMetadata, Long>)
					OAuthClientPRLocalMetadata::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<OAuthClientPRLocalMetadata, Long>)
					OAuthClientPRLocalMetadata::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<OAuthClientPRLocalMetadata, String>)
					OAuthClientPRLocalMetadata::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<OAuthClientPRLocalMetadata, Date>)
					OAuthClientPRLocalMetadata::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<OAuthClientPRLocalMetadata, Date>)
					OAuthClientPRLocalMetadata::setModifiedDate);
			attributeSetterBiConsumers.put(
				"localWellKnownEnabled",
				(BiConsumer<OAuthClientPRLocalMetadata, Boolean>)
					OAuthClientPRLocalMetadata::setLocalWellKnownEnabled);
			attributeSetterBiConsumers.put(
				"localWellKnownURI",
				(BiConsumer<OAuthClientPRLocalMetadata, String>)
					OAuthClientPRLocalMetadata::setLocalWellKnownURI);
			attributeSetterBiConsumers.put(
				"metadataJSON",
				(BiConsumer<OAuthClientPRLocalMetadata, String>)
					OAuthClientPRLocalMetadata::setMetadataJSON);
			attributeSetterBiConsumers.put(
				"resource",
				(BiConsumer<OAuthClientPRLocalMetadata, String>)
					OAuthClientPRLocalMetadata::setResource);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public String getExternalReferenceCode() {
		if (_externalReferenceCode == null) {
			return "";
		}
		else {
			return _externalReferenceCode;
		}
	}

	@Override
	public void setExternalReferenceCode(String externalReferenceCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_externalReferenceCode = externalReferenceCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalExternalReferenceCode() {
		return getColumnOriginalValue("externalReferenceCode");
	}

	@JSON
	@Override
	public long getOAuthClientPRLocalMetadataId() {
		return _oAuthClientPRLocalMetadataId;
	}

	@Override
	public void setOAuthClientPRLocalMetadataId(
		long oAuthClientPRLocalMetadataId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oAuthClientPRLocalMetadataId = oAuthClientPRLocalMetadataId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getLocalWellKnownEnabled() {
		return _localWellKnownEnabled;
	}

	@JSON
	@Override
	public boolean isLocalWellKnownEnabled() {
		return _localWellKnownEnabled;
	}

	@Override
	public void setLocalWellKnownEnabled(boolean localWellKnownEnabled) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_localWellKnownEnabled = localWellKnownEnabled;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalLocalWellKnownEnabled() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("localWellKnownEnabled"));
	}

	@JSON
	@Override
	public String getLocalWellKnownURI() {
		if (_localWellKnownURI == null) {
			return "";
		}
		else {
			return _localWellKnownURI;
		}
	}

	@Override
	public void setLocalWellKnownURI(String localWellKnownURI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_localWellKnownURI = localWellKnownURI;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLocalWellKnownURI() {
		return getColumnOriginalValue("localWellKnownURI");
	}

	@JSON
	@Override
	public String getMetadataJSON() {
		if (_metadataJSON == null) {
			return "";
		}
		else {
			return _metadataJSON;
		}
	}

	@Override
	public void setMetadataJSON(String metadataJSON) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_metadataJSON = metadataJSON;
	}

	@JSON
	@Override
	public String getResource() {
		if (_resource == null) {
			return "";
		}
		else {
			return _resource;
		}
	}

	@Override
	public void setResource(String resource) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resource = resource;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalResource() {
		return getColumnOriginalValue("resource");
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				OAuthClientPRLocalMetadata.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OAuthClientPRLocalMetadata.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OAuthClientPRLocalMetadata toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OAuthClientPRLocalMetadata>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OAuthClientPRLocalMetadataImpl oAuthClientPRLocalMetadataImpl =
			new OAuthClientPRLocalMetadataImpl();

		oAuthClientPRLocalMetadataImpl.setMvccVersion(getMvccVersion());
		oAuthClientPRLocalMetadataImpl.setUuid(getUuid());
		oAuthClientPRLocalMetadataImpl.setExternalReferenceCode(
			getExternalReferenceCode());
		oAuthClientPRLocalMetadataImpl.setOAuthClientPRLocalMetadataId(
			getOAuthClientPRLocalMetadataId());
		oAuthClientPRLocalMetadataImpl.setCompanyId(getCompanyId());
		oAuthClientPRLocalMetadataImpl.setUserId(getUserId());
		oAuthClientPRLocalMetadataImpl.setUserName(getUserName());
		oAuthClientPRLocalMetadataImpl.setCreateDate(getCreateDate());
		oAuthClientPRLocalMetadataImpl.setModifiedDate(getModifiedDate());
		oAuthClientPRLocalMetadataImpl.setLocalWellKnownEnabled(
			isLocalWellKnownEnabled());
		oAuthClientPRLocalMetadataImpl.setLocalWellKnownURI(
			getLocalWellKnownURI());
		oAuthClientPRLocalMetadataImpl.setMetadataJSON(getMetadataJSON());
		oAuthClientPRLocalMetadataImpl.setResource(getResource());

		oAuthClientPRLocalMetadataImpl.resetOriginalValues();

		return oAuthClientPRLocalMetadataImpl;
	}

	@Override
	public OAuthClientPRLocalMetadata cloneWithOriginalValues() {
		OAuthClientPRLocalMetadataImpl oAuthClientPRLocalMetadataImpl =
			new OAuthClientPRLocalMetadataImpl();

		oAuthClientPRLocalMetadataImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		oAuthClientPRLocalMetadataImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		oAuthClientPRLocalMetadataImpl.setExternalReferenceCode(
			this.<String>getColumnOriginalValue("externalReferenceCode"));
		oAuthClientPRLocalMetadataImpl.setOAuthClientPRLocalMetadataId(
			this.<Long>getColumnOriginalValue("oAuthClientPRLocalMetadataId"));
		oAuthClientPRLocalMetadataImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		oAuthClientPRLocalMetadataImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		oAuthClientPRLocalMetadataImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		oAuthClientPRLocalMetadataImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		oAuthClientPRLocalMetadataImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		oAuthClientPRLocalMetadataImpl.setLocalWellKnownEnabled(
			this.<Boolean>getColumnOriginalValue("localWellKnownEnabled"));
		oAuthClientPRLocalMetadataImpl.setLocalWellKnownURI(
			this.<String>getColumnOriginalValue("localWellKnownURI"));
		oAuthClientPRLocalMetadataImpl.setMetadataJSON(
			this.<String>getColumnOriginalValue("metadataJSON"));
		oAuthClientPRLocalMetadataImpl.setResource(
			this.<String>getColumnOriginalValue("resource"));

		return oAuthClientPRLocalMetadataImpl;
	}

	@Override
	public int compareTo(
		OAuthClientPRLocalMetadata oAuthClientPRLocalMetadata) {

		long primaryKey = oAuthClientPRLocalMetadata.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OAuthClientPRLocalMetadata)) {
			return false;
		}

		OAuthClientPRLocalMetadata oAuthClientPRLocalMetadata =
			(OAuthClientPRLocalMetadata)object;

		long primaryKey = oAuthClientPRLocalMetadata.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OAuthClientPRLocalMetadata> toCacheModel() {
		OAuthClientPRLocalMetadataCacheModel
			oAuthClientPRLocalMetadataCacheModel =
				new OAuthClientPRLocalMetadataCacheModel();

		oAuthClientPRLocalMetadataCacheModel.mvccVersion = getMvccVersion();

		oAuthClientPRLocalMetadataCacheModel.uuid = getUuid();

		String uuid = oAuthClientPRLocalMetadataCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			oAuthClientPRLocalMetadataCacheModel.uuid = null;
		}

		oAuthClientPRLocalMetadataCacheModel.externalReferenceCode =
			getExternalReferenceCode();

		String externalReferenceCode =
			oAuthClientPRLocalMetadataCacheModel.externalReferenceCode;

		if ((externalReferenceCode != null) &&
			(externalReferenceCode.length() == 0)) {

			oAuthClientPRLocalMetadataCacheModel.externalReferenceCode = null;
		}

		oAuthClientPRLocalMetadataCacheModel.oAuthClientPRLocalMetadataId =
			getOAuthClientPRLocalMetadataId();

		oAuthClientPRLocalMetadataCacheModel.companyId = getCompanyId();

		oAuthClientPRLocalMetadataCacheModel.userId = getUserId();

		oAuthClientPRLocalMetadataCacheModel.userName = getUserName();

		String userName = oAuthClientPRLocalMetadataCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			oAuthClientPRLocalMetadataCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			oAuthClientPRLocalMetadataCacheModel.createDate =
				createDate.getTime();
		}
		else {
			oAuthClientPRLocalMetadataCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			oAuthClientPRLocalMetadataCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			oAuthClientPRLocalMetadataCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		oAuthClientPRLocalMetadataCacheModel.localWellKnownEnabled =
			isLocalWellKnownEnabled();

		oAuthClientPRLocalMetadataCacheModel.localWellKnownURI =
			getLocalWellKnownURI();

		String localWellKnownURI =
			oAuthClientPRLocalMetadataCacheModel.localWellKnownURI;

		if ((localWellKnownURI != null) && (localWellKnownURI.length() == 0)) {
			oAuthClientPRLocalMetadataCacheModel.localWellKnownURI = null;
		}

		oAuthClientPRLocalMetadataCacheModel.metadataJSON = getMetadataJSON();

		String metadataJSON = oAuthClientPRLocalMetadataCacheModel.metadataJSON;

		if ((metadataJSON != null) && (metadataJSON.length() == 0)) {
			oAuthClientPRLocalMetadataCacheModel.metadataJSON = null;
		}

		oAuthClientPRLocalMetadataCacheModel.resource = getResource();

		String resource = oAuthClientPRLocalMetadataCacheModel.resource;

		if ((resource != null) && (resource.length() == 0)) {
			oAuthClientPRLocalMetadataCacheModel.resource = null;
		}

		return oAuthClientPRLocalMetadataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OAuthClientPRLocalMetadata, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OAuthClientPRLocalMetadata, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OAuthClientPRLocalMetadata, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(OAuthClientPRLocalMetadata)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, OAuthClientPRLocalMetadata>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						OAuthClientPRLocalMetadata.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private String _uuid;
	private String _externalReferenceCode;
	private long _oAuthClientPRLocalMetadataId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _localWellKnownEnabled;
	private String _localWellKnownURI;
	private String _metadataJSON;
	private String _resource;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<OAuthClientPRLocalMetadata, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OAuthClientPRLocalMetadata)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"externalReferenceCode", _externalReferenceCode);
		_columnOriginalValues.put(
			"oAuthClientPRLocalMetadataId", _oAuthClientPRLocalMetadataId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"localWellKnownEnabled", _localWellKnownEnabled);
		_columnOriginalValues.put("localWellKnownURI", _localWellKnownURI);
		_columnOriginalValues.put("metadataJSON", _metadataJSON);
		_columnOriginalValues.put("resource", _resource);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("uuid_", 2L);

		columnBitmasks.put("externalReferenceCode", 4L);

		columnBitmasks.put("oAuthClientPRLocalMetadataId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("userName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("localWellKnownEnabled", 512L);

		columnBitmasks.put("localWellKnownURI", 1024L);

		columnBitmasks.put("metadataJSON", 2048L);

		columnBitmasks.put("resource", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OAuthClientPRLocalMetadata _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:2139144081