#
# This is a generated file.
#

api.version=v1.0
crud.entity.class.name=com.liferay.portal.tools.rest.builder.test.dto.v1_0.EntityModelResourceTestEntity2
crud.item.delegate=true
entity.class.name=com.liferay.portal.tools.rest.builder.test.dto.v1_0.EntityModelResourceTestEntity2
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Portal.Tools.REST.Builder.Test)
osgi.jaxrs.resource=true