modified.files.includes[relevant][upload-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][upload-java-rule]=\
    apps/upload/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][upload-java-rule]=\
    apps/upload/**/*Test.java

relevant.rule.names=upload-java-rule

test.batch.names[relevant][upload-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Item Selector