modified.files.includes[relevant][pmd-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][pmd-java-rule]=\
    util/pmd/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][pmd-java-rule]=\
    util/pmd/**/*Test.java

relevant.rule.names=pmd-java-rule

test.batch.names[relevant][pmd-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit