modified.files.includes[relevant][trash-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][trash-java-rule]=\
    apps/trash/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][trash-java-rule]=\
    apps/trash/**/*Test.java

relevant.rule.names=trash-java-rule

test.batch.names[relevant][trash-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Recycle Bin