modified.files.includes[relevant][style-book-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][style-book-java-rule]=\
    apps/style-book/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][style-book-java-rule]=\
    apps/style-book/**/*Test.java

relevant.rule.names=style-book-java-rule

test.batch.names[relevant][style-book-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Style Books