counter.increment.com.liferay.osb.patcher.model.PatcherBuild=1
release.info.build.number=730

upgrade.processes=\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_3_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_4_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_5_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_6_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_7_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_8_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_1_9_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_3_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_4_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_5_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_6_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_7_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_8_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_2_9_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_3_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_4_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_5_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_6_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_7_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_8_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_3_9_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_3_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_4_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_5_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_6_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_7_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_8_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_4_9_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_3_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_4_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_5_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_6_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_7_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_8_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_5_9_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_3_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_4_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_5_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_6_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_7_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_8_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_6_9_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_7_0_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_7_1_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_7_2_0,\
    com.liferay.osb.patcher.hook.upgrade.UpgradeProcess_7_3_0