modified.files.includes[relevant][document-library-web-functional-rule]=**
modified.files.includes[relevant][document-library-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][document-library-web-playwright-rule]=\
    document-library-web.main

relevant.rule.names=\
    document-library-web-functional-rule,\
    document-library-web-playwright-rule

test.batch.names[relevant][document-library-web-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][document-library-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][document-library-web-functional-rule]=\
    (testray.component.names == "Documents and Media") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Documents and Media