dependencies {
	testIntegrationImplementation project(":apps:commerce:commerce-discount-api")
	testIntegrationImplementation project(":apps:commerce:commerce-product-api")
	testIntegrationImplementation project(":apps:commerce:commerce-product-test-util")
	testIntegrationImplementation project(":apps:portal:portal-upgrade-test-util")
	testIntegrationImplementation project(":apps:static:portal:portal-upgrade-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}