modified.files.includes[relevant][layout-js-components-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][layout-js-components-web-playwright-rule]=\
    journal-web.main,\
    layout-admin-web.main,\
    layout-content-page-editor-web.main,\
    layout-page-template-admin-web.main,\
    style-book-web.main

relevant.rule.names=layout-js-components-web-playwright-rule

test.batch.names[relevant][layout-js-components-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Content Pages