#
# This is a generated file.
#

api.version=v1.0
entity.class.name=com.liferay.exportimport.rest.dto.v1_0.PublishPreview
osgi.jaxrs.application.select=(osgi.jaxrs.name=Export.Import.REST)
osgi.jaxrs.resource=true