#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.exportimport.rest.dto.v1_0.ReportEntry
batch.engine.task.item.delegate=true
batch.planner.export.enabled=false
batch.planner.import.enabled=false
crud.entity.class.name=com.liferay.exportimport.rest.dto.v1_0.ReportEntry
crud.item.delegate=true
entity.class.name=com.liferay.exportimport.rest.dto.v1_0.ReportEntry
osgi.jaxrs.application.select=(osgi.jaxrs.name=Export.Import.REST)
osgi.jaxrs.resource=true