modified.files.includes[relevant][locked-items-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][locked-items-web-playwright-rule]=\
    locked-items-web.main

relevant.rule.names=locked-items-web-playwright-rule

test.batch.names[relevant][locked-items-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57