apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-100"
        azure.workload.identity/client-id: {{ .Values.deploymentContext.crossplaneDataClientId | quote }}
    name: crossplane-data
    namespace: {{ .Values.crossplaneNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-100"
        azure.workload.identity/client-id: {{ .Values.deploymentContext.crossplaneIamClientId | quote }}
    name: crossplane-iam
    namespace: {{ .Values.crossplaneNamespace }}