/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.layout.content.model.impl;

import com.liferay.layout.content.model.LayoutContentVersionPreview;
import com.liferay.layout.content.service.LayoutContentVersionPreviewLocalServiceUtil;

/**
 * The extended model base implementation for the LayoutContentVersionPreview service. Represents a row in the &quot;LayoutContentVersionPreview&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutContentVersionPreviewImpl}.
 * </p>
 *
 * @author Lourdes Fernández Besada
 * @see LayoutContentVersionPreviewImpl
 * @see LayoutContentVersionPreview
 * @generated
 */
public abstract class LayoutContentVersionPreviewBaseImpl
	extends LayoutContentVersionPreviewModelImpl
	implements LayoutContentVersionPreview {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout content version preview model instance should use the <code>LayoutContentVersionPreview</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			LayoutContentVersionPreviewLocalServiceUtil.
				addLayoutContentVersionPreview(this);
		}
		else {
			LayoutContentVersionPreviewLocalServiceUtil.
				updateLayoutContentVersionPreview(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1697540088