modified.files.includes[relevant][data-engine-functional-rule]=**

modified.files.includes[relevant][data-engine-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][data-engine-java-rule]=\
    apps/company/**/CompanyLocalServiceTest.java,\
    apps/data-engine/**/*Test.java,\
    apps/dynamic-data-lists/**/*Test.java,\
    apps/dynamic-data-mapping/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][data-engine-java-rule]=\
    apps/company/**/CompanyLocalServiceTest.java,\
    apps/data-engine/**/*Test.java,\
    apps/dynamic-data-lists/**/*Test.java,\
    apps/dynamic-data-mapping/**/*Test.java

relevant.rule.names=\
    data-engine-functional-rule,\
    data-engine-java-rule

test.batch.names[relevant][data-engine-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][data-engine-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][data-engine-functional-rule]=\
    (\
        (data.archive.type != "data-archive-calendar") AND \
        (portal.acceptance == true) AND \
        (portal.release != "false") AND \
        (testray.main.component.name == "Upgrades Forms")\
    ) OR \
    (\
        (portal.acceptance == true) AND \
        (testray.main.component.name ~ "Upgrades Content Management")\
    )

testray.main.component.name=Data Engine