modified.files.includes[relevant][seo-studio-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][seo-studio-java-rule]=\
    dxp/apps/seo-studio/**/*Test.java

relevant.rule.names=seo-studio-java-rule

test.batch.names[relevant][seo-studio-java-rule]=\
    modules-integration-postgresql163

testray.main.component.name=SEO Studio