modified.files.includes[relevant][json-storage-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][json-storage-java-rule]=\
    apps/json-storage/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][json-storage-java-rule]=\
    apps/json-storage/**/*Test.java

relevant.rule.names=json-storage-java-rule

test.batch.names[relevant][json-storage-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services