modified.files.includes[relevant][core-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][core-java-rule]=\
    apps/**/src/testIntegration/**/*Test.java,\
    core/**/src/testIntegration/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][core-java-rule]=\
    apps/accessibility/**/*Test.java,\
    core/**/*Test.java

relevant.rule.names=core-java-rule

test.batch.names[relevant][core-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services