#
# OAuth
#

liferay.oauth.application.external.reference.codes=liferay-streamhub-etc-spring-boot-oauth-application-user-agent

liferay.oauth.urls.excludes=/ready

#
# Spring Boot
#

server.port=58081