module "eks" {
	cluster_addons={
		amazon-cloudwatch-observability={
			most_recent=true
		}
		aws-ebs-csi-driver={
			most_recent=true
		}
		coredns={
			most_recent=true
		}
		kube-proxy={
			most_recent=true
		}
		metrics-server={
			most_recent=true
		}
		vpc-cni={
			most_recent=true
		}
	}
	cluster_endpoint_private_access=true
	cluster_endpoint_public_access=true
	cluster_name="${var.deployment_name}-eks"
	cluster_security_group_id=aws_security_group.cluster.id
	cluster_version="1.32"
	eks_managed_node_groups={
		liferay_dxp={
			ami_type=var.node_group_ami_type
			block_device_mappings={
				device_name="/dev/xvda"
				ebs={
					encrypted=true
					volume_size=var.root_volume_size
					volume_type=var.root_volume_type
				}
			}
			cluster_primary_security_group_id=module.eks.cluster_primary_security_group_id
			desired_size=var.node_group_desired_size
			disk_size=var.root_volume_size
			iam_role_additional_policies={
				AmazonEBSCSIDriverPolicy="arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
				CloudWatchAgentServerPolicy="arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
			}
			instance_types=[var.node_instance_type]
			max_size=var.node_group_max_size
			min_size=var.node_group_min_size
			tags={
				DeploymentName=var.deployment_name
				"kubernetes.io/cluster/${module.eks.cluster_name}"="owned"
				"liferay.cloud/nodegroup/name"="liferay-dxp"
				"liferay.cloud/nodegroup/type"=var.node_instance_type
			}
			vpc_security_group_ids=[
				aws_security_group.cluster.id,
				aws_security_group.nodes.id
			]
		}
	}
	enable_cluster_creator_admin_permissions=true
	enable_irsa=true
	node_security_group_id=aws_security_group.nodes.id
	source="terraform-aws-modules/eks/aws"
	subnet_ids=module.vpc.private_subnets
	version="20.13.1"
	vpc_id=module.vpc.vpc_id
}