locals {
	oidc_provider_arn="arn:${var.arn_partition}:iam::${data.aws_caller_identity.current.account_id}:oidc-provider/${module.eks.oidc_provider}"
}
module "eks" {
	addons={
		amazon-cloudwatch-observability={
			most_recent=true
		}
		aws-ebs-csi-driver={
			most_recent=true
			service_account_role_arn=aws_iam_role.ebs_csi_driver.arn
		}
		coredns={
			before_compute=true
			most_recent=true
		}
		kube-proxy={
			before_compute=true
			most_recent=true
		}
		metrics-server={
			most_recent=true
		}
		vpc-cni={
			before_compute=true
			most_recent=true
		}
	}
	cloudwatch_log_group_retention_in_days=90
	compute_config={
		enabled=true
		node_pools=["general-purpose"]
	}
	create_cloudwatch_log_group=true
	create_kms_key=false
	enable_cluster_creator_admin_permissions=true
	enable_irsa=true
	encryption_config={
		provider_key_arn=aws_kms_key.eks_secrets.arn
	}
	endpoint_private_access=true
	endpoint_public_access=true
	iam_role_additional_policies={
		AmazonEKSBlockStoragePolicy="arn:${var.arn_partition}:iam::aws:policy/AmazonEKSBlockStoragePolicy"
		AmazonEKSComputePolicy="arn:${var.arn_partition}:iam::aws:policy/AmazonEKSComputePolicy"
		AmazonEKSLoadBalancingPolicy="arn:${var.arn_partition}:iam::aws:policy/AmazonEKSLoadBalancingPolicy"
		AmazonEKSNetworkingPolicy="arn:${var.arn_partition}:iam::aws:policy/AmazonEKSNetworkingPolicy"
	}
	kubernetes_version=data.aws_eks_cluster_versions.available.cluster_versions[0].cluster_version
	name="${var.deployment_name}-eks"
	node_security_group_id=aws_security_group.nodes.id
	security_group_id=aws_security_group.cluster.id
	source="terraform-aws-modules/eks/aws"
	subnet_ids=module.vpc.private_subnets
	version="21.3.1"
	vpc_id=module.vpc.vpc_id
}
resource "aws_eks_addon" "s3_csi" {
	addon_name="aws-mountpoint-s3-csi-driver"
	addon_version=data.aws_eks_addon_version.s3_csi.version
	cluster_name=module.eks.cluster_name
	resolve_conflicts_on_update="OVERWRITE"
	service_account_role_arn=aws_iam_role.s3_csi_driver.arn
}
resource "aws_iam_role" "ebs_csi_driver" {
	assume_role_policy=jsonencode(
		{
			Statement=[
				{
					Action="sts:AssumeRoleWithWebIdentity"
					Condition={
						StringEquals={
							"${module.eks.oidc_provider}:sub"="system:serviceaccount:kube-system:ebs-csi-controller-sa"
							"${module.eks.oidc_provider}:aud"="sts.amazonaws.com"
						}
					}
					Effect="Allow"
					Principal={
						Federated=local.oidc_provider_arn
					}
				}
			]
			Version="2012-10-17"
		}
	)
	force_detach_policies=true
	name="${var.deployment_name}-ebs_csi_driver"
}
resource "aws_iam_role" "irsa" {
	assume_role_policy=jsonencode(
		{
			Statement=[
				{
					Action="sts:AssumeRoleWithWebIdentity"
					Condition={
						StringEquals={
							"${module.eks.oidc_provider}:sub" : "system:serviceaccount:${var.deployment_namespace}:liferay-default"
						}
					}
					Effect="Allow"
					Principal={
						Federated=local.oidc_provider_arn
					}
				}
			]
			Version="2012-10-17"
		}
	)
	force_detach_policies=true
	name="${var.deployment_name}-irsa"
}
resource "aws_iam_role" "s3_csi_driver" {
	assume_role_policy=jsonencode(
    {
			Statement=[
				{
					Action="sts:AssumeRoleWithWebIdentity"
					Condition={
						StringEquals={
							"${module.eks.oidc_provider}:sub"="system:serviceaccount:kube-system:s3-csi-controller-sa"
							"${module.eks.oidc_provider}:aud"="sts.amazonaws.com"
						}
					}
					Effect="Allow"
					Principal={
						Federated=local.oidc_provider_arn
					}
				}
			]
			Version="2012-10-17"
		}
	)
  force_detach_policies=true
  name="${var.deployment_name}-s3_csi_driver"
}
resource "aws_iam_role_policy" "s3_csi_driver" {
	policy=jsonencode(
		{
			Statement=[
				{
					Action=[
						"s3:GetObject",
						"s3:ListBucket",
					]
					Effect="Allow"
					Resource=[
						"arn:${var.arn_partition}:s3:::${var.deployment_name}-extensions-*",
						"arn:${var.arn_partition}:s3:::${var.deployment_name}-extensions-*/*"
					]
					Sid="AllowS3BucketOperations"
				}
			]
			Version="2012-10-17"
		}
	)
	role=aws_iam_role.s3_csi_driver.id
}
resource "aws_iam_role_policy" "this" {
	count = length(var.ecr_repositories) > 0 ? 1 : 0
	policy=jsonencode(
		{
			Statement=[
				{
					Action=[
						"ecr:BatchCheckLayerAvailability",
						"ecr:BatchGetImage",
						"ecr:GetAuthorizationToken",
						"ecr:GetDownloadUrlForLayer"
					]
					Effect="Allow"
					Resource=[
						for k, v in var.ecr_repositories : v.arn
					]
				}
			]
			Version="2012-10-17"
		}
	)
	role=aws_iam_role.irsa.id
}
resource "aws_iam_role_policy_attachment" "role_policy_attachment_ebs_csi_driver" {
	policy_arn="arn:${var.arn_partition}:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"
	role=aws_iam_role.ebs_csi_driver.name
}
resource "aws_kms_alias" "eks_kms_alias" {
	name="alias/${var.deployment_name}-eks_kms"
	target_key_id=aws_kms_key.eks_secrets.key_id
}
resource "aws_kms_key" "eks_secrets" {
	deletion_window_in_days=7
	description="KMS key for EKS secrets encryption"
}