/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.exportimport.report.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.report.model.ExportImportReportEntry;
import com.liferay.exportimport.report.model.ExportImportReportEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ExportImportReportEntry service. Represents a row in the &quot;ExportImportReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ExportImportReportEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExportImportReportEntryImpl}.
 * </p>
 *
 * @author Carlos Correa
 * @see ExportImportReportEntryImpl
 * @generated
 */
public class ExportImportReportEntryModelImpl
	extends BaseModelImpl<ExportImportReportEntry>
	implements ExportImportReportEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a export import report entry model instance should use the <code>ExportImportReportEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "ExportImportReportEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"exportImportReportEntryId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"classExternalReferenceCode", Types.VARCHAR},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"exportImportConfigurationId", Types.BIGINT},
		{"errorMessage", Types.CLOB}, {"errorStacktrace", Types.CLOB},
		{"modelName", Types.VARCHAR}, {"origin", Types.INTEGER},
		{"scope", Types.VARCHAR}, {"scopeKey", Types.VARCHAR},
		{"type_", Types.INTEGER}, {"status", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("exportImportReportEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classExternalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("exportImportConfigurationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("errorMessage", Types.CLOB);
		TABLE_COLUMNS_MAP.put("errorStacktrace", Types.CLOB);
		TABLE_COLUMNS_MAP.put("modelName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("origin", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("scope", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scopeKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ExportImportReportEntry (mvccVersion LONG default 0 not null,exportImportReportEntryId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,classExternalReferenceCode VARCHAR(75) null,classNameId LONG,classPK LONG,exportImportConfigurationId LONG,errorMessage TEXT null,errorStacktrace TEXT null,modelName VARCHAR(255) null,origin INTEGER,scope VARCHAR(75) null,scopeKey VARCHAR(75) null,type_ INTEGER,status INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table ExportImportReportEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY exportImportReportEntry.exportImportReportEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ExportImportReportEntry.exportImportReportEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPORTIMPORTCONFIGURATIONID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPORTIMPORTREPORTENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ExportImportReportEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _exportImportReportEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setExportImportReportEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _exportImportReportEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ExportImportReportEntry.class;
	}

	@Override
	public String getModelClassName() {
		return ExportImportReportEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ExportImportReportEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ExportImportReportEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExportImportReportEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ExportImportReportEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ExportImportReportEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ExportImportReportEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ExportImportReportEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ExportImportReportEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ExportImportReportEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<ExportImportReportEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<ExportImportReportEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ExportImportReportEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", ExportImportReportEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"exportImportReportEntryId",
				ExportImportReportEntry::getExportImportReportEntryId);
			attributeGetterFunctions.put(
				"groupId", ExportImportReportEntry::getGroupId);
			attributeGetterFunctions.put(
				"companyId", ExportImportReportEntry::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", ExportImportReportEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", ExportImportReportEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"classExternalReferenceCode",
				ExportImportReportEntry::getClassExternalReferenceCode);
			attributeGetterFunctions.put(
				"classNameId", ExportImportReportEntry::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", ExportImportReportEntry::getClassPK);
			attributeGetterFunctions.put(
				"exportImportConfigurationId",
				ExportImportReportEntry::getExportImportConfigurationId);
			attributeGetterFunctions.put(
				"errorMessage", ExportImportReportEntry::getErrorMessage);
			attributeGetterFunctions.put(
				"errorStacktrace", ExportImportReportEntry::getErrorStacktrace);
			attributeGetterFunctions.put(
				"modelName", ExportImportReportEntry::getModelName);
			attributeGetterFunctions.put(
				"origin", ExportImportReportEntry::getOrigin);
			attributeGetterFunctions.put(
				"scope", ExportImportReportEntry::getScope);
			attributeGetterFunctions.put(
				"scopeKey", ExportImportReportEntry::getScopeKey);
			attributeGetterFunctions.put(
				"type", ExportImportReportEntry::getType);
			attributeGetterFunctions.put(
				"status", ExportImportReportEntry::getStatus);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<ExportImportReportEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ExportImportReportEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ExportImportReportEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"exportImportReportEntryId",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setExportImportReportEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<ExportImportReportEntry, Date>)
					ExportImportReportEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<ExportImportReportEntry, Date>)
					ExportImportReportEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"classExternalReferenceCode",
				(BiConsumer<ExportImportReportEntry, String>)
					ExportImportReportEntry::setClassExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setClassPK);
			attributeSetterBiConsumers.put(
				"exportImportConfigurationId",
				(BiConsumer<ExportImportReportEntry, Long>)
					ExportImportReportEntry::setExportImportConfigurationId);
			attributeSetterBiConsumers.put(
				"errorMessage",
				(BiConsumer<ExportImportReportEntry, String>)
					ExportImportReportEntry::setErrorMessage);
			attributeSetterBiConsumers.put(
				"errorStacktrace",
				(BiConsumer<ExportImportReportEntry, String>)
					ExportImportReportEntry::setErrorStacktrace);
			attributeSetterBiConsumers.put(
				"modelName",
				(BiConsumer<ExportImportReportEntry, String>)
					ExportImportReportEntry::setModelName);
			attributeSetterBiConsumers.put(
				"origin",
				(BiConsumer<ExportImportReportEntry, Integer>)
					ExportImportReportEntry::setOrigin);
			attributeSetterBiConsumers.put(
				"scope",
				(BiConsumer<ExportImportReportEntry, String>)
					ExportImportReportEntry::setScope);
			attributeSetterBiConsumers.put(
				"scopeKey",
				(BiConsumer<ExportImportReportEntry, String>)
					ExportImportReportEntry::setScopeKey);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<ExportImportReportEntry, Integer>)
					ExportImportReportEntry::setType);
			attributeSetterBiConsumers.put(
				"status",
				(BiConsumer<ExportImportReportEntry, Integer>)
					ExportImportReportEntry::setStatus);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getExportImportReportEntryId() {
		return _exportImportReportEntryId;
	}

	@Override
	public void setExportImportReportEntryId(long exportImportReportEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_exportImportReportEntryId = exportImportReportEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassExternalReferenceCode() {
		if (_classExternalReferenceCode == null) {
			return "";
		}
		else {
			return _classExternalReferenceCode;
		}
	}

	@Override
	public void setClassExternalReferenceCode(
		String classExternalReferenceCode) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classExternalReferenceCode = classExternalReferenceCode;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	@Override
	public long getExportImportConfigurationId() {
		return _exportImportConfigurationId;
	}

	@Override
	public void setExportImportConfigurationId(
		long exportImportConfigurationId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_exportImportConfigurationId = exportImportConfigurationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalExportImportConfigurationId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("exportImportConfigurationId"));
	}

	@Override
	public String getErrorMessage() {
		return _errorMessage;
	}

	@Override
	public void setErrorMessage(String errorMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorMessage = errorMessage;
	}

	@Override
	public String getErrorStacktrace() {
		return _errorStacktrace;
	}

	@Override
	public void setErrorStacktrace(String errorStacktrace) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorStacktrace = errorStacktrace;
	}

	@Override
	public String getModelName() {
		if (_modelName == null) {
			return "";
		}
		else {
			return _modelName;
		}
	}

	@Override
	public void setModelName(String modelName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modelName = modelName;
	}

	@Override
	public int getOrigin() {
		return _origin;
	}

	@Override
	public void setOrigin(int origin) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_origin = origin;
	}

	@Override
	public String getScope() {
		if (_scope == null) {
			return "";
		}
		else {
			return _scope;
		}
	}

	@Override
	public void setScope(String scope) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_scope = scope;
	}

	@Override
	public String getScopeKey() {
		if (_scopeKey == null) {
			return "";
		}
		else {
			return _scopeKey;
		}
	}

	@Override
	public void setScopeKey(String scopeKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_scopeKey = scopeKey;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ExportImportReportEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ExportImportReportEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ExportImportReportEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ExportImportReportEntryImpl exportImportReportEntryImpl =
			new ExportImportReportEntryImpl();

		exportImportReportEntryImpl.setMvccVersion(getMvccVersion());
		exportImportReportEntryImpl.setExportImportReportEntryId(
			getExportImportReportEntryId());
		exportImportReportEntryImpl.setGroupId(getGroupId());
		exportImportReportEntryImpl.setCompanyId(getCompanyId());
		exportImportReportEntryImpl.setCreateDate(getCreateDate());
		exportImportReportEntryImpl.setModifiedDate(getModifiedDate());
		exportImportReportEntryImpl.setClassExternalReferenceCode(
			getClassExternalReferenceCode());
		exportImportReportEntryImpl.setClassNameId(getClassNameId());
		exportImportReportEntryImpl.setClassPK(getClassPK());
		exportImportReportEntryImpl.setExportImportConfigurationId(
			getExportImportConfigurationId());
		exportImportReportEntryImpl.setErrorMessage(getErrorMessage());
		exportImportReportEntryImpl.setErrorStacktrace(getErrorStacktrace());
		exportImportReportEntryImpl.setModelName(getModelName());
		exportImportReportEntryImpl.setOrigin(getOrigin());
		exportImportReportEntryImpl.setScope(getScope());
		exportImportReportEntryImpl.setScopeKey(getScopeKey());
		exportImportReportEntryImpl.setType(getType());
		exportImportReportEntryImpl.setStatus(getStatus());

		exportImportReportEntryImpl.resetOriginalValues();

		return exportImportReportEntryImpl;
	}

	@Override
	public ExportImportReportEntry cloneWithOriginalValues() {
		ExportImportReportEntryImpl exportImportReportEntryImpl =
			new ExportImportReportEntryImpl();

		exportImportReportEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		exportImportReportEntryImpl.setExportImportReportEntryId(
			this.<Long>getColumnOriginalValue("exportImportReportEntryId"));
		exportImportReportEntryImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		exportImportReportEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		exportImportReportEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		exportImportReportEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		exportImportReportEntryImpl.setClassExternalReferenceCode(
			this.<String>getColumnOriginalValue("classExternalReferenceCode"));
		exportImportReportEntryImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		exportImportReportEntryImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		exportImportReportEntryImpl.setExportImportConfigurationId(
			this.<Long>getColumnOriginalValue("exportImportConfigurationId"));
		exportImportReportEntryImpl.setErrorMessage(
			this.<String>getColumnOriginalValue("errorMessage"));
		exportImportReportEntryImpl.setErrorStacktrace(
			this.<String>getColumnOriginalValue("errorStacktrace"));
		exportImportReportEntryImpl.setModelName(
			this.<String>getColumnOriginalValue("modelName"));
		exportImportReportEntryImpl.setOrigin(
			this.<Integer>getColumnOriginalValue("origin"));
		exportImportReportEntryImpl.setScope(
			this.<String>getColumnOriginalValue("scope"));
		exportImportReportEntryImpl.setScopeKey(
			this.<String>getColumnOriginalValue("scopeKey"));
		exportImportReportEntryImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));
		exportImportReportEntryImpl.setStatus(
			this.<Integer>getColumnOriginalValue("status"));

		return exportImportReportEntryImpl;
	}

	@Override
	public int compareTo(ExportImportReportEntry exportImportReportEntry) {
		long primaryKey = exportImportReportEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ExportImportReportEntry)) {
			return false;
		}

		ExportImportReportEntry exportImportReportEntry =
			(ExportImportReportEntry)object;

		long primaryKey = exportImportReportEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ExportImportReportEntry> toCacheModel() {
		ExportImportReportEntryCacheModel exportImportReportEntryCacheModel =
			new ExportImportReportEntryCacheModel();

		exportImportReportEntryCacheModel.mvccVersion = getMvccVersion();

		exportImportReportEntryCacheModel.exportImportReportEntryId =
			getExportImportReportEntryId();

		exportImportReportEntryCacheModel.groupId = getGroupId();

		exportImportReportEntryCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			exportImportReportEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			exportImportReportEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			exportImportReportEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			exportImportReportEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		exportImportReportEntryCacheModel.classExternalReferenceCode =
			getClassExternalReferenceCode();

		String classExternalReferenceCode =
			exportImportReportEntryCacheModel.classExternalReferenceCode;

		if ((classExternalReferenceCode != null) &&
			(classExternalReferenceCode.length() == 0)) {

			exportImportReportEntryCacheModel.classExternalReferenceCode = null;
		}

		exportImportReportEntryCacheModel.classNameId = getClassNameId();

		exportImportReportEntryCacheModel.classPK = getClassPK();

		exportImportReportEntryCacheModel.exportImportConfigurationId =
			getExportImportConfigurationId();

		exportImportReportEntryCacheModel.errorMessage = getErrorMessage();

		String errorMessage = exportImportReportEntryCacheModel.errorMessage;

		if ((errorMessage != null) && (errorMessage.length() == 0)) {
			exportImportReportEntryCacheModel.errorMessage = null;
		}

		exportImportReportEntryCacheModel.errorStacktrace =
			getErrorStacktrace();

		String errorStacktrace =
			exportImportReportEntryCacheModel.errorStacktrace;

		if ((errorStacktrace != null) && (errorStacktrace.length() == 0)) {
			exportImportReportEntryCacheModel.errorStacktrace = null;
		}

		exportImportReportEntryCacheModel.modelName = getModelName();

		String modelName = exportImportReportEntryCacheModel.modelName;

		if ((modelName != null) && (modelName.length() == 0)) {
			exportImportReportEntryCacheModel.modelName = null;
		}

		exportImportReportEntryCacheModel.origin = getOrigin();

		exportImportReportEntryCacheModel.scope = getScope();

		String scope = exportImportReportEntryCacheModel.scope;

		if ((scope != null) && (scope.length() == 0)) {
			exportImportReportEntryCacheModel.scope = null;
		}

		exportImportReportEntryCacheModel.scopeKey = getScopeKey();

		String scopeKey = exportImportReportEntryCacheModel.scopeKey;

		if ((scopeKey != null) && (scopeKey.length() == 0)) {
			exportImportReportEntryCacheModel.scopeKey = null;
		}

		exportImportReportEntryCacheModel.type = getType();

		exportImportReportEntryCacheModel.status = getStatus();

		return exportImportReportEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ExportImportReportEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ExportImportReportEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ExportImportReportEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ExportImportReportEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ExportImportReportEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						ExportImportReportEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _exportImportReportEntryId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _classExternalReferenceCode;
	private long _classNameId;
	private long _classPK;
	private long _exportImportConfigurationId;
	private String _errorMessage;
	private String _errorStacktrace;
	private String _modelName;
	private int _origin;
	private String _scope;
	private String _scopeKey;
	private int _type;
	private int _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<ExportImportReportEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ExportImportReportEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"exportImportReportEntryId", _exportImportReportEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"classExternalReferenceCode", _classExternalReferenceCode);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put(
			"exportImportConfigurationId", _exportImportConfigurationId);
		_columnOriginalValues.put("errorMessage", _errorMessage);
		_columnOriginalValues.put("errorStacktrace", _errorStacktrace);
		_columnOriginalValues.put("modelName", _modelName);
		_columnOriginalValues.put("origin", _origin);
		_columnOriginalValues.put("scope", _scope);
		_columnOriginalValues.put("scopeKey", _scopeKey);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("exportImportReportEntryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("classExternalReferenceCode", 64L);

		columnBitmasks.put("classNameId", 128L);

		columnBitmasks.put("classPK", 256L);

		columnBitmasks.put("exportImportConfigurationId", 512L);

		columnBitmasks.put("errorMessage", 1024L);

		columnBitmasks.put("errorStacktrace", 2048L);

		columnBitmasks.put("modelName", 4096L);

		columnBitmasks.put("origin", 8192L);

		columnBitmasks.put("scope", 16384L);

		columnBitmasks.put("scopeKey", 32768L);

		columnBitmasks.put("type_", 65536L);

		columnBitmasks.put("status", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ExportImportReportEntry _escapedModel;

}