modified.files.includes[relevant][questions-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][questions-java-rule]=\
    apps/message-boards/**/*Test.java,\
    apps/questions/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][questions-java-rule]=\
    apps/message-boards/**/*Test.java,\
    apps/questions/**/*Test.java

relevant.rule.names=questions-java-rule

test.batch.names[relevant][questions-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Questions