dependencies {
	compileInclude group: "org.apache.pdfbox", name: "fontbox", version: "3.0.7"
	compileInclude group: "org.apache.pdfbox", name: "jbig2-imageio", version: "3.0.3"
	compileInclude group: "org.apache.pdfbox", name: "pdfbox", version: "3.0.7"
	compileInclude group: "org.apache.pdfbox", name: "pdfbox-io", version: "3.0.7"
	compileOnly group: "org.osgi", name: "osgi.core", version: "6.0.0"
}