ext.expectedContentStrings = [
	'"externalReferenceCode": "External Reference Code"',
	'"membershipType": "open"',
	'"name": "Site Name"',
	'"name_i18n": {',
	'"de_DE": "Site Name DE"',
	'"en_US": "Site Name US"',
	'"parentSiteKey": "Parent Site Name"',
	'"templateKey": "Sample Template Key"',
	'"templateType": "site-initializer"',
]
ext.expectedFilePath = "site-initializer/site-initializer.json"
ext.taskPath = ":site-initializer:createClientExtensionConfig"

apply from: project.property("commonScript.testClientExtensionBuildFileContentsTestCase.gradle")