/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.patcher.service.base;

import com.liferay.osb.patcher.model.PatcherFixComponent;
import com.liferay.osb.patcher.service.PatcherFixComponentLocalService;
import com.liferay.osb.patcher.service.persistence.PatcherAccountPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherBuildPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherBuildRelPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherFixComponentPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherFixPackPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherFixPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherFixRelPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherProductVersionPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherProjectVersionPersistence;
import com.liferay.osb.patcher.service.persistence.PatcherTicketHintPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.persistence.ClassNamePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the patcher fix component local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.patcher.service.impl.PatcherFixComponentLocalServiceImpl}.
 * </p>
 *
 * @author Calvin Keum
 * @see com.liferay.osb.patcher.service.impl.PatcherFixComponentLocalServiceImpl
 * @see com.liferay.osb.patcher.service.PatcherFixComponentLocalServiceUtil
 * @generated
 */
public abstract class PatcherFixComponentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements PatcherFixComponentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.osb.patcher.service.PatcherFixComponentLocalServiceUtil} to access the patcher fix component local service.
	 */

	/**
	 * Adds the patcher fix component to the database. Also notifies the appropriate model listeners.
	 *
	 * @param patcherFixComponent the patcher fix component
	 * @return the patcher fix component that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PatcherFixComponent addPatcherFixComponent(
		PatcherFixComponent patcherFixComponent) throws SystemException {
		patcherFixComponent.setNew(true);

		return patcherFixComponentPersistence.update(patcherFixComponent);
	}

	/**
	 * Creates a new patcher fix component with the primary key. Does not add the patcher fix component to the database.
	 *
	 * @param patcherFixComponentId the primary key for the new patcher fix component
	 * @return the new patcher fix component
	 */
	@Override
	public PatcherFixComponent createPatcherFixComponent(
		long patcherFixComponentId) {
		return patcherFixComponentPersistence.create(patcherFixComponentId);
	}

	/**
	 * Deletes the patcher fix component with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param patcherFixComponentId the primary key of the patcher fix component
	 * @return the patcher fix component that was removed
	 * @throws PortalException if a patcher fix component with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PatcherFixComponent deletePatcherFixComponent(
		long patcherFixComponentId) throws PortalException, SystemException {
		return patcherFixComponentPersistence.remove(patcherFixComponentId);
	}

	/**
	 * Deletes the patcher fix component from the database. Also notifies the appropriate model listeners.
	 *
	 * @param patcherFixComponent the patcher fix component
	 * @return the patcher fix component that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PatcherFixComponent deletePatcherFixComponent(
		PatcherFixComponent patcherFixComponent) throws SystemException {
		return patcherFixComponentPersistence.remove(patcherFixComponent);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(PatcherFixComponent.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return patcherFixComponentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.osb.patcher.model.impl.PatcherFixComponentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return patcherFixComponentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.osb.patcher.model.impl.PatcherFixComponentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return patcherFixComponentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return patcherFixComponentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) throws SystemException {
		return patcherFixComponentPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public PatcherFixComponent fetchPatcherFixComponent(
		long patcherFixComponentId) throws SystemException {
		return patcherFixComponentPersistence.fetchByPrimaryKey(patcherFixComponentId);
	}

	/**
	 * Returns the patcher fix component with the primary key.
	 *
	 * @param patcherFixComponentId the primary key of the patcher fix component
	 * @return the patcher fix component
	 * @throws PortalException if a patcher fix component with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public PatcherFixComponent getPatcherFixComponent(
		long patcherFixComponentId) throws PortalException, SystemException {
		return patcherFixComponentPersistence.findByPrimaryKey(patcherFixComponentId);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return patcherFixComponentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the patcher fix components.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.osb.patcher.model.impl.PatcherFixComponentModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of patcher fix components
	 * @param end the upper bound of the range of patcher fix components (not inclusive)
	 * @return the range of patcher fix components
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public List<PatcherFixComponent> getPatcherFixComponents(int start, int end)
		throws SystemException {
		return patcherFixComponentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of patcher fix components.
	 *
	 * @return the number of patcher fix components
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public int getPatcherFixComponentsCount() throws SystemException {
		return patcherFixComponentPersistence.countAll();
	}

	/**
	 * Updates the patcher fix component in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param patcherFixComponent the patcher fix component
	 * @return the patcher fix component that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PatcherFixComponent updatePatcherFixComponent(
		PatcherFixComponent patcherFixComponent) throws SystemException {
		return patcherFixComponentPersistence.update(patcherFixComponent);
	}

	/**
	 * Returns the patcher account local service.
	 *
	 * @return the patcher account local service
	 */
	public com.liferay.osb.patcher.service.PatcherAccountLocalService getPatcherAccountLocalService() {
		return patcherAccountLocalService;
	}

	/**
	 * Sets the patcher account local service.
	 *
	 * @param patcherAccountLocalService the patcher account local service
	 */
	public void setPatcherAccountLocalService(
		com.liferay.osb.patcher.service.PatcherAccountLocalService patcherAccountLocalService) {
		this.patcherAccountLocalService = patcherAccountLocalService;
	}

	/**
	 * Returns the patcher account persistence.
	 *
	 * @return the patcher account persistence
	 */
	public PatcherAccountPersistence getPatcherAccountPersistence() {
		return patcherAccountPersistence;
	}

	/**
	 * Sets the patcher account persistence.
	 *
	 * @param patcherAccountPersistence the patcher account persistence
	 */
	public void setPatcherAccountPersistence(
		PatcherAccountPersistence patcherAccountPersistence) {
		this.patcherAccountPersistence = patcherAccountPersistence;
	}

	/**
	 * Returns the patcher build local service.
	 *
	 * @return the patcher build local service
	 */
	public com.liferay.osb.patcher.service.PatcherBuildLocalService getPatcherBuildLocalService() {
		return patcherBuildLocalService;
	}

	/**
	 * Sets the patcher build local service.
	 *
	 * @param patcherBuildLocalService the patcher build local service
	 */
	public void setPatcherBuildLocalService(
		com.liferay.osb.patcher.service.PatcherBuildLocalService patcherBuildLocalService) {
		this.patcherBuildLocalService = patcherBuildLocalService;
	}

	/**
	 * Returns the patcher build persistence.
	 *
	 * @return the patcher build persistence
	 */
	public PatcherBuildPersistence getPatcherBuildPersistence() {
		return patcherBuildPersistence;
	}

	/**
	 * Sets the patcher build persistence.
	 *
	 * @param patcherBuildPersistence the patcher build persistence
	 */
	public void setPatcherBuildPersistence(
		PatcherBuildPersistence patcherBuildPersistence) {
		this.patcherBuildPersistence = patcherBuildPersistence;
	}

	/**
	 * Returns the patcher build rel local service.
	 *
	 * @return the patcher build rel local service
	 */
	public com.liferay.osb.patcher.service.PatcherBuildRelLocalService getPatcherBuildRelLocalService() {
		return patcherBuildRelLocalService;
	}

	/**
	 * Sets the patcher build rel local service.
	 *
	 * @param patcherBuildRelLocalService the patcher build rel local service
	 */
	public void setPatcherBuildRelLocalService(
		com.liferay.osb.patcher.service.PatcherBuildRelLocalService patcherBuildRelLocalService) {
		this.patcherBuildRelLocalService = patcherBuildRelLocalService;
	}

	/**
	 * Returns the patcher build rel persistence.
	 *
	 * @return the patcher build rel persistence
	 */
	public PatcherBuildRelPersistence getPatcherBuildRelPersistence() {
		return patcherBuildRelPersistence;
	}

	/**
	 * Sets the patcher build rel persistence.
	 *
	 * @param patcherBuildRelPersistence the patcher build rel persistence
	 */
	public void setPatcherBuildRelPersistence(
		PatcherBuildRelPersistence patcherBuildRelPersistence) {
		this.patcherBuildRelPersistence = patcherBuildRelPersistence;
	}

	/**
	 * Returns the patcher fix local service.
	 *
	 * @return the patcher fix local service
	 */
	public com.liferay.osb.patcher.service.PatcherFixLocalService getPatcherFixLocalService() {
		return patcherFixLocalService;
	}

	/**
	 * Sets the patcher fix local service.
	 *
	 * @param patcherFixLocalService the patcher fix local service
	 */
	public void setPatcherFixLocalService(
		com.liferay.osb.patcher.service.PatcherFixLocalService patcherFixLocalService) {
		this.patcherFixLocalService = patcherFixLocalService;
	}

	/**
	 * Returns the patcher fix persistence.
	 *
	 * @return the patcher fix persistence
	 */
	public PatcherFixPersistence getPatcherFixPersistence() {
		return patcherFixPersistence;
	}

	/**
	 * Sets the patcher fix persistence.
	 *
	 * @param patcherFixPersistence the patcher fix persistence
	 */
	public void setPatcherFixPersistence(
		PatcherFixPersistence patcherFixPersistence) {
		this.patcherFixPersistence = patcherFixPersistence;
	}

	/**
	 * Returns the patcher fix component local service.
	 *
	 * @return the patcher fix component local service
	 */
	public com.liferay.osb.patcher.service.PatcherFixComponentLocalService getPatcherFixComponentLocalService() {
		return patcherFixComponentLocalService;
	}

	/**
	 * Sets the patcher fix component local service.
	 *
	 * @param patcherFixComponentLocalService the patcher fix component local service
	 */
	public void setPatcherFixComponentLocalService(
		com.liferay.osb.patcher.service.PatcherFixComponentLocalService patcherFixComponentLocalService) {
		this.patcherFixComponentLocalService = patcherFixComponentLocalService;
	}

	/**
	 * Returns the patcher fix component persistence.
	 *
	 * @return the patcher fix component persistence
	 */
	public PatcherFixComponentPersistence getPatcherFixComponentPersistence() {
		return patcherFixComponentPersistence;
	}

	/**
	 * Sets the patcher fix component persistence.
	 *
	 * @param patcherFixComponentPersistence the patcher fix component persistence
	 */
	public void setPatcherFixComponentPersistence(
		PatcherFixComponentPersistence patcherFixComponentPersistence) {
		this.patcherFixComponentPersistence = patcherFixComponentPersistence;
	}

	/**
	 * Returns the patcher fix pack local service.
	 *
	 * @return the patcher fix pack local service
	 */
	public com.liferay.osb.patcher.service.PatcherFixPackLocalService getPatcherFixPackLocalService() {
		return patcherFixPackLocalService;
	}

	/**
	 * Sets the patcher fix pack local service.
	 *
	 * @param patcherFixPackLocalService the patcher fix pack local service
	 */
	public void setPatcherFixPackLocalService(
		com.liferay.osb.patcher.service.PatcherFixPackLocalService patcherFixPackLocalService) {
		this.patcherFixPackLocalService = patcherFixPackLocalService;
	}

	/**
	 * Returns the patcher fix pack persistence.
	 *
	 * @return the patcher fix pack persistence
	 */
	public PatcherFixPackPersistence getPatcherFixPackPersistence() {
		return patcherFixPackPersistence;
	}

	/**
	 * Sets the patcher fix pack persistence.
	 *
	 * @param patcherFixPackPersistence the patcher fix pack persistence
	 */
	public void setPatcherFixPackPersistence(
		PatcherFixPackPersistence patcherFixPackPersistence) {
		this.patcherFixPackPersistence = patcherFixPackPersistence;
	}

	/**
	 * Returns the patcher fix rel local service.
	 *
	 * @return the patcher fix rel local service
	 */
	public com.liferay.osb.patcher.service.PatcherFixRelLocalService getPatcherFixRelLocalService() {
		return patcherFixRelLocalService;
	}

	/**
	 * Sets the patcher fix rel local service.
	 *
	 * @param patcherFixRelLocalService the patcher fix rel local service
	 */
	public void setPatcherFixRelLocalService(
		com.liferay.osb.patcher.service.PatcherFixRelLocalService patcherFixRelLocalService) {
		this.patcherFixRelLocalService = patcherFixRelLocalService;
	}

	/**
	 * Returns the patcher fix rel persistence.
	 *
	 * @return the patcher fix rel persistence
	 */
	public PatcherFixRelPersistence getPatcherFixRelPersistence() {
		return patcherFixRelPersistence;
	}

	/**
	 * Sets the patcher fix rel persistence.
	 *
	 * @param patcherFixRelPersistence the patcher fix rel persistence
	 */
	public void setPatcherFixRelPersistence(
		PatcherFixRelPersistence patcherFixRelPersistence) {
		this.patcherFixRelPersistence = patcherFixRelPersistence;
	}

	/**
	 * Returns the patcher product version local service.
	 *
	 * @return the patcher product version local service
	 */
	public com.liferay.osb.patcher.service.PatcherProductVersionLocalService getPatcherProductVersionLocalService() {
		return patcherProductVersionLocalService;
	}

	/**
	 * Sets the patcher product version local service.
	 *
	 * @param patcherProductVersionLocalService the patcher product version local service
	 */
	public void setPatcherProductVersionLocalService(
		com.liferay.osb.patcher.service.PatcherProductVersionLocalService patcherProductVersionLocalService) {
		this.patcherProductVersionLocalService = patcherProductVersionLocalService;
	}

	/**
	 * Returns the patcher product version persistence.
	 *
	 * @return the patcher product version persistence
	 */
	public PatcherProductVersionPersistence getPatcherProductVersionPersistence() {
		return patcherProductVersionPersistence;
	}

	/**
	 * Sets the patcher product version persistence.
	 *
	 * @param patcherProductVersionPersistence the patcher product version persistence
	 */
	public void setPatcherProductVersionPersistence(
		PatcherProductVersionPersistence patcherProductVersionPersistence) {
		this.patcherProductVersionPersistence = patcherProductVersionPersistence;
	}

	/**
	 * Returns the patcher project version local service.
	 *
	 * @return the patcher project version local service
	 */
	public com.liferay.osb.patcher.service.PatcherProjectVersionLocalService getPatcherProjectVersionLocalService() {
		return patcherProjectVersionLocalService;
	}

	/**
	 * Sets the patcher project version local service.
	 *
	 * @param patcherProjectVersionLocalService the patcher project version local service
	 */
	public void setPatcherProjectVersionLocalService(
		com.liferay.osb.patcher.service.PatcherProjectVersionLocalService patcherProjectVersionLocalService) {
		this.patcherProjectVersionLocalService = patcherProjectVersionLocalService;
	}

	/**
	 * Returns the patcher project version persistence.
	 *
	 * @return the patcher project version persistence
	 */
	public PatcherProjectVersionPersistence getPatcherProjectVersionPersistence() {
		return patcherProjectVersionPersistence;
	}

	/**
	 * Sets the patcher project version persistence.
	 *
	 * @param patcherProjectVersionPersistence the patcher project version persistence
	 */
	public void setPatcherProjectVersionPersistence(
		PatcherProjectVersionPersistence patcherProjectVersionPersistence) {
		this.patcherProjectVersionPersistence = patcherProjectVersionPersistence;
	}

	/**
	 * Returns the patcher ticket hint local service.
	 *
	 * @return the patcher ticket hint local service
	 */
	public com.liferay.osb.patcher.service.PatcherTicketHintLocalService getPatcherTicketHintLocalService() {
		return patcherTicketHintLocalService;
	}

	/**
	 * Sets the patcher ticket hint local service.
	 *
	 * @param patcherTicketHintLocalService the patcher ticket hint local service
	 */
	public void setPatcherTicketHintLocalService(
		com.liferay.osb.patcher.service.PatcherTicketHintLocalService patcherTicketHintLocalService) {
		this.patcherTicketHintLocalService = patcherTicketHintLocalService;
	}

	/**
	 * Returns the patcher ticket hint persistence.
	 *
	 * @return the patcher ticket hint persistence
	 */
	public PatcherTicketHintPersistence getPatcherTicketHintPersistence() {
		return patcherTicketHintPersistence;
	}

	/**
	 * Sets the patcher ticket hint persistence.
	 *
	 * @param patcherTicketHintPersistence the patcher ticket hint persistence
	 */
	public void setPatcherTicketHintPersistence(
		PatcherTicketHintPersistence patcherTicketHintPersistence) {
		this.patcherTicketHintPersistence = patcherTicketHintPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.liferay.osb.patcher.model.PatcherFixComponent",
			patcherFixComponentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.liferay.osb.patcher.model.PatcherFixComponent");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return PatcherFixComponent.class;
	}

	protected String getModelClassName() {
		return PatcherFixComponent.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = patcherFixComponentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.osb.patcher.service.PatcherAccountLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherAccountLocalService patcherAccountLocalService;
	@BeanReference(type = PatcherAccountPersistence.class)
	protected PatcherAccountPersistence patcherAccountPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherBuildLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherBuildLocalService patcherBuildLocalService;
	@BeanReference(type = PatcherBuildPersistence.class)
	protected PatcherBuildPersistence patcherBuildPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherBuildRelLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherBuildRelLocalService patcherBuildRelLocalService;
	@BeanReference(type = PatcherBuildRelPersistence.class)
	protected PatcherBuildRelPersistence patcherBuildRelPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherFixLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherFixLocalService patcherFixLocalService;
	@BeanReference(type = PatcherFixPersistence.class)
	protected PatcherFixPersistence patcherFixPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherFixComponentLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherFixComponentLocalService patcherFixComponentLocalService;
	@BeanReference(type = PatcherFixComponentPersistence.class)
	protected PatcherFixComponentPersistence patcherFixComponentPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherFixPackLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherFixPackLocalService patcherFixPackLocalService;
	@BeanReference(type = PatcherFixPackPersistence.class)
	protected PatcherFixPackPersistence patcherFixPackPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherFixRelLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherFixRelLocalService patcherFixRelLocalService;
	@BeanReference(type = PatcherFixRelPersistence.class)
	protected PatcherFixRelPersistence patcherFixRelPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherProductVersionLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherProductVersionLocalService patcherProductVersionLocalService;
	@BeanReference(type = PatcherProductVersionPersistence.class)
	protected PatcherProductVersionPersistence patcherProductVersionPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherProjectVersionLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherProjectVersionLocalService patcherProjectVersionLocalService;
	@BeanReference(type = PatcherProjectVersionPersistence.class)
	protected PatcherProjectVersionPersistence patcherProjectVersionPersistence;
	@BeanReference(type = com.liferay.osb.patcher.service.PatcherTicketHintLocalService.class)
	protected com.liferay.osb.patcher.service.PatcherTicketHintLocalService patcherTicketHintLocalService;
	@BeanReference(type = PatcherTicketHintPersistence.class)
	protected PatcherTicketHintPersistence patcherTicketHintPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ClassNameLocalService.class)
	protected com.liferay.portal.service.ClassNameLocalService classNameLocalService;
	@BeanReference(type = com.liferay.portal.service.ClassNameService.class)
	protected com.liferay.portal.service.ClassNameService classNameService;
	@BeanReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private PatcherFixComponentLocalServiceClpInvoker _clpInvoker = new PatcherFixComponentLocalServiceClpInvoker();
}