apiDir: ../object-admin-rest-api/src/main/java
apiPackagePath: com.liferay.object.admin.rest
application:
    baseURI: /object-admin
    className: ObjectAdminRESTApplication
    name: Liferay.Object.Admin.REST
author: Javier Gamarra
clientDir: ../object-admin-rest-client/src/main/java
compatibilityVersion: 13
forcePredictableOperationId: true
generateClientJS: true
javaEEPackage: jakarta
testDir: ../object-admin-rest-test/src/testIntegration/java