modified.files.includes[relevant][portal-user-locale-options-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][portal-user-locale-options-web-playwright-rule]=\
    portal-user-locale-options-web.main

relevant.rule.names=portal-user-locale-options-web-playwright-rule

test.batch.names[relevant][portal-user-locale-options-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163