modified.files.includes[relevant][saved-content-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][saved-content-java-rule]=\
    apps/saved-content/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][saved-content-java-rule]=\
    apps/saved-content/**/*Test.java

relevant.rule.names=saved-content-java-rule

test.batch.names[relevant][saved-content-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Documents and Media