sourceCompatibility = "1.8"
targetCompatibility = "1.8"

dependencies {
	api group: "com.puppycrawl.tools", name: "checkstyle", version: "8.43"
	api group: "commons-io", name: "commons-io", version: "2.19.0"
	api group: "org.antlr", name: "antlr4-runtime", version: "4.9.2"
	compileInclude group: "com.liferay", name: "com.liferay.petra.string", version: "2.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly project(":core:petra:petra-io")
}

updateFileVersions {
	replaceOnlyIf([{
		String group, String replacement, String content, File contentFile ->

		if (contentFile.parentFile.name in ["portal-tools-rest-builder", "portal-tools-service-builder", "source-formatter"]) {
			return true
		}

		return false
	}])
}