modified.files.includes[relevant][feature-flag-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][feature-flag-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][feature-flag-java-rule]=\
    apps/feature-flag/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][feature-flag-java-rule]=\
    apps/feature-flag/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][feature-flag-playwright-rule]=\
    feature-flag-web.main

relevant.rule.names=\
    feature-flag-java-rule,\
    feature-flag-playwright-rule

test.batch.names[relevant][feature-flag-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][feature-flag-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Feature Flag