resource "helm_release" "argo_workflows" {
	chart="argo-workflows"
	depends_on=[
		kubernetes_namespace.argocd,
	]
	name="argo-workflows"
	namespace=var.argo_workflows_namespace
	repository="https://argoproj.github.io/argo-helm"
	upgrade_install=true
	values=[
		yamlencode(
			{
				controller={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
					workflowDefaults={
						spec={
							securityContext={
								runAsNonRoot=true
								runAsUser=8737
								seccompProfile={
									type="RuntimeDefault"
								}
							}
						}
					}
				}
				executor={
					image={
						tag="v4.1.2-nonroot"
					}
					securityContext={
						allowPrivilegeEscalation=false
						capabilities={
							drop=["ALL"]
						}
						runAsNonRoot=true
						runAsUser=8737
						seccompProfile={
							type="RuntimeDefault"
						}
					}
				}
				extraObjects=[
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="argo-workflows-metrics-ingress"
						}
						spec={
							ingress=[
								{
									from=[
										{
											namespaceSelector={
												matchLabels={
													"kubernetes.io/metadata.name"=var.observability_config.namespace
												}
											}
										},
									]
									ports=[
										{
											port="metrics"
											protocol="TCP"
										},
									]
								},
							]
							podSelector={
								matchLabels={
									"app.kubernetes.io/instance"="argo-workflows"
									"app.kubernetes.io/name"="argo-workflows-workflow-controller"
								}
							}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="default-deny-ingress"
						}
						spec={
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
				]
				mainContainer={
					securityContext={
						allowPrivilegeEscalation=false
						capabilities={
							drop=["ALL"]
						}
						runAsNonRoot=true
						runAsUser=8737
						seccompProfile={
							type="RuntimeDefault"
						}
					}
				}
				server={
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
			}),
	]
	version=var.argo_workflows_helm_chart_version
}
resource "kubernetes_namespace" "argo_workflows" {
	metadata {
		labels=local.common_labels
		name=var.argo_workflows_namespace
	}
}