resource "helm_release" "crossplane" {
	atomic=true
	chart="crossplane"
	cleanup_on_fail=true
	create_namespace=true
	name="crossplane"
	namespace=var.crossplane_namespace
	repository="https://charts.crossplane.io/stable"
	values=[
		yamlencode(
			{
				extraObjects=[
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=merge(
								local.common_labels,
								{
									"app.kubernetes.io/name"="crossplane-function-grpc-ingress"
								})
							name="crossplane-function-grpc-ingress"
						}
						spec={
							ingress=[
								{
									from=[
										{
											podSelector={
												matchLabels={
													"app"="crossplane"
													"release"="crossplane"
												}
											}
										},
									]
									ports=[
										{
											port="grpc"
											protocol="TCP"
										},
									]
								},
							]
							podSelector={
								matchExpressions=[
									{
										key="pkg.crossplane.io/function"
										operator="Exists"
									},
								]
							}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=merge(
								local.common_labels,
								{
									"app.kubernetes.io/name"="crossplane-metrics-ingress"
								})
							name="crossplane-metrics-ingress"
						}
						spec={
							ingress=[
								{
									from=[
										{
											namespaceSelector={
												matchLabels={
													"kubernetes.io/metadata.name"=var.observability_namespace
												}
											}
										},
									]
									ports=[
										{
											port="metrics"
											protocol="TCP"
										},
									]
								},
							]
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=merge(
								local.common_labels,
								{
									"app.kubernetes.io/name"="crossplane-webhook-ingress"
								})
							name="crossplane-webhook-ingress"
						}
						spec={
							ingress=[
								{
									from=[
										{
											ipBlock={
												cidr=var.master_ipv4_cidr_block
											}
										},
									]
									ports=[
										{
											port=9443
											protocol="TCP"
										},
									]
								},
							]
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=merge(
								local.common_labels,
								{
									"app.kubernetes.io/name"="default-deny-ingress"
								})
							name="default-deny-ingress"
						}
						spec={
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
				]
				resourcesCrossplane={
					limits={
						memory="2Gi"
					}
					requests={
						cpu="63m"
						memory="768Mi"
					}
				}
				resourcesRBACManager={
					limits={
						memory="512Mi"
					}
					requests={
						cpu="15m"
						memory="256Mi"
					}
				}
			})
	]
	version=var.crossplane_helm_chart_version
	wait=true
}