resource "helm_release" "external_secrets" {
	chart="external-secrets"
	create_namespace=true
	name="external-secrets"
	namespace=var.external_secrets_namespace
	repository="https://charts.external-secrets.io"
	values=[
		yamlencode(
			{
				certController={
					resources={
						limits={
							memory="512Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
				extraObjects=[
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="default-deny-ingress"
						}
						spec={
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="external-secrets-metrics-ingress"
						}
						spec={
							ingress=[
								{
									from=[
										{
											namespaceSelector={
												matchLabels={
													"kubernetes.io/metadata.name"=var.observability_config.namespace
												}
											}
										},
									]
									ports=[
										{
											port="metrics"
											protocol="TCP"
										},
									]
								},
							]
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="external-secrets-webhook-ingress"
						}
						spec={
							ingress=[
								{
									from=local.webhook_ingress_from
									ports=[
										{
											port="webhook"
											protocol="TCP"
										},
									]
								},
							]
							podSelector={
								matchLabels={
									"app.kubernetes.io/instance"="external-secrets"
									"app.kubernetes.io/name"="external-secrets-webhook"
								}
							}
							policyTypes=["Ingress"]
						}
					},
				]
				installCRDs=true
				resources={
					limits={
						memory="512Mi"
					}
					requests={
						cpu="15m"
						memory="128Mi"
					}
				}
				webhook={
					resources={
						limits={
							memory="256Mi"
						}
						requests={
							cpu="15m"
							memory="128Mi"
						}
					}
				}
			}),
	]
	version=var.external_secrets_helm_chart_version
	wait=true
}