resource "helm_release" "keda" {
	chart="keda"
	count=var.keda_enabled ? 1 : 0
	create_namespace=true
	name="keda"
	namespace=var.keda_namespace
	repository="https://kedacore.github.io/charts"
	values=[
		yamlencode(
			{
				extraObjects=[
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="default-deny-ingress"
						}
						spec={
							podSelector={}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="keda-admission-webhooks-ingress"
						}
						spec={
							ingress=[
								{
									from=local.webhook_ingress_from
									ports=[
										{
											port=9443
											protocol="TCP"
										},
									]
								},
							]
							podSelector={
								matchLabels={
									"app"="keda-admission-webhooks"
								}
							}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="keda-operator-ingress"
						}
						spec={
							ingress=[
								{
									from=[
										{
											podSelector={
												matchLabels={
													"app"="keda-operator-metrics-apiserver"
												}
											}
										},
									]
									ports=[
										{
											port="metricsservice"
											protocol="TCP"
										},
									]
								},
							]
							podSelector={
								matchLabels={
									"app"="keda-operator"
								}
							}
							policyTypes=["Ingress"]
						}
					},
					{
						apiVersion="networking.k8s.io/v1"
						kind="NetworkPolicy"
						metadata={
							labels=local.common_labels
							name="keda-operator-metrics-apiserver-ingress"
						}
						spec={
							ingress=[
								{
									from=local.webhook_ingress_from
									ports=[
										{
											port=6443
											protocol="TCP"
										},
									]
								},
							]
							podSelector={
								matchLabels={
									"app"="keda-operator-metrics-apiserver"
								}
							}
							policyTypes=["Ingress"]
						}
					},
				]
				networkPolicy={
					enabled=false
				}
				service={
					portHttpsTarget=6443
				}
				webhooks={
					port=9443
				}
			}),
	]
	version=var.keda_helm_chart_version
}