apiDir: ../object-rest-api/src/main/java
apiPackagePath: com.liferay.object.rest
author: Javier Gamarra
compatibilityVersion: 13
forcePredictableOperationId: true
generateOpenAPI: false
javaEEPackage: jakarta