resource "helm_release" "crossplane" {
	atomic=true
	chart="crossplane"
	cleanup_on_fail=true
	create_namespace=true
	name="crossplane"
	namespace=var.crossplane_namespace
	repository="https://charts.crossplane.io/stable"
	values=[
		yamlencode(
			{
				resourcesCrossplane={
					limits={
						cpu="500m"
						memory="1Gi"
					}
					requests={
						cpu="100m"
						memory="768Mi"
					}
				}
				resourcesRBACManager={
					limits={
						cpu="500m"
						memory="512Mi"
					}
					requests={
						cpu="100m"
						memory="256Mi"
					}
				}
			})
	]
	version="2.1.3"
	wait=true
}