resource "helm_release" "external_secrets" {
	chart="external-secrets"
	create_namespace=true
	name="external-secrets"
	namespace=var.external_secrets_namespace
	repository="https://charts.external-secrets.io"
	values=[
		yamlencode(
			{
				certController={
					resources={
						limits={
							cpu="50m"
							memory="256Mi"
						}
						requests={
							cpu="20m"
							memory="128Mi"
						}
					}
				}
				installCRDs=true
				resources={
					limits={
						cpu="100m"
						memory="256Mi"
					}
					requests={
						cpu="20m"
						memory="128Mi"
					}
				}
				webhook={
					resources={
						limits={
							cpu="50m"
							memory="256Mi"
						}
						requests={
							cpu="20m"
							memory="128Mi"
						}
					}
				}
			}),
	]
	version="1.0.0"
	wait=true
}