modified.files.includes[relevant][shared-dependencies-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][shared-dependencies-java-rule]=\
    apps/shared-dependencies/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][shared-dependencies-java-rule]=\
    apps/shared-dependencies/**/*Test.java

relevant.rule.names=shared-dependencies-java-rule

test.batch.names[relevant][shared-dependencies-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services