/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.patcher.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.patcher.model.PatcherTicketHint;
import com.liferay.osb.patcher.model.PatcherTicketHintModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PatcherTicketHint service. Represents a row in the &quot;OSBPatcher_PatcherTicketHint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PatcherTicketHintModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatcherTicketHintImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatcherTicketHintImpl
 * @generated
 */
public class PatcherTicketHintModelImpl
	extends BaseModelImpl<PatcherTicketHint> implements PatcherTicketHintModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patcher ticket hint model instance should use the <code>PatcherTicketHint</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBPatcher_PatcherTicketHint";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"patcherTicketHintId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP},
		{"patcherProductVersionId", Types.BIGINT}, {"script", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patcherTicketHintId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("patcherProductVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("script", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBPatcher_PatcherTicketHint (mvccVersion LONG default 0 not null,patcherTicketHintId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,patcherProductVersionId LONG,script VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBPatcher_PatcherTicketHint";

	public static final String ORDER_BY_JPQL =
		" ORDER BY patcherTicketHint.patcherTicketHintId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBPatcher_PatcherTicketHint.patcherTicketHintId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATCHERPRODUCTVERSIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATCHERTICKETHINTID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PatcherTicketHintModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _patcherTicketHintId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatcherTicketHintId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _patcherTicketHintId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PatcherTicketHint.class;
	}

	@Override
	public String getModelClassName() {
		return PatcherTicketHint.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PatcherTicketHint, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PatcherTicketHint, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatcherTicketHint, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PatcherTicketHint)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PatcherTicketHint, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PatcherTicketHint, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PatcherTicketHint)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PatcherTicketHint, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PatcherTicketHint, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PatcherTicketHint, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PatcherTicketHint, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PatcherTicketHint, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PatcherTicketHint::getMvccVersion);
			attributeGetterFunctions.put(
				"patcherTicketHintId",
				PatcherTicketHint::getPatcherTicketHintId);
			attributeGetterFunctions.put(
				"companyId", PatcherTicketHint::getCompanyId);
			attributeGetterFunctions.put(
				"userId", PatcherTicketHint::getUserId);
			attributeGetterFunctions.put(
				"userName", PatcherTicketHint::getUserName);
			attributeGetterFunctions.put(
				"createDate", PatcherTicketHint::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PatcherTicketHint::getModifiedDate);
			attributeGetterFunctions.put(
				"patcherProductVersionId",
				PatcherTicketHint::getPatcherProductVersionId);
			attributeGetterFunctions.put(
				"script", PatcherTicketHint::getScript);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PatcherTicketHint, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PatcherTicketHint, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<PatcherTicketHint, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PatcherTicketHint, Long>)
					PatcherTicketHint::setMvccVersion);
			attributeSetterBiConsumers.put(
				"patcherTicketHintId",
				(BiConsumer<PatcherTicketHint, Long>)
					PatcherTicketHint::setPatcherTicketHintId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PatcherTicketHint, Long>)
					PatcherTicketHint::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<PatcherTicketHint, Long>)
					PatcherTicketHint::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<PatcherTicketHint, String>)
					PatcherTicketHint::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PatcherTicketHint, Date>)
					PatcherTicketHint::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PatcherTicketHint, Date>)
					PatcherTicketHint::setModifiedDate);
			attributeSetterBiConsumers.put(
				"patcherProductVersionId",
				(BiConsumer<PatcherTicketHint, Long>)
					PatcherTicketHint::setPatcherProductVersionId);
			attributeSetterBiConsumers.put(
				"script",
				(BiConsumer<PatcherTicketHint, String>)
					PatcherTicketHint::setScript);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getPatcherTicketHintId() {
		return _patcherTicketHintId;
	}

	@Override
	public void setPatcherTicketHintId(long patcherTicketHintId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patcherTicketHintId = patcherTicketHintId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getPatcherProductVersionId() {
		return _patcherProductVersionId;
	}

	@Override
	public void setPatcherProductVersionId(long patcherProductVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patcherProductVersionId = patcherProductVersionId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPatcherProductVersionId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("patcherProductVersionId"));
	}

	@Override
	public String getScript() {
		if (_script == null) {
			return "";
		}
		else {
			return _script;
		}
	}

	@Override
	public void setScript(String script) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_script = script;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PatcherTicketHint.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PatcherTicketHint toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PatcherTicketHint>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatcherTicketHintImpl patcherTicketHintImpl =
			new PatcherTicketHintImpl();

		patcherTicketHintImpl.setMvccVersion(getMvccVersion());
		patcherTicketHintImpl.setPatcherTicketHintId(getPatcherTicketHintId());
		patcherTicketHintImpl.setCompanyId(getCompanyId());
		patcherTicketHintImpl.setUserId(getUserId());
		patcherTicketHintImpl.setUserName(getUserName());
		patcherTicketHintImpl.setCreateDate(getCreateDate());
		patcherTicketHintImpl.setModifiedDate(getModifiedDate());
		patcherTicketHintImpl.setPatcherProductVersionId(
			getPatcherProductVersionId());
		patcherTicketHintImpl.setScript(getScript());

		patcherTicketHintImpl.resetOriginalValues();

		return patcherTicketHintImpl;
	}

	@Override
	public PatcherTicketHint cloneWithOriginalValues() {
		PatcherTicketHintImpl patcherTicketHintImpl =
			new PatcherTicketHintImpl();

		patcherTicketHintImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		patcherTicketHintImpl.setPatcherTicketHintId(
			this.<Long>getColumnOriginalValue("patcherTicketHintId"));
		patcherTicketHintImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		patcherTicketHintImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		patcherTicketHintImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		patcherTicketHintImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		patcherTicketHintImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		patcherTicketHintImpl.setPatcherProductVersionId(
			this.<Long>getColumnOriginalValue("patcherProductVersionId"));
		patcherTicketHintImpl.setScript(
			this.<String>getColumnOriginalValue("script"));

		return patcherTicketHintImpl;
	}

	@Override
	public int compareTo(PatcherTicketHint patcherTicketHint) {
		long primaryKey = patcherTicketHint.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PatcherTicketHint)) {
			return false;
		}

		PatcherTicketHint patcherTicketHint = (PatcherTicketHint)object;

		long primaryKey = patcherTicketHint.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PatcherTicketHint> toCacheModel() {
		PatcherTicketHintCacheModel patcherTicketHintCacheModel =
			new PatcherTicketHintCacheModel();

		patcherTicketHintCacheModel.mvccVersion = getMvccVersion();

		patcherTicketHintCacheModel.patcherTicketHintId =
			getPatcherTicketHintId();

		patcherTicketHintCacheModel.companyId = getCompanyId();

		patcherTicketHintCacheModel.userId = getUserId();

		patcherTicketHintCacheModel.userName = getUserName();

		String userName = patcherTicketHintCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			patcherTicketHintCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			patcherTicketHintCacheModel.createDate = createDate.getTime();
		}
		else {
			patcherTicketHintCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			patcherTicketHintCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			patcherTicketHintCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		patcherTicketHintCacheModel.patcherProductVersionId =
			getPatcherProductVersionId();

		patcherTicketHintCacheModel.script = getScript();

		String script = patcherTicketHintCacheModel.script;

		if ((script != null) && (script.length() == 0)) {
			patcherTicketHintCacheModel.script = null;
		}

		return patcherTicketHintCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PatcherTicketHint, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PatcherTicketHint, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatcherTicketHint, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PatcherTicketHint)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PatcherTicketHint>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PatcherTicketHint.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _patcherTicketHintId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _patcherProductVersionId;
	private String _script;

	public <T> T getColumnValue(String columnName) {
		Function<PatcherTicketHint, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PatcherTicketHint)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("patcherTicketHintId", _patcherTicketHintId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"patcherProductVersionId", _patcherProductVersionId);
		_columnOriginalValues.put("script", _script);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("patcherTicketHintId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("patcherProductVersionId", 128L);

		columnBitmasks.put("script", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PatcherTicketHint _escapedModel;

}