/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.patcher.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.patcher.model.PatcherFixRel;
import com.liferay.osb.patcher.model.PatcherFixRelModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PatcherFixRel service. Represents a row in the &quot;OSBPatcher_PatcherFixRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PatcherFixRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatcherFixRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatcherFixRelImpl
 * @generated
 */
public class PatcherFixRelModelImpl
	extends BaseModelImpl<PatcherFixRel> implements PatcherFixRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patcher fix rel model instance should use the <code>PatcherFixRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSBPatcher_PatcherFixRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"patcherFixRelId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"childPatcherFixId", Types.BIGINT},
		{"parentPatcherFixId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patcherFixRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("childPatcherFixId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentPatcherFixId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSBPatcher_PatcherFixRel (mvccVersion LONG default 0 not null,patcherFixRelId LONG not null primary key,companyId LONG,childPatcherFixId LONG,parentPatcherFixId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table OSBPatcher_PatcherFixRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY patcherFixRel.patcherFixRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSBPatcher_PatcherFixRel.patcherFixRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATCHERFIXRELID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PatcherFixRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _patcherFixRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatcherFixRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _patcherFixRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PatcherFixRel.class;
	}

	@Override
	public String getModelClassName() {
		return PatcherFixRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PatcherFixRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PatcherFixRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatcherFixRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PatcherFixRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PatcherFixRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PatcherFixRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PatcherFixRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PatcherFixRel, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PatcherFixRel, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<PatcherFixRel, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<PatcherFixRel, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PatcherFixRel, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PatcherFixRel::getMvccVersion);
			attributeGetterFunctions.put(
				"patcherFixRelId", PatcherFixRel::getPatcherFixRelId);
			attributeGetterFunctions.put(
				"companyId", PatcherFixRel::getCompanyId);
			attributeGetterFunctions.put(
				"childPatcherFixId", PatcherFixRel::getChildPatcherFixId);
			attributeGetterFunctions.put(
				"parentPatcherFixId", PatcherFixRel::getParentPatcherFixId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<PatcherFixRel, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PatcherFixRel, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<PatcherFixRel, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PatcherFixRel, Long>)PatcherFixRel::setMvccVersion);
			attributeSetterBiConsumers.put(
				"patcherFixRelId",
				(BiConsumer<PatcherFixRel, Long>)
					PatcherFixRel::setPatcherFixRelId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PatcherFixRel, Long>)PatcherFixRel::setCompanyId);
			attributeSetterBiConsumers.put(
				"childPatcherFixId",
				(BiConsumer<PatcherFixRel, Long>)
					PatcherFixRel::setChildPatcherFixId);
			attributeSetterBiConsumers.put(
				"parentPatcherFixId",
				(BiConsumer<PatcherFixRel, Long>)
					PatcherFixRel::setParentPatcherFixId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getPatcherFixRelId() {
		return _patcherFixRelId;
	}

	@Override
	public void setPatcherFixRelId(long patcherFixRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patcherFixRelId = patcherFixRelId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getChildPatcherFixId() {
		return _childPatcherFixId;
	}

	@Override
	public void setChildPatcherFixId(long childPatcherFixId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_childPatcherFixId = childPatcherFixId;
	}

	@Override
	public long getParentPatcherFixId() {
		return _parentPatcherFixId;
	}

	@Override
	public void setParentPatcherFixId(long parentPatcherFixId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentPatcherFixId = parentPatcherFixId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PatcherFixRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PatcherFixRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PatcherFixRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatcherFixRelImpl patcherFixRelImpl = new PatcherFixRelImpl();

		patcherFixRelImpl.setMvccVersion(getMvccVersion());
		patcherFixRelImpl.setPatcherFixRelId(getPatcherFixRelId());
		patcherFixRelImpl.setCompanyId(getCompanyId());
		patcherFixRelImpl.setChildPatcherFixId(getChildPatcherFixId());
		patcherFixRelImpl.setParentPatcherFixId(getParentPatcherFixId());

		patcherFixRelImpl.resetOriginalValues();

		return patcherFixRelImpl;
	}

	@Override
	public PatcherFixRel cloneWithOriginalValues() {
		PatcherFixRelImpl patcherFixRelImpl = new PatcherFixRelImpl();

		patcherFixRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		patcherFixRelImpl.setPatcherFixRelId(
			this.<Long>getColumnOriginalValue("patcherFixRelId"));
		patcherFixRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		patcherFixRelImpl.setChildPatcherFixId(
			this.<Long>getColumnOriginalValue("childPatcherFixId"));
		patcherFixRelImpl.setParentPatcherFixId(
			this.<Long>getColumnOriginalValue("parentPatcherFixId"));

		return patcherFixRelImpl;
	}

	@Override
	public int compareTo(PatcherFixRel patcherFixRel) {
		long primaryKey = patcherFixRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PatcherFixRel)) {
			return false;
		}

		PatcherFixRel patcherFixRel = (PatcherFixRel)object;

		long primaryKey = patcherFixRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PatcherFixRel> toCacheModel() {
		PatcherFixRelCacheModel patcherFixRelCacheModel =
			new PatcherFixRelCacheModel();

		patcherFixRelCacheModel.mvccVersion = getMvccVersion();

		patcherFixRelCacheModel.patcherFixRelId = getPatcherFixRelId();

		patcherFixRelCacheModel.companyId = getCompanyId();

		patcherFixRelCacheModel.childPatcherFixId = getChildPatcherFixId();

		patcherFixRelCacheModel.parentPatcherFixId = getParentPatcherFixId();

		return patcherFixRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PatcherFixRel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PatcherFixRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatcherFixRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PatcherFixRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PatcherFixRel>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PatcherFixRel.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _patcherFixRelId;
	private long _companyId;
	private long _childPatcherFixId;
	private long _parentPatcherFixId;

	public <T> T getColumnValue(String columnName) {
		Function<PatcherFixRel, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PatcherFixRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("patcherFixRelId", _patcherFixRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("childPatcherFixId", _childPatcherFixId);
		_columnOriginalValues.put("parentPatcherFixId", _parentPatcherFixId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("patcherFixRelId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("childPatcherFixId", 8L);

		columnBitmasks.put("parentPatcherFixId", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PatcherFixRel _escapedModel;

}