/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.osb.patcher.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.osb.patcher.model.PatcherProjectVersion;
import com.liferay.osb.patcher.model.PatcherProjectVersionModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PatcherProjectVersion service. Represents a row in the &quot;PProjectVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PatcherProjectVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatcherProjectVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatcherProjectVersionImpl
 * @generated
 */
public class PatcherProjectVersionModelImpl
	extends BaseModelImpl<PatcherProjectVersion>
	implements PatcherProjectVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patcher project version model instance should use the <code>PatcherProjectVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "PProjectVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"patcherProjectVersionId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"patcherProductVersionId", Types.BIGINT},
		{"rootPatcherProjectVersionId", Types.BIGINT},
		{"combinedBranch", Types.BOOLEAN}, {"committish", Types.VARCHAR},
		{"fixedIssues", Types.CLOB}, {"hide", Types.BOOLEAN},
		{"name", Types.VARCHAR}, {"productVersion", Types.INTEGER},
		{"repositoryName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("patcherProjectVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("patcherProductVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rootPatcherProjectVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("combinedBranch", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("committish", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fixedIssues", Types.CLOB);
		TABLE_COLUMNS_MAP.put("hide", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productVersion", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("repositoryName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PProjectVersion (mvccVersion LONG default 0 not null,patcherProjectVersionId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,patcherProductVersionId LONG,rootPatcherProjectVersionId LONG,combinedBranch BOOLEAN,committish VARCHAR(150) null,fixedIssues TEXT null,hide BOOLEAN,name VARCHAR(150) null,productVersion INTEGER,repositoryName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table PProjectVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY patcherProjectVersion.patcherProjectVersionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PProjectVersion.patcherProjectVersionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PATCHERPROJECTVERSIONID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PatcherProjectVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _patcherProjectVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPatcherProjectVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _patcherProjectVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PatcherProjectVersion.class;
	}

	@Override
	public String getModelClassName() {
		return PatcherProjectVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PatcherProjectVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PatcherProjectVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatcherProjectVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PatcherProjectVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PatcherProjectVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PatcherProjectVersion, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PatcherProjectVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PatcherProjectVersion, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PatcherProjectVersion, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<PatcherProjectVersion, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<PatcherProjectVersion, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<PatcherProjectVersion, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", PatcherProjectVersion::getMvccVersion);
			attributeGetterFunctions.put(
				"patcherProjectVersionId",
				PatcherProjectVersion::getPatcherProjectVersionId);
			attributeGetterFunctions.put(
				"companyId", PatcherProjectVersion::getCompanyId);
			attributeGetterFunctions.put(
				"userId", PatcherProjectVersion::getUserId);
			attributeGetterFunctions.put(
				"userName", PatcherProjectVersion::getUserName);
			attributeGetterFunctions.put(
				"createDate", PatcherProjectVersion::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", PatcherProjectVersion::getModifiedDate);
			attributeGetterFunctions.put(
				"patcherProductVersionId",
				PatcherProjectVersion::getPatcherProductVersionId);
			attributeGetterFunctions.put(
				"rootPatcherProjectVersionId",
				PatcherProjectVersion::getRootPatcherProjectVersionId);
			attributeGetterFunctions.put(
				"combinedBranch", PatcherProjectVersion::getCombinedBranch);
			attributeGetterFunctions.put(
				"committish", PatcherProjectVersion::getCommittish);
			attributeGetterFunctions.put(
				"fixedIssues", PatcherProjectVersion::getFixedIssues);
			attributeGetterFunctions.put(
				"hide", PatcherProjectVersion::getHide);
			attributeGetterFunctions.put(
				"name", PatcherProjectVersion::getName);
			attributeGetterFunctions.put(
				"productVersion", PatcherProjectVersion::getProductVersion);
			attributeGetterFunctions.put(
				"repositoryName", PatcherProjectVersion::getRepositoryName);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<PatcherProjectVersion, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<PatcherProjectVersion, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<PatcherProjectVersion, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<PatcherProjectVersion, Long>)
					PatcherProjectVersion::setMvccVersion);
			attributeSetterBiConsumers.put(
				"patcherProjectVersionId",
				(BiConsumer<PatcherProjectVersion, Long>)
					PatcherProjectVersion::setPatcherProjectVersionId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<PatcherProjectVersion, Long>)
					PatcherProjectVersion::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<PatcherProjectVersion, Long>)
					PatcherProjectVersion::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<PatcherProjectVersion, String>)
					PatcherProjectVersion::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<PatcherProjectVersion, Date>)
					PatcherProjectVersion::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<PatcherProjectVersion, Date>)
					PatcherProjectVersion::setModifiedDate);
			attributeSetterBiConsumers.put(
				"patcherProductVersionId",
				(BiConsumer<PatcherProjectVersion, Long>)
					PatcherProjectVersion::setPatcherProductVersionId);
			attributeSetterBiConsumers.put(
				"rootPatcherProjectVersionId",
				(BiConsumer<PatcherProjectVersion, Long>)
					PatcherProjectVersion::setRootPatcherProjectVersionId);
			attributeSetterBiConsumers.put(
				"combinedBranch",
				(BiConsumer<PatcherProjectVersion, Boolean>)
					PatcherProjectVersion::setCombinedBranch);
			attributeSetterBiConsumers.put(
				"committish",
				(BiConsumer<PatcherProjectVersion, String>)
					PatcherProjectVersion::setCommittish);
			attributeSetterBiConsumers.put(
				"fixedIssues",
				(BiConsumer<PatcherProjectVersion, String>)
					PatcherProjectVersion::setFixedIssues);
			attributeSetterBiConsumers.put(
				"hide",
				(BiConsumer<PatcherProjectVersion, Boolean>)
					PatcherProjectVersion::setHide);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<PatcherProjectVersion, String>)
					PatcherProjectVersion::setName);
			attributeSetterBiConsumers.put(
				"productVersion",
				(BiConsumer<PatcherProjectVersion, Integer>)
					PatcherProjectVersion::setProductVersion);
			attributeSetterBiConsumers.put(
				"repositoryName",
				(BiConsumer<PatcherProjectVersion, String>)
					PatcherProjectVersion::setRepositoryName);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getPatcherProjectVersionId() {
		return _patcherProjectVersionId;
	}

	@Override
	public void setPatcherProjectVersionId(long patcherProjectVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patcherProjectVersionId = patcherProjectVersionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getPatcherProductVersionId() {
		return _patcherProductVersionId;
	}

	@Override
	public void setPatcherProductVersionId(long patcherProductVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_patcherProductVersionId = patcherProductVersionId;
	}

	@Override
	public long getRootPatcherProjectVersionId() {
		return _rootPatcherProjectVersionId;
	}

	@Override
	public void setRootPatcherProjectVersionId(
		long rootPatcherProjectVersionId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rootPatcherProjectVersionId = rootPatcherProjectVersionId;
	}

	@Override
	public boolean getCombinedBranch() {
		return _combinedBranch;
	}

	@Override
	public boolean isCombinedBranch() {
		return _combinedBranch;
	}

	@Override
	public void setCombinedBranch(boolean combinedBranch) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_combinedBranch = combinedBranch;
	}

	@Override
	public String getCommittish() {
		if (_committish == null) {
			return "";
		}
		else {
			return _committish;
		}
	}

	@Override
	public void setCommittish(String committish) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_committish = committish;
	}

	@Override
	public String getFixedIssues() {
		if (_fixedIssues == null) {
			return "";
		}
		else {
			return _fixedIssues;
		}
	}

	@Override
	public void setFixedIssues(String fixedIssues) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fixedIssues = fixedIssues;
	}

	@Override
	public boolean getHide() {
		return _hide;
	}

	@Override
	public boolean isHide() {
		return _hide;
	}

	@Override
	public void setHide(boolean hide) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hide = hide;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public int getProductVersion() {
		return _productVersion;
	}

	@Override
	public void setProductVersion(int productVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_productVersion = productVersion;
	}

	@Override
	public String getRepositoryName() {
		if (_repositoryName == null) {
			return "";
		}
		else {
			return _repositoryName;
		}
	}

	@Override
	public void setRepositoryName(String repositoryName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_repositoryName = repositoryName;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PatcherProjectVersion.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PatcherProjectVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PatcherProjectVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatcherProjectVersionImpl patcherProjectVersionImpl =
			new PatcherProjectVersionImpl();

		patcherProjectVersionImpl.setMvccVersion(getMvccVersion());
		patcherProjectVersionImpl.setPatcherProjectVersionId(
			getPatcherProjectVersionId());
		patcherProjectVersionImpl.setCompanyId(getCompanyId());
		patcherProjectVersionImpl.setUserId(getUserId());
		patcherProjectVersionImpl.setUserName(getUserName());
		patcherProjectVersionImpl.setCreateDate(getCreateDate());
		patcherProjectVersionImpl.setModifiedDate(getModifiedDate());
		patcherProjectVersionImpl.setPatcherProductVersionId(
			getPatcherProductVersionId());
		patcherProjectVersionImpl.setRootPatcherProjectVersionId(
			getRootPatcherProjectVersionId());
		patcherProjectVersionImpl.setCombinedBranch(isCombinedBranch());
		patcherProjectVersionImpl.setCommittish(getCommittish());
		patcherProjectVersionImpl.setFixedIssues(getFixedIssues());
		patcherProjectVersionImpl.setHide(isHide());
		patcherProjectVersionImpl.setName(getName());
		patcherProjectVersionImpl.setProductVersion(getProductVersion());
		patcherProjectVersionImpl.setRepositoryName(getRepositoryName());

		patcherProjectVersionImpl.resetOriginalValues();

		return patcherProjectVersionImpl;
	}

	@Override
	public PatcherProjectVersion cloneWithOriginalValues() {
		PatcherProjectVersionImpl patcherProjectVersionImpl =
			new PatcherProjectVersionImpl();

		patcherProjectVersionImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		patcherProjectVersionImpl.setPatcherProjectVersionId(
			this.<Long>getColumnOriginalValue("patcherProjectVersionId"));
		patcherProjectVersionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		patcherProjectVersionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		patcherProjectVersionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		patcherProjectVersionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		patcherProjectVersionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		patcherProjectVersionImpl.setPatcherProductVersionId(
			this.<Long>getColumnOriginalValue("patcherProductVersionId"));
		patcherProjectVersionImpl.setRootPatcherProjectVersionId(
			this.<Long>getColumnOriginalValue("rootPatcherProjectVersionId"));
		patcherProjectVersionImpl.setCombinedBranch(
			this.<Boolean>getColumnOriginalValue("combinedBranch"));
		patcherProjectVersionImpl.setCommittish(
			this.<String>getColumnOriginalValue("committish"));
		patcherProjectVersionImpl.setFixedIssues(
			this.<String>getColumnOriginalValue("fixedIssues"));
		patcherProjectVersionImpl.setHide(
			this.<Boolean>getColumnOriginalValue("hide"));
		patcherProjectVersionImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		patcherProjectVersionImpl.setProductVersion(
			this.<Integer>getColumnOriginalValue("productVersion"));
		patcherProjectVersionImpl.setRepositoryName(
			this.<String>getColumnOriginalValue("repositoryName"));

		return patcherProjectVersionImpl;
	}

	@Override
	public int compareTo(PatcherProjectVersion patcherProjectVersion) {
		long primaryKey = patcherProjectVersion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PatcherProjectVersion)) {
			return false;
		}

		PatcherProjectVersion patcherProjectVersion =
			(PatcherProjectVersion)object;

		long primaryKey = patcherProjectVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PatcherProjectVersion> toCacheModel() {
		PatcherProjectVersionCacheModel patcherProjectVersionCacheModel =
			new PatcherProjectVersionCacheModel();

		patcherProjectVersionCacheModel.mvccVersion = getMvccVersion();

		patcherProjectVersionCacheModel.patcherProjectVersionId =
			getPatcherProjectVersionId();

		patcherProjectVersionCacheModel.companyId = getCompanyId();

		patcherProjectVersionCacheModel.userId = getUserId();

		patcherProjectVersionCacheModel.userName = getUserName();

		String userName = patcherProjectVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			patcherProjectVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			patcherProjectVersionCacheModel.createDate = createDate.getTime();
		}
		else {
			patcherProjectVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			patcherProjectVersionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			patcherProjectVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		patcherProjectVersionCacheModel.patcherProductVersionId =
			getPatcherProductVersionId();

		patcherProjectVersionCacheModel.rootPatcherProjectVersionId =
			getRootPatcherProjectVersionId();

		patcherProjectVersionCacheModel.combinedBranch = isCombinedBranch();

		patcherProjectVersionCacheModel.committish = getCommittish();

		String committish = patcherProjectVersionCacheModel.committish;

		if ((committish != null) && (committish.length() == 0)) {
			patcherProjectVersionCacheModel.committish = null;
		}

		patcherProjectVersionCacheModel.fixedIssues = getFixedIssues();

		String fixedIssues = patcherProjectVersionCacheModel.fixedIssues;

		if ((fixedIssues != null) && (fixedIssues.length() == 0)) {
			patcherProjectVersionCacheModel.fixedIssues = null;
		}

		patcherProjectVersionCacheModel.hide = isHide();

		patcherProjectVersionCacheModel.name = getName();

		String name = patcherProjectVersionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			patcherProjectVersionCacheModel.name = null;
		}

		patcherProjectVersionCacheModel.productVersion = getProductVersion();

		patcherProjectVersionCacheModel.repositoryName = getRepositoryName();

		String repositoryName = patcherProjectVersionCacheModel.repositoryName;

		if ((repositoryName != null) && (repositoryName.length() == 0)) {
			patcherProjectVersionCacheModel.repositoryName = null;
		}

		return patcherProjectVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PatcherProjectVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PatcherProjectVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PatcherProjectVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(PatcherProjectVersion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PatcherProjectVersion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PatcherProjectVersion.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _patcherProjectVersionId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _patcherProductVersionId;
	private long _rootPatcherProjectVersionId;
	private boolean _combinedBranch;
	private String _committish;
	private String _fixedIssues;
	private boolean _hide;
	private String _name;
	private int _productVersion;
	private String _repositoryName;

	public <T> T getColumnValue(String columnName) {
		Function<PatcherProjectVersion, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PatcherProjectVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"patcherProjectVersionId", _patcherProjectVersionId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put(
			"patcherProductVersionId", _patcherProductVersionId);
		_columnOriginalValues.put(
			"rootPatcherProjectVersionId", _rootPatcherProjectVersionId);
		_columnOriginalValues.put("combinedBranch", _combinedBranch);
		_columnOriginalValues.put("committish", _committish);
		_columnOriginalValues.put("fixedIssues", _fixedIssues);
		_columnOriginalValues.put("hide", _hide);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("productVersion", _productVersion);
		_columnOriginalValues.put("repositoryName", _repositoryName);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("patcherProjectVersionId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("patcherProductVersionId", 128L);

		columnBitmasks.put("rootPatcherProjectVersionId", 256L);

		columnBitmasks.put("combinedBranch", 512L);

		columnBitmasks.put("committish", 1024L);

		columnBitmasks.put("fixedIssues", 2048L);

		columnBitmasks.put("hide", 4096L);

		columnBitmasks.put("name", 8192L);

		columnBitmasks.put("productVersion", 16384L);

		columnBitmasks.put("repositoryName", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PatcherProjectVersion _escapedModel;

}