create table BatchEngineExportTask (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	batchEngineExportTaskId LONG not null primary key,
	companyId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	callbackURL VARCHAR(255) null,
	className VARCHAR(255) null,
	content BLOB,
	contentType VARCHAR(75) null,
	endTime DATE null,
	errorMessage TEXT null,
	executeStatus VARCHAR(75) null,
	fieldNames STRING null,
	parameters TEXT null,
	processedItemsCount INTEGER,
	startTime DATE null,
	taskItemDelegateName VARCHAR(75) null,
	totalItemsCount INTEGER
);

create table BatchEngineImportTask (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	batchEngineImportTaskId LONG not null primary key,
	companyId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	batchSize LONG,
	callbackURL VARCHAR(255) null,
	className VARCHAR(255) null,
	content BLOB,
	contentType VARCHAR(75) null,
	endTime DATE null,
	errorMessage TEXT null,
	executeStatus VARCHAR(75) null,
	fieldNameMapping TEXT null,
	importStrategy INTEGER,
	operation VARCHAR(75) null,
	parameters TEXT null,
	processedItemsCount INTEGER,
	startTime DATE null,
	taskItemDelegateName VARCHAR(75) null,
	totalItemsCount INTEGER
);

create table BatchEngineImportTaskError (
	mvccVersion LONG default 0 not null,
	batchEngineImportTaskErrorId LONG not null primary key,
	companyId LONG,
	userId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	batchEngineImportTaskId LONG,
	item TEXT null,
	itemIndex INTEGER,
	message TEXT null
);