modified.files.includes[relevant][ratings-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][ratings-java-rule]=\
    apps/ratings/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][ratings-java-rule]=\
    apps/ratings/**/*Test.java

relevant.rule.names=ratings-java-rule

test.batch.names[relevant][ratings-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Ratings