modified.files.includes[relevant][address-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][address-web-playwright-rule]=\
    address-web.main

relevant.rule.names=address-web-playwright-rule

test.batch.names[relevant][address-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57