modified.files.includes[relevant][connected-app-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][connected-app-java-rule]=\
    apps/connected-app/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][connected-app-java-rule]=\
    apps/connected-app/**/*Test.java

relevant.rule.names=connected-app-java-rule

test.batch.names[relevant][connected-app-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Documents and Media