modified.files.includes[relevant][iframe-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][iframe-java-rule]=\
    apps/iframe/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][iframe-java-rule]=\
    apps/iframe/**/*Test.java

relevant.rule.names=iframe-java-rule

test.batch.names[relevant][iframe-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=IFrame Portlet