modified.files.includes[relevant][configuration-admin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][configuration-admin-web-playwright-rule]=\
    configuration-admin-web.main

relevant.rule.names=configuration-admin-web-playwright-rule

test.batch.names[relevant][configuration-admin-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=System Settings