modified.files.includes[relevant][layout-admin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][layout-admin-web-playwright-rule]=\
    layout-admin-web.main

relevant.rule.names=layout-admin-web-playwright-rule

test.batch.names[relevant][layout-admin-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57

testray.main.component.name=Content Pages