modified.files.includes[relevant][mentions-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][mentions-java-rule]=\
    apps/mentions/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][mentions-java-rule]=\
    apps/mentions/**/*Test.java

relevant.rule.names=mentions-java-rule

test.batch.names[relevant][mentions-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Mentions