modified.files.includes[relevant][service-component-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][service-component-java-rule]=\
    apps/service-component/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][service-component-java-rule]=\
    apps/service-component/**/*Test.java

relevant.rule.names=service-component-java-rule

test.batch.names[relevant][service-component-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Portal Services