compileJava {
	setActions([])

	doLast {
		ant.taskdef classpath: configurations.ajc.asPath, resource: "org/aspectj/tools/ant/taskdefs/aspectjTaskdefs.properties"

		ant.iajc(classpath: compileJava.classpath.asPath, destDir: compileJava.destinationDir, source: compileJava.sourceCompatibility, target: compileJava.targetCompatibility, XlintFile: "src/main/resources/com/liferay/aspectj/Xlint.properties") {
			sourceRoots {
				sourceSets.main.java.srcDirs.each {
					File dir ->

					pathelement location: dir
				}
			}
		}
	}
}

configurations {
	ajc
}

dependencies {
	ajc group: "org.aspectj", name: "aspectjtools", version: "1.9.22.1"
	api group: "org.aspectj", name: "aspectjrt", version: "1.9.22.1"
	api group: "org.aspectj", name: "aspectjweaver", version: "1.9.22.1"
	api group: "org.eclipse.persistence", name: "javax.persistence", version: "2.2.1"
	compileOnly group: "com.liferay", name: "org.hibernate.core", version: "5.6.7.LIFERAY-PATCHED-2.JAKARTA_LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly project(":core:petra:petra-lang")
}