modified.files.includes[relevant][staging-functional-rule]=**

modified.files.includes[relevant][staging-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-*][relevant][staging-java-rule]=\
    **/asset-test/**/AssetSearcherStagingTest.java,\
    **/src/testIntegration/**/calendar/**/*Test.java,\
    **/src/testIntegration/**/staging/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][staging-java-rule]=\
    apps/staging/**/*Test.java

relevant.rule.names=\
    staging-functional-rule,\
    staging-java-rule

test.batch.names[relevant][staging-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.names[relevant][staging-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][staging-functional-rule]=\
    (portal.acceptance == true) AND \
    (testray.main.component.name ~ "Upgrades Staging")

testray.main.component.name=Staging