dependencies {
	testIntegrationImplementation project(":apps:portal-language:portal-language-override-api")
	testIntegrationImplementation project(":apps:portal:portal-upgrade-test-util")
	testIntegrationImplementation project(":apps:static:portal:portal-upgrade-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}