modified.files.includes[relevant][blogs-service-functional-rule]=**
relevant.rule.names=blogs-service-functional-rule

test.batch.names[relevant][blogs-service-functional-rule]=\
    functional-upgrade-tomcat90-mysql57

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*][relevant][blogs-service-functional-rule]=\
    (testray.component.names == "Blogs") AND \
    (testray.main.component.name == "Upgrades Content Management")

testray.main.component.name=Blogs