concurrency:
    cancel-in-progress: true
    group: push-cloud-preview-container-images-${{github.ref_name}}
defaults:
    run:
        shell: bash
jobs:
    push-rc-image-dxp-operator:
        if: ${{github.repository == 'cloudnative-team/liferay-portal'}}
        uses: ./.github/workflows/ci-reusable-push-container-image.yaml
        with:
            image_name: liferay-dxp-operator
            sparse_checkout: |
                cloud/operator
                cloud/scripts
            working_directory: ./cloud/operator
on:
    push:
        branches:
            -   LCD-*
        paths:
            -   .github/workflows/ci-push-cloud-preview-container-images.yaml
            -   .github/workflows/ci-reusable-push-container-image.yaml
            -   cloud/operator/**
            -   cloud/scripts/versions.json
permissions:
    contents: read
    id-token: write