jobs:
    publish-liferay-sample-workspace-evergreen:
        secrets: inherit
        uses: ./.github/workflows/ci-publish-workspace.yaml
        with:
            workspace-artifact-id-suffix: evergreen
            workspace-includes: .agents/**,.claude/**
            workspace-name: liferay-sample-workspace
on:
    push:
        branches:
            -   master
        paths:
            -   workspaces/liferay-sample-workspace/.agents/**
            -   workspaces/liferay-sample-workspace/.claude/**
    workflow_dispatch: