defaults:
    run:
        shell: bash
jobs:
    push:
        outputs:
            image_ref: ${{steps.push.outputs.image_ref}}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1
                    filter: tree:0
                    show-progress: false
                    sparse-checkout: ${{inputs.sparse_checkout}}
            -   name: Authenticate to Google Cloud
                uses: google-github-actions/auth@v3
                with:
                    project_id: ${{vars.GCP_PROJECT_ID_EXTERNAL_NONPRODUCTION}}
                    workload_identity_provider: ${{vars.GCP_WORKLOAD_IDENTITY_PROVIDER_EXTERNAL_NONPRODUCTION}}
            -   name: Set up Google Cloud CLI
                uses: google-github-actions/setup-gcloud@v2
                with:
                    project_id: ${{vars.GCP_PROJECT_ID_EXTERNAL_NONPRODUCTION}}
            -   name: Log in to GAR
                run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
            -   env:
                    CONTAINER_IMAGE_REGISTRY_NONPRODUCTION: ${{vars.CONTAINER_IMAGE_REGISTRY_NONPRODUCTION}}
                id: push
                name: Build and push image
                run: |
                    set -o errexit
                    set -o nounset
                    set -o pipefail

                    function main {
                        local sanitized_branch

                        sanitized_branch=$(echo "${GITHUB_REF_NAME}" | tr 'A-Z/' 'a-z-')

                        local registry_path="${CONTAINER_IMAGE_REGISTRY_NONPRODUCTION}/${sanitized_branch}"

                        local image_ref="${registry_path}/${{inputs.image_name}}:${sanitized_branch}-${GITHUB_SHA::7}${{inputs.image_tag_suffix}}"

                        docker \
                            build \
                            --pull \
                            --tag "${image_ref}" \
                            .

                        docker push "${image_ref}"
                    }

                    main "${@}"
                working-directory: ${{inputs.working_directory}}
on:
    workflow_call:
        inputs:
            image_name:
                required: true
                type: string
            image_tag_suffix:
                default: ""
                required: false
                type: string
            sparse_checkout:
                required: true
                type: string
            working_directory:
                required: true
                type: string
        outputs:
            image_ref:
                value: ${{jobs.push.outputs.image_ref}}
permissions:
    contents: read
    id-token: write