defaults:
    run:
        shell: bash
jobs:
    test-cloud-helm-chart-smoke:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
            -   name: Create kind cluster
                uses: helm/kind-action@v1
            -   name: Install Helm
                uses: azure/setup-helm@v4
            -   name: Install CRDs
                run: kubectl apply --server-side --force-conflicts -f ./cloud/helm/dxp-operator/crds
            -   name: Validate Helm chart
                run: helm install liferay . --dry-run=server
                working-directory: ./cloud/helm/default
on:
    workflow_call:
permissions:
    contents: read