jobs:
    test-cloud-operator:
        if: ${{github.repository == 'cloudnative-team/liferay-portal'}}
        permissions:
            checks: write
            contents: read
        uses: ./.github/workflows/ci-reusable-test-cloud-operator.yaml
on:
    pull_request:
        paths:
            -   .github/workflows/ci-reusable-test-cloud-operator.yaml
            -   .github/workflows/ci-test-cloud-operator.yaml
            -   cloud/operator/**