##
## Jakarta
##

    jakarta.used.branch=true

##
## Checkstyle Properties
##

    checkstyle.CompanyThreadLocalCheck.enabled=true

    checkstyle.InstanceInitializerCheck.enabled=true

    checkstyle.RedundantLogCheck.enabled=true

    checkstyle.ReferenceAnnotationCheck.checkReferenceCardinalityOptional=true

    checkstyle.UpgradeProcessCheck.enabled=true

##
## Source Check Properties
##

    source.check.IfStatementCheck.enabled=true

    source.check.JavaClassNameCheck.enabled=false

    source.check.JavaCollapseImportsCheck.jarDirectoryName=src/test/resources

    source.check.JavaComponentAnnotationsCheck.checkImmediateAttribute=true

    source.check.JavaConstructorParametersCheck.checkPassedInVariables=true

    source.check.JavaExceptionCheck.enabled=false

    source.check.JavaFeatureFlagManagerUtilCheck.enabled=true

    source.check.JavaModuleInheritableVariableAccessModifierCheck.enabled=false

    source.check.JavaNewProblemInstantiationParametersCheck.enabled=true

    source.check.JavaReferenceAnnotationsCheck.checkReferenceMethod=true

    source.check.JavaReturnStatementCheck.enabled=true

    source.check.JavaSourceFormatterDocumentationCheck.enabled=false

    source.check.JavaStaticMethodCheck.enabled=false

    source.check.JavaUpgradeDropTableCheck.enabled=true

    source.check.JavaUpgradeVersionCheck.checkMissingRegisterInitialization=true

    source.check.JSPLanguageKeysCheck.portalLanguagePropertiesFileName=\
        modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties

    source.check.JSPLanguageUtilCheck.enabled=true

    source.check.JSPTagAttributesCheck.checkClayAlertMessage=true

    source.check.JSPTaglibMissingAttributesCheck.enabled=true

    source.check.LanguageKeysCheck.portalLanguagePropertiesFileName=\
        modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties

    source.check.LogParametersCheck.enabled=true

    source.check.PropertiesLanguageKeysCheck.portalLanguagePropertiesFileName=\
        modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties

    source.check.PropertiesLanguageKeysContextCheck.enabled=true