modified.files.includes[relevant][source-formatter-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][source-formatter-java-rule]=\
    util/source-formatter/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][source-formatter-java-rule]=\
    util/source-formatter/**/*Test.java

relevant.rule.names=source-formatter-java-rule

test.batch.names[relevant][source-formatter-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Source Formatter