modified.files.includes[relevant][portal-instances-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][portal-instances-web-playwright-rule]=\
    portal-instances-web.main

relevant.rule.names=portal-instances-web-playwright-rule

test.batch.names[relevant][portal-instances-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163