apiVersion: v2
appVersion: latest
dependencies:
    -   condition: liferay-subchart-backup-controller.enabled
        name: liferay-subchart-backup-controller
        version: 0.1.2
    -   condition: liferay-subchart-backup-create.enabled
        name: liferay-subchart-backup-create
        version: 0.1.1
    -   condition: liferay-subchart-backup-restore.enabled
        name: liferay-subchart-backup-restore
        version: 0.1.3
description:
    Liferay is an all-in-one DXP, LCAP, and Commerce platform. This chart provides cloud infrastructure resource
    definitions for GCP.
icon: https://www-cdn.liferay.com/documents/d/guest/liferay-logo
name: liferay-gcp-infrastructure-provider
type: application
version: 1.0.0