clusterBootstrap:
    enabled: true
    image: alpine:3
    resources:
        limits:
            cpu: 3m
            memory: 16Mi
        requests:
            cpu: 1m
            memory: 8Mi
    script: |
        sysctl -w vm.max_map_count=1048576
crossplaneGsaEmail: ""
crossplaneNamespace: crossplane-system
eck-operator:
    enabled: true
filestore:
    enabled: true
    storageClassName: filestore-sc
    tier: standard
gateway:
    enabled: true
    internetFacing: true
    namespace: envoy-gateway-system
global:
    gcp: {}
liferay-dxp-operator:
    enabled: true
    fullnameOverride: dxp-operator
    marketplace:
        claimName: dxp-operator-marketplace
        csi:
            driver: filestore.csi.storage.gke.io
            volumeAttributes:
                protocol: NFS_V3
                volume: marketplace
        enabled: true
        mountPath: /marketplace
    namespaceOverride: dxp-operator-system
    podSecurityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
liferay-subchart-backup-controller:
    enabled: true
    serviceAccountName: backup-controller
liferay-subchart-backup-create:
    enabled: true
liferay-subchart-backup-restore:
    enabled: true
providers:
    enabled: true