dependencies {
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-api")
	testIntegrationImplementation project(":apps:layout:layout-content-api")
	testIntegrationImplementation project(":apps:layout:layout-page-template-api")
	testIntegrationImplementation project(":apps:layout:layout-page-template-test-util")
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":apps:layout:layout-utility-page-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}