dependencies {
	testIntegrationImplementation group: "com.liferay.portal", name: "com.liferay.portal.impl", version: "default"
	testIntegrationImplementation project(":apps:change-tracking:change-tracking-api")
	testIntegrationImplementation project(":apps:fragment:fragment-api")
	testIntegrationImplementation project(":apps:fragment:fragment-entry-processor:fragment-entry-processor-api")
	testIntegrationImplementation project(":apps:layout:layout-api")
	testIntegrationImplementation project(":apps:layout:layout-content-api")
	testIntegrationImplementation project(":apps:layout:layout-page-template-api")
	testIntegrationImplementation project(":apps:layout:layout-page-template-test-util")
	testIntegrationImplementation project(":apps:layout:layout-test-util")
	testIntegrationImplementation project(":apps:layout:layout-utility-page-api")
	testIntegrationImplementation project(":apps:segments:segments-api")
	testIntegrationImplementation project(":test:arquillian-extension-junit-bridge")
}