/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.sso.openid.connect.persistence.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.security.sso.openid.connect.persistence.model.OpenIdConnectUser;
import com.liferay.portal.security.sso.openid.connect.persistence.model.OpenIdConnectUserModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OpenIdConnectUser service. Represents a row in the &quot;OpenIdConnectUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OpenIdConnectUserModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OpenIdConnectUserImpl}.
 * </p>
 *
 * @author Arthur Chan
 * @see OpenIdConnectUserImpl
 * @generated
 */
public class OpenIdConnectUserModelImpl
	extends BaseModelImpl<OpenIdConnectUser> implements OpenIdConnectUserModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a open ID connect user model instance should use the <code>OpenIdConnectUser</code> interface instead.
	 */
	public static final String TABLE_NAME = "OpenIdConnectUser";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"openIdConnectUserId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"issuer", Types.VARCHAR},
		{"subject", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("openIdConnectUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("issuer", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OpenIdConnectUser (mvccVersion LONG default 0 not null,openIdConnectUserId LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,issuer VARCHAR(75) null,subject VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table OpenIdConnectUser";

	public static final String ORDER_BY_JPQL =
		" ORDER BY openIdConnectUser.openIdConnectUserId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OpenIdConnectUser.openIdConnectUserId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ISSUER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBJECT_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long OPENIDCONNECTUSERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public OpenIdConnectUserModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _openIdConnectUserId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOpenIdConnectUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _openIdConnectUserId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OpenIdConnectUser.class;
	}

	@Override
	public String getModelClassName() {
		return OpenIdConnectUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OpenIdConnectUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OpenIdConnectUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OpenIdConnectUser, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((OpenIdConnectUser)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OpenIdConnectUser, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OpenIdConnectUser, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OpenIdConnectUser)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OpenIdConnectUser, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OpenIdConnectUser, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<OpenIdConnectUser, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<OpenIdConnectUser, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<OpenIdConnectUser, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", OpenIdConnectUser::getMvccVersion);
			attributeGetterFunctions.put(
				"openIdConnectUserId",
				OpenIdConnectUser::getOpenIdConnectUserId);
			attributeGetterFunctions.put(
				"companyId", OpenIdConnectUser::getCompanyId);
			attributeGetterFunctions.put(
				"userId", OpenIdConnectUser::getUserId);
			attributeGetterFunctions.put(
				"createDate", OpenIdConnectUser::getCreateDate);
			attributeGetterFunctions.put(
				"issuer", OpenIdConnectUser::getIssuer);
			attributeGetterFunctions.put(
				"subject", OpenIdConnectUser::getSubject);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<OpenIdConnectUser, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<OpenIdConnectUser, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<OpenIdConnectUser, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<OpenIdConnectUser, Long>)
					OpenIdConnectUser::setMvccVersion);
			attributeSetterBiConsumers.put(
				"openIdConnectUserId",
				(BiConsumer<OpenIdConnectUser, Long>)
					OpenIdConnectUser::setOpenIdConnectUserId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<OpenIdConnectUser, Long>)
					OpenIdConnectUser::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<OpenIdConnectUser, Long>)
					OpenIdConnectUser::setUserId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<OpenIdConnectUser, Date>)
					OpenIdConnectUser::setCreateDate);
			attributeSetterBiConsumers.put(
				"issuer",
				(BiConsumer<OpenIdConnectUser, String>)
					OpenIdConnectUser::setIssuer);
			attributeSetterBiConsumers.put(
				"subject",
				(BiConsumer<OpenIdConnectUser, String>)
					OpenIdConnectUser::setSubject);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getOpenIdConnectUserId() {
		return _openIdConnectUserId;
	}

	@Override
	public void setOpenIdConnectUserId(long openIdConnectUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_openIdConnectUserId = openIdConnectUserId;
	}

	@Override
	public String getOpenIdConnectUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(
				getOpenIdConnectUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setOpenIdConnectUserUuid(String openIdConnectUserUuid) {
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public String getIssuer() {
		if (_issuer == null) {
			return "";
		}
		else {
			return _issuer;
		}
	}

	@Override
	public void setIssuer(String issuer) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_issuer = issuer;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalIssuer() {
		return getColumnOriginalValue("issuer");
	}

	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subject = subject;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSubject() {
		return getColumnOriginalValue("subject");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OpenIdConnectUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OpenIdConnectUser toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OpenIdConnectUser>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OpenIdConnectUserImpl openIdConnectUserImpl =
			new OpenIdConnectUserImpl();

		openIdConnectUserImpl.setMvccVersion(getMvccVersion());
		openIdConnectUserImpl.setOpenIdConnectUserId(getOpenIdConnectUserId());
		openIdConnectUserImpl.setCompanyId(getCompanyId());
		openIdConnectUserImpl.setUserId(getUserId());
		openIdConnectUserImpl.setCreateDate(getCreateDate());
		openIdConnectUserImpl.setIssuer(getIssuer());
		openIdConnectUserImpl.setSubject(getSubject());

		openIdConnectUserImpl.resetOriginalValues();

		return openIdConnectUserImpl;
	}

	@Override
	public OpenIdConnectUser cloneWithOriginalValues() {
		OpenIdConnectUserImpl openIdConnectUserImpl =
			new OpenIdConnectUserImpl();

		openIdConnectUserImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		openIdConnectUserImpl.setOpenIdConnectUserId(
			this.<Long>getColumnOriginalValue("openIdConnectUserId"));
		openIdConnectUserImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		openIdConnectUserImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		openIdConnectUserImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		openIdConnectUserImpl.setIssuer(
			this.<String>getColumnOriginalValue("issuer"));
		openIdConnectUserImpl.setSubject(
			this.<String>getColumnOriginalValue("subject"));

		return openIdConnectUserImpl;
	}

	@Override
	public int compareTo(OpenIdConnectUser openIdConnectUser) {
		long primaryKey = openIdConnectUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OpenIdConnectUser)) {
			return false;
		}

		OpenIdConnectUser openIdConnectUser = (OpenIdConnectUser)object;

		long primaryKey = openIdConnectUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<OpenIdConnectUser> toCacheModel() {
		OpenIdConnectUserCacheModel openIdConnectUserCacheModel =
			new OpenIdConnectUserCacheModel();

		openIdConnectUserCacheModel.mvccVersion = getMvccVersion();

		openIdConnectUserCacheModel.openIdConnectUserId =
			getOpenIdConnectUserId();

		openIdConnectUserCacheModel.companyId = getCompanyId();

		openIdConnectUserCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			openIdConnectUserCacheModel.createDate = createDate.getTime();
		}
		else {
			openIdConnectUserCacheModel.createDate = Long.MIN_VALUE;
		}

		openIdConnectUserCacheModel.issuer = getIssuer();

		String issuer = openIdConnectUserCacheModel.issuer;

		if ((issuer != null) && (issuer.length() == 0)) {
			openIdConnectUserCacheModel.issuer = null;
		}

		openIdConnectUserCacheModel.subject = getSubject();

		String subject = openIdConnectUserCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			openIdConnectUserCacheModel.subject = null;
		}

		return openIdConnectUserCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OpenIdConnectUser, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OpenIdConnectUser, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OpenIdConnectUser, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(OpenIdConnectUser)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OpenIdConnectUser>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					OpenIdConnectUser.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _openIdConnectUserId;
	private long _companyId;
	private long _userId;
	private Date _createDate;
	private String _issuer;
	private String _subject;

	public <T> T getColumnValue(String columnName) {
		Function<OpenIdConnectUser, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((OpenIdConnectUser)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("openIdConnectUserId", _openIdConnectUserId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("issuer", _issuer);
		_columnOriginalValues.put("subject", _subject);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("openIdConnectUserId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("issuer", 32L);

		columnBitmasks.put("subject", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private OpenIdConnectUser _escapedModel;

}