modified.files.includes[relevant][frontend-data-set-admin-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-mysql57][relevant][frontend-data-set-admin-web-playwright-rule]=\
    frontend-data-set-admin-web.main

relevant.rule.names=frontend-data-set-admin-web-playwright-rule

test.batch.names[relevant][frontend-data-set-admin-web-playwright-rule]=\
    playwright-js-tomcat101-mysql57