modified.files.includes[relevant][notifications-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][notifications-java-rule]=\
    apps/notifications/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][notifications-java-rule]=\
    apps/notifications/**/*Test.java

relevant.rule.names=notifications-java-rule

test.batch.names[relevant][notifications-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Notifications